Feature/add resources
betagouv/aides-jeunes pull request #1513
Opened 2021-03-17 16:44 UTC by ClementNumericite

à voir si la logique de division des étapes convient

2021-03-17 16:54 UTC, ClementNumericite commented on src/lib/Individu.js
>      }
pas sûr de ça, mais je n'ai pas de notion de role dans l'url dans la partie ressources.
est ce qu'il faut ajouter ça avec un refactor du router sur cette partie @guillett ?

2021-03-17 17:42 UTC, guillett commented on src/lib/Individu.js
>      }
Le role est inclut dans l'id :sweat_smile:

2021-03-18 06:54 UTC, guillett requested changes
Merci pour l'ajout de ces éléments de logique.

Je pense qu'avant de merger, c'est bien de mettre ces éléments un peu plus au propre.

- Déplacer les `views/Foyer/**` vers `views/Simulation/**` pour faire le tri entre l'historique et l'actuel
- Récrire les éléments de textes pour formuler des questions
- Réutiliser le composant `<Actions>` plutôt que de le réimplémenter

2021-03-18 06:54 UTC, guillett commented on src/components/Ressource/Types.vue
> +      Sélectionnez les types de ressources perçues <strong><span v-if="individu._role !== 'demandeur'">par {{ individu._firstName }}</span> depuis {{ $store.state.dates.twelveMonthsAgo.label }}</stro
Attention cette reformulation ne fonctionne pas pour le conjoint car `_firstName` n'existe que pour les enfants.

2021-03-18 06:54 UTC, guillett commented on src/components/Ressource/Types.vue
> +    <div class="next form__group">
Ce bloc est historique, il serait préférable d'utiliser le composant qui mutualise désormais cette logique comme c'est fait dans les premiers écrans du parcours par exemple dans [Enfants.vue](https://github.com/betagouv/aides-jeunes/blob/master/src/views/Simulation/Enfants.vue).

2021-03-18 06:54 UTC, guillett commented on src/lib/Ressource.js
> +function getIndividuRessourceCategories(individu) {
Cette fonction est difficile à lire, est-ce tu pourrais essayer de la reformuler ?

2021-03-18 06:54 UTC, guillett commented on src/lib/Ressource.js
> +    return _.filter(_.filter(ressourceTypes, isRessourceOnMainScreen), (ressourceType) => {
Le double `filter` associé au `reduce` oblige le lecteur à penser à plusieurs choses en même, en passant par une variable intermédiaire cela pourrait faire diminuer la charge cognitive associée.

2021-03-19 18:23 UTC, guillett commented on src/views/Simulation/Ressources/Types.vue
> +      return Individu.find(this.$store.state.situation, _.get(this.$route.params.id.split('_'), '0', this.$route.params.id), this.$route.params.id)
```suggestion
      return Individu.find(this.$store.state.situation, this.$route.params.id.split('_')[0], this.$route.params.id)
```
fait la même chose sans renforcé la dépendance à `lodash`.

2021-03-21 16:43 UTC, guillett approved these changes
Merci pour les simplifications apportées, j'ai fait quelques modifs supplémentaires marginales.

2021-03-21 16:43 UTC, merged