Feature/advanced design
betagouv/aides-jeunes pull request #1540
Opened 2021-03-24 17:04 UTC by ClementNumericite

2021-03-24 17:12 UTC, ClementNumericite commented
@guillett 
normalement ready to merge, j'ai fait un rebase (douloureux :D) ce matin.
seul truc j'ai voulu ajouter un timeout sur les étapes auto submit, pour laisser l'animation de coche se faire et avoir moins l'impression de téléportation au click... Mais tous les tests cypress tombent avec ce delay...
Est ce que tu veux que je corrige le cypess pour accueillir cet effet avant le merge ? (perso je trouve que ça change pas mal l'UX dans le parcours)

2021-03-25 14:37 UTC, guillett requested changes
Merci beaucoup, j'ai fait pas mal de commentaires, en particulier sur l'accessibilité et les `label`/`input`.

2021-03-25 14:37 UTC, guillett commented on src/mixins/IndividuMixin.js
> +
Plutôt mettre ça dans un paramètre du constructeur de mixin ? comme `optional`, genre `manualValidation` et le défaut serait false et donc un passage automatique à la page suivante ?

2021-03-25 14:37 UTC, guillett commented on src/mixins/IndividuMixin.js
> +                    // setTimeout(this.onSubmit, 400)
Est-ce-que `setTimeout(this.onSubmit, 0)` fonctionne ?
On pourrait avoir un `setTimeout(this.onSubmit, process.env.VUE_APP_VALIDATION_DELAY || 0)` ? :sweat_smile:

2021-03-25 14:37 UTC, guillett commented on src/mixins/IndividuMixin.js
> +                if (this.autoValidate) {
Il faudrait avoir une logique plus importante que `this.autoValidate` par exemple `this.autoValidate && !this.initiallySet` pour s'assurer que la réédition ne fasse pas de passage à l'écran suivant intempestif. (Mais c'est peut-être du zèle de ma part) à confronter aux premiers usages.

2021-03-25 14:37 UTC, guillett commented on src/mixins/IndividuMixin.js
> +                }
Pour moi cette logique a plutôt sa place dans une fonction d'un autre mixin (dont celui-là dépendrait) et qui pourrait être mutualiser avec les écrans famille/ménage/foyerFiscal.

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Enfants.vue
> +    <!--</ul>-->
À supprimer ?

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Enfants.vue
> +]
Éviter la duplication et regrouper ces infos dans une lib par exemple.

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Enfants.vue
> +            return moment(date).format('DD/MM/YYYY')
Ce n'est pas l'âge.

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Enfants.vue
> +                    return 'Non européenne';
Mettre ce code là dans `src/lib/Nationality.js` ?

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Individu/DateDebutChomage.vue
> +  mixins: [createIndividuMixin('date_debut_chomage', true)],
Pourquoi avoir rendu ce champ optionnel ?

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Individu/DateNaissance.vue
> +        <EnSavoirPlus text="Lorem ipsum dolor sit amen insec elpur vim datae" />
:scream:

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Individu/DateDebutChomage.vue
> +      <legend>Quand {{getLabel('avoir')}} commencé à être au chômage&nbsp;?</legend>
Un élément `legend` ne peut pas être dans un `label`.

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Individu/EchelonBourse.vue
> +    <legend>À quel échelon {{ getLabel('être') }} boursier ?</legend>
Un élément `legend` ne peut pas être dans un `form`, il ne peut être que le premier élément d'un `fieldset`. Ici, l'input n'a pas de label ce qui implique qu'aucun texte n'est lu pour les personnes malvoyantes.

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Individu/GIR.vue
> +    <legend>{{ getLabel('avoir') | capitalize }} besoin d’une aide à la personne&nbsp;?</legend>
Un élément `legend` ne peut pas être dans un `form`, il ne peut être que le premier élément d'un `fieldset`.

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Individu/Handicap/TauxIncapacite.vue
> +    <legend>{{ role === 'demandeur' ? `Quel est votre taux d'incapacité` : `Quel est le taux d'incapacité de ${getLabel('nom')}` }} évalué par {{getLabel('possessif')}} <abbr title="Maison départemen
Un élément `legend` ne peut pas être dans un `form`, il ne peut être que le premier élément d'un `fieldset`. Ici, l'input n'a pas de label ce qui implique qu'aucun texte n'est lu pour les personnes malvoyantes.

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Individu/Nationalite.vue
> +    <legend>{{ role === 'demandeur' ? 'Quelle est votre nationalité&nbsp;?' : `Quelle est la nationalité de ${getLabel('nom')}&nbsp;?` }}</legend>
Un élément `legend` ne peut pas être dans un `form`, il ne peut être que le premier élément d'un `fieldset`. Ici, l'input n'a pas de label ce qui implique qu'aucun texte n'est lu pour les personnes malvoyantes.

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Individu/Scolarite.vue
> +    <legend>Où sera scolarisé·e {{individu._firstName}} à la rentrée prochaine&nbsp;?</legend>
Idem

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Individu/StatutMarital.vue
> +    <legend>Quelle est votre relation avec votre conjoint&nbsp;?</legend>
Idem.

2021-03-25 14:37 UTC, guillett commented on src/views/Simulation/Individu/_FirstName.vue
> +    <legend>Quel est le prénom de votre enfant ? Il servira uniquement à vous faciliter la saisie par la suite.</legend>
Idem

2021-03-25 15:55 UTC, ClementNumericite commented on src/views/Simulation/Individu/DateDebutChomage.vue
> +  mixins: [createIndividuMixin('date_debut_chomage', true)],
Bizarre, ça doit être une erreur lors du rebase.

2021-03-28 15:56 UTC, guillett approved these changes
Merci pour le rebase et la prise en compte des commentaires ! J'ai ajouté quelques modifications complémentaires pour pouvoir merger ça rapidement et nous permettre de travailler sur une base commune.

2021-03-28 15:56 UTC, merged