Feature/integration resultats
betagouv/aides-jeunes pull request #1566
Opened 2021-04-02 11:34 UTC by ClementNumericite

2021-04-02 11:57 UTC, guillett commented
:warning: Tu as modifié le package-lock.json et ta version de `npm` l'a fait repassé en `"lockfileVersion": 1,`, pourrais-tu monter ta version de `npm` et revert les modifs sur ce fichier ?

2021-04-02 11:57 UTC, ClementNumericite commented
rebase done

2021-04-05 09:18 UTC, guillett requested changes

2021-04-05 09:18 UTC, guillett commented on src/views/Simulation/Enfants.vue
> +    <button class="button outline with-icon" id="add-pac" v-on:click="addPAC()">
Les tests E2E ont un comportement un peu aléatoire à cause de ce `m-auto` qui fait (faisait) sauter le bouton du milieu vers la gauche (et vice versa).

2021-04-05 09:18 UTC, guillett commented on src/components/DroitsList.vue
> +        <div v-for="(droit, index) in list"
L'utilisation d'un `a` est faite pour faciliter la vie des lecteurs d'écran. Il faudrait reprendre cette logique.

2021-04-05 09:42 UTC, guillett commented
Ah et le spinner n'apparait pas.

2021-04-05 10:25 UTC, ClementNumericite commented
correction des retours + rebase done

2021-04-05 11:25 UTC, guillett requested changes
Merci Clément !
Les reformulations me semblent importantes. Le reste c'est plutôt des remarques/suggestions.

2021-04-05 11:25 UTC, guillett commented on backend/lib/mes-aides/emails/initial.js
> +            ctaLabel = 'Formulaire papier';
Pourquoi avoir fait cette modif ? Les phrases avec un verbe à l'infinitif permettent d'être très explicite sur les attentes légitimes en cliquant sur les liens.

2021-04-05 11:25 UTC, guillett commented on src/components/BenefitCtaLink.vue
> +    form: 'Formulaire papier',
Même remarque.

> Pourquoi avoir fait cette modif ? Les phrases avec un verbe à l'infinitif permettent d'être très explicite sur les attentes légitimes en cliquant sur les liens.

2021-04-05 11:25 UTC, guillett commented on src/components/DroitsDetails.vue
> +                        <p class="aj-droit-conditions-title">Conditions à réunir</p>
L'expression utilisée jusqu'à présent « Pour en bénéficier, vous devez également : » condense plus d'informations. Elle introduit les conditions textuelles, c'est à dire les conditions qui n'ont pas été prises en compte dans le simulateur.
Je pense que, pour le moment, il est préférable de conserver l'expression historique.

2021-04-05 11:25 UTC, guillett commented on src/components/DroitsList.vue
> +                    <img src="@/assets/images/warning.svg"> Attention, cette aide vous est accessible sous certaines conditions
> sous certaines conditions supplémentaires.

2021-04-05 11:25 UTC, guillett commented on src/views/Simulation/Enfants.vue
> +    <button class="button outline m-auto with-icon" id="add-pac" v-on:click="addPAC()">
Éviter le diff.

2021-04-05 11:32 UTC, guillett commented
De plus, suite un test en local
- le bouton retour sur la page de détails d'une aide et trop petit, en particulier sur mobile. Je pense qu'un bouton aussi gros que les autres est pertinent.
- sur firefox, le montant des aides est mal aligné.
![Screenshot_2021-04-05 Évaluez vos droits aux aides sociales](https://user-images.githubusercontent.com/1410356/113569734-415b9c80-9613-11eb-90bb-bf5f95e22b53.png)

2021-04-05 12:51 UTC, ClementNumericite commented on backend/lib/mes-aides/emails/initial.js
> +            ctaLabel = 'Formulaire papier';
Ça mettait le texte du bouton sur deux lignes, donc ça cassait un peu l'harmonie. :/

2021-04-05 12:51 UTC, ClementNumericite commented on src/components/DroitsDetails.vue
> +                        <p class="aj-droit-conditions-title">Conditions à réunir</p>
Ok j'avais repris cette reformulation du figma. Je vais remettre l'ancienne.

2021-04-05 13:00 UTC, ClementNumericite commented on backend/lib/mes-aides/emails/initial.js
> +            ctaLabel = 'Formulaire papier';
![Capture du 2021-04-05 15-00-19](https://user-images.githubusercontent.com/80679266/113576341-b0d78900-961f-11eb-9421-6afb57cf1b78.png)

2021-04-05 13:07 UTC, guillett commented on src/components/BenefitCtaLink.vue
> +    form: 'Formulaire papier',
:ok_hand: je pense que ce n'est pas grave que ce soit sur deux lignes mais effectivement ça serait top de réussir à faire _tomber_ le mot formulaire sur la seconde.

2021-04-05 14:36 UTC, guillett commented
Sur ordinateur, la page de détail d'un résultat est très resserrée au milieu de l'écran et j'ai l'impression qu'elle se retrouve plus lourde que la page de résultats.

Extrait de la page de résultats
![Screenshot_2021-04-05 Évaluez vos droits aux aides sociales(4)](https://user-images.githubusercontent.com/1410356/113585676-d8811e00-962c-11eb-9163-b58b83d3d8c8.png)


Page de détails
![Screenshot_2021-04-05 Évaluez vos droits aux aides sociales(3)](https://user-images.githubusercontent.com/1410356/113585710-e6cf3a00-962c-11eb-94d1-7bbc4e081787.png)


Sur mobile, le texte n'est pas limité à la colonne du centre mais passe sur le logo et le montant, je pense que ça serait mieux au moins en ayant le texte qui soit sur les deux colonnes (centre + droite).

2021-04-05 15:57 UTC, ClementNumericite commented
@guillett ok corrigé pour le desktop.
par contre je ne vois pas le comportement que tu décris en mobile.
screenshot sur mon mobile OnePlus7 (et même résultat sur mes simulations d'autres tailles via Chrome)

![Screenshot_20210405-165203](https://user-images.githubusercontent.com/80679266/113594718-5c8cd300-9638-11eb-9900-13ecd939ba32.jpg)

2021-04-05 16:04 UTC, guillett commented
Sur mobile je trouve ça bien (il n'y pas d'espaces pour faire autrement :sweat_smile: ) que le texte ne soit pas bloqué entre le logo et le montant.

2021-04-05 16:09 UTC, ClementNumericite commented
> Sur mobile, le texte n'est pas limité à la colonne du centre mais passe sur le logo et le montant, je pense que ça serait mieux au moins en ayant le texte qui soit sur les deux colonnes (centre + droite).

j'avais juste mal compris cette phrase... décidément aujourd'hui 

donc ce que tu dis c'est avoir plutôt le texte qui s'agrandirait pour prendre la place du montant. faudrait que j'en touche un mot à Augustin demain pour voir où on peut placer le montant dans ce cas.

2021-04-05 16:13 UTC, guillett commented
C'est top sur mobile, :sweat: désolé pour mon manque de clarté. Le point positif c'est que ça met en évidence l'importance des échanges en synchro. :)

2021-04-06 15:36 UTC, ClementNumericite commented
@guillett après discussion avec augustin, plus de place pour le texte de contenu des aides dans la page de détail

2021-04-06 19:18 UTC, guillett approved these changes
Merci beaucoup pour cette partie de refonte, on commence à voir le bout ! :pray: 

> Il y a des règles CSS de folie, :sweat_smile:

2021-04-06 19:18 UTC, merged

2021-04-15 13:13 UTC, guillett commented on src/styles/partials/desktop/_resultats.scss
> +        }
@ClementNumericite  y-a-t-il une raison d'avoir appliqué ça directement aux `h2` plutôt qu'à une classe genre `moblie-only` ou `x-desktop` ? Ma question est liée à https://github.com/betagouv/aides-jeunes/pull/1598/files#diff-4b2b9b87601f4e64b297a207f7212b65f8e5803686a75709b21a61e7bfa1a4dfR123 qui tente de réutiliser de la logique.