Intègre le composant wizard
betagouv/aides-jeunes pull request #1603
Opened 2021-04-14 08:38 UTC by ClementNumericite

2021-04-15 14:48 UTC, ClementNumericite commented
@guillett j'ai fait un commit pour l'implémentation simple (possibilité de revenir en arrière mais pas de gestion de _redo_ via le wizard)

je continue mon expérimentation dans feature/parcours-wizard-complexe

2021-04-16 08:35 UTC, guillett requested changes
C'est vraiment chouette d'ajouter ça, ça apporte de la visibilité ! Merci beaucoup.

Je pense qu'il y a de la duplication de l'info pour le moment c'est la raison principale du _request changes_.

Je trouve que le mot _wizard_ est très peu explicite sur le contenu du composant.

De plus, le design en l'état, avec la navigation sur fond blanc et le reste sur fond gris c'est bizarre (désolé je n'ai pas de meilleur mot). Le fait qu'à gauche de la navigation c'est un fond gris est surprenant.
![Screenshot_2021-04-16 Évaluez vos droits aux aides sociales](https://user-images.githubusercontent.com/1410356/114996636-4fc17800-9e9f-11eb-9dd9-f1d6cc237378.png)

2021-04-16 08:35 UTC, guillett commented on src/components/Wizard.vue
> +                {id: 5, title: 'Mes projets', value: 'projets', done: false},
Il y a du contenu dupliqué avec [TitreChapitre](https://github.com/betagouv/aides-jeunes/blob/master/src/components/TitreChapitre.vue#L20-L35) ça vaut le coup de regrouper les infos dans une lib.

2021-04-16 08:35 UTC, guillett commented on src/components/Wizard.vue
> +                {id: 5, title: 'Mes projets', value: 'projets', done: false},
Et pourquoi ne pas générer l'info `done` via une `computed` ?

2021-04-16 08:35 UTC, guillett commented on src/components/Wizard.vue
> +                    return 5;
Idem, cette succession d'étapes est une forme de duplication. Pourquoi ne pas générer les indices à partir du chemin complet (avec les étapes inactives pour bien avoir toutes les sections ou pas d'ailleurs car sinon il faudra de la complexité supplémentaire pour les passer en done :thinking: ).

2021-04-16 09:16 UTC, ClementNumericite commented
@guillett ok je vais adapter.

Pour le design on a vu avec augustin hier et c'est la solution court terme qu'on a trouvé pour l'intégrer dans le container.
Je suis d'accord que le bleu/gris à gauche fait bizarre, je regarde si je trouve une solution plus adapté.

2021-04-16 10:41 UTC, ClementNumericite commented
@guillett pour le nom "Sommaire" te parait mieux ? :thinking:

2021-04-20 13:14 UTC, guillett commented on src/lib/State/index.js
> +}
Cette logique pourrait-elle être intégrée au bloc [`chapters`](https://github.com/betagouv/aides-jeunes/pull/1603/files#diff-592092e114799d970e599994ac3e33f0d33b2c670c788746792f6cb858cf900bR60) juste au dessus ?

En l'état, la fonction `full` se retrouve être appelée de nombreuses fois et cela à chaque changement de pages.

2021-04-20 14:16 UTC, ClementNumericite commented on src/lib/State/index.js
> +}
ok bien vu j'ai rassemblé dans chapter.

de plus je limite l'utilisation de full à 1 fois max par page via ce commit : https://github.com/betagouv/aides-jeunes/pull/1603/commits/2bed0bbbf843d931def0c84f84e915d9bcd1a4af

2021-04-29 13:28 UTC, ClementNumericite commented
J'ai déplacé la logique de génération des steps dans le store.

J'aimerais bien éviter  d'appeler _commit('setFullSteps')_ dans chaque mutation impactant _situation_, mais pour l'instant je ne trouve pas de moyen simple de "watch" un changement de situation tout au long du parcours (testé avec [subscribe](https://vuex.vuejs.org/api/#subscribe) mais pas mieux)

Je vois une refonte du store à terme qui feraient passer les mutations saveFamille, saveIndividu etc par un setter saveSituation final qui nous permettrait de gérer des traitements à chaque changements de situtation.

2021-04-29 14:13 UTC, guillett commented on src/store.js
> +      return state.fullSteps
Pourquoi tu ne retournes pas `generateFullSteps(defaultSituation)` ?

> Vuex allows us to define "getters" in the store. You can think of them as computed properties for stores.
https://vuex.vuejs.org/guide/getters.html

2021-05-04 17:35 UTC, guillett commented
Je me rends compte qu'on a pas de version mobile de ce sommaire. Penses-tu qu'il faille le faire dans cette PR ? ou bien dans une séparée ? (J'aurais tendance à dire dans cette PR car je voudrais la déployer avec de l'AB testing mais bon ça retarde la MEP de la PR).

2021-05-05 08:50 UTC, ClementNumericite commented
@guillett j'essaie d'itérer avec augustin pour voir s'il pense voir une v1 mobile

2021-05-05 10:41 UTC, guillett commented
Autres remarques
- Les éléments du sommaire n'ont pas d'indice visuel au focus
- Le sommaire arrive avant le corps de la page au clavier cela rend la navigation (au clavier) laborieuse car il faut passer tout le sommaire à chaque passage d'écran. Je pensais faire un commit en faisant un flex-reverse comme c'est le cas pour `aj-actions` mais je préfère te laisser faire.

En ce qui concerne la vue mobile, je pense qu'il va falloir faire une logique similaire au `en_savoir_plus` avec une page dédiée.

2021-05-10 13:01 UTC, ClementNumericite commented
@guillett première version mobile
j'attends qu'on itère pour rebase, je sens beaucoup de conflits arriver

2021-05-26 12:52 UTC, QuentinMadura commented
Salut @ClementNumericite.
J'ai une remarque sur la forme plus que sur le fond. Si je m'appuie sur les maquettes réalisées, j'ai l'impression qu'il y a une différence au niveau du positionnement du sommaire. En format desktop, celui-ci devrait être collé sur le côté gauche et non avoir de gouttière sur les côtés. Selon moi, cette différence s'explique par le fait qu'on utilise la classe `container` qui applique un margin-auto sur le container `aj-layout-container ` de la `Simulation.vue`.

2021-06-02 16:34 UTC, Kout95 commented
Lorsque l'utilisateur réalise la manipulation suivante une erreur peut se produire :
- clique sur un chapitre complété précédemment
- réponds à une réponse (ou plusieurs)
- revient en arrière jusqu'a revenir sur la position précédente
le journey fini par être corrompu

Ce problème est réglé dans la version complète du sommaire attendons-nous la version complète ou tolérons-nous ce bug ?

2021-06-08 08:14 UTC, Kout95 commented
J'ai changé le bouton pour accéder au sommaire pour le rendre plus intuitif,  qu'en pensez-vous ? 
@guillett @QuentinMadura Aurélien

2021-06-09 12:35 UTC, guillett commented
![signal-2021-06-09-142749_001](https://user-images.githubusercontent.com/1410356/121355156-e3f40c80-c92f-11eb-9d0c-4d3028a3f7ea.png)
![signal-2021-06-09-142749_002](https://user-images.githubusercontent.com/1410356/121355164-e48ca300-c92f-11eb-8e41-8d405e948c73.png)

2021-06-14 17:40 UTC, guillett requested changes
* Sur mobile, la barre 1J1S + le titre + le bouton toutes les étapes prennent plus de 1/3 de l'écran, ça me semble problématique.
   * Est ce que tu pourrais tenter de déplacer le bouton Toutes les étapes pour le mettre entre le bouton précédent et suivant (et peut-être supprimé la flèche vers la gauche du bouton précédent qui prend de la place :sweat_smile: )
* Le bouton Retour sur la vue Sommaire bouge au clic.

2021-06-14 17:40 UTC, guillett commented on src/components/BaseLayout.vue
> +      return this.$store.getters.getMobileMenu
À quoi sert cette logique ?

2021-06-14 17:40 UTC, guillett commented on src/lib/State/generator.js
> +      throw Error("" + b + " (" + (b instanceof Array ? "array" : "?") + ")")
Oui effectivement, ça pourrait être amélioré. Cela dit, pour clarifier, c'est de la logique qui a été déplacée, ce n'est pas du nouveau code.

2021-06-14 17:40 UTC, guillett commented on src/store.js
>      },
Pourquoi avoir modifié le store ? Le numéro de version ne devrait pas être remis à zéro.

2021-06-15 08:47 UTC, Kout95 commented on src/store.js
>      },
Je corrige ça merci

2021-06-15 08:59 UTC, Kout95 commented on src/components/BaseLayout.vue
> +      return this.$store.getters.getMobileMenu
En effet le code n'était plus utilisé après le passage en router, je viens de supprimer cette partie

2021-06-15 10:02 UTC, Kout95 commented
> * Sur mobile, la barre 1J1S + le titre + le bouton toutes les étapes prennent plus de 1/3 de l'écran, ça me semble problématique.
>   
>   * Est ce que tu pourrais tenter de déplacer le bouton Toutes les étapes pour le mettre entre le bouton précédent et suivant (et peut-être supprimé la flèche vers la gauche du bouton précédent qui prend de la place sweat_smile )
> * Le bouton Retour sur la vue Sommaire bouge au clic.

L'espace est beaucoup trop juste pour les petits écrans : 
![avec un iphone 5](https://user-images.githubusercontent.com/65901733/122034189-8b11f180-cdd1-11eb-9e04-c5892893738c.png)

2021-06-15 10:39 UTC, Kout95 commented
J'ai essayé d'ajuster ça qu'en penses-tu @guillett ?
![image](https://user-images.githubusercontent.com/65901733/122038990-7d129f80-cdd6-11eb-865a-9d0871069861.png)

2021-06-15 15:22 UTC, guillett requested changes
C'est top, merci @Kout95 pour avoir fait aboutir cette PR. Avant de la valider, est-ce-que tu peux faire un rebase et me redemander une revue ? Il faudrait prendre en compte les aspects d'accessibilité (je pense qu'on est globalement bon) et s'assurer de bien gérer les conflits avec les branches récemment mergées. Merci !

2021-06-16 08:31 UTC, Kout95 commented
@guillett Je viens de faire le merge.
Vérifications effectuées :
- code sur github :heavy_check_mark:
- Test en utilisateur mobile :heavy_check_mark: 
- Test en utilisateur desktop clavier :heavy_check_mark: => le sommaire est facilement accessible pour un utilisateur clavier

2021-06-16 13:08 UTC, guillett approved these changes
:tada: :tada: Encore un beau morceau qui avance ! C'est top, bravo @ClementNumericite et @Kout95  !

2021-06-16 13:32 UTC, merged