Feature/accessibilite
betagouv/aides-jeunes pull request #1625
Opened 2021-05-03 12:25 UTC by ClementNumericite

2021-05-03 12:27 UTC, ClementNumericite commented
Utilisation du plugin WAVE pour détecter les erreurs et alertes d'accessibilité.

Une erreur de contraste subsiste sur les boutons outline (je vais voir avec augustin ce qu'on peut faire) :
![Capture du 2021-05-03 14-21-26](https://user-images.githubusercontent.com/80679266/116875708-a5c24980-ac1b-11eb-92ff-598c9b4d75cc.png)
![Capture du 2021-05-03 14-21-19](https://user-images.githubusercontent.com/80679266/116875712-a65ae000-ac1b-11eb-9733-1e3a2b2e0f19.png)

2021-05-03 12:29 UTC, ClementNumericite commented
Également le plugin n'aime pas qu'il y ait une balise <noscript> pour les navigateurs où javascript est disable. Après quelques recherche je ne vois pas d'alternative simple pour éviter cette alerte. ([cf ce lien](https://webaim.org/techniques/javascript/alternatives#noscript))

2021-05-04 10:46 UTC, ClementNumericite commented
Tests effectués avec un screenreader chrome ([plugin](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn/related?hl=fr)). L'auto-submit est vraiment pas accessible dans ce cas, impossible pour le reader de lire les réponses avant de les valider.
Pour le reste c'est OK.

2021-05-05 14:40 UTC, guillett commented
@ClementNumericite est ce que tu peux donner quelques détails des travaux menés sur [les 10 axes référencés](https://doc.incubateur.net/design/ressources-design/kit-accessibilite/accessibilite/10-choses-faciles-a-verifier-pour-un-site-plus-accessible) ?

2021-05-17 11:51 UTC, Kout95 commented
En plus de la remarque de @guillett,
un changement possible pour les svg est de mettre une balise title : 
https://developer.mozilla.org/fr/docs/Web/SVG/Element/title

C'est utile notamment lorsqu'on met un lien avec comme contenu unique un svg (sur wave).

2021-06-02 09:27 UTC, QuentinMadura commented
- [ ] Tester le site avec Ansi
- [ ] Le titre des pages
- [ ] Les alternatives aux images
- [ ] La hiérarchie de l’information
- [ ]  Les contraste des couleurs
- [ ] La personnalisation du texte
- [ ] La navigation au clavier
- [ ] Les formulaires
- [ ] Les alternative aux médias
- [ ] La structure des pages

2021-06-02 16:21 UTC, Kout95 commented
Je viens d'ajouter les titres pour la partie ma simulation et mes résultats pour augmenter partiellement l'accessibilité.
Suite à la tâche du sommaire il pourrait être intéressant de changer le titre en fonction du chapitre et/ou de la question.

2021-06-15 10:38 UTC, guillett requested changes
Franchement, c'est hyper chouette les différentes touches ajoutées (indices visuels, etC.) 

J'ai fait des commentaires/suggestions.

Sur la home, la navigation par tabulation repart du début de la page alors qu'en prod, il y a le focus sur le h1 et dès la première tabulation on est sur le bouton Je commence.

2021-06-15 10:38 UTC, guillett commented on src/components/Ressource/Montants.vue
> +    </legend>
`legend` n'est adapté qu'aux `fieldsets`.
```suggestion
    <h2 v-if="!withoutHeader">{{ type.meta.label }}</h2>
```

2021-06-15 10:38 UTC, guillett commented on src/router.js
> +        headTitle: "Ma simulation sur le simulateur d'aides 1jeune1solution ",
```suggestion
        headTitle: "Ma simulation sur le simulateur d'aides 1jeune1solution",
```

2021-06-15 14:59 UTC, guillett approved these changes
:tada: Merci @ClementNumericite @QuentinMadura et @Kout95  pour cette belle PR, on va mettre ça dans les mains d'usager en situation de handicap visuel pour savoir si on va dans la bonne direction ! :clap:

2021-06-15 15:02 UTC, merged