Feature/filtre dynamique etablissements
betagouv/aides-jeunes pull request #1662
Opened 2021-05-27 09:41 UTC by QuentinMadura

2021-05-27 13:56 UTC, QuentinMadura commented
J'ai ajouté la majeure partie de la fonctionnalité (+ test). Il me manque plus qu'à implémenter le style global du composant qui n'est pas très propre.

2021-05-28 13:35 UTC, Kout95 commented
Pour la partie fonctionnelle j'ajouterais un bouton "réinitialiser" quand des filtres sont actifs

2021-06-10 12:39 UTC, Kout95 requested changes
Test réalisé avec 98800 (Nouméa) en Nouvelle Calédonie, il y a pas de résultat
![image](https://user-images.githubusercontent.com/65901733/121526172-6e547300-c9f9-11eb-878f-49a116560d66.png)

Suggestion :
Afficher un message disant qu'il n y a aucun résultat, et potentiellement retourner un event matomo quand la liste est vide

2021-06-10 16:24 UTC, QuentinMadura commented
Changé, merci @Kout95 !

2021-06-14 13:36 UTC, Kout95 commented on src/views/Simulation/Resultats/LieuxGeneriques.vue
> +          !item.isRelevant ||
Je me demande si ça pourrait pas être intéressant d'ajouter ça quand la liste est vide :
```
this.$matomo.trackEvent(
        "General",
        "Aucun établissement dans trouver de l'aide",
        `DEPCOM : ${
          this.$store.state.situation.menage.depcom
        } ; Age : ${Individu.age(
          this.$store.state.situation.demandeur.date_naissance,
          this.$store.state.situation.dateDeValeur
        )} ;
        Activite : ${this.$store.state.situation.demandeur.activite} ;
        Handicap : ${this.$store.state.situation.demandeur.handicap}`
      )

2021-06-14 13:37 UTC, Kout95 commented on src/views/Simulation/Resultats/LieuxGeneriques.vue
> +          !item.isRelevant ||
@QuentinMadura @guillett

2021-06-14 13:46 UTC, Kout95 approved these changes

2021-06-14 13:46 UTC, merged