Ajoute un message indiquant la non fiabilité du simulateur pour la Nouvelle  Calédonie
betagouv/aides-jeunes pull request #1684
Opened 2021-06-10 09:10 UTC by QuentinMadura

Cette PR permet d'ajouter un message indiquant la non fiabilité du simulateur pour la Nouvelle Calédonie

2021-06-14 12:29 UTC, Kout95 requested changes

2021-06-14 12:29 UTC, Kout95 commented on src/views/Simulation/Menage/Depcom.vue
> +              communeCode98[this.codePostalQuestion.selectedValue] &&
Pour faire le lien avec cette tâche similaire : [](https://trello.com/c/5fwfgyHw/207-ajouter-un-message-dattention-limitation-pour-les-villes-de-mayotte ).
J'adapterais cette condition à tous les codes postaux supérieurs à 95 avec le message suivant : 
"Attention, les calculs du simulateur sont peu fiables pour les départements hors de la France métropolitaine."

2021-06-14 15:33 UTC, QuentinMadura commented on src/views/Simulation/Menage/Depcom.vue
> +              communeCode98[this.codePostalQuestion.selectedValue] &&
J'ai légèrement changé la logique pour que l'on puisse adapter les messages d'erreurs en fonction de différentes variations

2021-06-14 15:39 UTC, guillett commented on src/views/Simulation/Menage/Depcom.vue
> +              communeCode98[this.codePostalQuestion.selectedValue] &&
@Kout95, le simulateur n'est pas limité pour tous les territoires ultramarins, il est sensé fonctionner correctement en Guadeloupe, Martinique notamment.

2021-06-14 15:40 UTC, guillett requested changes
@QuentinMadura pourquoi n'as-tu pas utilisé un `computed` ? Là, il y a un side effect au `asyncComputed` qui me parait pas très recommandé.

2021-06-15 07:15 UTC, QuentinMadura commented
> @QuentinMadura pourquoi n'as-tu pas utilisé un `computed` ? Là, il y a un side effect au `asyncComputed` qui me parait pas très recommandé.

Merci pour le retour, j'ai effectué les changements !

2021-06-15 16:12 UTC, Kout95 requested changes

2021-06-15 16:12 UTC, Kout95 commented on src/lib/Warnings.js
> +      if (variation === "97600")
Ca ne fonctionne pas pour toutes les communes de mayotte
https://fr.wikipedia.org/wiki/Bandraboua

2021-06-15 16:31 UTC, guillett commented on src/lib/Warnings.js
> +      if (variation === "97600")
Dans certains cas, il ne faut pas hésiter à faire de l'[archéologie](https://github.com/betagouv/aides-jeunes/commit/463da290ab66afb427eb41906cc95801ff9ba797#diff-de26039efda0fe31239628265fa5e05c2d3967532a0af44661e1e2615e18324bL270).

ou https://github.com/betagouv/aides-jeunes/search?q=mayotte&type=commits

2021-06-16 09:36 UTC, QuentinMadura commented on src/lib/Warnings.js
> +      if (variation === "97600")
Merci, je pensais que Mayotte était une commune et non un département ! J'ai remplacé `(variation === "97600")` par `(variation.startsWith( "97600")`

2021-06-17 07:54 UTC, Kout95 approved these changes

2021-06-21 09:39 UTC, guillett approved these changes
J'ai ajouté un commit pour peaufiner la PR.

2021-06-21 10:32 UTC, merged