Corrige l'input number pour éviter de pouvoir submit un formulaire en complétant une fausse valeur
betagouv/aides-jeunes pull request #1698
Opened 2021-06-17 07:02 UTC by Kout95

2021-06-23 12:31 UTC, guillett requested changes

2021-06-23 12:31 UTC, guillett commented on src/components/InputNumber.vue
> +    </div>
Le rouge utilisé n'est pas accessible à cause d'un mauvais contraste avec la couleur d'arrière plan.

2021-06-28 08:49 UTC, Kout95 commented on src/components/InputNumber.vue
> +    </div>
C'est corrigé !

2021-07-12 06:28 UTC, guillett approved these changes

2021-07-12 10:47 UTC, merged