Répare les inputs date en format mobile
betagouv/aides-jeunes pull request #1701
Opened 2021-06-17 13:23 UTC by QuentinMadura

Ancienne version : 
![Screenshot 2021-06-17 at 15 22 52](https://user-images.githubusercontent.com/6544169/122404969-f0a3e080-cf7f-11eb-99c3-53c26a719111.png)
![Screenshot 2021-06-17 at 15 22 09](https://user-images.githubusercontent.com/6544169/122404975-f1d50d80-cf7f-11eb-992e-1d71b4a5d0fb.png)

2021-06-18 07:51 UTC, guillett commented
Ça ne répare pas la situation chez moi


Avant
![avant](https://user-images.githubusercontent.com/1410356/122526566-bc313280-d01a-11eb-8cdc-1afa49ddee46.png)

Apres
![apres](https://user-images.githubusercontent.com/1410356/122526563-bb989c00-d01a-11eb-9a81-2f5cb4719b2f.png)

2021-06-24 08:27 UTC, QuentinMadura commented
Avant : 
![Screenshot_20210624_102517_com brave browser](https://user-images.githubusercontent.com/6544169/123229556-b5049b80-d4d6-11eb-961e-0e246c5f5e93.jpg)
Après :
![Screenshot_20210624_102522_com brave browser](https://user-images.githubusercontent.com/6544169/123229564-b635c880-d4d6-11eb-8ee0-c65009ecdcb3.jpg)

2021-06-24 15:33 UTC, Kout95 requested changes

2021-06-24 15:33 UTC, Kout95 commented on src/styles/partials/tablet/_inputs.scss
> +        width: 80px;
le `.aj-input-date` sert à supprimer `!important` qui peut devenir problématique et qui n'est pas utile dans le cas présent.

2021-06-25 07:30 UTC, QuentinMadura commented on src/styles/partials/tablet/_inputs.scss
> +        width: 80px;
👍

2021-07-01 10:20 UTC, Kout95 approved these changes

2021-07-05 13:41 UTC, merged