Améliore la visualisation des pages
betagouv/aides-jeunes pull request #1703
Opened 2021-06-18 08:36 UTC by Kout95

2021-06-21 10:39 UTC, Kout95 commented
Corrige les pages avec du texte :
![image](https://user-images.githubusercontent.com/65901733/122749410-98295780-d28d-11eb-8c07-8ed2ada35847.png)
Résultat : 
![image](https://user-images.githubusercontent.com/65901733/122749547-c313ab80-d28d-11eb-8045-73f2f02a5aab.png)

2021-06-22 09:01 UTC, guillett requested changes
J'ai l'impression que cette PR cache sous le tapis le problème. De plus, j'ai l'impression que c'est un problème CSS mais la solution implique du JS. On peut prendre le temps de ralentir pour corriger [certaines choses qu'on a fait quand on a été vite](https://github.com/betagouv/aides-jeunes/pull/1603/files#diff-1a49d57c3c90f791b39637e2f17a2b8c88e6ccdccc75c2bb48da311ef44cffa7R3).

D'une certaine façon, je m'attends à ce qu'une telle PR rembourse de la dette technique (et très probablement, diminue le nombre de lignes de code dans le projet).

2021-06-24 14:46 UTC, Kout95 commented
En effet, je viens de déplacer la correction pour visualiser en bleu la partie de droite uniquement dans les pages de simulations

2021-07-08 12:17 UTC, Kout95 commented
@guillett cette branche devrait pouvoir passer :)

2021-07-12 06:30 UTC, guillett approved these changes

2021-07-12 06:32 UTC, merged