Ajouter des conditions textuelles pour la BCS
betagouv/aides-jeunes pull request #1706
Opened 2021-06-21 07:58 UTC by Kout95

2021-06-21 08:09 UTC, guillett requested changes

2021-06-21 08:09 UTC, guillett commented on data/benefits/bourse_criteres_sociaux.yml
> +  - Avoir au moins validé 180 crédits ECTS pour le 6ème et 7ème droit à la bourse.
Ces 3 conditions me semblent trop précises pour être afficher à tous les usagers. Je pense que ce sont des critères très généralement satisfaits et donc peu générateurs de frustration. Je pense que c'est bien de ne pas les afficher.

2021-06-21 08:13 UTC, Kout95 commented on data/benefits/bourse_criteres_sociaux.yml
> +  - Avoir au moins validé 180 crédits ECTS pour le 6ème et 7ème droit à la bourse.
Ok :)

2021-06-23 07:57 UTC, guillett approved these changes

2021-06-23 11:33 UTC, merged