Ajoute l'aide au mérite
betagouv/aides-jeunes pull request #1714
Opened 2021-06-24 14:20 UTC by QuentinMadura

2021-06-28 08:07 UTC, Kout95 requested changes

2021-06-28 08:07 UTC, Kout95 commented on src/lib/IndividuQuestions.js
> +    question: "Avez-vous obtenu une mention au baccalauréat  ?",
Remplacer le double espace par un seul espace insécable

2021-06-28 08:12 UTC, Kout95 requested changes

2021-06-28 08:12 UTC, Kout95 commented on src/lib/Individu.js
> +      label: "Mention très bien avec félicitations du jury",
Est-il nécessaire d'avoir `Mention très bien avec félicitations du jury` lorsqu'on a `Mention très bien` dans le cas où ça n'impacte pas le calcul de l'aide ?

2021-06-28 08:12 UTC, Kout95 commented on src/lib/Individu.js
> +      label: "Mention très bien avec félicitations du jury",
@guillett

2021-08-11 09:31 UTC, Kout95 requested changes

2021-08-11 09:31 UTC, Kout95 commented on src/lib/Individu.js
> +  mentionsBaccalaureat: [
Est-ce utile de le mettre dans individu si il n'est utilisé que dans individuQuestions ?

2021-08-11 09:31 UTC, Kout95 commented on data/benefits/aide_merite_eligibilite.yml
> +label: Aide au mérite
Pourquoi avoir choisi `aide_merie_eligibilite` alors que la variable : `aide_merite_montant` existe ?

2021-09-09 09:33 UTC, QuentinMadura commented on data/benefits/aide_merite_eligibilite.yml
> +label: Aide au mérite
Merci 👍 . J'ai changé la variable suite au changement de période de cette aide sur [Openfisca](https://github.com/openfisca/openfisca-france/pull/1670)

2021-09-09 09:46 UTC, Kout95 requested changes

2021-09-09 09:46 UTC, Kout95 commented on data/benefits/aide_merite_montant.yml
> +description: L'aide au mérite est une aide de 900€ qui concerne les étudiants ayant reçu une mention "très bien" durant la dernière session du baccalauréat.
Le montant pouvant varier je supprimerais cette info de la description

2021-09-09 10:14 UTC, Kout95 approved these changes

2021-09-09 10:15 UTC, merged

2021-09-09 10:15 UTC, Kout95 commented
Merci @QuentinMadura