Répare la page attendu
betagouv/aides-jeunes pull request #1717
Opened 2021-06-30 09:32 UTC by QuentinMadura

2021-07-12 08:13 UTC, Kout95 commented on src/router.js
> +      path: "/resultats/attendu",
Pourquoi ce changement ? Et pourquoi ne pas le laisser dans simulation ?

2021-07-16 07:20 UTC, QuentinMadura commented on src/router.js
> +      path: "/resultats/attendu",
Réparé ! 👍

2021-07-19 13:49 UTC, guillett commented on src/views/Foyer/Resultat/Attendu.vue
>      },
Je trouve ça bizarre d'utiliser une `method` plutôt qu'une `computed` (lié à https://github.com/betagouv/aides-jeunes/pull/1652/files#r672313840)

2021-07-19 13:50 UTC, guillett commented on src/views/Foyer/Resultat/Attendu.vue
> +    extensionAndRepository() {
Étant donné que la logique à un peu changer cet attribut n'est plus utile.

2021-07-19 13:51 UTC, guillett requested changes
Il y a un peu de code mort à supprimer avant de pouvoir merge.

2021-07-19 14:33 UTC, QuentinMadura commented
Merci @guillett , je viens d'effectuer les changements

> Il y a un peu de code mort à supprimer avant de pouvoir merge.

2021-07-22 16:11 UTC, guillett commented
Il faudrait que la liste des aides soit par ordre alphabétique pour que ça soit plus facile pour les usagers de retrouver l'aide qu'il recherche.

2021-07-29 06:17 UTC, guillett approved these changes
J'ai appliqué quelques correctifs en les distinguant dans des commits séparés pour relecture.

Les fichiers YAML générés ne peuvent pas être utilisés sur OpenFisca-France sans charger toutes les extensions en même temps (France-Local et Paris) car les variables de ces extensions sont conservées dans le fichier YAML alors qu'elles devraient être supprimées.

J'ai commencé une PR sur ce sujet (avec, au départ, un objectif un peu différent, qui était de mieux vérifier la bonne prise en compte des changements majeurs dans OpenFisca-France).

2021-07-29 06:59 UTC, merged