Supprime un fichier inutilisé
betagouv/aides-jeunes pull request #1723
Opened 2021-07-07 13:49 UTC by Kout95

2021-07-16 09:34 UTC, Kout95 commented
Ok mais nécessite de passer la PR suivante pour fonctionner : https://github.com/openfisca/openfisca-france/pull/1591

2021-07-30 08:29 UTC, guillett commented
Note : L'utilisation de merge commit dans les branches rends la réutilisation de ces branches complexes car l'historique contient plusieurs branches (les commits et les branches mergées). Faire un rebase de cette branche est assez laborieux surtout que des dévs sont faits puis défaits mais que la gestion des conflits doit être faits sur chaque commit (alors que pour certains bouts de code les conflits n'existent plus à la fin).

2021-07-30 08:37 UTC, guillett commented
Note 2 : Pour m'en sortir, j'a fait un merge commit `git merge 1f493133`, un `git reset 1f493133` puis un `git commit -am "Intègre des modifications côté OpenFisca-France" --author="kout95 <antoine.bernier@outlook.fr>"`.

2021-07-30 10:18 UTC, guillett commented
- [ ] migration
- [ ] correction du problème de persistance des ressources annuelles N-1 (pour les AE)

2021-08-02 15:50 UTC, Kout95 commented
> Reste à faire :
> 
> * [x]  migration
> * [x]  correction du problème de persistance des ressources annuelles N-1 (pour les AE)
> * [ ]  Gérer l'utilisation de `famille.bourse_lycee` à la place de `individu.aide_mobilite_parcoursup_boursier_lycee`
>   
>   * changement de la route ?
>   * gestion de la logique de surcharge ?

Pour etre sur de rien oublier de quoi parles tu pour `gestion de la logique de surcharge ?` ?

2021-08-04 10:08 UTC, guillett requested changes
Il y a des erreurs dans la CI et des console.log dans les test.

2021-08-06 07:38 UTC, Kout95 commented
Mon message ne s'est pas envoyé... Les tests et les lints sont corrigés

2021-08-06 07:54 UTC, Kout95 commented
Néanmoins il reste le bug avec openfisca que je n'ai pas en local. Connais-tu son origine, où il faut que j'inspecte ça en détail ?

2021-08-09 09:17 UTC, guillett approved these changes
Merci pour la nouvelle passe !

2021-08-09 09:22 UTC, merged