Mutualise les questions dans individu
betagouv/aides-jeunes pull request #1729
Opened 2021-07-13 09:11 UTC by Kout95

2021-08-04 12:42 UTC, guillett requested changes
C'est chouette de continuer à mutualiser ! J'ai fait une première passe mais je ferais des tests quand il y aura plus de conflits avec master.

2021-08-09 09:23 UTC, guillett requested changes
Même remarque avec le _merge_ de #1723

2021-08-09 09:54 UTC, Kout95 commented
Merci pour ton retour, je viens de nettoyer ça

2021-08-09 14:16 UTC, guillett approved these changes
Merci beaucoup !

2021-08-09 14:16 UTC, merged