ajoute une question pour les alternants pour connaitre leur type de c…
betagouv/aides-jeunes pull request #1739
Opened 2021-08-02 12:45 UTC by Kout95

…ontrat

2021-08-02 12:51 UTC, guillett commented on src/lib/IndividuQuestions.js
> +      },
```suggestion
    question: "Êtes-vous ?",
    questionType: "enum",
    items: [
      {
        value: "apprenti",
        label: "En alternance",
      },
      {
        value: "professionnalisation",
        label: "En contrat de professionnalisation",
      },
```

2021-08-02 13:09 UTC, Kout95 commented on src/lib/IndividuQuestions.js
> +      },
L'utilisateur risque pas de répondre non à `Etes-vous en alternance ?` si il est en contrat de professionnalisation ?

2021-08-02 13:17 UTC, guillett commented on src/lib/IndividuQuestions.js
> +      },
Merci pour ta viligence, j'avais mis _en alternance_ à la place de _en apprentissage_.

2021-08-02 13:42 UTC, Kout95 commented
C'est bon pour moi :)

2021-08-04 09:07 UTC, guillett commented
As-tu réussi à afficher sur la page de résultats, l'aide correspondant à `aide_financement_permis_apprenti` ?

2021-08-04 09:08 UTC, guillett commented on backend/lib/definitions.js
> +    _contrat_alternant: String,
```suggestion
    _contrat_alternant: {
      type: String,
      enum: ["apprenti", "professionnalisation"],
    },
```

2021-08-04 09:09 UTC, guillett requested changes
Je pense que ça vaut le coup de spécifier les valeurs possibles pour l'énum.

2021-08-04 09:32 UTC, Kout95 commented
> As-tu réussi à afficher sur la page de résultats, l'aide correspondant à `aide_financement_permis_apprenti` ?
Oui :)
![image](https://user-images.githubusercontent.com/65901733/128158133-e6d9ee62-cc08-45da-8b4c-b67912fe9a32.png)

2021-08-04 10:12 UTC, guillett approved these changes
:+1:

2021-08-04 10:12 UTC, merged