Ajoute l'aide mon job mon logement
betagouv/aides-jeunes pull request #1745
Opened 2021-08-09 08:57 UTC by Kout95

2021-09-08 14:34 UTC, QuentinMadura requested changes

2021-09-09 07:14 UTC, Kout95 commented on backend/lib/openfisca/mapping/menage/index.js
> +  return date && moment(date).format("YYYY-MM-DD")
Je viens de remplacer ça

2021-09-09 12:49 UTC, QuentinMadura approved these changes

2021-09-09 12:49 UTC, merged

2021-09-09 15:29 UTC, guillett commented on src/lib/State/blocks.js
> +              steps: [r("contrat_de_travail_debut")],
Cette question est posée à vraiment beaucoup de monde et c'est une question compliquée. N'est-ce pas possible de poser une question supplémentaire par exemple « Avez-vous signé votre contrat de travail après XXX ? »

2021-09-09 15:29 UTC, guillett commented on src/lib/State/blocks.js
> +              steps: [r("contrat_de_travail_debut")],
Les dates précises c'est quand même difficile, les mois ne suffissent pas ?

2021-09-09 15:36 UTC, guillett commented on src/lib/State/blocks.js
> +              steps: [r("contrat_de_travail_debut")],
J'ai regardé la PR sur OpenFisca et je pense qu'on peut limiter le travail qu'on demande aux usager en posant des questions plus simple.

« Avez-vous signé votre contrat il y a moins de 3/6 mois ? »
« Avez-vous emménagé dans votre logement il y a moins de 3 mois  ? » 

https://github.com/openfisca/openfisca-france/pull/1586/files#diff-4e5c99aea126ee18ecb5e0413a503c356710faa3a4cfa8fef7c452faf826f46bR25