Affiche les montants dans les emails
betagouv/aides-jeunes pull request #1772
Opened 2021-08-27 14:52 UTC by Kout95

2021-09-01 06:51 UTC, Kout95 commented
@QuentinMadura pour tester tu peux lancer la commande `node mjml.js`

2021-09-01 13:55 UTC, QuentinMadura commented
Route d'API vous visualiser l'email : http://localhost:9001/mjml/{situationID}/initial

2021-09-01 14:01 UTC, QuentinMadura requested changes
Je vois deux améliorations possibles au regard de la situation que j'ai reçu par mail (cf le payload de la situation pour reproduire le problème) :
- 
![Screenshot 2021-09-01 at 15 55 30](https://user-images.githubusercontent.com/6544169/131685146-49dbf1ca-55aa-42b0-90f1-4135f0ddbfc4.png)
le montant de l'aide s'affiche avec de multiples chiffres après la virgule. 
- la première lettre du nom des aides peuvent être mise en lettre majuscule. 

```
{
    "_id" : ObjectId("612f844719e540889c7a4cf3"),
    "conjoint" : null,
    "status" : "new",
    "dateDeValeur" : ISODate("2021-09-01T13:43:03.000Z"),
    "enfants" : [],
    "famille" : {
        "en_couple" : false
    },
    "foyer_fiscal" : {},
    "menage" : {
        "aide_logement_date_pret_conventionne" : "2018-12-31",
        "statut_occupation_logement" : "sans_domicile",
        "depcom" : "95563",
        "_codePostal" : "95320",
        "_nomCommune" : "Saint-Leu-la-Forêt"
    },
    "parents" : {
        "_situation" : "sans_autorite"
    },
    "version" : 3,
    "demandeur" : {
        "id" : "demandeur",
        "date_naissance" : ISODate("1995-05-01T22:00:00.000Z"),
        "nationalite" : "FR",
        "_role" : "demandeur",
        "activite" : "etudiant",
        "scolarite" : "grande_ecole_du_numerique",
        "alternant" : false,
        "handicap" : false,
        "_continuite_etudes" : false,
        "plus_haut_diplome_niveau" : "niveau_8",
        "plus_haut_diplome_date_obtention" : ISODate("2018-02-02T23:00:00.000Z"),
        "_boursier_derniere_annee_etudes" : false,
        "statut_marital" : "celibataire",
        "_interetPermisDeConduire" : false
    },
    "modifiedFrom" : "612f838319e540889c7a4cf2",
    "abtesting" : {
        "submit" : {
            "index" : 1,
            "deleted" : true,
            "value" : "manual"
        }
    },
    "createdAt" : ISODate("2021-09-01T13:46:47.334Z"),
    "token" : "9Ead2xcKIqcoXO9aVinUJjMkCRtHAIhUla_AYZeYuOJggONv8Q5tOf6Bl103gMvJ",
    "__v" : 0
}
```

2021-09-02 09:20 UTC, Kout95 commented
> Je vois deux améliorations possibles au regard de la situation que j'ai reçu par mail (cf le payload pour reproduire la situation) :
> 
> * le montant de l'aide s'affiche avec de multiples chiffres après la virgule.
> * la première lettre du nom des aides peuvent être mise en lettre majuscule.
> 
> ```
> {
>     "_id" : ObjectId("612f844719e540889c7a4cf3"),
>     "conjoint" : null,
>     "status" : "new",
>     "dateDeValeur" : ISODate("2021-09-01T13:43:03.000Z"),
>     "enfants" : [],
>     "famille" : {
>         "en_couple" : false
>     },
>     "foyer_fiscal" : {},
>     "menage" : {
>         "aide_logement_date_pret_conventionne" : "2018-12-31",
>         "statut_occupation_logement" : "sans_domicile",
>         "depcom" : "95563",
>         "_codePostal" : "95320",
>         "_nomCommune" : "Saint-Leu-la-Forêt"
>     },
>     "parents" : {
>         "_situation" : "sans_autorite"
>     },
>     "version" : 3,
>     "demandeur" : {
>         "id" : "demandeur",
>         "date_naissance" : ISODate("1995-05-01T22:00:00.000Z"),
>         "nationalite" : "FR",
>         "_role" : "demandeur",
>         "activite" : "etudiant",
>         "scolarite" : "grande_ecole_du_numerique",
>         "alternant" : false,
>         "handicap" : false,
>         "_continuite_etudes" : false,
>         "plus_haut_diplome_niveau" : "niveau_8",
>         "plus_haut_diplome_date_obtention" : ISODate("2018-02-02T23:00:00.000Z"),
>         "_boursier_derniere_annee_etudes" : false,
>         "statut_marital" : "celibataire",
>         "_interetPermisDeConduire" : false
>     },
>     "modifiedFrom" : "612f838319e540889c7a4cf2",
>     "abtesting" : {
>         "submit" : {
>             "index" : 1,
>             "deleted" : true,
>             "value" : "manual"
>         }
>     },
>     "createdAt" : ISODate("2021-09-01T13:46:47.334Z"),
>     "token" : "9Ead2xcKIqcoXO9aVinUJjMkCRtHAIhUla_AYZeYuOJggONv8Q5tOf6Bl103gMvJ",
>     "__v" : 0
> }
> ```
> 
> ![Screenshot 2021-09-01 at 15 55 30](https://user-images.githubusercontent.com/6544169/131685146-49dbf1ca-55aa-42b0-90f1-4135f0ddbfc4.png)

Je viens de faire les correctifs

2021-09-02 09:21 UTC, QuentinMadura commented
> > Je vois deux améliorations possibles au regard de la situation que j'ai reçu par mail (cf le payload pour reproduire la situation) :
> > 
> > * le montant de l'aide s'affiche avec de multiples chiffres après la virgule.
> > * la première lettre du nom des aides peuvent être mise en lettre majuscule.
> > 
> > ```
> > {
> >     "_id" : ObjectId("612f844719e540889c7a4cf3"),
> >     "conjoint" : null,
> >     "status" : "new",
> >     "dateDeValeur" : ISODate("2021-09-01T13:43:03.000Z"),
> >     "enfants" : [],
> >     "famille" : {
> >         "en_couple" : false
> >     },
> >     "foyer_fiscal" : {},
> >     "menage" : {
> >         "aide_logement_date_pret_conventionne" : "2018-12-31",
> >         "statut_occupation_logement" : "sans_domicile",
> >         "depcom" : "95563",
> >         "_codePostal" : "95320",
> >         "_nomCommune" : "Saint-Leu-la-Forêt"
> >     },
> >     "parents" : {
> >         "_situation" : "sans_autorite"
> >     },
> >     "version" : 3,
> >     "demandeur" : {
> >         "id" : "demandeur",
> >         "date_naissance" : ISODate("1995-05-01T22:00:00.000Z"),
> >         "nationalite" : "FR",
> >         "_role" : "demandeur",
> >         "activite" : "etudiant",
> >         "scolarite" : "grande_ecole_du_numerique",
> >         "alternant" : false,
> >         "handicap" : false,
> >         "_continuite_etudes" : false,
> >         "plus_haut_diplome_niveau" : "niveau_8",
> >         "plus_haut_diplome_date_obtention" : ISODate("2018-02-02T23:00:00.000Z"),
> >         "_boursier_derniere_annee_etudes" : false,
> >         "statut_marital" : "celibataire",
> >         "_interetPermisDeConduire" : false
> >     },
> >     "modifiedFrom" : "612f838319e540889c7a4cf2",
> >     "abtesting" : {
> >         "submit" : {
> >             "index" : 1,
> >             "deleted" : true,
> >             "value" : "manual"
> >         }
> >     },
> >     "createdAt" : ISODate("2021-09-01T13:46:47.334Z"),
> >     "token" : "9Ead2xcKIqcoXO9aVinUJjMkCRtHAIhUla_AYZeYuOJggONv8Q5tOf6Bl103gMvJ",
> >     "__v" : 0
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Screenshot 2021-09-01 at 15 55 30](https://user-images.githubusercontent.com/6544169/131685146-49dbf1ca-55aa-42b0-90f1-4135f0ddbfc4.png)
> 
> Je viens de faire les correctifs

Corrigé ensemble, merci 👍

2021-09-02 09:22 UTC, QuentinMadura approved these changes

2021-09-02 09:43 UTC, merged