Ajoute le service civique dans les activités possibles
betagouv/aides-jeunes pull request #1776
Opened 2021-09-02 13:31 UTC by QuentinMadura

2021-09-06 08:10 UTC, Kout95 commented
Les changements pour openfisca me paraissent bons. Néanmoins pour la partie aides jeunes il manque les modifications liées à l'activité. Une des modifications à faire est s'assurer que les personnes en service civique passent bien par le chemin d'un actif si on les considère comme tels. Il faut vérifier d'autres endroits potentiels où la variable `activite` peut changer le parcours utilisateur.

2021-09-06 08:10 UTC, Kout95 requested changes
Les changements pour openfisca me paraissent bons. Néanmoins pour la partie aides jeunes il manque les modifications liées à l'activité. Une des modifications à faire est s'assurer que les personnes en service civique passent bien par le chemin d'un actif si on les considère comme tels. (block.js)
Il faut vérifier d'autres endroits potentiels où la variable activite peut changer le parcours utilisateur.

2021-09-07 10:07 UTC, QuentinMadura commented
Merci @Kout95 pour les remarques. Je viens d'ajouter les modifications dans le (commit)[https://github.com/betagouv/aides-jeunes/commit/079501ad3ecc8e8b75eb307efd09164aa38046d9]

2021-09-07 10:27 UTC, Kout95 approved these changes

2021-09-07 12:53 UTC, merged