Review stats page
betagouv/aides-jeunes pull request #1790
Opened 2021-09-20 07:45 UTC by desoindx

2021-09-20 09:02 UTC, Kout95 requested changes
Merci @desoindx ! Il faut corriger les lints `npm run prettier:fix`.

2021-09-20 09:03 UTC, Kout95 commented on src/views/Stats.vue
> -    <p
Pourquoi avoir remplacé la balise `p` par `div` ?

2021-09-20 09:06 UTC, Kout95 commented
Également peux-tu mettre dans la description de la PR le but des ces modifications que tu nous a expliqué par visio. Merci !

2021-09-23 07:19 UTC, desoindx commented on src/views/Stats.vue
> -    <p
Parceque le p a des marges par defauts qui alourdissaient la lisibilité du texte, une div permet juste une mise a la ligne

2021-09-23 10:37 UTC, Kout95 commented on src/views/Stats.vue
> -    <p
Ok :)

2021-09-23 10:40 UTC, Kout95 approved these changes

2021-09-23 10:41 UTC, merged