Improve spacing of simulation questions
betagouv/aides-jeunes pull request #1797
Opened 2021-09-24 12:59 UTC by desoindx

Various modificiation of the css

2021-09-27 12:28 UTC, Kout95 requested changes
C'est plus propre avec cet espace.
Néanmoins un `margin-bottom` essentiel servant de marge pour les boutons en positon absolute a été retiré. Les boutons passent au dessus du footer pour les questions plus longues :

![image](https://user-images.githubusercontent.com/65901733/134907539-10b6704a-b61a-47a1-b185-df38f893c6b3.png)

2021-09-29 10:14 UTC, Kout95 commented
Je viens de faire une passe de correction c'est bon pour moi :smile: 

@guillett je te laisse checker si les placements te conviennent :
- taille du formulaire
- boutons précédent et suivant alignés aux inputs
- input date avec les titres centrés par rapport aux champs (jour, mois, année)
- bouton ajouter un enfant aligné à la qustion

2021-09-29 10:14 UTC, Kout95 approved these changes

2021-09-29 10:42 UTC, Kout95 commented
je regarde le test_e2e après manger

2021-09-29 12:41 UTC, guillett commented
Merci @Kout95 ! Je vais laisser @desoindx faire le retour, il avait implémenté une certaine logique (des multiples de 8 et des 8/4/2/1/0.5, etc.) Si c'est bon pour lui c'est bon pour moi. :)

2021-09-30 06:54 UTC, desoindx reviewed
Ok pour moi

2021-09-30 08:27 UTC, merged