Simplifie la manipulation d'aide
betagouv/aides-jeunes pull request #1944
Opened 2021-11-22 11:31 UTC by Kout95

2021-12-06 10:30 UTC, Cugniere requested changes

2021-12-06 10:30 UTC, Cugniere commented on backend/lib/mes-aides/emails/initial.js
> +      imgSrc: "/img/" + droit.institution.imgSrc,
Il faudrait qu'on définisse une norme, mais de mon point de vue en terme de concaténation de chaîne de caractères ça pourrait être plus propre d'utiliser des littéraux de gabarit plutôt que de `+` : 
```javascript
imgSrc: `/img/${droit.provider.imgSrc}`,
```

2021-12-06 10:30 UTC, Cugniere commented on backend/lib/openfisca/test.js
> +  .forEach((benefit) => {
Je suis d'accord que c'est plus propre d'utiliser `filter` pour des conditions, mais là au final on se retrouve à boucler deux fois sur les aides au lieu d'une. 

Ça reste une complexité linéaire O(n) donc ça n'impacte pas vraiment les perfs et pour moi ça peut rester en l'état, mais il faut faire gaffe à ne pas faire passer la lisibilité du code avant la performance

2021-12-06 10:30 UTC, Cugniere commented on lib/Benefits/Compute.js
> +        benefit.id + "_non_calculable",
Idem qu'au dessus pour la concaténation

2021-12-06 10:30 UTC, Cugniere commented on lib/Benefits/ComputeJavascript.js
> +    .forEach(function (benefit) {
Idem, pourquoi filter+forEach plutôt que rester sur un forEach ?

2021-12-06 10:30 UTC, Cugniere commented on testBenefitsUrls.js
> +  )
❤️

2021-12-06 17:09 UTC, Kout95 commented on backend/lib/mes-aides/emails/initial.js
> +      imgSrc: "/img/" + droit.institution.imgSrc,
je suis totalement d'accord, j'en profite pour le changer !

2021-12-06 17:09 UTC, Kout95 commented on src/views/Home.vue
> +    console.log(`Nombre d'aide local : ${count.local}`)
Je supprime

2021-12-06 17:26 UTC, Kout95 commented on backend/lib/openfisca/test.js
> +  .forEach((benefit) => {
Pour reprendre le 80 - 20 de Thomas, dans 80 % des cas la différence entre les old loop/forEach ne sont pas conséquentes. 
Tant que le changement n'est pas notable et que les performances ne sont pas nécessaires il me parait prématuré de chercher ce genre d'optimisation au détriment de la lisibilité de code.

2021-12-06 17:30 UTC, Kout95 commented on lib/Benefits/ComputeJavascript.js
> +    .forEach(function (benefit) {
Pour un souci de clarté, je trouve ça plus lisible qu'un early return ou un if qui créer une indentation.

2021-12-07 08:17 UTC, Cugniere commented on backend/lib/openfisca/test.js
> +  .forEach((benefit) => {
Yes pas de soucis

2021-12-07 08:17 UTC, Cugniere approved these changes

2021-12-07 08:20 UTC, Cugniere reviewed
La CI plante : https://app.netlify.com/sites/aides-jeunes/deploys/61ae48f51f070500077f4390

Dans `home.vue` on a l'import `Institution` qui ne sert plus à rien

2021-12-07 09:18 UTC, merged