[399] Séparer en deux dossiers les aides openfisca et les aides simples
betagouv/aides-jeunes pull request #1945
Opened 2021-11-24 08:01 UTC by Cugniere

2021-11-30 17:54 UTC, guillett commented
En échangeant cet après midi avec @clembiffaud et @charlottelecuit on a pensé à des améliorations mineures que j'ai mises dans la PR https://github.com/betagouv/aides-jeunes/pull/1947 je pensais te laisser les intégrer dans cette PR ou le faire plus tard.

2021-12-01 10:31 UTC, Cugniere commented
> En échangeant cet après midi avec @clembiffaud et @charlottelecuit on a pensé à des améliorations mineures que j'ai mises dans la PR #1947 je pensais te laisser les intégrer dans cette PR ou le faire plus tard.

C'est fait.

2021-12-01 15:10 UTC, Kout95 requested changes

2021-12-01 15:10 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +      - *field_entite_rattachement_openfisca
Pas utile

2021-12-01 15:10 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +      - *field_fiabilite_montant
pas utile

2021-12-01 15:10 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +  field_formulaire_imprimer: &field_formulaire_imprimer
```suggestion
  field_lien_formulaire: &field_lien_formulaire
```

2021-12-01 15:10 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +  field_instructions: &field_instructions
```suggestion
  field_lien_instructions: &field_lien_instructions
```

2021-12-01 15:10 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +  field_page_info_reference: &field_page_info_reference
```suggestion
  field_lien_plus_informations: &field_lien_plus_informations
```

2021-12-01 15:27 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +      - label: Régions
Ce field a été supprimé récemment au profit de conditions_generales

2021-12-01 15:27 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +      - label: Code des départements
idem que région

2021-12-01 15:27 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +      - label: Code INSEE des communes
idem que region

2021-12-01 15:50 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +    label: Aides complexes
ou simplement "Aide simple"

2021-12-01 15:50 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +    label_singular: Aide complexe
"Aide simple"

2021-12-01 16:00 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +    required: false
retirer le champ

2021-12-02 09:17 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +    label_singular: Aide simple
Corrigé.

2021-12-02 09:17 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +    label: Aides simples
Corrigé.

2021-12-02 09:18 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +  - name: benefits_javascript
Tranché en faveur de `benefits_javascript` et renommage de `computeFrontEndBenefits` en `computeJavascriptBenefits`

2021-12-02 09:18 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +    label: Aides complexes
Corrigé en `Aides avec critères d'éligibilités`

2021-12-02 09:19 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +    label_singular: Aide complexe
Renommé en "Aides avec critères d'éligibilités"

2021-12-02 09:36 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +  field_formulaire_imprimer: &field_formulaire_imprimer
Corrigé.

2021-12-02 09:36 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +  field_instructions: &field_instructions
Corrigé.

2021-12-02 09:37 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +  field_page_info_reference: &field_page_info_reference
Corrigé.

2021-12-02 09:37 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +      - label: Conditions générales à satisfaire simultanément
Corrigé.

2021-12-02 09:38 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +    required: false
Corrigé.

2021-12-02 09:39 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +      - *field_fiabilite_montant
Corrigé.

2021-12-02 09:39 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +      - *field_entite_rattachement_openfisca
Corrigé.

2021-12-02 09:45 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +      - label: Régions
Corrigé.

2021-12-02 09:45 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +      - label: Code INSEE des communes
Corrigé.

2021-12-02 09:45 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +      - label: Code des départements
Corrigé.

2021-12-02 13:32 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +      - *field_montant_maximal_aide
Il manque :
- field_legende_montant
- field_interet_particulier

2021-12-02 13:44 UTC, Kout95 requested changes

2021-12-02 13:44 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +      - *field_type_resultat
Il manque en dessous de ça :
```
- *field_unite_resultat
- *field_periodicite_montant_aide
- *field_legende_montant
```

2021-12-02 13:44 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +      - *field_montant_maximal_aide
Il manque en dessous de ça :

```
- *field_interet_particulier
```

2021-12-02 13:44 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +      - *field_montant_maximal_aide
On peut supprimer `*field_montant_maximal_aide`, uniquement utile pour afficher les montants en mode debug.

Note: Si c'est réellement nécessaire, il est plus pertinent de faire un lien vers le paramètre montant openfisca.

2021-12-02 13:44 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +      - *field_profil_eligibilite
`*field_profil_eligibilite` a supprimer car le moteur de calcul est openfisca

2021-12-02 13:46 UTC, Kout95 commented on lib/Benefits/ComputeFrontEnd.js
>    )
Il faut renommer le fichier en `ComputeJavascript`

2021-12-03 09:41 UTC, Kout95 approved these changes

2021-12-03 09:58 UTC, Kout95 commented
Testé en local

2021-12-03 09:59 UTC, merged