Ajoute l'institution dans le nom
betagouv/aides-jeunes pull request #2006
Opened 2021-12-09 16:00 UTC by Kout95

2021-12-09 18:18 UTC, Cugniere requested changes

2021-12-09 18:18 UTC, Cugniere commented on src/styles/partials/desktop/_resultats.scss
> +      color: var(--dark-grey);
Duplicat de la ligne `color`

2021-12-09 18:20 UTC, Cugniere commented on src/styles/partials/desktop/_resultats.scss
> +      color: var(--dark-grey);
Et la classe `aj-institution-label` est utilisée quelque part d'ailleurs ?

2021-12-10 10:53 UTC, Kout95 commented on src/styles/partials/desktop/_resultats.scss
> +      color: var(--dark-grey);
oui je l'ai ajouté pour le support internet explorer : https://developer.mozilla.org/fr/docs/Web/CSS/var()

2021-12-10 10:57 UTC, Kout95 commented on src/styles/partials/desktop/_resultats.scss
> +      color: var(--dark-grey);
je viens de supprimer la ligne :)

2021-12-10 10:57 UTC, Kout95 commented on src/styles/partials/desktop/_resultats.scss
> +      color: var(--dark-grey);
c'est une nouvelle classe que je viens de créer

2021-12-10 12:59 UTC, Cugniere commented on src/styles/partials/desktop/_resultats.scss
> +      color: var(--dark-grey);
Effectivement, je sais pas lire

2021-12-10 12:59 UTC, Cugniere approved these changes

2021-12-10 13:00 UTC, merged