Feat/445
betagouv/aides-jeunes pull request #2276
Opened 2022-01-05 13:34 UTC by Kout95

2022-01-06 15:04 UTC, Cugniere commented on data/benefits/javascript/caf-allier-aide-bafa-session-generale.yml
> +    value: 900
Idéalement il faudrait faire ces modifs dans tous les yaml faisant mention du quotient familial.

2022-01-06 15:05 UTC, Cugniere requested changes
Ok pour moi, reste à modifier les yaml qui font référence au quotient familial

2022-01-06 15:24 UTC, Cugniere commented on lib/Benefits/compute-javascript.js
> +      const quotient_familial = rfr / nbptr / 12
Après discussion le calcul du quotient familial peut se faire pour un mois ou pour une année. Du coup il faudrait rajouter un paramètre mensuel/annuel ce qui impacterait cette ligne

2022-01-07 08:08 UTC, Kout95 commented on data/benefits/javascript/caf-allier-aide-bafa-session-generale.yml
> +    value: 900
En effet je souhaitais le faire dans un second temps après avoir validé la méthode de calcul :)

2022-01-07 08:15 UTC, Cugniere commented on contribuer/public/admin/config.yml
> +    name: quotient_familial
Si on suit la logique du quotient familial mensuel et du quotient familial annuel on devrait avoir quelque chose du genre : 
```yaml 
field_quotient_familial_mensuel: &field_quotient_familial_mensuel
    <<: *field_number
    label: Quotient familial (par mois)
    name: quotient_familial_mensuel
field_quotient_familial_annuel: &field_quotient_familial_annuel
    <<: *field_number
    label: Quotient familial (par année)
    name: quotient_familial_annuel
```

2022-01-07 13:41 UTC, Kout95 commented on data/benefits/javascript/caf-eure-aide-bafa-generale.yml
> -  - Avoir un quotient familial inférieur ou égal à 600 € le mois de la demande.
Comme discuté avec Thomas :
Nous prenons le quotient familial pour l'année fiscale et non le dernier mois.
Cela va potentiellement engendré des faux positifs et faux négatifs

2022-01-10 14:34 UTC, Cugniere approved these changes

2022-01-10 14:42 UTC, merged