Crée une page dédiée pour chaque aide
betagouv/aides-jeunes pull request #2376
Opened 2022-01-26 07:01 UTC by Vanessa-D

2022-01-26 07:56 UTC, Kout95 requested changes

2022-01-26 07:56 UTC, Kout95 commented on src/views/aide.vue
> +      return benefit
```suggestion
      const benefits = Institution.benefits.benefitsMap
      return benefits[this.benefitId]
```

2022-01-26 07:56 UTC, Kout95 commented on src/views/aide.vue
> +      debugger
A supprimer

2022-01-26 07:56 UTC, Kout95 commented on src/views/aide.vue
> +      <img
Je te propose d'utliser DroitHeader pour simplifier la partie.
Il faudra surement toucher au css.

2022-01-27 13:52 UTC, Vanessa-D commented
![demo](https://user-images.githubusercontent.com/78914809/151372197-aa441cff-18f5-4d8e-b4ac-50f508ae9e68.png)

2022-01-27 14:16 UTC, Vanessa-D commented
Bien que ça fonctionne, j'ai un warning dans la console en local  ```Property "route" was accessed during render but is not defined on instance.  
at <AideDetails onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >  
at <RouterView>  
at <BaseLayout>  
at <App>  
at <App>```  
Je pense comprendre que le fichier aide.vue a besoin d'une indication "on instance", j'explore.

2022-02-02 15:38 UTC, Kout95 commented on src/components/benefit-cta.vue
> +        route !== routeAide
```suggestion
        $route.name !== 'aide'
```
A tester mais normalement ca fonctionne et ça évite de changer quand l'url change

2022-02-02 15:44 UTC, Kout95 commented on src/views/liste-aides.vue
> +            </a>
```suggestion
            <router-link :to="{name: 'aide',  params: { benefitId: benefit.id }}}`">
              {{ $filters.capitalize(benefit.label) }}
            </router-link>
```

2022-02-02 15:46 UTC, Kout95 commented on src/components/droit-estime.vue
> +  <div v-if="droit.type && route !== routeAide" class="aj-droit-estime">
idem que précédement

2022-02-02 15:48 UTC, Kout95 commented
Autre point d'attention. La page ne contient pas de H1 ce qui est une erreur en html et accessibilité.

2022-02-03 14:34 UTC, Kout95 commented on src/views/aide.vue
> +<style>
```suggestion
<style scoped>
```
Sinon le css s'applique à tous les composants vue

2022-02-03 16:32 UTC, Kout95 commented
> @Kout95 je ne comprends pas ta suggestion d'ajouter un back button alors que le navigateur le propose déjà. En quoi cela manque-t-il selon toi ?

Bien que le bouton précédent existe, il me parait nécessaire d'avoir un lien vers la liste des aides pour revenir vers cette liste. C'est assez courant dans les sites web, et rend plus accessible le site : un bouton "Retour à la liste des aides" est plus intuitif que le bouton "précédent".

2022-02-07 11:11 UTC, Kout95 commented
Suite à l'échange avec la team des designers transverses : https://mattermost.incubateur.net/betagouv/pl/qxj6zybdytdz5xqgrzjmonwgtw

Je serais d'avis d'ajouter le bouton comme ci-dessous : 
![image](https://user-images.githubusercontent.com/65901733/152777225-e67fb8bf-d997-4b84-9fa6-bf82b6a36109.png)

Le fil d'ariane peut être une solution future mais je pense qu'il est prématuré de faire ce changement ici étant donné que ça remet en question la charte graphique du site.

2022-02-09 14:08 UTC, Cugniere approved these changes
Testé en local, ok pour moi

2022-02-09 14:55 UTC, merged