Correctifs pour l'outil d'accompagnement
betagouv/aides-jeunes pull request #2453
Opened 2022-02-21 05:23 UTC by Cugniere

## Description

Correctifs :
- sur l'outil d'accompagnement, n'affiche la valeur numérique d'une aide que si elle est numérique
- via le bot Mattermost, n'affiche la valeur numérique d'une aide que si elle est numérique

2022-02-21 10:54 UTC, guillett reviewed
J'ai l'impression que `simulationCreationDate` n'est pas le bon nom (ça semble plutôt faire référence à la surveyCreationDate), ni la bonne variable (alors que j'aurais tendance à préférer la FollowupCreationDate).

2022-02-21 10:54 UTC, guillett commented on backend/controllers/followups.js
> +    .then((simulation) => {
```suggestion
    .then((followup) => {
```
?

2022-02-21 10:54 UTC, guillett commented on backend/controllers/followups.js
> +      $gte: new Date(req.params.simulationCreationDate),
J'ai l'impression qu'il va manquer quelque chose pour que ça fonctionne. Ne faut-il pas imposer un `sort({createdAt})` ?

2022-02-21 10:54 UTC, guillett commented on backend/controllers/followups.js
> +    "surveys.createdAt": {
Pourquoi prendre `surveys.createdAt` plutôt que `createdAt` ?

2022-02-24 11:23 UTC, Kout95 commented
Il faut supprimer les token lors du get des followups sinon on envoie l'access token en frontend

2022-02-24 11:24 UTC, Kout95 requested changes
Il faut supprimer les token lors du get des followups sinon on envoie l'access token en frontend.

Une règle qui pourrait etre cool est de supprimer tout les champs commencant par token lors des get

2022-02-24 15:10 UTC, Kout95 commented on backend/controllers/followups.js
> +    .select("-surveys.accessToken")
Je vois une répétition de code est-il mutualisable ? :)

2022-02-24 15:49 UTC, merged