Correspondances API Pôle Emploi
betagouv/aides-jeunes pull request #2658
Opened 2022-04-04 08:36 UTC by Vanessa-D

2022-04-04 08:50 UTC, guillett commented on tools/read-xlsx.js
> +const path = require("path")
Dans un premier temps, ça serait chouette que cette logique génère une structure de données équivalente à `correspondance.json` voire aussi la génération du JSON associé par exemple `extract_correspondance.json`

2022-04-04 10:27 UTC, guillett commented on tools/correspondance-pe-aj.js
> +const apiPe = require("./aids.json")
À la place de récupérer les données dans le fichiers JSON enregistré manuellement tu peux regarder [comment utiliser `axios`](/home/thomas/repos/aides-jeunes/backend/lib/openfisca/getter.js) pour prendre les données à la source https://mes-aides.pole-emploi.fr/api/aids.

2022-04-07 08:51 UTC, guillett commented on tools/update-pe-aj-matches.js
> +      })
Si je comprends bien ta question. C'est normal que le fichier JSON n'est pas modifié tu ne le réécris pas. C'était fait aux [lignes suivantes](https://github.com/betagouv/aides-jeunes/pull/2658/files#diff-f1c9d773cfd72ce826c6d12dbbff78ce6a51f24efbfcd4e94a3ea66a5feedb97R25-R28) dans [`tools/read-xlsx.js`](https://github.com/betagouv/aides-jeunes/pull/2658/files#diff-f1c9d773cfd72ce826c6d12dbbff78ce6a51f24efbfcd4e94a3ea66a5feedb97R25-R28).

2022-04-07 09:37 UTC, Vanessa-D commented
Pour l'instant, ce qu'on a codé permet

d'un côté en se connectant à l'API PE, de :
- générer un fichier ``todo.json``  pour repérer les aides AJ candidates
- générer un fichier ``table.json`` qui sert à remplir le Google doc partagé (via conversion en csv puis copier/coller

de l'autre en se branchant à l'url du doc, de :
- rester à jour sur le fichier des aides certifiées

Maintenant, est-ce que l'on veut à partir du fichier ``table.json`` ne pas passer par la conversion manuelle et injecter les données dans le Google doc ?

2022-06-27 10:50 UTC, Kout95 requested changes
Dans l'ensemble ca fonctionne bien. Néanmoins le code étant dense, j'ajouterais bien un commentaire sur chaque fonction comme par exemple `getGoogleData` pour expliquer le but de la fonction pour expliquer le process et ce que fait l'outil

2022-06-27 10:50 UTC, Kout95 commented on tools/generate-matches-worksheet.js
> +  xlsx.writeFile(workbook, "../../matches-worksheet.xlsx")
je changerais le chemin vers la racine du projet AJ. en l'ajoutant dans le `.gitignore` pour éviter d'avoir des changements sur git

2022-06-27 10:50 UTC, Kout95 commented on tools/generate-matches-worksheet.js
> +    "Nouvelle récupération",
```suggestion
    `Nouvelle récupération du ${moment().format("YYYY-MM-DD")}`,
```

2022-09-06 10:59 UTC, guillett commented
Travaux repris dans #3050. Je ferme cette PR pour faire un peu de ménage.

2022-09-06 10:59 UTC, closed without merging