[746] mise à jour de terme français en anglais dans les fichiers YAML
betagouv/aides-jeunes pull request #2844
Opened 2022-05-06 08:29 UTC by Cugniere

## Détails

[Tâche Trello](https://trello.com/c/YL0mZbhQ/746-refacto-tech-g%C3%A9rer-le-franglais-dans-les-fichiers-yaml)

2022-05-06 08:54 UTC, guillett reviewed
:+1:

2022-05-06 08:54 UTC, guillett commented on contribuer/public/admin/config.yml
> +  field_prefix: &field_prefix
J'ai un doute sur celui là mais dans l'autre sens. Peut-être qu'étant donnée la complexité de ce champs ça pourrait être la version française qu'on utilise ici et comme nom d'attribut.

2022-05-06 08:54 UTC, guillett commented on contribuer/public/admin/config.yml
> +  field_unsupported_conditions: &field_unsupported_conditions
`unsupported` `unmodeled` ?
Ça serait aussi bien renommer le champs qui est aujourd'hui `conditions`.

2022-05-11 13:51 UTC, Vanessa-D commented on contribuer/public/admin/config.yml
> +  field_unmodeled_conditions: &field_unmodeled_conditions
J'avais un doute sur le sens de ``non modélisées`` pour ``non prises en compte`` mais je manque peut-être de contexte :)
En alternative au cas où : ``not included``, ``not taken into account``, ``not considered``

2022-05-12 09:32 UTC, Vanessa-D approved these changes
Ok pour moi

2022-05-12 09:58 UTC, Kout95 requested changes

2022-05-12 09:58 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +    name: profiles
Ce changement implique de changer tous les fichiers YAML
ainsi que compute-javascript.js

2022-05-12 12:44 UTC, guillett commented on contribuer/public/admin/config.yml
> +    name: profiles
:+1: Très bien vu !

Peut-être en commençant par modifier les tests.
Est ce qu'on a la possibilité de valider un schéma ?
Je pense par exemple à faire valider le schéma des tests à partir du contenu de ce fichier de config. Je réfléchi à une façon de faire casser les tests en cas de changement comme celui-là.

2022-05-12 14:06 UTC, Kout95 commented on contribuer/public/admin/config.yml
> +    name: profiles
En effet une routine sur le fichier de config peut etre pertinent pour etre sur de ne pas casser la prod. Thomas tu ajoutes une carte sur Trello ?
> Je pense par exemple à faire valider le schéma des tests à partir du contenu de ce fichier de config. Je réfléchi à une 
> façon de faire casser les tests en cas de changement comme celui-là.

2022-05-13 09:14 UTC, Kout95 approved these changes

2022-05-13 09:15 UTC, merged