Refactorise le test qui valide le bon ajout de critères géographiques
betagouv/aides-jeunes pull request #2898
Opened 2022-05-18 04:46 UTC by Vanessa-D

Dans cette PR, les aides aux critères géographiques complexes / multiples ne sont toujours pas prises en compte dans le test, mais gérées par une condition de longueur de la liste pour éviter d'avoir à éditer le test manuellement en ajoutant  au fur et à mesure les nouvelles aides aux critères géographiques complexes.

2022-05-27 09:31 UTC, guillett commented
J'ai l'impression que mon teste ne devrait pas en être un mais plutôt un outil de validation régulière. Je suis un peu embêté par l'inscription dans le code d'une liste gérée manuellement mais en même temps je trouve que c'est la bonne chose à faire mais peut-être un peu différemment.

J'ai aussi l'impression que le blocage technique a été réglé par une PR précédente.

2022-05-27 09:31 UTC, guillett commented
cc @Cugniere un avis ?

2022-06-27 09:23 UTC, Kout95 commented on tools/test-benefits-geographical-constraint-coherence.js
> +function testGeoRelevancy(benefit) {
Cette fonction devrait se trouver dans le dossier `lib/`

2022-06-27 09:26 UTC, Kout95 requested changes

2022-06-27 09:26 UTC, Kout95 commented on tools/test-benefits-geographical-constraint-coherence.js
> +function testGeoRelevancy(benefit) {
dans le fichier `geographical-relevancy.js` et je renommerais `testGeoRelevancy` en `testGeographicalRelevancy`

2022-06-27 09:32 UTC, Kout95 commented on tools/test-benefits-geographical-constraint-coherence.js
> +function testGeoRelevancy(benefit) {
Renommer en `testGeographicalRelevancy` comme le nom du fichier

2022-06-27 09:43 UTC, Kout95 commented on tools/test-benefits-geographical-constraint-coherence.js
> +      console.log(result.conditions)
```suggestion
      console.log("================================")
      console.log(`Benefit : ${benefit.id}`)
      console.log(`Insee code : ${benefit.institution.code_insee}`)
      console.log("potentially incompatible with conditions :")
      console.log(result.conditions)
```

2022-06-27 10:35 UTC, Kout95 commented on tools/test-benefits-geographical-constraint-coherence.js
> +function testGeoRelevancy(benefit) {
En meme temps renommer les fichiers `tools/test-benefits-geographical-constraint-coherence.js` en tools/test-benefits-geographical-constraint-consitency.js

2022-06-27 16:34 UTC, Kout95 commented on tools/test-benefits-geographical-constraint-consistency.js
> +    if (!result.isValid) {
```suggestion
    if (!result?.isValid) {
```

2022-06-27 16:35 UTC, Kout95 commented on tools/test-benefits-geographical-constraint-consistency.js
> +      console.log(result.conditions)
```suggestion
      console.log(result?.conditions)
```

2022-06-27 16:36 UTC, Kout95 commented on tools/test-benefits-geographical-constraint-consistency.js
> +    if (!result.isValid) {
Dans le cas ou une aide n'a pas de conditions géographiques nous retournons undefined

2022-06-27 17:22 UTC, Kout95 approved these changes

2022-06-27 17:32 UTC, merged