[792] Ajout de typescript sur le backend
betagouv/aides-jeunes pull request #2909
Opened 2022-05-19 10:39 UTC by Cugniere

## Description

[Carte Trello](https://trello.com/c/nuIbomsY/792-ajouter-typescript-sur-le-backend)

## Notes

Ajout d'un fichier de configuration spécifique pour typescript pour le backend

À noter que la [PR #115](https://github.com/betagouv/aides-jeunes-ops/pull/115/files) du repo Ops est nécessaire afin de maintenir certaines fonctionnalités de la prod fonctionnelles.

2022-05-20 14:04 UTC, guillett commented
Cool, c'est cool que ça soit aussi minimaliste en terme de fichiers modifiés !
Il faudra faire attention à mettre à jour l'OPS pour s'assurer que l'on lance le bon script server.js en production.

2022-06-07 07:28 UTC, Kout95 requested changes

2022-06-09 08:32 UTC, Kout95 approved these changes
Testé en local. Ok pour moi, on peut en profiter pour passer la libraire `@vue/cli-plugin-typescript` en version ^5.0.4 pour être en accord avec les autres librairies vue-cli

2022-06-10 04:30 UTC, merged

2022-06-12 09:12 UTC, guillett commented on package.json
> +    "build:server": "npx tsc -p tsconfig.server.json && cp -r lib backend data contribuer dist-server/",
Je ne comprends pas pourquoi on utilise `npx` plutôt que des scripts depuis des paquets spécifiés dans les dépendances ?

Un autre usage avait était initialement ajouté dans #2398  (cf [lignes](https://github.com/betagouv/aides-jeunes/pull/2398/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R17-R18))