Question nombre de mois d'entrée logement
betagouv/aides-jeunes pull request #3414
Opened 2022-12-19 09:44 UTC by Shamzic

[Tâche trello]

Affiche la question du nombre de mois d'entrée dans le logement uniquement aux locataires

Fix : la réponse "Non, j'ai emmenagé il y a moins de 3 mois" n'était plus affichée car le label a été refacto précédement et n'était plus fetch

Le nom de la page / quesiton ne me paraît pas cohérent et pourrait être refacto : pourquoi "_nombreMoisEntreeLogement" avec la question "Prévoyez-vous de déménager prochainement ?" ?

2022-12-21 07:50 UTC, guillett requested changes
Top la correction `statut_occupation_logement` !


Tu peux regarder ou on pourra regarder ensemble comment ces infos sont utilisées.

Effectivement l'url ne colle ps parfaitement à la question qui est posée mais ça colle bien à l'information qui est collectée. Ça me gêne pas trop qu'il y ait cette distinction, les URL sont des outils plutôt pour nous et pas vraiment pour les usagers. La fait le lien entre la complexité qu'on rend visible et celle qu'on cache (pour ne pas surcharger les usagers).

2022-12-21 07:50 UTC, guillett commented on lib/state/blocks.ts
> +        isActive: (subject) => subject._logementType === "locataire",
Une personne qui est hébergée peut nous indiquer vouloir déménager prochainement. C'était une feature de l'afficher à ces personnes là, pas un bug.

2022-12-21 11:19 UTC, Shamzic commented on lib/state/blocks.ts
> +        isActive: (subject) => subject._logementType === "locataire",
Ok du coup je dois laisser tel quel ? Ce n'est toujours pas clair sur la définition de la tâche terminée ?
<img width="324" alt="image" src="https://user-images.githubusercontent.com/18016058/208893063-ffc6c0f1-8941-4c9f-98ae-4029dceebd74.png">

2022-12-21 13:33 UTC, Shamzic commented on lib/state/blocks.ts
> +        isActive: (subject) => subject._logementType === "locataire",
Ah 

> Ok du coup je dois laisser tel quel ? Ce n'est toujours pas clair sur la définition de la tâche terminée :
> 
> <img alt="image" width="324" src="https://user-images.githubusercontent.com/18016058/208893063-ffc6c0f1-8941-4c9f-98ae-4029dceebd74.png">

Après réflexion, je pense que le plus logique c'est d'afficher cette question pour les locataire, les propriétaire et les personnes hébergée mais pas pour les sans domiciles fixes (et encore, ça se discute)

2022-12-27 08:24 UTC, guillett commented on lib/state/blocks.ts
> +        isActive: (subject) => subject._logementType === "locataire",
La personne qui est aujourd'hui sans domicile stable, en emménageant devrait pouvoir rentrer dans les critères d'éligibilités des aides d'Action Logement (cf `date_entree_logement` dans le dépôt et OpenFisca).

Je pense que c'est bien de n'exclure cette question (et donc ces aides) que pour les propriétaires.
Par soucis de lisibilité, on peut changer la logique et lister les cas où la question est affichée plutôt que les cas où elle ne l'est pas. Je te laisse voir ça.

2022-12-27 12:14 UTC, Shamzic commented on lib/state/blocks.ts
> +        isActive: (subject) => subject._logementType === "locataire",
C'est plus clair comme ça, merci. (:

2023-01-02 14:41 UTC, Valandr approved these changes
Ok pour moi. La logique implémentée consistant à expliciter les cas où la question du nombre de mois d'entrée doit s'afficher, fonctionne.

2023-01-02 14:43 UTC, guillett approved these changes

2023-01-02 14:43 UTC, guillett commented on lib/properties/menage-properties.ts
>            return value?.startsWith("locataire")
Pour être plus explicite, maintenant que c'est possible avec les 2 variables, j'aurais une préférence pour remplacer :
```suggestion
          return _logementType ==="locataire"
```

2023-01-02 14:43 UTC, Shamzic commented on lib/properties/menage-properties.ts
>            return value?.startsWith("locataire")
J'ai fait la même remarque à Valérie à l'instant! Je corrige, merci 👍

2023-01-02 14:54 UTC, merged