Allongement barre separation 2
betagouv/aides-jeunes pull request #3471
Opened 2023-01-23 13:09 UTC by Valandr

[Tâche Trello](https://trello.com/c/znN5vmSr/1099-ui-allonger-la-barre-de-s%C3%A9paration-entre-le-r%C3%A9sum%C3%A9-%C3%A0-gauche-et-la-question) : 

- Ancien aperçu : cf capture tâche trello

- Nouvel aperçu : 

<img width="1440" alt="Capture d’écran 2023-01-05 à 12 40 53" src="https://user-images.githubusercontent.com/52297439/210772191-3b0c7882-f905-4674-873e-06801c79b3e7.png">

2023-01-23 20:40 UTC, guillett commented
Lié à https://github.com/betagouv/aides-jeunes/pull/3443
Pourquoi repartir sur une nouvelle PR ?

2023-01-24 08:59 UTC, Valandr commented
J'ai fait plusieurs rebase qui n'ont pas fonctionné et il y avait des commits qui n'étaient pas pris en compte dans l'historique. Ensuite après échange avec Willy, c'était plus simple de procéder de cette façon. C'est vrai que ce n'est pas forcément la meilleure solution.

2023-01-24 09:39 UTC, Shamzic reviewed
Un problème d'espace vide persiste dans certaines largeurs d'écran, ici avec 640px : 
![image](https://user-images.githubusercontent.com/18016058/214258415-b16f77e3-7644-475c-b143-a90389c65b48.png)

2023-01-24 09:52 UTC, Valandr commented
Ok je regarde, merci d'avoir noté ça.

2023-01-26 16:06 UTC, Shamzic requested changes

2023-01-26 16:06 UTC, Shamzic commented on src/styles/aides-jeunes.css
> +  }
J'ai l'impression que ces lignes sont redondantes car elle sont déjà présentes à un niveau supérieur ligne 201

2023-01-30 12:59 UTC, Shamzic approved these changes

2023-01-30 13:01 UTC, merged