Permet l'inclusion en iframe sans support des cookies
betagouv/aides-jeunes pull request #3579
Opened 2023-03-08 10:05 UTC by Cugniere

## Détails

[Tâche Trello](https://trello.com/c/UtFuGyKM/1175-permettre-le-fonctionnement-de-liframe-sur-tous-les-navigateurs-modernes)

## Notes

Le but de cette tâche est de permettre l'intégration de l'iframe du simulateur depuis d'autres sites internet.

## Problématiques

À date 4 formats de stockage de données sont utilisés côté client par le simulateur : 
- les cookies avec :
    - `latestSimulation` l'identifiant de la dernière simulation
    - `simulation_*` un id et un token pour chaque simulation effectué
    - `_pk_id_*` qui contiennent des informations permettant le tracking de comprotement utilisateur
- le local storage qui est utilisé pour stocker les données relatives à l'AB-testing (exemple de donnée : clef `ABTesting` pour `{"css_text":{"index":1,"value":"C"}}`)
- le session storage qui conserve les données utilisées par le store. Cela permet de reprendre une simulation si la page est rechargée ou fermée puis rouverte.
- une variable `state` qui a un contenu similaire au session storage mais qui est par nature perdue au rechargement de la page puis réinitialisé avec les valeurs du session storage

Plusieurs erreurs ont été détectées en lien avec une intégration par iframe ; notamment : 
- [Erreur Sentry 507](https://sentry.incubateur.net/organizations/betagouv/issues/507/?project=18&query=is%3Aunresolved) et [Erreur Sentry 25957](https://sentry.incubateur.net/organizations/betagouv/issues/25957/?project=18&query=is%3Aunresolved) : l'accès au session storage est refusé, principalement sur **Chrome** ainsi que **Chrome Mobile** et **Edge**
- Erreur `You do not have access to this situation` lorsque l'on arrive sur la page de résultat. Cette erreur est dûe au refus par le navigateur d'enregistrer un cookie permettant au serveur de lui permettre d'accéder à ses résultats de simulation

[Un correctif fait en février 2022](https://github.com/betagouv/aides-jeunes/pull/2456) permet le support des third-party cookies sur la plupart des navigateurs intégrant le simulateur en iframe.

## Support des stockages par les navigateurs
<table>
  <tr>
    <td align="center"><b></b></td>
    <td colspan="2" align="center"><b>Chrome</b></td>
    <td colspan="2" align="center"><b>Firefox</b></td>
    <td colspan="2" align="center"><b>Safari</b></td>
    <td colspan="2" align="center"><b>Edge</b></td>
  </tr>
  <tr>
    <td align="center"><b></b></td>
    <td>Standard</td>
    <td>Privé</td>
    <td>Standard</td>
    <td>Privé</td>
    <td>Standard</td>
    <td>Privé</td>
    <td>Standard</td>
    <td>Privé</td>
  </tr>
 <tr>
<td align="center"><b>Cookies tiers</b></td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
</tr>
<tr>
<td align="center"><b>Cookies tiers dans une iframe</b></td>
<td align="center">✅</td>
<td align="center">❌</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">❌</td>
<td align="center">❌</td>
<td align="center">✅</td>
<td align="center">✅</td>
</tr>
<tr>
<td align="center"><b>Local storage</b></td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
</tr>
<tr>
<td align="center"><b>Local storage dans une iframe</b></td>
<td align="center">✅</td>
<td align="center">❌</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
<td align="center">✅</td>
</tr>
</table>

## Questions / réponses

### Est-ce possible de permettre l'enregistrement de cookies third-parties en dehors d'une iframe ?

Par défaut, les paramètres de confidentialité de [Firefox](https://support.mozilla.org/en-US/kb/third-party-cookies-firefox-tracking-protection), [Chrome](https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure) et [Safari](https://support.apple.com/guide/safari/prevent-cross-site-tracking-sfri40732/mac) bloquent les third-parties cookies.

Il est cependant possible d'indiquer qu'un cookie third-party a vocation a être partagé en ajoutant les attributs `SameSite=None` et `Secure` à chaque cookie enregistré. Les cookies du simulateur `latestSimulation` et `simulation_*` ont ces deux attributs lorsqu'ils sont servis via https.

[Plus d'information](https://developers.google.com/search/blog/2020/01/get-ready-for-new-samesitenone-secure).

### Est-ce possible d'enregistrer des cookies third-parties dans une iframe ?

>Les cookies enregistré par l'iframe sur [la page iframe du site du simulateur](https://mes-aides.1jeune1solution.beta.gouv.fr/iframe) ne sont pas considérés comme des cookies third-party car le nom de de domaine est identique.
>Par contre les cookies enregistré par l'iframe sur la page https://aides-jeunes-experimentations.netlify.app/iframe sont considérés comme third-party

Cela va dépendre des navigateurs et du mode de navigation (standard ou privé)

---

#### Safari

Par défaut Safari bloque les third-party cookies dans une iframe si celle-ci n'est pas intégrée dans une page qui est sur le même nom de domaine.

La simulation se déroule correctement mais à la page de résultat affiche une erreur : `You do not have access to this situation`

Cela est dû au fait que la requête `GET https://mes-aides.1jeune1solution.beta.gouv.fr/api/simulation/*/results` accepte les requêtes avec un cookie contenant le token de la simulation.

---

#### Chrome

Par défaut Chrome accepte les third-party cookies avec les attributs `SameSite: None` et `Secure`.

Cependant en mode de navigation privée ça n'est plus le cas ; les cookies third-party ne sont pas enregistrés par défaut :
![image](https://user-images.githubusercontent.com/16650011/230157704-d63f295c-6fbc-4f55-894f-344c86e6f80f.png)

---

#### Firefox et Edge

Les third-party cookies sont acceptés avec les attributs `SameSite: None` et `Secure`.

## Solutions testées

### Stockage du token de simulation dans le session storage

La solution étudiée dans la [PR 3579](https://github.com/betagouv/aides-jeunes/pull/3579) est d'utilisé le session storage lorsqu'il est disponible pour stocker la valeur du token permettant d'obtenir les résultats de simulation. Ce token est alors utilisé lors des requêtes vers les résultats de simulation.

Il serait possible de rajouter une fonctionnalité permettant d'utiliser le session storage seulement si il n'est pas possible d'écrire de cookie dans l'iframe (via la variable `navigator.cookieEnabled`).

Un risque partiellement négligeable (dans le cadre du simulateur) est que, contrairement à un cookie, un token peut être récupéré via une [cross site request forgery](https://owasp.org/www-community/attacks/csrf).

---

### Détection de l'accès au local/session storage

La Storage Access API met à disposition plusieurs méthodes pour contrôler le local storage : 
- `document.hasStorageAccess()` demande au navigateur si la page a accès au local storage.
- `document.requestStorageAccess` permet de demander  à l'utilisateur l'autorisation d'accéder au local storage

**[⚠️ Chrome ne dispose pas d'implémentation de ces 2 méthodes dans sa version actuelle (111)](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API#api.document.hasstorageaccess)**

La solution implémentée dans la PR 3579 est d'implémenter des méthodes de contrôle d'accès au storage ([voir fichier storage-controller.ts](https://github.com/betagouv/aides-jeunes/blob/58c9a7108ab6786297de727546fb00ac5c400bf9/src/lib/storage-controller.ts)).

Le contrôle de l'accès aux local et session storage est une version simplifiée basée sur [du code proposé sur mdm web docs](https://developer.mozilla.org/fr/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#test_du_support_et_disponibilit%C3%A9).

---

### Demander l'autorisation d'écrire des third-party cookies de [...]

2023-03-09 08:39 UTC, guillett requested changes

2023-03-09 08:39 UTC, guillett commented on backend/controllers/simulation.ts
> +      token: req.query.token || req.simulation.token,
:warning: ça semble donner accès aux résultats d'une simulation à toutes les personnes ayant l'identifiant associé.

2023-03-09 14:39 UTC, Shamzic reviewed
Ok pour moi. Je laisse Thomas approuver la PR, je n'ai rien remarqué de bloquant dans mes tests.

Juste une remarque supplémentaire qui est probablement hors sujet mais qui s'appllque ici concernant les requêtes axios qui n'ont pas de gestion des erreurs mutualisée. Cela pourrait par exemple être dans une méthode comme ceci :

```js
async function getRequest(url: string, params: any) {
  try {
    const response = await axios.get(url, { params })
    return response
  } catch (error) {
    console.error(`Error sending request to ${url}:`, error)
    throw error
  }
}
```

2023-03-09 14:39 UTC, Shamzic commented on src/stores/index.ts
> +    token: undefined,
J'aurais tendance à nommer le token `simulationToken` voir même à le placer dans l'objet `simulation` au dessus si ça ne casse rien

2023-03-13 10:20 UTC, Valandr reviewed
Tous les tests sont ok de mon côté sur tous les navigateurs, sauf sur Safari.

2023-03-13 10:34 UTC, baptou12 commented on src/main.ts
> +if (navigator.cookieEnabled) {
Pour bien comprendre : c'était un bug, mais pas lié au iframe si ?

2023-03-13 11:42 UTC, baptou12 commented on src/stores/index.ts
> +        ...(simulationToken && { simulationToken }),
Ça continue de fonctionner avec ce changement ici ? car j'ai l'impression que [ici](https://github.com/betagouv/aides-jeunes/blob/c7cb12bcff66c1de34042df43b38d23b015e3735/backend/models/simulation.ts#L85) on attend `token`

2023-03-13 11:43 UTC, baptou12 commented on src/stores/index.ts
> +        ...(simulationToken && { simulationToken }),
Same here

2023-03-13 14:07 UTC, baptou12 submitted a review, later dismissed
LGTM

2023-03-20 09:27 UTC, baptou12 approved these changes
LGTM

2023-03-23 10:34 UTC, guillett reviewed
J'ai fait des commentaires non bloquants.

Je me dis qu'en cible, ça pourrait être bien de n'avoir qu'un seul mécanisme et si c'est via l'auth bearer c'est ok.

2023-04-05 17:06 UTC, guillett reviewed
Je ne suis pas bloquant sur cette PR. Est ce que tu pourrais mettre ton travail d'investigation ici (celui qui est dans un pad) ?

Quelques notes / remarques pour garder une trace :
- il faudra peut-être choisir un mode authentification
- j'utilise le mode cookie en dev/accompagnement tech pour explorer les end point de l'API et leurs contenus
- à voir comment les règles sur les cookies tiers évoluent et comment ça impacte les intégrations en iframe (la situation actuelle avec Safari permet hyper limitante).

2023-04-05 17:07 UTC, guillett commented
Merci beaucoup pour le travail réalisé et les itérations !

2023-04-06 09:15 UTC, Valandr approved these changes

2023-04-06 09:52 UTC, Shamzic approved these changes
RAS, ok pour moi

2023-04-06 09:57 UTC, merged