1191 ajouter des stats sur laffichage du lien pour prendre rdv
betagouv/aides-jeunes pull request #3586
Opened 2023-03-13 16:15 UTC by baptou12

1191-ajouter
ajouter
Pull Request not related to a Trello Ticket

2023-03-15 11:35 UTC, Shamzic requested changes
Des suggestions de déstructuration (je suis adepte de ça mais si ce n'est pas ton cas, n'hésite pas à me le dire pour que je ne te fasse plus de suggestions à ce sujet) et une remarque elle aussi non bloquante

2023-03-15 11:35 UTC, Shamzic commented on src/views/suivi.vue
> +        )
On peut utiliser l'opérateur de coalescence des nuls (`??`) et l'opérateur de chainage optionnel `?.` :
```suggestion
return this.droits?.some(droit => ["failed", "nothing"].includes(droit.choiceValue)) ?? false;
```

2023-03-15 11:35 UTC, Shamzic commented on src/views/suivi.vue
> +    )
```suggestion
const { data: followup } = await axios.get(`/api/followups/surveys/${this.$route.query.token}`);
const followupBenefits = followup.benefits.map(({ id }) => getBenefit(id));
```

2023-03-15 11:35 UTC, Shamzic commented on src/views/suivi.vue
> +    })
```suggestion
this.droits = followupBenefits.map(benefit => ({
  ...benefit,
  montant: this.followup.benefits.find(({ id }) => id === benefit.id).amount,
  choices,
  choiceValue: null,
  choiceComments: "",
}));
```

2023-03-15 11:35 UTC, Shamzic commented on src/views/suivi.vue
> +      }
```suggestion
const { status } = await axios.post(`/api/followups/surveys/${this.$route.query.token}/answers`, answers);
if (status !== 201) return;
```

2023-03-15 11:35 UTC, Shamzic commented on src/views/suivi.vue
> +        choices: choices,
```suggestion
        montant,
        choices,
```

2023-03-15 11:35 UTC, Shamzic commented on src/views/suivi.vue
> +        "show-accompaniment-link",
J'aurais eu tendance à nommer cet événement `submit-survey` car ce nom est en lien avec l'action du bouton plutôt que la page qui s'ensuit et qui n'est pas toujours la même selon les réponses du sondage

2023-03-15 13:19 UTC, baptou12 commented on src/views/suivi.vue
> +        )
Ça simplifie sans dégrader la lecture :-) je change !

2023-03-15 13:39 UTC, baptou12 commented on src/views/suivi.vue
> +        "show-accompaniment-link",
Ah bien vu, enfin j'ai oublié d'ajouter une condition sur `showAccompanimentBlock` car l'événement c'est justement seulement quand le bouton de prise de RDV est montré. Donc je vais rajouter la condition et laissé ce nom d'événement (qui ne sera plus un simple submit). 

Qu'en pense tu ?

2023-03-15 13:41 UTC, baptou12 commented on src/views/suivi.vue
> +    })
Je garde la decomposition de l'object `followupBenefit` qui simplifie la lecture, mais pas sûr que d'économiser la déclaration de variable apporte, je push tout ça et on peut en discuter si tu veux @Shamzic

2023-03-15 14:04 UTC, Shamzic commented on src/views/suivi.vue
> +        "show-accompaniment-link",
Oui si il y a une condition qui force l'affichage alors ça me paraît déjà plus cohérent 👍

2023-03-15 14:08 UTC, Shamzic commented on src/views/suivi.vue
> +    })
Pas de problème :)

2023-03-15 14:12 UTC, Shamzic approved these changes

2023-03-20 09:38 UTC, baptou12 commented on src/views/suivi.vue
> +        ) ?? false
Bien vu, je change

2023-03-21 11:52 UTC, Shamzic approved these changes
Ok pour moi

2023-03-21 13:14 UTC, merged