Correction bug envoi statistiques
betagouv/aides-jeunes pull request #3587
Opened 2023-03-15 09:13 UTC by Valandr

[Tâche trello](https://trello.com/c/4FFGL7oi/1198-corriger-lenvoi-de-statistiques-quand-on-clic-sur-un-lien) : 

Ce bug serait dû à l'utilisation de la directive ```v-analytics``` dans le composant ```router-link```. Quand on remplace ```router-link```par une balise ```a``` , l'événement est bien enregistré. Cf => la capture d'écran. 
La doc préconise de ne pas utiliser de custom-directive sur les composants et ```router-link``` est un composant. Mais ```router-link``` est préférable à une balise ```a``` d'après la doc aussi.

<img width="1434" alt="Capture d’écran 2023-03-15 à 10 13 19" src="https://user-images.githubusercontent.com/52297439/225262125-4c5da739-abd5-4424-94f8-6ca7e241d1ed.png">

2023-03-15 10:09 UTC, guillett commented
Est ce qu'avec @baptou12 vous pouvez mettre ici vos résultats d'investigation vis à vis de
> La doc préconise de ne pas utiliser de custom-directive sur les composants


Je trouve surprenant cette préconisation et je me dis que c'est bien si on arrive à une compréhension partagée des limitations.

2023-03-15 10:40 UTC, baptou12 commented
> Est ce qu'avec @baptou12 vous pouvez mettre ici vos résultats d'investigation vis à vis de

Yes 🙂 (pour info y'a encore une notion de l'explication qui est floue pour moi : "component's root node" et en particulier "multi-root component")

Mais dans [cette page](https://vuejs.org/guide/reusability/custom-directives.html#usage-on-components) à propos des Custom Directive on a cette phrase : 
> In general, it is not recommended to use custom directives on components.

Et dans [cette page](https://v3.router.vuejs.org/api/) sur le `router-link` on a 
> `<router-link>` is the component for enabling user navigation in a router-enabled app.

2023-03-17 09:11 UTC, baptou12 requested changes
Comme on part sur cette solution je pense qu'on devrait gérer dans ce cas tout les cas de `v-analytics` sur des `router-link` (Ex: [ici](https://github.com/betagouv/aides-jeunes/blob/f9797e74938000c3c9272d9e0568345580614f39/src/components/benefit-cta.vue#L23-L25))

À l'inverse, si on souhaite garder `router-link` (_car ça apporte sur la navigation je crois??_) on peut p.e. modifier la directive pour qu'elle n'en soit plus une mais juste un appel à fonction onClick (_[ici](https://stackoverflow.com/a/42092519) ils parlent de comment faire fonctionner un onClick sur un `react-router`_) et la fonction serait une version ressemblant à  `myAnalyticsHandler`.

2023-03-31 14:37 UTC, baptou12 requested changes
On en discute quand tu veux, j'ai checkout et je vois bien les event plusieurs fois désormais !

2023-03-31 14:37 UTC, baptou12 commented on src/components/buttons/analytic-router-link.vue
> +    <slot> </slot>
```suggestion
    <slot />
```

C'est la même chose en plus concis

2023-03-31 14:37 UTC, baptou12 commented on src/directives/analytics.js
> +function sendStatistics(instance, action, name) {
Les modifications faites dans ce fichier ne sont pas utilisées et font que actuellement les autres `v-analytics` dans le code ne fonctionnent plus.

Je ne suis pas sûr à 100% qu'on puisse supprimer cette directive (cf (1)) **donc faudrait rollback les changements dans ce fichier**. 

En revanche il faut aussi selon moi **remplacer le maximum d'utilisation de** `v-analytics` par `AnalyticRouterLink` afin de corriger pas seulement le soucis sur l'event `show-unexpected` mais aussi sur les autres :-)

(1): [ici](https://github.com/betagouv/aides-jeunes/blob/f9797e74938000c3c9272d9e0568345580614f39/src/components/error-save-block.vue#L5-L18) même si c'est un lien comme ça envoi un email faudrait voir si ça fonctionne avec `AnalyticRouterLink` sinon on doit au moins temporairement garder la directive.

2023-04-05 08:48 UTC, baptou12 requested changes

2023-04-05 08:48 UTC, baptou12 commented on src/components/benefit-cta-link.vue
> +  <AnalyticRouterLink
@Valandr sur ce changement je pense que tout n'est pas fini, en effet il manque au moins les paramètre qui étaient passé à `v-analytics` qui ne sont pas passé à `AnalyticRouterLink` 
Comme tu avais dit qu'on faisait pas les `<a>..</a>` on peut p.e. sortir ça de la PR ?

2023-04-05 15:28 UTC, baptou12 commented on src/components/buttons/analytic-router-link.vue
> +    },
T'es sûr @Cugniere ? 
[ici](https://github.com/betagouv/aides-jeunes/blob/7b6ab0dc21bcb940dcf6eaa4553685044a12e57d/src/mixins/resultats.js#L20-L22) on a un computed sur resultats et [ici](https://github.com/betagouv/aides-jeunes/blob/7b6ab0dc21bcb940dcf6eaa4553685044a12e57d/src/mixins/resultats.js#L5-L7) on tape dans `droitsEligibles` j'aurais pensé qu'on était dans la même config ?

2023-04-05 15:37 UTC, Valandr commented on src/components/buttons/analytic-router-link.vue
> +    },
Elle retourne la liste des droits quand je fais un ```console.log```, cf => screen. 

<img width="778" alt="Capture d’écran 2023-04-05 à 17 36 30" src="https://user-images.githubusercontent.com/52297439/230131406-87142b32-42c7-4689-8473-ada9036739c6.png">

2023-04-06 08:43 UTC, Valandr commented
Merci pour les retours.

2023-04-06 08:43 UTC, merged