Migration front js vers ts
betagouv/aides-jeunes pull request #3596
Opened 2023-03-21 07:49 UTC by Valandr

Ticket [Trello](https://trello.com/c/nWgp0coq/1205-migrer-le-code-javascript-vers-du-code-typescript-pour-le-dossier-src-lib) :

2023-03-22 16:19 UTC, Shamzic requested changes

2023-03-22 16:19 UTC, Shamzic commented on src/lib/contributions.ts
> +    } as T)
Suggestion plus lisible :
```javascript
  const { sha, label } = contribution.head
  const [_, folder, filename] = label.split("/")
  if (folder === type) {
    acc.push({
      sha,
      filename: `${filename}.yml`,
      folder,
    } as T)
  ```

2023-03-22 16:19 UTC, Shamzic commented on src/lib/simulation.ts
> +const Simulation: Simulation = {
Je ne sais pas dans quelle mesure ce n'est pas un peu redondant de tout typer, même quand tout est explicite comme ici ?

2023-03-22 16:19 UTC, Shamzic commented on src/lib/warnings.ts
> +  aj_not_reliable(variation?: string): string | undefined
Mettre des `| undefined` n'est à mon sens pas une bonne solution et je préconiserais plus de revoir le fonctionnement de la méthode / variable associée et supprimer cela

2023-03-22 16:19 UTC, Shamzic commented on src/lib/warnings.ts
> +  get(attribute: string, variation?: string): string | undefined
Même remarque ici avec le `| undefined`

2023-03-23 14:48 UTC, Valandr commented on src/lib/benefits.ts
> +    filterSublist = null
En fait, je suis obligée d'initialiser la variable ```filterSublist``` à une valeur par défaut dans le bloc else, sinon je rencontre l'erreur ```Variable 'filterSublist' is used before being assigned```.

2023-03-23 15:07 UTC, Valandr commented on src/components/en-savoir-plus-content.vue
> +import Hint from "@/lib/hint.ts"
En laissant l'extension ```.js``` j'avais des erreurs au moment de lancer le build.

2023-04-05 15:42 UTC, Shamzic approved these changes
Ma remarque sur l'ajout d'un type dans `src/lib/contributions.ts` pour améliorer la lisibilité est toujours d'actu mais sinon ok pour moi (:

2023-04-06 15:22 UTC, Valandr commented on src/lib/simulation.ts
> +export default Simulation
Testé de mon côté, tout est ok.

2023-04-07 05:50 UTC, merged