1214 service de stats
betagouv/aides-jeunes pull request #3622
Opened 2023-03-29 10:05 UTC by baptou12

1214-service
service
Pull Request not related to a Trello Ticket

2023-03-30 08:45 UTC, baptou12 commented on lib/types/benefits.d.ts
> +export interface BenefitLayout {
A valider avec vous, mais la démarche que je suis est la suivante : 
- J'ajoute une interface pour là où j'utilise, donc je ne met que les attribut dont je me sert. 
- A l'avenir si il manque un attribut (réellement lié à un droit) alors on pourra le rajouter

Pensez vous qu'il y ai besoin d'un comment pour s'assurer que les future développements ne rajoute pas encore une autre interface ?

2023-03-30 08:55 UTC, baptou12 commented on lib/enums/behaviour-event-types.ts
> +export enum BehaviourEventTypes {
Cette liste vient de 
- de la liste dans le projet mes-aides-analytics ([ici](https://github.com/betagouv/mes-aides-analytics/blob/386aef6832da62b7c11dcd6d511096d4fdcac88c/pages/behaviours.js#L35))
- des nouveaux event rajouté depuis quelques semaines

2023-04-03 15:40 UTC, Shamzic requested changes

2023-04-03 15:40 UTC, Shamzic commented on src/mixins/statistics.ts
> +      droitId: string | undefined = undefined,
Pourquoi ne pas en profiter pour uniformiser les termes pour qualifier une aide ?
```suggestion
      benefits: BenefitLayout[] = [],
      benefitId: string | undefined = undefined,
```

2023-04-03 15:40 UTC, Shamzic commented on tests/unit/utils.spec.js
> +})
Je n'ai pas bien compris pourquoi tu fais ces tests ?

2023-04-03 15:40 UTC, Shamzic commented on src/lib/statistics-service/recorder.ts
> +  event.droits.forEach((droit, i) => {
```suggestion
droits.forEach((droit, i) => {
```

2023-04-03 16:29 UTC, Shamzic requested changes

2023-04-03 16:29 UTC, Shamzic commented on src/lib/statistics-service/shared.ts
> +    window.navigator.doNotTrack === "1" &&
Cette fonctionnalité est expérimentale https://developer.mozilla.org/fr/docs/Web/API/Navigator/doNotTrack et je sais pas si c'est une bonne idée de mettre ça en production

2023-04-03 16:29 UTC, Shamzic commented on tests/unit/utils.spec.js
> +    delete process.env.TEST_VARIABLE
```suggestion
    delete process.env.VITE_TEST_VARIABLE
```

2023-04-04 08:04 UTC, baptou12 commented on src/lib/statistics-service/shared.ts
> +    window.navigator.doNotTrack === "1" &&
Je l'ai mis car c'était déjà présent comme condition : https://github.com/betagouv/aides-jeunes/blob/80b4af814f3e5aa4f64fbd3841c98203a7d1c5d7/src/mixins/statistics.js#L9

Je vois que safari l'a enlevé, mais que tout les autres navigateurs l'ont. La question que je me pose c'est que est-ce que depuis y'a mieux ?

Je suis pour le laisser afin de garder tout ISO, mais a gardé en tête aussi, t'en pense quoi ?

2023-04-04 08:06 UTC, baptou12 commented on src/mixins/statistics.ts
> +      droitId: string | undefined = undefined,
Ok, je vais regarder pour améliorer dans ce sens, il y a déjà une guideline de discutée à ce sujet, c'est un peu confus encore

2023-04-04 08:48 UTC, Shamzic commented on src/components/en-savoir-plus.vue
> +      this.sendEventToMatomo("Parcours", "En savoir plus", this.$route.path)
j'ai remarqué que cet évènement est envoyé au mouseOver du bouton "en savoir plus" (historiquement il y avait une fenêtre d'info au survol), on pourrait en profiter pour refacto cette partie et remplacer le @mouseOver par un @click

2023-04-04 09:03 UTC, baptou12 commented on src/components/en-savoir-plus.vue
> +      this.sendEventToMatomo("Parcours", "En savoir plus", this.$route.path)
Je rajoute un commit, c'est une bonne idée

2023-04-04 09:46 UTC, Shamzic commented on tests/unit/utils.spec.js
> +    delete process.env.TEST_VARIABLE
C'est vite qui demande de préfixer ses variables d'environnement par "VITE_"du coup c'est juste une suggestion pour harmoniser le nommage, mais effectivement cela n'a pas d'impact dans ce cas

2023-04-04 09:49 UTC, Shamzic commented on src/lib/statistics-service/shared.ts
> +    window.navigator.doNotTrack === "1" &&
Ah, je n'avais pas vu que c'était déjà présent, ok du coup pas de problème 👍

2023-04-04 10:14 UTC, Shamzic commented
Je viens de tester en local en mettant en dur les var d'env VITE_STATS_URL (scalingo / benefits) et VITE_STATS_VERSION (2), les requêtes des événements sont bien postées mais le payload des requêtes sont vides

2023-04-04 12:42 UTC, baptou12 commented
Merci @Shamzic, je check tout ça : 
- Le en savoir plus j'ai pas testé le changement en effet, je vais creuser
- Le reste je comprend pas trop, mais je viens de trouver
- Je tente de rajouter un test cypress comme dit ce matin a minima sur l'appel au recorder

Je repasse en draft en attendant

2023-04-04 13:52 UTC, baptou12 commented on backend/config/development.ts
> +    url: "http://localhost:4000/benefits",
On peut en discuter : 
Mon point de vu c'est qu'il vaut mieux le définir ensuite comme c'est un service de stats, on ne devrait pas être bloqué si le recorder ne répond pas (dans l'idée)

Dans les fait si c'est pas le cas on devrait plutôt faire en sorte que le recorder ne bloque aucun chemin critique si il ne fonctionne pas plutôt que de le débrancher en dev. 

Je suis preneur de vos avis y'a probablement mieux encore

2023-04-04 16:03 UTC, Shamzic commented
j'ai ajouté ces deux log au début de la méthode `sendEventToRecorder`
```js
console.log("event", event)
console.log("skipSendEventToRecorder(event)", skipSendEventToRecorder(event))
```
on a bien l'event show qui est envoyé mais pas `show-unexpected-amount-link` :
La console quand on clique sur le dernier bouton pour accéder aux résultats:

![image](https://user-images.githubusercontent.com/18016058/229850861-bd2a25e3-abce-404d-9491-5e11623cb734.png)

J'imagine que le deuxième skipSendEventToRecorder(event) devrait être `false` donc la condition doit avoir un problème ?

2023-04-04 16:13 UTC, Shamzic commented
> Concernant "En Savoir Plus" j'ai bien les event qui partent sans toucher à la config pour info

J'ai mis ceci pour tester :
```js
function skipSendEventToMatomo(matomo: IMatomo | undefined): boolean {
  return false // skipSendStatistics() || matomo === undefined
}
```

2023-04-05 09:32 UTC, baptou12 commented
@Shamzic Merci j'ai trouvé le soucis sur `show-unexpected-amount-link` j'avais mis un `forEach` alors qu'il fallait un `filter` [ici](https://github.com/betagouv/aides-jeunes/compare/77e6e32c45ddf8ab51fec3c95a0112a6cbca4532..103e8cb4d058e484e27add8cc2f0810e8675b1ef)

2023-04-06 08:19 UTC, baptou12 commented on lib/types/benefits.d.ts
> +export interface BenefitLayout {
Tu pense quoi de `BenefitType` dans ce cas là ?

2023-04-06 13:49 UTC, Shamzic commented on src/components/en-savoir-plus.vue
> +      this.sendEventToMatomo("Parcours", "En savoir plus", this.$route.path)
> C'est toujours le même comportement qu'avant : <img alt="image" width="409" src="https://user-images.githubusercontent.com/16650011/230038612-ab794b63-1f87-45f1-ac90-e53c58ae70b2.png">
> 
> On affiche le message avec un mouseover et on permet aussi à l'utilisateur de cliquer dessus (ce qui entraine un changement de page mais permet de garder le même composant pour les utilisateurs mobiles)

Au temps pour moi ce bouton me donnait plus "envie" de cliquer dessus que de le survoler et donc d'envoyer l'événement au clic qu'au hover ^^

2023-04-06 14:15 UTC, Shamzic approved these changes
Ok pour moi.
(Suite au commentaire de Willy, j'imagine qu'il est préférable de remettre le mouseover pour l'envoi matomo dans le bouton "en savoir plus")

2023-04-07 15:30 UTC, baptou12 commented on src/components/en-savoir-plus.vue
> +      this.sendEventToMatomo("Parcours", "En savoir plus", this.$route.path)
J'ai enlevé le commit

2023-04-13 08:57 UTC, baptou12 commented on tools/check-links-validity.ts
> +      BehaviourEventTypes.teleservice,
Je check, je me suis p.e. fait avoir, si c'est pas lié au event j'enlève pour simplifier la PR

2023-04-13 09:14 UTC, baptou12 commented on tools/check-links-validity.ts
> +      BehaviourEventTypes.teleservice,
Ouais conceptuellement parlant c'est pas exactement la même chose, j'enlève

2023-04-17 08:53 UTC, merged