Expérimente France Connect et ses API
betagouv/aides-jeunes pull request #3627
Opened 2023-03-31 12:15 UTC by guillett

2023-04-04 09:35 UTC, guillett commented on backend/routes/auth.ts
> +  "2791a731e6a59f56b6b4dd0d08c9b1f593b5f3658b9fd731cb24248e2669af4b"
J'imagine que c'est une alerte qui a été gérée dans le passé et que ça a été déclaré comme sans risque. Merci pour ton message de réassurance !

2023-04-04 15:16 UTC, Shamzic commented on backend/routes/auth.ts
> +      console.log(e)
```suggestion
      console.error(e)
```

2023-04-04 15:20 UTC, Shamzic reviewed
🚀

2023-04-20 16:30 UTC, guillett commented on backend/routes/auth.ts
> +export default function (api) {
J'ai modifié la structure du fichier. J'ai l'impression que cette modification a perdu de son intérêt, je mets en résolu pour le moment.

2023-04-28 16:03 UTC, baptou12 requested changes
Fonctionnel sauf le bouton FranceConnect

2023-04-28 16:03 UTC, baptou12 commented on src/views/simulation.vue
> +        <button
La fonction `franceconnect()` n'est plus défini, mais même en enlevant le `@click="franceconnect"` ça ne marche pas chez moi, j'ai du transformer le bouton en lien pour que ça fonctionne.

2023-05-03 15:54 UTC, baptou12 commented
Je me suis permis de rebase sur master afin de partir de cette PR pour l'anonymisation (+ pouvoir avoir le code recent de cette partie)

2023-05-16 12:08 UTC, closed without merging

2023-05-16 16:24 UTC, Shamzic reviewed
Review pas encore exhaustive, fonctionnel en local

2023-05-16 16:24 UTC, Shamzic commented on backend/controllers/france-connect.ts
> +  res.cookie("fc_state", state)
Un enum pourrait décrire les clefs des cookies par exemple :

```js
export const enum CookiesKeys {
  fcState = "fc_state",
  fcNonce = "fc_nonce",
  fcIdTokenHint = "fc_id_token_hint",
  fcLogoutState = "fc_logout_state",
}
```