Ajoute un layout pour déployer la charte graphique de mes-aides.gouv.fr
betagouv/aides-jeunes pull request #3628
Opened 2023-03-31 16:23 UTC by Shamzic

Tentative de réalisation de la tâche : https://trello.com/c/A9F2WoDb/1213-permettre-le-d%C3%A9ploiement-de-lapp-avec-la-charte-graphique-de-mes-aidesgouvfr-fork-pour-le-moment

2023-04-05 12:57 UTC, Valandr reviewed
Testé en local, c'est fonctionnel.

2023-04-06 14:31 UTC, baptou12 requested changes
Fonctionnel, j'ai un comment sur la factorisation des méthodes des components de Layout. 
Sinon je pensais aussi, sans que ce soit obligatoire, tu pense quoi de rajouter un paragraphe dans le readme pour expliquer comment changer un Layout ?

2023-04-06 14:31 UTC, baptou12 commented on src/components/mes-aides-layout.vue
> +  watch: {
On pourrait mettre ça dans un mixin afin de factorisé avec le code de `BaseLayout` ? 

https://github.com/betagouv/aides-jeunes/blob/f9d9ccadf90aae29d07307430c84ca49c7a0799a/src/components/base-layout.vue#L76-L92

2023-04-10 13:28 UTC, Shamzic commented on src/components/mes-aides-layout.vue
> +  watch: {
C'est refacto, merci pour cette remarque

2023-04-20 12:04 UTC, baptou12 requested changes
Commentaires mineurs, fonctionne en local

2023-04-21 14:31 UTC, Shamzic commented on src/mixins/layout-route-mixin.js
> +          console.log("focus anchor", anchor, this.$refs[anchor])
Non, c'est un oubli !

2023-04-21 14:32 UTC, Shamzic commented on vite.config.ts
> +    VITE_LAYOUT: "BaseLayout", // "MesAidesLayout" | "BaseLayout"
Oui ça pourrait, mais je sais pas où ni comment le mettre pour que ce soit bien visible ?

2023-04-25 15:03 UTC, baptou12 commented on vite.config.ts
> +    VITE_LAYOUT: "BaseLayout", // "MesAidesLayout" | "BaseLayout"
Après juste le fait de l'importer pour l'utilisé ici permet de le localiser si il est autre part non ?

2023-04-26 12:32 UTC, Shamzic commented on vite.config.ts
> +    VITE_LAYOUT: "BaseLayout", // "MesAidesLayout" | "BaseLayout"
Yes, pour l'instant je le laisse là tant qu'il est utilisé uniquement dans ce contexte et on le déplacera si on en a un jour besoin ailleurs

2023-04-26 12:32 UTC, merged