email scripts refacto
betagouv/aides-jeunes pull request #3649
Opened 2023-04-14 14:40 UTC by baptou12

email_scripts_refacto-

Pull Request not related to a Trello Ticket

2023-04-19 11:34 UTC, Shamzic commented on backend/lib/email.ts
>      parser.printHelp()
J'ai l'impression que c'est plutôt `parser.print_help()` qu'il faut appeler ici

2023-04-19 14:34 UTC, Shamzic requested changes

2023-04-19 14:34 UTC, Shamzic commented on backend/lib/emails/sending.ts
> +  if (emailType !== "initial-survey") {
Du coup ici tu peux utiliser l'enum initialSurvey :)

2023-04-19 15:49 UTC, baptou12 commented on backend/lib/email.ts
> +    console.log("DB disconnected")
Tu as raison, après je me pose la question de supprimer ces process.exit car 'ai l'impression qu'il ont été ajouté car le script s'arrêtait pas et le script s'arrêtait pas car on avait pas coupé la connexion mongoose, je check et jte dis

2023-04-20 09:39 UTC, baptou12 commented on backend/lib/email.ts
> +    console.log("DB disconnected")
Du coup le comportement que j'ai c'est : 
- Quand on a pas la déconnexion de mongo et pas le process.exit => le script reste bloqué
- Si on a un des deux => le script fini bien

Je pense que la déconnexion mongo est suffisante du coup => je vire le `process.exit(1)`

2023-04-21 14:05 UTC, Shamzic commented on backend/lib/email.ts
> +    console.log("DB disconnected")
✅

2023-04-28 14:06 UTC, Shamzic approved these changes

2023-05-02 08:04 UTC, merged