Corrige le calcul de la distance au foyer familial pour les personnes orphelines qui étudient
betagouv/aides-jeunes pull request #3651
Opened 2023-04-17 16:41 UTC by guillett

2023-04-18 13:19 UTC, guillett commented on backend/lib/openfisca/mapping/individu/index.ts
>        if (individu.habite_chez_parents) {
Je trouve la non simplification plus agréable à lire d'un point de vu métier.
- Pas de parents _puis_
- Parents mais j'habite chez eux, etc.

2023-04-19 07:03 UTC, Allan-CodeWorks commented
Les modifications de cette PR semblent contenues dans la PR [Ajoute la variable pour gérer le cas des étudiants orphelins pour la BCS](https://github.com/betagouv/aides-jeunes/pull/3652/files), non ?

2023-04-19 10:15 UTC, Allan-CodeWorks requested changes
Certains tests ne passent pas.
Ma compréhension est que dans les tests, on construit des `situations` en rapport avec le test.
Dans certains d'entre eux, `_situation` n'existe pas est ça plante lorsqu'on essaie d'y accéder.

Ce diagnostique est frêle, car mes tentatives de régler le problème restent vaines.

Edit : ëgalement, ne faudrait-il pas ajouter un test?

2023-04-24 09:52 UTC, Allan-CodeWorks approved these changes
Parfait, la nouvelle méthode rend la lisibili meilleur et ça fonctionne toujours chez moi.

2023-04-24 15:47 UTC, merged