Informations d'un établissement dans un composant dédié
betagouv/aides-jeunes pull request #3657
Opened 2023-04-19 16:46 UTC by Shamzic

2023-04-21 13:56 UTC, baptou12 commented on src/components/etablissement.vue
> +const showInformationsButton = () => {
Je trouve le nom de la function un peu loin de ce qu'elle fait, que penses-tu de `toggleShowInformation` ? 

Sinon y'a un `console.log` qui semble avoir été oublié

2023-04-21 15:08 UTC, baptou12 requested changes
Les vue que tu as ajoutées fonctionnent bien, cependant la vue `/simulation/resultats/lieux` (lien direct sur la page de résultat sans passer par une aide ne fonctionne plus). Pas trouvé de causes évidentes encore.

2023-04-21 15:08 UTC, baptou12 commented on src/composables/use-etablissements.ts
> +  const types = getBenefitEtablissements(benefit)
Que penses-tu de mettre EtablissementTypes plutôt que juste `types` (j'ai vu qu'on mettait `types` partout ailleurs). Ça fait un peu confusant au premier abord je trouve.

2023-04-24 14:35 UTC, Shamzic commented on src/views/simulation/resultats/lieu-informations.vue
> +    <etablissement-informations
Ok my bad c'est juste le nommage de la balise

2023-04-24 15:19 UTC, baptou12 requested changes
Juste le `catch`

2023-04-25 13:53 UTC, baptou12 commented on src/composables/use-etablissements.ts
> +      isRelevant: (demandeur: any, situation: any) => {
Ok, j'ai compris d'où venait cette logique ([ici](https://github.com/betagouv/aides-jeunes/blob/17036c9efdfb04567679f604ead2798ea2518147/src/views/simulation/resultats/lieux-generiques.vue#L44-L72)).

Mais du coup la logique est totalement dupliquée maintenant. Tu pense que ce serait trop gros d'utiliser `useEtablissements` dans `lieux-generiques` dans cette PR ?

2023-04-25 13:56 UTC, baptou12 reviewed
Juste une question, mis à part `lieux-generiques` qui est pas totalement concerné par la PR ça me semble bon et fonctionnel

2023-04-26 09:35 UTC, Shamzic commented on src/composables/use-etablissements.ts
> +      isRelevant: (demandeur: any, situation: any) => {
Je viens de faire le changement que tu questionnes dans mon dernier commit. Cela simplifie énormément `lieux-génériques` mais c'est dû surtout au parti pris de supprimer également la gestion de la liste des établissement dans le store `helping-institution` qui pour moi n'a pas d'intérêt car à chaque page utilisant les lieux, il est nécessaire de faire appel à l'API pour récupérer les lieux

2023-04-26 14:50 UTC, baptou12 commented on src/composables/use-etablissements.ts
> +    loadEtablissements,
J'ai l'impression que l'ajout de `loadEtablissements` est en trop ?

2023-04-26 14:52 UTC, baptou12 commented on src/composables/use-etablissements.ts
> +      isRelevant: (demandeur: any, situation: any) => {
Pas sûr de comprendre non plus pourquoi on avait cette gestion ? (p.e. pour si on perd le depcom ? mais je dis ça sans grande conviction, et quoi qu'il arrive ça me semble pas trop pertinent).

Perso je trouve ça beaucoup plus simple et ça fonctionne bien. 

Juste un mini comment sur l'ajout de `loadEtablissements` dans le return ?

2023-04-26 15:01 UTC, baptou12 commented on src/views/simulation/resultats/lieux-generiques.vue
>    <router-link :to="{ name: 'resultats' }">
Rien à voir avec ta PR, mais on a un soucis d'UI ici, le `router-link` + `BackButton` ça fait qu'on a "Retour aux résultats" de souligné 🤓
<img width="290" alt="image" src="https://user-images.githubusercontent.com/4059803/234617680-b2081768-8020-4b4a-8681-1418e3487706.png">

2023-04-27 14:54 UTC, Shamzic commented on src/views/simulation/resultats/lieux-generiques.vue
>    <router-link :to="{ name: 'resultats' }">
Yes, ça peut être corrigé en supprimant le router-link et en plaçant un petit `
    @click="$router.push({ name: 'resultats' })"` directement dans le back-button

2023-04-28 08:14 UTC, Shamzic commented
> La partie page individuel d'un établissement est ok pour moi, par contre je trouve qu'on perd en facilité d'accès à l'information pour les utilisateurs. Avant on affichait : <img alt="image" width="794" src="https://user-images.githubusercontent.com/16650011/235078747-bce12ebf-0f6c-484a-98ee-60f08d7eb331.png">
> 
> Maintenant on a : <img alt="image" width="728" src="https://user-images.githubusercontent.com/16650011/235078800-fc130178-649d-4cd8-9615-dacb87c86e49.png">
> 
> De mon point ça pourrait être pertinent de garder l'affichage historique pour la page `/simulation/resultats/lieux` (quand les utilisateurs cliquent sur "Trouver de l'aide près de chez moi" ou "À proximité de chez vous") et de mettre le nouvelle affichage lorsqu'on listera directement les établissements sur la page d'une aide.
> 
> Là on rajoute l'obligation d'un clique pour avoir le détail d'un établissement à la fois.

Yes, après c'est la maquette qui veut cela.
De mon côté je trouve cela plus pertinent de ne pas surcharger d'informations l'utilisateur sur cette page et de lui proposer d'accéder à l'information seulement si il en a besoin

2023-04-28 08:17 UTC, baptou12 reviewed
Tout fonctionne chez moi, le code semble good. 
Juste par rapport au figma que tu m'a envoyé ce matin : https://www.figma.com/file/7jf3cnZ1CbmTtb3GZlcYrg/Aides-jeunes?node-id=158-38

J'ai l'impression que ça diffère par rapport à ce qui est voulu, cependant comme il y a une seconde PR j'imagine que ça sera intégré à ce moment là ? 

Dans ce cas p.e. attendre de mettre les deux en même temps ? (celle ci à l'avantage de faire déjà une belle refacto) 

Vous en pensez quoi @Shamzic @Cugniere ?

2023-04-28 08:37 UTC, Shamzic commented
> Tout fonctionne chez moi, le code semble good. Juste par rapport au figma que tu m'a envoyé ce matin : https://www.figma.com/file/7jf3cnZ1CbmTtb3GZlcYrg/Aides-jeunes?node-id=158-38
> 
> J'ai l'impression que ça diffère par rapport à ce qui est voulu, cependant comme il y a une seconde PR j'imagine que ça sera intégré à ce moment là ?
> 
> Dans ce cas p.e. attendre de mettre les deux en même temps ? (celle ci à l'avantage de faire déjà une belle refacto)
> 
> Vous en pensez quoi @Shamzic @Cugniere ?

Oui, ici l'objectif principal de la PR est de séparer les informations dans une vue et d'en profiter pour refacto, l'intégration de la maquette sera dans les PR suivantes. On pourra toutes les PR d'un coup pour que ce soit plus cohérent effectivement.

2023-04-28 09:47 UTC, Shamzic commented
> Après c'est mon interprétation de l'ux de la tâche

Ok j'ai compris, je supprime la proposition de refonte sur la page `/simulaiton/resultats/lieux` mais je la laisse sur la page `simulation/resultats/:droitId`

2023-05-09 07:12 UTC, Valandr reviewed
Testé en local, ok pour moi.

2023-05-17 08:03 UTC, Shamzic commented
Je ferme cette PR car elle va être intégrée dans la PR #3662

2023-05-17 08:03 UTC, closed without merging