Fix and refacto le script d'anonymisation
betagouv/aides-jeunes pull request #3661
Opened 2023-04-24 14:17 UTC by baptou12

- ⚙️ Suppression des process.exit qui faisait s'arrêter le script en cours de traitement (le fait de finir les followup faisait s'arrêter les simulations par exemple)
- Utilisation d'async/await pour faciliter la lecture
- Ajout d'une déconnexion de la DB à la fin du script

2023-04-24 15:02 UTC, Shamzic commented
J'ai testé et ça fonctionne bien en local, même si je ne pense pas être exhaustif dans mes tests. 
Est-ce que des tests unitaires pourraient être envisagés pour cette feature ? Je ne crois pas qu'il en existe aujourd'hui ?

2023-04-24 15:22 UTC, baptou12 commented on tools/cleaner.ts
>    const aWeekAgo = new Date().getTime() - 7 * 24 * 60 * 60 * 1000
Je change. En effet c'était pas très beau

2023-04-25 12:04 UTC, Shamzic requested changes

2023-04-25 12:04 UTC, Shamzic commented on package.json
> +      "^(?!.*currency\\.js)(.+)\\.js$": "$1",
J'ai testé de remettre `"(.+)\\.js": "$1",` et les tests jest passent toujours. Quels étaient tests qui bloquaient chez toi dans le cadre de cette modification ?

2023-04-25 12:18 UTC, baptou12 commented on package.json
> +      "^(?!.*currency\\.js)(.+)\\.js$": "$1",
Ah oui depuis que j'ai extrait les fonctions c'est peut être plus nécéssaire, même si y'a belle et bien un soucis avec la lib `currency.js` (juste parce qu'elle fini en `.js` d'ailleurs. 

Quand on essaie d'importé n'importe quel fichier qui fait appel à `./lib/benefits/details.ts` jest ne sait pas importé et ça met l'erreur suivante : 

<img width="684" alt="image" src="https://user-images.githubusercontent.com/4059803/234273389-39712461-b5c2-4b7b-a0b8-e87ffa943842.png">
je vais retirer le commit et créer un ticket, une solution plus propre serait p.e. d'exiger que l'import comment par au moins un `.` et/ou un `/` ?

2023-04-25 12:23 UTC, baptou12 commented on package.json
> +      "^(?!.*currency\\.js)(.+)\\.js$": "$1",
Ticket : https://trello.com/c/vp1NVmgJ/1270-fix-des-du-modulenamemapper-pour-les-imports-dans-jest

2023-04-26 12:55 UTC, Shamzic approved these changes
Une remarque anodine de refacto et ok pour moi également :)

2023-04-26 12:55 UTC, Shamzic commented on tests/unit/tools/cleaner.spec.js
Pour tous les termes d'anonymisation, en anglais tu as utilisé `anonymize` du coup je te propose d'uniformiser avec le `z` dans ce fichier aussi

2023-04-26 13:20 UTC, merged