Ajoute les lieux à proximité directement en résultats d'une aide
betagouv/aides-jeunes pull request #3662
Opened 2023-04-25 15:19 UTC by Shamzic

Cette tâche ajouter les encarts de la refonte UI/UX des pages de résultats.

- [x] Ajouter l'encart pour l'affichage des lieux à proximité
- [ ] Ajouter l'encart "Comment l'obtenir"
- [ ] Supprimer les informations redondantes : WIP

2023-05-02 15:49 UTC, baptou12 requested changes

2023-05-02 15:49 UTC, baptou12 commented on src/components/droits-details.vue
> -        <BenefitCta :benefit="droit" />
J'ai l'impression que le composant `BenefitCta` n'est plus utilisé, si je me trompe pas on pourrait l'enlever ?

2023-05-02 15:49 UTC, baptou12 commented on src/composables/use-etablissements.ts
> +    const benefitId = $route.params.benefit_id || $route.params.droitId // Problème historique => Todo : uniformiser les paramètres des routes avec benefit_id
On y utilise pas `use-etablissement` mais on a même `:benefitId` pour la vue [Aides](https://github.com/betagouv/aides-jeunes/blob/b3933cc366035892b7da502cee91e05ea05b1eb3/src/views/aide.vue#L0-L1) pour info (à mettre dans le ticket de todo je pense)

2023-05-02 15:49 UTC, baptou12 commented on src/components/droits-details-lieux.vue
> +    <p v-show="updating" class="fr-py-3w">
Ce paragraph n'est jamais montré car il faut que `updating` soit falsy ligne 15

2023-05-02 15:49 UTC, baptou12 commented on src/views/simulation/resultats/lieu-informations.vue
> +    <BackButton class="fr-mb-2w" size="small" @click="goBackToNearbyPlaces">
Y'a un truc qui me parait potentiellement source de bugs ici : 
On a deux condition différentes (p.e. très proche niveau metier, mais pas identique) qui gère ce qu'on dit que fait le bouton (`backButtonLabel`) et ce que fait réellement le bouton `goBackToNearbyPlaces`. 

J'ai l'impression qu'on devrait choisir une de ces deux conditions quitte à faire une fonction qui renvoi le bouton en entier ? afin d'éviter une potentiel (et future) désynchro entre ce que le bouton fait et dit qu'il fait ?

2023-05-02 15:49 UTC, baptou12 commented on src/components/benefit-cta-link-light.vue
> +  mixins: [ResultatsMixin],
J'ai l'impression qu'on a pas besoin de ce Mixin

2023-05-02 16:40 UTC, Shamzic commented on src/components/droits-details.vue
> -        <BenefitCta :benefit="droit" />
Oui je l'ai laissé car c'est un souhait exprimé de vouloir garder les versions historiques de cette partie là pour pouvoir faire un retour en arrière rapidement (c'est ce que j'ai compris @Cugniere , n'hésite pas à me corriger si j'ai mal compris)

2023-05-02 16:41 UTC, Shamzic commented on src/components/benefit-cta-link-light.vue
> +  mixins: [ResultatsMixin],
Il est utilisé en version historique (cf ma réponse dans le premier commentaire)

2023-05-03 08:41 UTC, baptou12 commented on src/components/droits-details.vue
> -        <BenefitCta :benefit="droit" />
Ok je comprend l'idée, pas super fan de garder du code mort. Mais comme on part sur ça on pourrait créer un ticket avec une due date dans X semaines/mois, pour se rappeler de l'enlever si on est finalement pas revenu en arrière ?

2023-05-03 08:47 UTC, Shamzic commented on src/composables/use-etablissements.ts
> +    const benefitId = $route.params.benefit_id || $route.params.droitId // Problème historique => Todo : uniformiser les paramètres des routes avec benefit_id
J'ai ajouté cela au ticket suivant https://trello.com/c/bfBUIsDf/1286-uniformiser-le-nom-et-la-casse-des-param%C3%A8tres-des-routes-contenant-benefitid-droitid-benefitid

2023-05-03 09:50 UTC, Shamzic commented on src/components/droits-details.vue
> -        <BenefitCta :benefit="droit" />
Je suis bien d'accord avec toi car on a l'historique de git et le code mort est encombrant. 
Il faut voir aussi si faire de l'AB testing est souhaité sur cette partie. Je poserais la question au prochain point d'équipe 👍

2023-05-03 09:51 UTC, Shamzic commented on src/components/benefit-cta-link-light.vue
> +  mixins: [ResultatsMixin],
J'ai supprimé le mixin suite à un refacto en composition api

2023-05-03 09:54 UTC, Shamzic commented on src/components/droits-details-lieux.vue
> +    <p v-show="updating" class="fr-py-3w">
Chez moi il est pourtant visible tant que la requête pour récupérer les lieux n'a pas aboutie car updating est initialisé à `false` dans `use-etablissement.ts` et se met à `true` une fois l'appel à l'API du service public effectué et terminé

2023-05-03 14:51 UTC, Shamzic commented on src/views/simulation/resultats/lieu-informations.vue
> +    <BackButton class="fr-mb-2w" size="small" @click="goBackToNearbyPlaces">
J'ai pas mal réfléchi à ta proposition qui était plutôt pertinente. Dans un premier temps j'ai pensé faire ce que tu proposais mais j'ai trouvé le fait de construire un composant dans un méthode un peu compliqué pour ce qu'on voulait faire. Au final j'ai refacto la page /aides et la double logique présente dans ce fichier n'est plus nécessaire et permet d'éviter de chercher la solution à ce problème qui n'existe plus (le bouton de retour a désormais un seul label)

2023-05-04 08:55 UTC, Shamzic commented on src/components/droits-details.vue
> -        <BenefitCta :benefit="droit" />
Conclusion suite au point avec l'équipe : on garde le code actuel pour faire de l'AB testing

2023-05-04 12:06 UTC, Shamzic commented
Je repasse en draft le temps d'implémenter l'ab testing

2023-05-05 15:14 UTC, Shamzic commented
Tests e2e corrigés avec l'AB testing, dispo pour une nouvelle review 🐼

2023-05-09 07:15 UTC, Valandr reviewed
Testé de mon côté en local, c'est fonctionnel.

2023-05-11 13:27 UTC, baptou12 requested changes
Je n'ai pas eu le temps de check en local avant, mais voici une première partie de mes retours

2023-05-11 13:27 UTC, baptou12 commented on src/components/etablissement-informations.vue
> +    {{ etablissement.telephone }}
On met deux fois le numéro de téléphone non ?

2023-05-11 13:27 UTC, baptou12 commented on src/router.js
> +          name: "benefitEtablissementInformationsLight",
Comme y'a le AB testing on a encore besoin de ces deux routes (avec celle au dessus) ? elle redirige vers la même vue actuellement

2023-05-11 13:27 UTC, baptou12 commented on src/components/etablissement.vue
> +              etablissement_id: etablissement.id,
Si y'a un benefitId, on devrait pas le mettre dans les params ?

2023-05-11 13:27 UTC, baptou12 commented on src/router.js
> +          name: "benefitEtablissementInformationsLight",
En gros sur les 4 routes, j'ai l'impression qu'il y en a une en trop, mais je me trompe p.e.

2023-05-12 14:57 UTC, baptou12 commented on src/components/droits-details.vue
> +      return ABTestingService.getValues().css_text
J'ai parcouru un peu le service d'A/B testing. J'ai l'impression qu'il était utilisé une seule fois avant afin d'afficher/modifier (ou non) la description du droit `css_participation_forfaitaire`  [ici](https://github.com/betagouv/aides-jeunes/blob/ff14e587666441e6180713806a67502214705201/src/components/droits-list.vue#L137)

D'où le nom css_text (j'avoue que je pensais au css plutôt qu'à "complémentaire santé solidaire" 😅)

Du coup a mon avis c'est pas bien d'utiliser ici le segment `css_text` de l'abtesting (défini [ici](https://github.com/betagouv/aides-jeunes/blob/b403477c726754139242c26b89bd338c9e28edfe/src/plugins/ab-testing-service.js#L30-L34))

Il faudrait rajouter un nouveau segment autre que `css_text` plus approprié avec ses propre proba (enfin on peut laisser 50/50, mais c'est pour l'idée).

2023-05-12 15:19 UTC, Shamzic commented on src/components/droits-details.vue
> +        <BenefitCta :benefit="droit" class="fr-mt-4w" :type="eventTypeMSA" />
J'ai l'impression que c'est une erreur car le composant n'attend pas de props `type` , merci pour la remarque 💭

2023-05-12 15:24 UTC, baptou12 commented on src/components/etablissement-informations.vue
> +    {{ etablissement.telephone }}
Ah c'est affichage et bouton en fait

2023-05-12 15:44 UTC, Shamzic commented on src/router.js
> +          name: "benefitEtablissementInformationsLight",
On en a encore besoin car les deux path ne sont pas les mêmes : 
`path: "resultats/:droitId/:etablissement_id/informations",`
et `path: "resultats/:benefit_id/lieux/:etablissement_id/informations",`. Ce sera à supprimer dans le ticket https://trello.com/c/bfBUIsDf/1286-uniformiser-le-nom-et-la-casse-des-param%C3%A8tres-des-routes-contenant-benefitid-droitid-benefitid

2023-05-15 15:16 UTC, Shamzic commented on src/components/etablissement.vue
> +              etablissement_id: etablissement.id,
Exact, c'est une erreur là aussi, ce composant est dédié uniquement à l'ancienne version, je supprime tout le code non utile

2023-05-16 08:51 UTC, baptou12 commented on src/router.js
> +          name: "benefitEtablissementInformationsLight",
Mais ce que je comprend pas c'est que même si le path est différent (ajout de "/lieux" au milieu) ça renvoi exactement sur la même vue, avec le même `headTitle`, les même paramètres définis (hormis le nom benefit/droit mais c'est géré [ici](https://github.com/betagouv/aides-jeunes/blob/b54c537e8ff14893668d5a86dadaa74ffbe89206/src/composables/use-etablissements.ts#L78) et sera fix par le ticket que tu mentionne) et par ailleurs on parse pas le current path pour voir si "/lieux" est inclu ou non. 

Du coup sauf si quelque chose m'échappe j'ai l'impression que ça envoi exactement vers la même page => c'est ça qui me fait dire qu'il y en a un en trop

2023-05-16 09:14 UTC, baptou12 commented on src/router.js
> +          path: "resultats/lieux/:etablissement_id/informations",
J'ai l'impression qu'on a un soucis sur cette route (pas sûr qu'il y ai un gros impacte en revanche) 
- on cherche à montrer un établissement par rapport à sont id (sans aides associé). 
- Pour ça on passe par useEtablissement qui fetch les établissement dans un depcom et filtre sur l'id

⚠️ en fait ici on est pas sensé avoir de depcom

- Soit on a celui de la simulation, mais rien ne garantie que l'établissement visé soit dans la ville => on affiche rien
- Soit on en a pas => dans ce cas ça devrait bugger je pense : on est sauvé par le fait que ce lien n'est pas affiché quand on a pas de simulation.

Tu fais le même constat ?

2023-05-16 13:39 UTC, Shamzic commented on src/router.js
> +          path: "resultats/lieux/:etablissement_id/informations",
Point résolu à l'oral : l'appel API a bien besoin d'un depcom pour charger la liste des établissements à proximité, mais le cas n'a jamais lieu dans le cadre de cette refonte. Une erreur sentry a quand même été ajoutée dans le dernier commit pour pouvoir identifier le cas si un jour il pouvait arriver dans un dev futur.

2023-05-16 13:43 UTC, Shamzic commented on src/router.js
> +          name: "benefitEtablissementInformationsLight",
Point résolu à l'oral avec Baptiste: les routes ajoutées ici seront bien fusionnées/modifiées dans un futur refacto car les seules choses qui changent sont le query param de l'id de l'aide et le path qui doit rester cohérent selon le contexte.

2023-05-17 09:23 UTC, guillett commented on src/components/droits-details.vue
> +    },
```suggestion
    experimentNewUI() {
      return ABTestingService.getValues().benefit_result_page == "newUI"
    },
```

2023-05-17 09:23 UTC, guillett commented on src/plugins/ab-testing-service.js
> +  ABTesting.benefit_result_page = ABTesting.benefit_result_page || {}
C => OldUI
D => NewUI

2023-05-17 09:23 UTC, guillett commented on src/plugins/ab-testing-service.js
> +    : "D"
```suggestion
  ABTesting.benefit_result_page = ABTesting.benefit_result_page || {}
  ABTesting.benefit_result_page.value = ABTesting.benefit_result_page.value || (Math.random() > 0.5
    ? "OldUI"
    : "NewUI")
```


La complexité du test AB au dessus est spécifique à la transformation d'un premier test en deux nouvelles variantes. Ça peut être simplifié ici.

2023-05-17 09:23 UTC, guillett commented on src/views/simulation/resultats/lieu-informations.vue
> +  if (benefit?.id) {
Sur cette page https://deploy-preview-3662--aides-jeunes.netlify.app/simulation/resultats/css_participation_forfaitaire/3ab4e10c-c4dd-4bbc-871c-71a3aa98dedb/informations en faisant précédent, on passe dans le `if` ou dans le `else` ?

2023-05-17 09:23 UTC, guillett commented on src/composables/use-etablissements.ts
> +  interface Etablissement {
Est ce qu'on pourrait trouver un meilleur nom pour ça ?

2023-05-17 09:23 UTC, guillett commented on src/composables/use-etablissements.ts
> +import { HelpingInstitution } from "@lib/types/helping-institution.d.js"
Peut-être que ça vaudrait le coup de faire un ticket trello pour normaliser la nomenclature français/anglais autour des lieux/établissements/institutions.

2023-05-17 10:12 UTC, Shamzic commented on src/components/benefit-cta-light.vue
> +<script setup lang="ts">
C'est le nom dans la maquette de Jérémie "Aide - Proposition - Light" 
https://www.figma.com/file/7jf3cnZ1CbmTtb3GZlcYrg/Aides-jeunes?type=design&node-id=158-38&t=0fHBJnEFIEdX1oLV-0

2023-05-17 10:21 UTC, Shamzic commented on src/components/droits-details-lieux.vue
> +      <div v-if="etablissements.length === 0">
Je suis d'accord, dans ce cas la logique avec le loader indiquant la récupération des établissements en cours disparaîtrait avec ?

2023-05-17 10:44 UTC, Shamzic commented on src/composables/use-etablissements.ts
> +import { HelpingInstitution } from "@lib/types/helping-institution.d.js"
Carrément

2023-05-17 11:09 UTC, Shamzic commented on src/views/simulation/resultats/lieu-informations.vue
> +  if (benefit?.id) {
Ca allait dans le `else` mais c'était une erreur : le `benefit.id` est `null`, il fallait utiliser `benefit.value.id`car cela provient du composable use-etablissement où `benefit` est une `ref`. 

Je viens de corriger la condition pour que cela passe dans le `if` et le $router.back n'est là que dans un cas potentiel où il n'y a pas de benefit, mais cela ne devrait jamais arriver (je pourrais presque le retirer ?).  J'ai aussi corrigé le chemin de retour qui n'était pas bon non plus

2023-05-17 11:17 UTC, Shamzic commented on src/composables/use-etablissements.ts
> +  interface Etablissement {
InstitutionTypes ?
InstitutionByTypes ?
NearbyInstitutionByTypes ?

2023-05-17 15:44 UTC, baptou12 commented on src/components/benefit-cta-link-light.vue
> +  link: "Plus d'informations",
Je n'avais pas vu, mais pourquoi override link ici ? c'est la même valeur.
En fait même pourquoi avoir cette `const` du coup ?

2023-05-19 09:40 UTC, Shamzic commented on src/components/benefit-cta-link-light.vue
> +  link: "Plus d'informations",
C'était historique dans le composant `benefit-cta-link`, je viens de proposer un refacto

2023-05-19 09:42 UTC, Shamzic commented on src/composables/use-etablissements.ts
> +  interface Etablissement {
Ok pour `EtablissementTypeCriteria`, merci pour la suggestion  👍

2023-05-19 09:50 UTC, Shamzic commented on src/components/droits-details.vue
> +      return ABTestingService.getValues().benefit_result_page
> J'ai l'impression que `experimentNewUI` c'est un peu comme une question ici ? "est-ce qu'on expérimente la nouvelle UI". Du coup on pourrait même faire que ça renvoi un bool pour simplifier les condition ?
> 
> T'en pense quoi ?

Ce nom était un souhait de Thomas et je suis ok avec ta logique :)

2023-05-19 09:55 UTC, Shamzic commented
> 



> Few comments, mais PR fonctionnelle, faudrait aussi listé les tickets suivant dans cette PR je pense non ?

Yes, j'ajoute les tickets suivants en description

2023-05-22 07:42 UTC, Shamzic commented on lib/benefits/etablissements.ts
> +export async function getEtablissements(depcom, etablissementTypes) {
Correctif intégré dans la PR #3699 pour alléger la lecture de cette PR

2023-05-24 14:13 UTC, baptou12 commented on src/components/droits-details-lieux.vue
> +      <div v-if="etablissements.length === 0">
Pas forcément, on peut aussi simplement supprimer ce div non ? 
Ça fera que on affichera peut être temporairement "Récupération des lieux à proximité en cours…" et que le div disparait. 
Ça me parait ok niveau UI

2023-05-24 14:38 UTC, baptou12 reviewed
Je viens de faire une dernière passe sur la PR,

TLDR : 1/ ça fonctionne, 2/ ça améliore pas mal certaines partie du code (1) 3/ en revanche la récupération de l'output de l'AB testing n'est pas super claire (2)

Ce dernier point est selon moi le plus important avant de merger car sinon soit on ne virera jamais le code A ou B (ou bien on pourrait le virer dès maintenant). Et comme la longueur de la PR est principalement lié à l'AB testing ça serait dommage 😅

Si cette partie est clair alors selon moi on peut merge. 

Quoi qu'il en soit j'ai l'impression qu'on pourrait ajouter (remettre) un event pour le recorder `showLocation` quand dans la nouvelle version on click sur un des établissements.

(1) même si certaines partie legacy pourrait être amélioré c'est pas le cadre de cette pull request selon moi.
(2) comment on prend la decision on garde A ou B

2023-06-02 17:02 UTC, baptou12 approved these changes
LGTM, en revanche il y a deux commentaires de @guillett qui n'ont pas été résolu, je ne sais pas si vous en avez parlé ensemble ?

2023-06-05 10:12 UTC, Shamzic commented on src/components/droits-details-lieux.vue
> +      <div v-if="etablissements.length === 0">
@baptou12 Si on supprime la div c'est un peu étrang, ça donne un onglet avec aucune information dedans : 
![image](https://github.com/betagouv/aides-jeunes/assets/18016058/6efa8016-5c32-4589-9ee5-e9d42153f8f7)

2023-06-06 13:26 UTC, merged