Ajoute un lien dans le footer et une route pour afficher le contenu HTML d'un email en ligne
betagouv/aides-jeunes pull request #3680
Opened 2023-05-09 15:20 UTC by Shamzic

https://trello.com/c/3JTAA7V2/1258-int%C3%A9grer-dans-les-emails-envoy%C3%A9s-un-lien-vers-une-version-de-lemail-accessible-en-ligne-et-s%C3%A9curis%C3%A9

2023-05-11 08:41 UTC, baptou12 requested changes

2023-05-11 08:41 UTC, baptou12 commented on backend/routes/emails.ts
> +      return
On pourrait raise une erreur ici si on pense que ça doit pas arrivé (qui sera catch ligne 46)

2023-05-11 08:41 UTC, baptou12 commented on backend/routes/emails.ts
> +      case EmailType.simulationUsefulness:
Peut être pas dans cette PR mais entre ça ici et le quasi inverse [ici](https://github.com/betagouv/aides-jeunes/blob/01f5241bc22c9dc9ce068e5da6dd52139d0d78fc/backend/models/followup.ts#L101-L105) je me demande si la distinction emailType surveyType est vraiment pertinente ?

2023-05-11 08:41 UTC, baptou12 commented on backend/routes/emails.ts
> +import Followup from "../../backend/models/followup.js"
Normalement on peut utiliser @backend maintenant : https://github.com/betagouv/aides-jeunes/blob/01f5241bc22c9dc9ce068e5da6dd52139d0d78fc/tsconfig.server.json#L24

2023-05-11 08:41 UTC, baptou12 commented on backend/lib/mes-aides/emails/email-render.ts
> +    emailRenderURL: `${config.baseURL}${APIEmailRenderURL}${followup._id}/${emailType}`,
Chaud pour en discuter en synchro à plusieurs, mais niveau sécurité a priori le principal soucis que je vois c'est que si quelqu'un a accès à un lien il peut potentiellement avoir accès aux autre email-type (même de mail non envoyé??)

2023-05-11 11:52 UTC, Shamzic commented on backend/routes/emails.ts
> +import Followup from "../../backend/models/followup.js"
J'ai essayé en testant d'autres config mais rien n'y fait, les imports avec @backend comme ` "@backend/models/followup.js" ` ne sont pas reconnus ici

2023-05-11 11:54 UTC, Shamzic commented on backend/routes/emails.ts
> +      case EmailType.simulationUsefulness:
Oui, c'est pertinent car tous les emails n'ont pas forcément de sondages rattachés donc les deux types cohabitent, mais il y a sûrement un refacto à faire pour améliorer cette logique effectivement

2023-05-11 12:46 UTC, baptou12 commented on backend/routes/emails.ts
> +import Followup from "../../backend/models/followup.js"
Ah mince bizarre

2023-05-17 15:37 UTC, Shamzic commented on backend/routes/emails.ts
> +      return
J'ai ajouté un throw, est-ce que ça aurait de la valeur de le capture dans Sentry ? (D'ordre général, je ne sais pas comment justifier l'utilisation de sentry ou non)

2023-05-17 15:42 UTC, Shamzic commented
J'ai ajouté un JWT dans l'url d'accès comme prévu au dernier point d'équipe sur le sujet de la partie "sécurisé" de ce ticket.

Ayant utilisé `config.sessionSecret` censée être set en variable d'environnement, je ne suis pas sûr que ce soit la meilleure clef secrète pour ce cas, je reste preneur de vos avis.

2023-05-19 08:01 UTC, baptou12 requested changes
Fonctionnel selon moi, quelques comments sur l'organisation du code

2023-05-19 08:06 UTC, baptou12 commented on backend/lib/mes-aides/emails/email-render.ts
> +  return jwt.sign(payload, config.sessionSecret)
Un potentielle soucis avec `sessionSecret` c'est que j'ai l'impression qu'il est pas défini en prod, du coup ce sera le secret par default (et visible pour tout le monde) qui sera pris en compte : faudrait s'assurer qu'on le set up en prod avant, (et qu'on réfléchisse à comment on le setup sur la PR ansible (1)). Mais ça reste pareil que ce soit cette clé ou une autre. (donc ok pour utilisé celle ci 🙂)

(1) car faudra qu'il ne change pas sinon ça invalidera les liens des emails

2023-05-22 07:44 UTC, guillett commented on backend/lib/mes-aides/emails/email-render.ts
> +  return `/api/email/${jwt.sign(payload, config.sessionSecret)}`
J'avoue je trouve ça compliqué avec le JWT.

Pourquoi ne pas avoir fait le dev sur 
```suggestion
  return `/api/simulations/:simulationId/followup/:followupId`
```

en sécurisant avec la logique existante (ie cookie) ?

2023-05-22 08:02 UTC, baptou12 commented on backend/lib/mes-aides/emails/email-render.ts
> +  return `/api/email/${jwt.sign(payload, config.sessionSecret)}`
En fait l'objectif qu'on souhaitait atteindre c'est : 
- Pouvoir identifier le followup de l'email
- Pouvoir s'assurer qu'on a bien déjà envoyé l'email pour l'afficher
(post initial [ici](https://github.com/betagouv/aides-jeunes/pull/3680#discussion_r1190822052))

Chose qu'on arrive à faire avec le JWT sans rajouter un token par email dans le followup. (car on met l'email type dans la payload avant de signer). 

Je ne vois pas trop comment faire avec la logique cookie (sachant qu'on a pas de moyen de s'assurer qu'on est sur le même navigateur que là où la simulation a été faite) mais on peut en parler.

2023-05-23 13:04 UTC, Shamzic commented on backend/lib/mes-aides/emails/email-render.ts
> +  return `/api/email/${jwt.sign(payload, config.sessionSecret)}`
> Pourquoi ne pas avoir fait le dev sur
>   return `/api/simulations/:simulationId/followup/:followupId`

J'ai passé un peu de temps à essayer de comprendre, mais j'arrive toujours pas à saisir pourquoi on aurait besoin de l'identifiant de la simulation dans la route pour identifier l'email alors que l'id du followup suffit et que l'id de la simulation est inclu dans ce dernier? Comment on identifie le type de l'email sans le mettre dans un query param ?

2023-05-25 08:16 UTC, baptou12 requested changes

2023-05-26 15:48 UTC, Shamzic commented on backend/controllers/emails.ts
> +      "simulation"
J'ai repris du code existant mais t'as raison je pense pas que ça soit nécessaire ici

2023-05-26 15:52 UTC, Shamzic commented on backend/controllers/emails.ts
> +      return res.sendStatus(404)
Oui, j'ai pas testé ce cas d'erreur en plus

2023-05-26 15:52 UTC, Shamzic commented on backend/controllers/emails.ts
> +    if (!followup) {
Yes, je supprime

2023-05-31 15:59 UTC, baptou12 requested changes
Dernier point, on en discute mais on est good après ça de mon point de vu

2023-06-01 14:45 UTC, baptou12 approved these changes
Good, et j'ai dit un bêtise en prio tout à l'heure sur les JWT vu qu'on les utilises plus maintenant

2023-06-01 15:07 UTC, merged