Corrige un bug d'accès au local storage depuis la page redirection
betagouv/aides-jeunes pull request #3695
Opened 2023-05-16 10:06 UTC by Cugniere

## Détails

Corrige une erreur lors d'un rechargement de la page de redirection sans identifiant de simulation.

2023-05-16 12:00 UTC, baptou12 requested changes
Voir le comment sur l'erreur

2023-05-16 14:24 UTC, Shamzic commented
Pas sûr d'avoir saisi l'intérêt de lever l'erreur sur le json.parse de l'item @baptou12 ? 
Ok pour moi sinon, fonctionnel en local :)

2023-05-16 15:06 UTC, baptou12 commented
> Pas sûr d'avoir saisi l'intérêt de lever l'erreur sur le json.parse de l'item ? Ok pour moi sinon, fonctionnel en local :)

En fait l'objectif c'est de catch les erreurs le plus haut possible pour se laisser le choix à l'endroit où on utilise le service de comment on traite l'erreur. 

Exemple : ici on pourrait vouloir traité différemment si la clé n'est pas défini (cas normal au début par exemple) de si elle n'est pas "json parsable" (cas d'erreur dû par exemple à un bug dans une précédente version). 

Si on fait en sorte que le service renvoi une erreur quand quelque chose se passe mal, ça ferme aucune porte à l'endroit où on utilise, on a toujours la possibilité : gestion du cas null puis catch de l'erreur dans l'autre cas. 

Après si on se rend compte que on fait toujours le même traitement "cas null et non parsable géré de la même manière", on pourra toujours rajouter une méthode du genre `getItemSafe` qui wrap `getItem` dans un catch et renvoi null si non parsable.

2023-05-17 13:03 UTC, baptou12 approved these changes

2023-05-17 13:03 UTC, baptou12 approved these changes

2023-05-17 13:07 UTC, merged