Reformule les finalités associées aux cookies
betagouv/aides-jeunes pull request #3697
Opened 2023-05-17 10:59 UTC by guillett

2023-05-19 15:31 UTC, baptou12 requested changes
Fonctionnel en local et cookies cohérents a priori.
Besoin d'éclaircissement pour valider complètement.

2023-05-24 12:43 UTC, baptou12 commented on src/views/confidentialite.vue
>        ] as Cookies,
D'ailleurs il nous faudrait un check vis à vis de ça, pour commencer un check lazy qui test les mauvais typages (sans forcément fail sur les non typages ou les typages trop permissifs)

2023-05-25 13:43 UTC, guillett commented on src/components/matomo-opt-out.vue
> +      pourrez donc pas vous inscrire tant que vous n'aurez pas désactivé la
J'ai aucune idée, une grosse typo ou un mauvais copier-coller. Merci !

2023-05-25 13:56 UTC, guillett commented on src/components/matomo-opt-out.vue
> +      isUserTracked.value = !doNotTrack && !this.isUserOptedOut()
C'est quand même fonctionnel chez 67% des navigateurs en France. https://caniuse.com/?search=do%20not%20track.

Effectivement ici ça semble superflu.

2023-05-30 09:03 UTC, baptou12 requested changes
Je ne comprend pas trop pourquoi, mais en refaisant mes test j'arrive à un comportement qu'on veut pas : 
- Cocher la case pour accepter les cookies
- Mettre son doNotTrack à true dans son navigateur

⇒ On envoi bien des requêtes piwik 😨. 

J'ai trouvé ça qui peut "forcer matomo à doNotTrack" : 
`_paq.push(["setDoNotTrack", window.navigator.doNotTrack === "1"]);` 
([ici](https://fr.matomo.org/faq/general/configure-privacy-settings-in-matomo/) "Step 4) Respect DoNotTrack preference")
> Note : quand la page est rechargée ça revient comme avant donc faut le mettre à un endroit plus central du site).

Chaud pour en discuter, je trouve ça bizarre de la part de matomo




À part ça faudrait rebase master encore, et petit remarque sur du naming.

2023-05-31 14:11 UTC, guillett commented
Je pense que le DoNotTrack DNT est géré coté serveur via le header dans les requêtes DNT.
1. soit on garde en l'état
2. soit on supprime la logique de gestion du DNT dans le navigateur (et on peu permet aux gens d'éviter que piwik envoie les infos au serveur (même si dans tous les cas, étant donné DNT=1, il les ignore.)

2023-05-31 14:51 UTC, merged