Sécurise le token d'accès github avec un jwt pour la page d'accompagnement
betagouv/aides-jeunes pull request #3700
Opened 2023-05-22 14:17 UTC by Shamzic

[Tâche [Trello]()](https://trello.com/c/1EE5v4jx/1289-corriger-la-gestion-dacc%C3%A8s-%C3%A0-loutil-daccompagnement-pour-%C3%A9viter-que-les-usagers-puissent-se-faire-passer-pour-nous-aupr%C3%A8s-de-gh)

J'ai repris la variable d'environnement `sessionSecret` comme pour la Pr #3680 afin de signer le token, il faudra donc s'assurer que celle ci est bien définie en production avant de merger.

2023-05-24 08:43 UTC, Shamzic commented on backend/controllers/github.ts
> +        access_token: result.data.access_token,
Hum effectivement, il faudrait donc soit crypter le payload du jwt, soit cypter directement le token github sans passer par un jwt ?

2023-05-24 12:14 UTC, Shamzic commented on backend/controllers/github.ts
> +        access_token: result.data.access_token,
Merci pour ta réponse, preneur également d'un point d'équipe pour mettre au clair la solution à choisir

2023-05-25 08:32 UTC, Shamzic commented on backend/controllers/github.ts
> +        access_token: result.data.access_token,
Suite au point oral tout à l'heure, de ce que j'ai saisi, la solution choisie est la suivante : 
On vérifie que le nom d'utilisateur github est dans la liste des utilisateurs autorisés comme actuellement, et si c'est le cas on signe directement ce pseudo avec notre clef secrete pour en faire un jwt qu'on stocke dans les cookies. Le github_token lui n'est pas conservé.

2023-05-25 14:11 UTC, Shamzic commented
Description mise à jour

2023-05-25 16:06 UTC, baptou12 reviewed
Cool, ça fonctionne, le code est good selon moi hormis peut être des soucis de naming, j'ai fait quelques proposition, rien de bloquant mais je serais chaud d'avoir ton avis.

2023-05-26 12:32 UTC, Shamzic commented on backend/controllers/github.ts
> +const postCodeValidation = async (code) => {
Effectivement, le but de cette méthode c'est bien de récupérer un token. J'étais pas très à l'aide de mettre `get` dans un méthode qui fait un post ^^
Du coup ok le nom `retrieveGithubAccessToken` 👍

2023-05-26 12:37 UTC, Shamzic commented on backend/controllers/github.ts
> +      const accessResponse = await postCodeValidation(githubCode)
Yes, je vais même mettre `githubAccessToken`

2023-05-26 13:41 UTC, guillett commented on backend/controllers/github.ts
> +        res.clearCookie("github_login_token")
Il y a une incohérence dans le nom de ce cookie. De plus j'ai une petite préférence pour `github_handle_token`.

2023-05-30 09:12 UTC, baptou12 commented on src/views/confidentialite.vue
> +              name: "github_signed_token",
Mauvais nom de cookie ici desormais

2023-05-30 09:16 UTC, baptou12 requested changes
Bloquant : la cohérence page confidentialité et nom de cookie

2023-05-30 09:34 UTC, Shamzic commented on backend/controllers/github.ts
> +const getGithubUsername = async (token) => {
Moi je préférais login car c'est ce qui est renvoyé dans la réponse Github

2023-05-31 12:20 UTC, merged