Ajout règle suppression data simulation/sondage
betagouv/aides-jeunes pull request #3706
Opened 2023-05-25 10:23 UTC by Valandr

[Tâche Trello](https://trello.com/c/uRGmjt9E/1291-ajouter-une-r%C3%A8gle-supprimant-les-donn%C3%A9es-de-simulation-sondage)

2023-05-25 13:18 UTC, baptou12 requested changes

2023-05-25 13:18 UTC, baptou12 commented on tools/cleaner.ts
> +  const twoYearsAgo = Date.now() - 2 * 365 * 24 * 60 * 60 * 1000
Je le fais aussi dans la PR d'anonymisation de FranceConnect, mais ici tu peux utiliser la lib `dayjs` pour avoir quelque chose de plus lisible (et ne pas répéter partout `24 * 60 * 60 * 1000`.

Exemple : https://github.com/betagouv/aides-jeunes/pull/3671/commits/63d6d67959eff730fb441af1929367471a63eb75

2023-05-25 13:18 UTC, baptou12 commented on tools/cleaner.ts
> +  const oldFollowupsCursor = await Followup.find({
On pourra en discuter, mais je me pose la question de la nécéssité de `console.log` la list des followup. Si on enlève cette contrainte alors on doit pouvoir faire quelque chose du style 
```
try {
  await Followup.find({ createdAt: { $lt: sixMonthsAgo } }).deleteMany()
} catch (err) {
  console.error("Error deleting followups", err)
}
```

Ça évite la boucle ici.

2023-05-25 13:20 UTC, baptou12 commented on tools/cleaner.ts
> +  const oldFollowupsCursor = await Followup.find({
Par ailleurs deleteMany renvoi le nombre de documents supprimés, ça peut être utile de l'afficher.

2023-06-06 12:18 UTC, baptou12 requested changes

2023-06-06 12:18 UTC, baptou12 commented on tools/cleaner.ts
> +    console.log(["Terminé", "Followup", followup_count].join(";"))
Il faut ressortir le `console.log` du for sinon ça va print à tout les saves et pas seulement pour le nombre total à la fin

2023-06-06 12:18 UTC, baptou12 commented on tools/cleaner.ts
> +    console.log(["Terminé", "Simulation", simulation_count].join(";"))
Parei ici, il faut le sortir du `for` comme c'était avant

2023-06-06 12:18 UTC, baptou12 commented on tools/cleaner.ts
> +  console.log(`Deleted ${deleteSixMonthsOldFollowups.deletedCount}`)
ici on peut ajouter un peu de context dans le log car si on a "Deleted 63" on sait pas trop de quoi on parle (enfin il faut regarder le code pour comprendre. 

```suggestion
  console.log(`Deleted ${deleteSixMonthsOldFollowups.deletedCount} followups`)
```

2023-06-06 12:18 UTC, baptou12 commented on tools/cleaner.ts
> +  console.log(`Deleted ${deleteTwoYearsOldSimulations.deletedCount}`)
```suggestion
  
  console.log(`Deleted ${deleteTwoYearsOldSimulations.deletedCount} simulations`)
```

2023-06-06 13:15 UTC, baptou12 approved these changes
Ça me semble good, comme ça touche à la suppression de donnée je préconise un deuxième avis avant de merger (ça sera effectif directement demain matin quand ça sera en prod)

2023-06-21 08:07 UTC, baptou12 commented on tools/cleaner.ts
> +    dateDeValeur: { $lt: twoYearsAgo },
A je viens de voir, pourquoi `dateDeValeur` et pas `createdAt` ici aussi @Valandr ?

2023-06-23 14:32 UTC, guillett commented
En fait on peut ajouter la suppression des messageId à l'étape d'anonymisation qui existe déjà.

Et créer une nouvelle étape d'anonymisation des followups et les passer à `unlinked` en supprimant le `simulationId`.

2023-07-06 12:39 UTC, baptou12 commented
Je ferme en attendant des précision venant de ce ticket : https://trello.com/c/uRGmjt9E/1291-expliciter-les-r%C3%A8gles-supprimant-les-donn%C3%A9es-de-simulation-sondage

2023-07-06 12:39 UTC, closed without merging