Supprime l'AB testing sur l'aide de la CSS et applique l'ancien scénario D
betagouv/aides-jeunes pull request #3729
Opened 2023-05-31 16:09 UTC by Shamzic

https://trello.com/c/oxrnL13Y/1308-supprimer-lab-testing-sur-la-css-et-utiliser-lalternative-d

2023-05-31 16:16 UTC, baptou12 requested changes

2023-05-31 16:16 UTC, baptou12 commented on src/components/droits-list.vue
> +            return {
Comme on override plus la description de l'aide [CSS](https://github.com/betagouv/aides-jeunes/blob/master/data/benefits/openfisca/css_participation_forfaitaire.yml), je pense qu'on peut modifier la description dans l'aide pour virer tout le map, ça fera toujours moins de code :-)

2023-05-31 16:16 UTC, baptou12 commented on src/plugins/ab-testing-service.js
> -  ABTesting.css_text = ABTesting.css_text || { index: 1 }
C'est pas vraiment lié à la PR, mais je comprend pas les commentaire au dessus 😅 (et je suis pas sûr qu'ils soient encore utils)

2023-06-01 15:03 UTC, Shamzic commented on src/plugins/ab-testing-service.js
> -  ABTesting.css_text = ABTesting.css_text || { index: 1 }
j'ai failli faire un commentaire là dessus mais je me suis dit que ça avait peut-être du sens pour Thomas donc je préfère ne pas y toucher ici

2023-06-01 15:05 UTC, baptou12 approved these changes

2023-06-01 15:40 UTC, merged