Ajoute une page dédiée pour le formulaire d'envoi de récap par email
betagouv/aides-jeunes pull request #3740
Opened 2023-06-02 14:03 UTC by Shamzic

[Tâche associée](https://trello.com/c/oSWLFtKi/1324-sortir-l%C3%A9cran-denvoi-dun-r%C3%A9cap-vers-une-vraie-page):

- [x]  Ajout d'une nouvelle page pour accéder au formulaire de récapitulatif de simulation par email
- [x] Ajout de l'AB testing: formulaire dans une fenêtre modale VS formulaire dans une nouvelle page
- [x] Modification de l'affichage du bouton d'accès au formulaire de recap (-> conservé même après l'envoi)
- [x] Correction et ajout de test e2e fixé sur la nouvelle version (nouvelle page)

2023-06-05 08:02 UTC, baptou12 commented on src/plugins/ab-testing-service.js
> +    (Math.random() > 0.5 ? "ModalComponent" : "NewPage")
Ah, pendant le daily je pensais à une tout autre PR mais ça fait sens de faire de l'ab-testing ici (au moins pour verifier qu'on degrade pas)

2023-06-05 14:09 UTC, baptou12 requested changes
J'ai mis quelque remarques. Niveau design j'ai pas trop de billes (mais en as tu 😅?) pour vérifier que c'est ce qu'on veut

2023-06-05 14:09 UTC, baptou12 commented on src/router.js
> +            headTitle: `Recevez par email le récapitulatif de vos réponses avec le simulateur d'aides ${context.name}`,
Chaud pour en discuter et avoir ton point de vu, j'ai l'impression que ça n'apporte pas grand chose

2023-06-05 14:09 UTC, baptou12 commented on src/components/titre-chapitre.vue
> +      if (path === "/simulation/resultats/recapitulatif_email") {
On pourrait aussi enlever le h2 de `recap-email.vue` pour mettre le titre ici : 
Avantage : ça fait gagner en coherence dans les vue (title puis back button) 

Ça fait bizarre de mettre le titre comme ça totalement ailleurs, mais c'est la vue simulation (et la logique router) qui veut ça.

2023-06-05 14:09 UTC, baptou12 commented on src/mixins/resultats.js
> +      console.log("this.store", this.store)
`console.log` temporaires qu'il ne faudra pas oublier

2023-06-05 14:09 UTC, baptou12 commented on src/views/simulation/resultats/recap-email.vue
> +const getRecap = async (surveyOptin) => {
Sans forcément changer la modal (qui est probablement vouer à disparaitre) je changerais le nom ici, car `getRecap` pour l'envoi d'un email ça fait bizarre. Pk pas `SendRecapEmail` ou quelque chose dans ce sens ?

2023-06-06 08:55 UTC, Shamzic commented on src/components/buttons/send-recap-email-button.vue
> +    @click="sendRecapEmailButtonClick"
Peut-être que j'ai mal traduit mais pour moi c'était assez explicite, vu que la traduction littérale est "clic sur le bouton d'envoi de récap d'email" mais je comprends que cela n'évoque pas l'affichage du formulaire qui s'ensuit, donc `GoToEmailForm` ça me va aussi (:

2023-06-06 08:59 UTC, Shamzic commented on src/plugins/ab-testing-service.js
> +    ABTesting.recap_email.value ||
Yes, c'est plus pertinent avec le nom `recap_email_form` et `modal` ou `page` en valeurs d'AB testing

2023-06-06 09:11 UTC, Shamzic commented on src/components/titre-chapitre.vue
> +      if (path === "/simulation/resultats/recapitulatif_email") {
Je voulais faire ça aussi au départ, mais le problème c'est que ça rend moche vu qu'on peut pas toucher au style du titre car il est générique

Ma modif actuelle : 
![image](https://github.com/betagouv/aides-jeunes/assets/18016058/696c8575-6d6b-44b8-8d91-28f15cb059d4)
 
 VS ta suggestion (grossièrement) :
 
 
![image](https://github.com/betagouv/aides-jeunes/assets/18016058/83d1d6e9-586e-433c-85c1-c16e0d10313c)

 
 Après je viens de penser qu'on peut overider le css dans le component recap-email mais ça fait un peu bricolage

2023-06-06 09:17 UTC, Shamzic commented on src/views/simulation/resultats/recap-email.vue
> +const getRecap = async (surveyOptin) => {
`sendEmailRecap` me paraît adéquat

2023-06-06 09:26 UTC, baptou12 commented on src/components/titre-chapitre.vue
> +      if (path === "/simulation/resultats/recapitulatif_email") {
Quand on clic sur une aide, y'a plus d'alignement : 
<img width="963" alt="image" src="https://github.com/betagouv/aides-jeunes/assets/4059803/89ddc49f-3702-4816-beee-a1f0affd02c2">
Peut être creuser par ici ? 

A voir niveau design t'en pense quoi ?

2023-06-06 09:34 UTC, Shamzic commented on src/components/titre-chapitre.vue
> +      if (path === "/simulation/resultats/recapitulatif_email") {
L'alignement du contenu par rapport au titre ici c'est facilement corrigable, le soucis principal c'est que le titre est tronqué

2023-06-06 09:48 UTC, baptou12 commented on src/router.js
> +            headTitle: `Recevez par email le récapitulatif de vos réponses avec le simulateur d'aides ${context.name}`,
Ça ne me choque pas trop, mais ça me va aussi de laisser ce que tu as fait :+1:

2023-06-07 09:46 UTC, Shamzic commented on src/components/titre-chapitre.vue
> +      if (path === "/simulation/resultats/recapitulatif_email") {
Solution optée : suggestion de @baptou12 avec la réutilisation du titre du composant générique; @Cugniere a proposé une modif dans la PR #3745 pour corriger le problème de ta taille max du titre

2023-06-08 16:12 UTC, Shamzic commented on src/components/buttons/send-recap-email-button.vue
> +    @click="goToEmailForm"
Effectivement, je ne l'avais pas vu. J'ai mis en place ta solution qui me semble bien résoudre le problème (:

2023-06-13 09:53 UTC, baptou12 commented on src/components/titre-chapitre.vue
> +      return this.$route.name === "resultats"
Ça me rappelle une discussion, ça permet à l'usager d'envoyer l'email à plusieurs endroit. Faut garder en tête que du coup (comme ça fonctionne) on a une relation one-to-many entre les simulations et les followup. Je pense que parfois on y pense pas tout le temps (on parle parfois du follow up d'une simulation).

2023-06-13 10:17 UTC, Shamzic commented on src/components/titre-chapitre.vue
> +      return this.$route.name === "resultats"
Oui, cela a été évoqué comme une feature par @guillett dans un daily, je me suis permis de l'ajouter ici et j'attends sa confirmation :)

2023-06-13 10:23 UTC, guillett commented on src/components/titre-chapitre.vue
> +      return this.$route.name === "resultats"
Ouais je trouve ça bien de pouvoir renvoyer un followup (on pourra d'ailleurs regarder si c'est utilisé). En test ça m'aurait faciliter la tâche et (surtout) pour les personnes qui souhaitent à la fois recevoir un email et l'envoyer à un.e proche, c'est plus pratique que de devoir faire une fwd.

2023-06-13 11:42 UTC, merged