Refacto etablissements into lieux
betagouv/aides-jeunes pull request #3766
Opened 2023-06-13 17:04 UTC by Shamzic

https://trello.com/c/KflhIcuk/1301-uniformiser-la-nomenclature-des-lieux-%C3%A9tablissements-institutions

2023-06-14 13:16 UTC, Shamzic commented on lib/benefits/lieux.ts
> +}
Il faudrait éventuellement que je retravaille cette partie là car j'ai l'impression que certaines aides ont encore `etablissement` en mot clef et qu'on ne pourra pas y déroger

2023-06-16 16:12 UTC, baptou12 reviewed
Je suis en train de regarder le renaming. 
Le premier blocker temporaire sur cette PR selon moi c'est qu'on modifie pas mal d'interfaces (j'ai en tête le endpoint `/api/benefits` qui est au moins utilisé par Mes-Aides-analytics [ici](https://github.com/betagouv/mes-aides-analytics/blob/9e4be4776036033f6eb572cc60255f7f65957ea1/next.config.js#L18)). 

Il faudra qu'on trouve un moyen de faire une passe sur tout ça.

Edit: Je viens de regarder en plus dans le recorder et a priori on utilise pas la notion d'établissement.

2023-06-19 13:14 UTC, Shamzic commented
> Je suis en train de regarder le renaming. Le premier blocker temporaire sur cette PR selon moi c'est qu'on modifie pas mal d'interfaces (j'ai en tête le endpoint `/api/benefits` qui est au moins utilisé par Mes-Aides-analytics [ici](https://github.com/betagouv/mes-aides-analytics/blob/9e4be4776036033f6eb572cc60255f7f65957ea1/next.config.js#L18)).
> 
> Il faudra qu'on trouve un moyen de faire une passe sur tout ça.

Qu'est-ce que tu suggères pour faire la passe ?

J'ai check dans mes-aides-analytics, je ne vois pas d'utilisation de variable `etablissement`, ni dans stats-recorder.
En ce qui concerne l'outil de contribution, c'est intégré dans ce répo donc à mon sens c'est ok pour cette partie aussi.

2023-06-19 14:02 UTC, baptou12 commented on contribuer/public/admin/config.yml
> +    name: lieux
C'est bizarre ici, car on avait bien `etablissements` donc on avait envi de mettre `lieux`. Mais d'un autre coté on parle d'institution, comme si `etablissements` était déjà faux ? 

Je continue de creuser y'a qqch de pas supra clair encore.

2023-06-19 15:00 UTC, baptou12 commented on contribuer/public/admin/config.yml
> +    name: lieux
J'ai l'impression que établissements / lieux dans les aides ou bien dans les institutions sont en fait des type d'établissement / types de lieux.

Les lieux sont récupéré ici à partir du `depcom` et du type d'établissement. 

Histoire d'être plus claire on pourrait renommer cette partie `lieux_types` ? (enfin si c'est bien ça)

2023-06-19 15:18 UTC, Shamzic commented on contribuer/public/admin/config.yml
> +    name: lieux
Oui, cela m'a l'air d'être ça. J'ai exploré un peu et si je ne me trompe pas, ce champ précis est utilisé exclusivement pour vérifier la cohérence du schéma des aides https://github.com/betagouv/aides-jeunes/blob/9781608e72877cfe1d607b814e71cf4f03c98aed/data/schemas.ts#L74, c'est pour cela qu'il est en `hidden`

2023-06-19 16:05 UTC, baptou12 requested changes
Cf quelques changement de lieux en lieuxTypes

2023-06-20 09:10 UTC, baptou12 requested changes
Simplement quelques questions sur le naming pour continue de bien différentier les différentes notions liées aux lieux

2023-06-20 09:10 UTC, baptou12 commented on src/modules/etablissement.js
> -const EtablissementModule = {
ah top ça supprime du code, c'était pas utilisé on est dac ?

2023-06-20 09:10 UTC, baptou12 commented on src/composables/use-lieux.ts
> +  const lieuxList: LieuTypeCriteria[] = [
```suggestion
  const lieuTypeCriteriaList: LieuTypeCriterion[] = [
```

Pas obligatoire, mais ça améliore encore un peu le naming je trouve. Dis moi ce que tu en pense. Le suffixe `List` devient même questionable.

2023-06-20 09:10 UTC, baptou12 commented on src/composables/use-lieux.ts
> +    for (const lieu of lieuxList) {
Ici en fait ce n'était pas vraiment des établissement et ce ne sont pas des lieu, plutôt des `lieuTypeCriterion` non ?

2023-06-20 12:55 UTC, Shamzic commented on lib/benefits/lieux.ts
> +export function hasLieux(benefit) {
Effectivement, on regarde les types dans cette méthode, mais le but de la méthode c'est de savoir si l'aide a des lieux à proximité du coup je laisserais bien comme ça

2023-06-20 12:58 UTC, Shamzic commented on rollup/benefits.ts
> +  "lieux",
Tout à fait

2023-06-20 14:32 UTC, baptou12 approved these changes

2023-06-20 14:32 UTC, baptou12 commented on lib/benefits/lieux.ts
> +export function hasLieux(benefit) {
Je comprend, ce qui peut arriver en revanche c'est que pour un `depcom` donné on ai un benefit qui a un `lieuxType` mais pas de lieux a proprement parler. 

c'est pas bloquant

2023-06-20 15:10 UTC, Shamzic commented on lib/benefits/lieux.ts
> +export function hasLieux(benefit) {
Ce serait surprenant qu'on ait renseigné un type de lieu pour une aide dans laquelle on a aucun établissement à proximité, mais effectivement ça pourrait potentiellement arriver. J'avoue que j'ai du mal à trancher pour ce cas

2023-06-20 15:12 UTC, Shamzic commented on src/modules/etablissement.js
> -const EtablissementModule = {
Oui, je n'ai pas trouvé d'import et d'utilisation de ce fichier!

2023-06-20 15:14 UTC, Shamzic commented on src/composables/use-lieux.ts
> +  const lieuxList: LieuTypeCriteria[] = [
Je suis d'accord, on peut retirer le mot "list", la variable étant nommée au pluriel :)

2023-06-20 16:33 UTC, Shamzic commented on lib/benefits/lieux.ts
> +  } catch (error) {
Pourquoi on ne voudrait pas de try/catch ? J'ai pour parti pris d'en mettre à pour toutes les requêtes api.

Si il n'y a pas de lieu ça renvoi un tableau vide et si il y a une erreur ça lève l'erreur et renvoi un tableau vide pour pouvoir que l'ux ne soit pas trop perturbée, c'est choquant ?

Je ne crois pas qu'actuellement Sentry liste les `console.error` sur ce répo, mais on doit pouvoir faire cela (éventuellement : https://stackoverflow.com/a/56736902/13728777)

2023-06-21 06:55 UTC, baptou12 commented on lib/benefits/lieux.ts
> +  } catch (error) {
En fait le soucis qu'il peut y avoir c'est que ça donne pas la main à l'utilisateur de la méthode de gérer lui même l'erreur. (par exemple pour afficher un message d'erreur, ou bien pour retry le call).
Dans ton cas si y'a une erreur ou un résultat vide ça renvoi la même chose, donc coté front on affiche rien et on a aucune notification (hormis le log bien sûr, mais il faut les regarder) de dans quel cas on est. 

Le top du top j'ai l'impression que c'est de catch l'erreur, de log (sentry ou console.error), de re-raise une exception et de catch au dessus pour savoir ce qu'on en fait (liste vide, message d'erreur, ...). 

Non bloquant car on le faisait pas super bien avant non plus.

2023-06-21 07:56 UTC, Shamzic commented on lib/benefits/lieux.ts
> +  } catch (error) {
Ok merci pour la réponse.

Si j'ai bien compris je place plutôt un `throw` à la place de mon `sentry.capture`ici https://github.com/betagouv/aides-jeunes/blob/ba87fba1ec9eb173f6c493dc4839924db80eda55/lib/benefits/lieux.ts#L57

Qui sera capturé et géré par un catch ici https://github.com/betagouv/aides-jeunes/blob/ba87fba1ec9eb173f6c493dc4839924db80eda55/src/composables/use-lieux.ts#L99

Où on lèvera l'erreur pour Sentry et on y ajoutera une div fr-alert contenant le message levé pour l'utilisateur. Est-ce que c'est ce que tu attendais ?

2023-06-21 08:01 UTC, baptou12 commented on lib/benefits/lieux.ts
> +  } catch (error) {
Yes, enfin je m'attend pas forcément à l'alerte dans la vue, c'est plus qu'en faisant comme ça on se laisse la possibilité de faire ce qu'on veut dans use-lieux.ts.

2023-06-21 15:21 UTC, baptou12 commented on lib/benefits/lieux.ts
> +export function hasLieux(benefit) {
Y'a le cas où les LieuxType ne sont pas dans tout les depcom par exemple.

2023-06-21 15:22 UTC, baptou12 approved these changes

2023-06-21 15:29 UTC, merged