Ajoute un outil de suivi des liens dans Grist
betagouv/aides-jeunes pull request #3778
Opened 2023-06-19 13:08 UTC by guillett

2023-06-20 15:59 UTC, baptou12 reviewed
@guillett Tu pourras nous mettre le lien du Grist (même en lecture seule). Et j'ai l'impression qu'il manque des choses pour que ça fonctionne, c'est le cas ou j'ai lu trop vite ?

2023-06-27 08:05 UTC, guillett commented on lib/benefits/link-validity.ts
> +            Aide: checkResult.id,
je ne mettrais à jour que le champ Corrigé.

2023-06-27 08:05 UTC, guillett commented on lib/benefits/link-validity.ts
> +                Aide: checkResult.id,
Item, je ne mettrais à jour que le champ Corrigé.

2023-06-27 08:05 UTC, guillett commented on tests/unit/tools/link-validator/existing.spec.ts
> +      expect(operations).toHaveLength(2)
Pourquoi attend-on deux opérations ? Il ne devrait y avoir qu'un update sans ajout non ?

2023-06-27 16:18 UTC, baptou12 commented on tools/check-links-validity.ts
> +      recordsUrl + '?filter={"Corrige": [false]}',
Je serais partant d'ajouter un argument `filter` dans la fonction `get` et de passer le `{"Corrige": [false]}` en dessous dans le main. 

Ça nous donne plus de contexte dans le `main` et permet de ne pas modifier ici si on veut changer le filter ou utilise le `get` autre part

2023-06-27 16:23 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +export function determineOperations(
Cette fonction est très grande, on pourrait ici ne garder que les if qui ferait appelle à différentes fonction d'insertion ou d'update de ligne de la spreadsheet

2023-06-27 16:25 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +          existingWarnings[checkResult.id][item.type].keep = true
Ça sera utilisé comment ?

2023-06-27 16:27 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +            Aide: checkResult.id,
Je me rend pas compte avec Grist que je ne connais pas trop, mais ça sert à quoi de changer `Aide` qui doit déjà avoir la bonne valeur ?

2023-06-27 16:28 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +      operations.push({
Je ne suis pas sûr de comprendre ce dernier ajout ^^

2023-06-27 16:29 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +    } else if (existingWarnings[checkResult.id]) {
Dans cette seconde partie j'ai l'impression qu'on ne gère pas le type de liens

2023-06-28 09:48 UTC, Valandr commented on tools/check-links-validity.ts
> +      m[operation.type].push(operation.record)
On a amélioré le nom de ```m``` et on a ajouté la propriété ```update``` .

2023-06-28 09:53 UTC, guillett commented on tools/check-links-validity.ts
> +      m[operation.type].push(operation.record)
Le regroupement des opérations permet de ne faire que deux appels API à Grist (ajout et update) plutôt qu'autant qu'il y a opérations unitaires à faire.

2023-06-30 11:31 UTC, guillett commented on lib/benefits/link-validity.ts
> +export function determineOperations(
En faisant des refactors sa taille a bien diminué. J'ai rapatrié du code dans ce nouveau fichier pour diminuer la taille du fichier script.

2023-06-30 13:22 UTC, guillett commented on tools/check-links-validity.ts
> +      recordsUrl + '?filter={"Corrige": [false]}',
Oui !! :)

2023-07-03 16:08 UTC, baptou12 commented
Question avant de commencer la review : 
@guillett j'ai l'impression que tu ajoute une tâche de CI pour vérifier les liens en cas de modifications des aides. 
C'est une bonne chose je trouve, de ne pas le déclencher sur les modifications de code only. Mais du coup on est d'accord qu'on ne peut plus créé/modifier/supprimer d'aides si un lien est valide ? 

- C'est assez drastique (même si je comprend l'intention)
- J'ai peur que dans le flow de création d'aide actuel ça pose des soucis car elles sont généralement créé à la suite donc on aura les job en parallèle (qui peuvent durer longtemps) et modifie la même resource in fine

A minima je me dit que ça serait plus pertinent d'essayer de cibler l'aide modifiée ?

2023-07-04 09:45 UTC, guillett commented
La tâche en CI n'est pas bloquante c'est juste pour renseigner les infos dans Grist. Pas d'impact sur le statut des PR.

2023-07-04 10:07 UTC, baptou12 commented
Ok :+1:  il y a certains aspects de mon précédent comment qui deviennent faux, mais plusieurs points restent discutables selon moi : 

- Les pull requests peuvent modifier le Grist, il représente non plus de la branche par défaut, mais de potentiellement plusieurs branches. Par conséquent, le statut d'un lien peut osciller entre corrigé ou en erreur : 

| Par exemple, une PR qui le répare le marquerait comme corrigé, alors qu'un cron pourrait le reclasser comme erreur et ainsi de suite.

- Il y a l'ajout potentiel d'un délai allant jusqu'à 60 minutes de CI pour chaque modification apportée à l'aide, d'autant plus que plusieurs PR sont généralement ajoutées simultanément.

2023-07-04 14:03 UTC, baptou12 requested changes
Review non finie, mais je pars en "formation feedback". Je suis partant pour parler de certains points de vive voix :-)

2023-07-04 14:03 UTC, baptou12 commented on tools/check-links-validity.ts
> +        fields: { PR: pullRequestURL },
Ok du coup je comprend mieux la partie pull request. En revanche je pense qu'on pourrait expliciter un peu plus, p.e. plutôt que de se servir de PullRequestUrl comme variable de switch, en nommer une autre pour dire qu'on est dans un mode de "feed la colonne PR du Grist" ?

2023-07-05 13:42 UTC, guillett commented on .github/has-file-changes.sh
> +result=$(git diff origin/master... --name-only -- "$1")
> git diff [\<options>\] \<commit>...\<commit> [--] [\<path>...]
> This form is to view the changes on the branch containing and up to the second \<commit>, starting at a common ancestor of both \<commit>. "git diff A...B" is equivalent to "git diff $(git merge-base A B) B". You can omit any one of \<commit>, which has the same effect as using HEAD instead.

Je vais ajouter `HEAD`.

2023-07-05 14:11 UTC, guillett commented on tools/check-links-validity.ts
> +function filterBenefitDataToProcess(
Par défaut on check tout sauf dans les PR et dans les test. Du coup, j'ai l'impression que ta proposition ne fonctionne pas.

2023-07-05 14:17 UTC, baptou12 commented on tools/check-links-validity.ts
> +function filterBenefitDataToProcess(
yes rien ne nous empêche de ne pas utiliser la fonction le second argument est vide (mais sortir cette logique au dessus)

2023-07-05 14:39 UTC, guillett commented on tools/check-links-validity.ts
> +function filterBenefitDataToProcess(
C'est un ET (et pas un OU) à partir de listes définies, je vois pas trop comment tu vois le truc.

2023-07-05 14:42 UTC, guillett commented
Preneur d'une nouvelle revue complète et d'une contribution sur la partie filtre si tu as le temps pour mieux comprendre ta proposition.

2023-07-05 15:31 UTC, baptou12 commented on tools/check-links-validity.ts
> +function filterBenefitDataToProcess(
Yes, si on veut que le cas très spécifique de `--only` en PR fonctionne faut remplacer l'union par une intersection. Donc je dirais si on simplifie la méthode comme je proposais 
un truc du genre : 

```
function filterBenefitDataToProcess(
  benefitData,
  benefitLimitationIds
) {
  return benefitData.filter((benefit) => {
    if (!benefitLimitationIds) {
      return true
    }

    return benefitLimitationIds.includes(benefit.id)
  })
}
```

et on gère la création de `benefitLimitationIds` comme étant l'intersection des limitation via pullRequest et only (*) dans la fonction main (possiblement via une autre méthode). 


(*) après je comprend pas trop le cas où on a les deux, un truc du genre 
```
if (only) {
   // on filtre sur only
} else if (Pull Request) {
  // on filtre sur les change
} 
```
me semble acceptable même si on perd un cas d'usage théorique. 

(d'ailleurs en fonction de l'urgence de la PR on peut voir les partie "simplicité de lecture" dans un second temps)

2023-07-05 16:00 UTC, baptou12 commented on .github/workflows/ci.yml
> +    name: Test benefit link improvements
De ce que j'ai compris le process lancé dans le cadre d'une pull request ne met à jour que la colonne PR du Grist si elle n'est pas déjà remplie. On pourrait trouver un nom qui reflète ce cas spécial ?

2023-07-05 16:02 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +    if (!item.ok) {
Pas obligé mais on peut changer pour commencer par 
```
if (item.ok) {
  return
}
``` 

Ça a l'avantage de montrer le cas simple tout de suite et d'éviter l'indentation en dessous

2023-07-05 16:02 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +      const warning = existingWarnings?.[checkResult.id]?.[item.type]
Je propose de remplacer `warning` par `existingWarning`

2023-07-05 16:06 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +      if (warning) {
On a deux branche de la condition qui finissent par la même execution `recordsToAdd.push(record)` et ça semble sémantiquement pour la même raison.
On pourrait faire quelque chose comme ça pour l'explicité : 
```
if (warning && warning.fields.Erreur === item.status) {
  existingWarning.keep = true
} else. {
  recordsToAdd.push(record)
}
```

2023-07-05 16:11 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +          warning.keep = true
Même si il est signaler dans le nom de la méthode cet effet de bord rend difficile là lecture je trouve. Après je pense que ça va être difficile de l'enlever sans gros changement et j'ai pas de solution en tête. Mais je veux bien savoir ce que tu en pense ?

2023-07-05 16:15 UTC, baptou12 commented on tools/check-links-validity.ts
>  async function checkURL(benefit) {
Je trouve que le nom de cette méthode ne reflète pas vraiment ce qu'elle fait. Je propose un truc du genre `checkBenefitUrls`  t'en pense quoi ?

2023-07-05 16:19 UTC, baptou12 commented on tools/check-links-validity.ts
> +  type recordsByOperationTypesType = { [operationType: string]: GristUpdate[] }
Ces lignes ne sont pas utilisées tout de suite, je propose de les descendre un peu après le calcul de `additionsByBenefit`

2023-07-10 09:45 UTC, guillett commented on tools/check-links-validity.ts
> +function filterBenefitDataToProcess(
Pour le dev et le debug, j'ai utilisé les différentes variantes, en particulier filter PR **et** via `--only`.

2023-07-17 08:05 UTC, guillett commented on .github/workflows/ci.yml
> +    name: Test benefit link improvements
Ouais alors c'était un choix un peu au hasard. En vrai on pourrait remettre à jour la PR dans le Grist. :shrug:

2023-07-17 08:16 UTC, guillett commented on lib/benefits/link-validity.ts
> +          warning.keep = true
C'est effectivement un peu compliqué. Après il s'agit de faire un calcul d'intersection entre deux ensembles. Aujourd'hui c'est délégué à la fonction appelante mais on peut le faire dans cette fonction en retournant un objet de la forme`{ add: [], keep: [], clear: []}`.

2023-07-17 08:23 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +          warning.keep = true
Ouais ça me semble être une bonne piste pour supprimer l'effet de bord (et expliciter. par la même occasion)

2023-07-17 13:01 UTC, guillett commented on .github/workflows/ci.yml
> +    name: Test benefit link improvements
J'ai changé, la PR est est à chaque fois mise à jour si besoin.

2023-07-17 13:05 UTC, guillett commented on lib/benefits/link-validity.ts
> +          warning.keep = true
Bon, j'ai fait un refactor avec pas mal de modifications, désolé.

2023-07-17 13:06 UTC, guillett commented on lib/benefits/link-validity.ts
> +          warning.keep = true
Merci beaucoup pour la suggestion, je crois que c'est (bien?) plus lisible.

2023-07-17 17:38 UTC, baptou12 requested changes

2023-07-17 17:38 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +function buildPRProcessor(pullRequestURL) {
J'ai l'impression qu'on gagne pas grand chose à abrévier PR d'autant qu'on peut pas le faire tout le temps (cf pullRequestUrl). ça te va d'uniformiser ?

2023-07-17 17:38 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +  checkResult: benefitData,
`checkResult` ne me semble pas très bien nommé, c'est un benefit finalement non ?

2023-07-17 17:38 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +  const result = { add, keep, update }
Finalement, j'aurais peut être mi `toAdd`, .. t'en pense quoi ? (mineur)

2023-07-17 17:38 UTC, baptou12 commented on tools/check-links-validity.ts
> +  const operationLists = results.map((linkCheckResult) =>
on pourrait renommer `benefitOperationsList` et ensuite plus bas dans le `forEach` avoir comme variable `benefitOperations`

2023-07-17 17:38 UTC, baptou12 commented on tools/check-links-validity.ts
> +    update: [],
Si tu fait la modification de `toAdd`, .. on peut la faire ici aussi

2023-07-17 17:38 UTC, baptou12 commented on lib/benefits/link-validity.ts
> +      keep.push(existingWarning)
J'ai l'impression qu'on a plus besoin de la gestion du `keep` maintenant que les update "Corrige" et "PR" sont faite ici, c'est bien le cas ?

2023-07-18 07:29 UTC, guillett commented on lib/benefits/link-validity.ts
> +      keep.push(existingWarning)
Oui carrément.

2023-07-19 14:56 UTC, baptou12 approved these changes
LGTM dernière question sur le fetch de la sheet courante, testé (approximativement (1) en local aussi) 

(1) sans connexion à Grist, mais je pense que tu l'as fait tourné pas mal de fois déjà :-)

2023-07-21 09:29 UTC, guillett commented on tools/check-links-validity.ts
> +    Aide: benefitIdsFromCLI,
Non `benefitsToAnalyze` arrive après, on peut récupérer toutes les lignes non corrigées dans Grist c'est toujours un échantillon de taille assez réduite.

2023-07-21 09:37 UTC, merged