Formulaire d'envoi de récap par SMS (partie 2 - backend)
betagouv/aides-jeunes pull request #3807
Opened 2023-06-30 17:13 UTC by Shamzic

2023-07-04 15:10 UTC, Shamzic commented on backend/models/followup.ts
> +import fetch from "node-fetch"
Ah, je n'avais pas pensé à utiliser axios sur le backend! 
J'ai essayé d'utiliser fetch nativement, sans succès, je reste sur axios qui fonctionne bien pour l'instant, et on pourra faire éventuellement une migration vers fetch natif plus tard dans une autre tâche si c'est pertinent 👍

2023-07-06 07:42 UTC, Shamzic commented on backend/controllers/followups.ts
> +    }
Effectivement, il faut que je repasse sur cette PR également ! Je remets ça en draft

2023-07-11 10:37 UTC, Shamzic commented on backend/models/followup.ts
> +  phone: string | any
J'imagine que c'était présent historiquement pour esquiver des warnings de ts au moment de dev

2023-07-11 12:29 UTC, Shamzic commented on backend/models/followup.ts
> +  const password = process.env.SMS_SERVICE_PASSWORD
Je saisi pas bien ce que tu proposes car c'est déjà des variables d'environnement ici ?
Qu'entends-tu par "on peut directement ne pas faire la query" ?

2023-07-11 12:40 UTC, Shamzic commented on backend/models/followup.ts
> +  const password = process.env.SMS_SERVICE_PASSWORD
Ah je crois que j'ai compris, tu veux que je les renseigne dans le fichier [backend/config/index.ts](https://github.com/betagouv/aides-jeunes/blob/efa423a49136084858f5b04882fde2300e969169/backend/config/index.ts) 👍

2023-07-12 09:14 UTC, baptou12 commented on backend/models/followup.ts
> +  const password = process.env.SMS_SERVICE_PASSWORD
@Shamzic Même avec des `.env` (qu'on devrait mettre en place :-) ) la [backend/config/index.ts](https://github.com/betagouv/aides-jeunes/blob/efa423a49136084858f5b04882fde2300e969169/backend/config/index.ts) à l'avantage de répertorier dans la code base les dimension de config voulu par l'application et de pouvoir définir à un endroit précis les fallback

2023-07-12 12:41 UTC, Shamzic commented on backend/models/followup.ts
> +  const password = process.env.SMS_SERVICE_PASSWORD
Je ne comprends pas bien cette partie : " les dimension de config voulu par l'application et de pouvoir définir à un endroit précis les fallback" est-ce que tu pourrais expliciter avec un exemple s'il te plaît ?

2023-08-25 16:22 UTC, Shamzic commented on backend/controllers/followups.ts
> +    )) as unknown as IFollowup
Ce point là m'embête un peu, je continue d'investiguer pour trouver mieux

2023-08-28 09:04 UTC, Shamzic commented on backend/controllers/followups.ts
> +    )) as unknown as IFollowup
Après investigation, ce problème est déjà présent sur la branche master, ce que je propose corrige le problème donc je vais laisser tel quel avec le `as unknow as IFollowup` mais je suis preneur de vos retours si vous avez une solution plus propre

2023-08-28 13:27 UTC, baptou12 requested changes

2023-08-28 13:27 UTC, baptou12 commented on backend/controllers/followups.ts
> +    )) as unknown as IFollowup
J'ai regardé un peu, pour le moment pas de piste si ce n'est qu'on s'y perd entre : 
- IFollowupModel
- FollowupInterface
- IFollowup
Je trouve, à creuser

2023-08-28 13:27 UTC, baptou12 commented on backend/lib/followup-factory.ts
>      email: string,
L'email devient optionnel aussi non ?

2023-08-28 13:27 UTC, baptou12 commented on backend/models/followup.ts
> +  this.messageId = messageId
On a pas de mécanisme pour garder une trace du SMS et de l'email non ? Là on va override, a voir si on a besoin d'un tel mecanisme, mais dans le doute si pas besoin je stockerais pas le messageId du SMS

2023-08-28 13:27 UTC, baptou12 commented on backend/models/followup.ts
> +  this.error = undefined
Idem ici

2023-08-28 13:27 UTC, baptou12 commented on backend/models/followup.ts
> +          : Promise.resolve({ messageId: "fake-message-id" })
Ça m'embête d'en passer par là, je réfléchi à une autre proposition, mais tu as les motivation de faker un messageId ? (y'a probablement des contraintes que j'ai pas en tête)

2023-08-28 21:31 UTC, Shamzic commented on backend/models/followup.ts
> +          : Promise.resolve({ messageId: "fake-message-id" })
J'ai du faire des tests avec des cas où sendMail était nul et vouloir tester quand même l'envoi d'un email mais effectivement, comme c'est vieux je dois sûrement pouvoir le refacto

2023-08-30 10:22 UTC, Shamzic commented on backend/controllers/followups.ts
> +  if (!(req.body.email?.length || req.body.phone?.length)) {
Si vous êtes deux à préférer cela, je modifie (:

2023-08-30 12:04 UTC, baptou12 commented on backend/controllers/followups.ts
> +    return res.status(400).send({ result: "Missing Email and Phone" })
```suggestion
    return res.status(400).send({ result: "Missing Email or Phone" })
```

2023-08-31 09:43 UTC, Shamzic commented on backend/models/followup.ts
> +  this.messageId = messageId
Refacto proposé en ajoutant des champs spécifiques aux données des sms

2023-08-31 12:28 UTC, baptou12 commented on backend/controllers/followups.ts
> +    )) as unknown as IFollowup
Du coup tu vas avoir un conflit au moment de rebase master (là ça se voit pas je pense car branches imbriquées)

2023-08-31 12:33 UTC, baptou12 commented on backend/controllers/followups.ts
> +    return res.status(400).send({ result: error })
ah, ici pour le coup j'enverrais pas l'erreur directement, parfois ça peut donner des infos qu'on souhaite pas rendre publique. Après dans un contexte Open Source je sais pas trop. 

Mais imaginons que pour une raison ou pour une autre par exemple l'erreur renvoi le call http complet d'envoi de SMS => ça donnerais la clé d'authentification et permettrait à qq1 de random d'envoyer des sms avec le compte AidesJeunes. 

Donc je mettrais un message générique à la place. 

Par ailleurs **même si pas lié à la PR** c'est une erreur 500 ici jusqu'à preuve du contraire :-)

2023-08-31 12:45 UTC, baptou12 requested changes
Principalement l'envoi de l'erreur vers le front.

2023-08-31 14:06 UTC, baptou12 submitted a review, later dismissed
Ok avec les changements, Là du coup tu va merger celle-ci dans la PR de frontend c'est ça ? Dans l'idéale ça aurait été mieux l'inverse non ? Mais pas bloquant on devrait s'en sortir :-)

2023-08-31 14:14 UTC, Shamzic commented
> Ok avec les changements, Là du coup tu va merger celle-ci dans la PR de frontend c'est ça ? Dans l'idéale ça aurait été mieux l'inverse non ? Mais pas bloquant on devrait s'en sortir :-)

Oui, c'est ça que j'avais prévu. Le front est déjà rebase très récemment dans celle-ci donc moi ça me parait pas mal de faire comme ça, mais j'imagine que merger un back avant le front c'est souvent mieux

2023-08-31 14:21 UTC, Shamzic commented
En fait je pourrais plutôt faire l'inverse comme tu le suggères, en mergant le front ici et en faisant pointer celle ci sur master. qu'en penses-tu ?

2023-08-31 15:09 UTC, Shamzic commented
L'initiative a été prise, j'ai mergé front et back ici et le rebase sur master est effectif, désolé pour la grosse PR finale (qui n'est que la fusion des deux précédentes avec en plus un léger rebase des récentes modif en typescript)

Lors du merge de cette PR sur master, ce ne sera de toutes manières pas effectif en production car nous n'avons pas encore de service SMS officiellement utilisable.

(@baptou12 Normalement, tu as pratiquement review la totalité du code ici. Merci pour tes retours !)

2023-09-04 09:21 UTC, baptou12 commented on vite.config.ts
> +    VITE_SHOW_SMS_TAB: process.env.SHOW_SMS_TAB || undefined,
Pour la partie `process.env.SHOW_SMS_TAB` ça serait mieux de prendre une valeur dans la config non ? On rajoute pas trop de variable d'env lors du démarrage du server (nécéssite une PR sur aides-jeunes-ops)

2023-09-04 09:32 UTC, baptou12 commented on src/components/recap-email-and-sms-form.vue
> +          <span class="fr-hint-text">Format attendu : 06 12 23 42 78</span>
Dans le format que tu propose y'a des espaces, en revanche le followup n'accepte pas d'espace : 
```
ERROR  error Followup validation failed: phone: 06 12 23 42 78 n'est pas un numéro de téléphone valide
```

2023-09-04 09:36 UTC, baptou12 commented on src/components/recap-email-and-sms-form.vue
> +          J'accepte d'être recontacté.e
```suggestion
          J'accepte d'être recontacté ou recontactée 
```

2023-09-04 14:13 UTC, Shamzic commented on vite.config.ts
> +    VITE_SHOW_SMS_TAB: process.env.SHOW_SMS_TAB || undefined,
Ah oui pardon j'ai lu de travers, ok pour une variable en config, bien-sûr !

2023-09-05 08:27 UTC, baptou12 commented on backend/config/continuous-integration.ts
> +    show: true,
Ça continue de fonctionner chez toi ? car je crois que si tu remet pas les `username`, `password` et `url`, ce smsService va erase celui de la config dans index

2023-09-05 09:38 UTC, Shamzic commented on backend/config/continuous-integration.ts
> +    show: true,
J'aimerais bien pouvoir te répondre mais je peux pas tester car le service est down depuis quelques jours :(

2023-09-05 09:42 UTC, Shamzic commented on backend/config/continuous-integration.ts
> +    show: true,
En run `dev` j'ai pas de soucis, c'est en run `ci` que je bloque

2023-09-05 11:18 UTC, Shamzic commented on backend/config/continuous-integration.ts
> +    show: true,
Après investigations, j'ai l'impression que les fichiers de configuration ne sont pas bien pris en compte ou overridés sans qu'on le veuille au moment de run `npm run ci`

2023-09-05 13:02 UTC, baptou12 commented on backend/config/continuous-integration.ts
> +    show: true,
Le `show: true` est bien pris en compte mais tu doit avoir le password et tout qui n'est plus defini en dev non ? 


Pour la CI on prend production.js/ts mais attention juste avant il est bien override ici : https://github.com/betagouv/aides-jeunes/blob/420263bfcb07a52dc0c8029b05577e1163a05e90/.github/workflows/ci.yml#L274

2023-09-05 14:20 UTC, Shamzic commented on backend/config/continuous-integration.ts
> +    show: true,
Le password et le username je les envoi en variable d'environnement dans le `npm run serve` et j'y ai bien accès en dev de même que le show:true

Pour la CI en test j'effectue bien le cp juste avant, mais ça prend quand même pas en compte le production.js copié, j'arrive pas à comprendre comment ça peut marcher en production aujourd'hui 🤔

2023-09-06 07:58 UTC, baptou12 commented on cypress/utils/results.js
> +        phone: "06000000",
```suggestion
        phone: "0600000000",
```

2023-09-06 08:08 UTC, baptou12 commented on src/components/recap-email-and-sms-form.vue
> +    phone: phone?.replace(/\s/g, ""),
Pour améliorer la lisibilité et surtout permettre des amélioration future on peut sortir de formatting dans une méthode : 
```
function formatPhoneNumber(phone) {
  return phone?.replace(/\s/g, "")
}
```

2023-09-06 08:09 UTC, baptou12 reviewed
Des mini remarque mais on est quasi good selon moi

2023-09-06 08:43 UTC, Shamzic commented on src/components/recap-email-and-sms-form.vue
> +    phone: phone?.replace(/\s/g, ""),
Oui, je l'avais fait au début et puis j'me suis dit qu'avec un seul appel ça valait pas vraiment la peine. Ok je le remet

2023-09-06 08:57 UTC, baptou12 approved these changes
LGTM

2023-09-06 09:46 UTC, merged