Ajoute le champ conditions_benevoles dans les détails d'une aide
betagouv/aides-jeunes pull request #3823
Opened 2023-07-05 16:17 UTC by Shamzic

2023-07-10 08:18 UTC, guillett commented
Dans une première itération, je trouverais bien de continuer à cacher la complexité en gardant le front actuel. Plus précisément, je ne ferais pas de traitement distinct pour ces conditions là et je les réintégrerais dans la liste « Pour en bénéficier vous devez également ».

J'ai l'impression qu'il y a 3 axes sur cette tâche
- modification de la modélisation dans les fichiers YAML
- modification du code
- modification visuelle du front (plus ou moins importante)


Un traitement distinct des conditions liées au bénévolat est pour moi une façon de rendre visible de la complexité là où, sur notre fil d'équilibriste avec le simulateur, on doit toujours jauger quelle complexité on afficher et laquelle on cache.

2023-07-13 16:02 UTC, baptou12 requested changes
Je n'ai pas pu tester vraiment car j'ai l'impression que depuis ce commit https://github.com/betagouv/aides-jeunes/commit/b3933cc366035892b7da502cee91e05ea05b1eb3 : le mode debug ne fonctionne plus. J'ai créé un ticket pour le fix : https://trello.com/c/spOgz55g/1386-fix-le-mode-debug-sur-la-page-de-resultats et je m'en charge

2023-07-18 12:53 UTC, Shamzic commented
> Je n'ai pas pu tester vraiment car j'ai l'impression que depuis ce commit [b3933cc](https://github.com/betagouv/aides-jeunes/commit/b3933cc366035892b7da502cee91e05ea05b1eb3) : le mode debug ne fonctionne plus. J'ai créé un ticket pour le fix : https://trello.com/c/spOgz55g/1386-fix-le-mode-debug-sur-la-page-de-resultats et je m'en charge

De quel mode debug tu parles ? Je n'ai pas de problème pour dev en local sur le simulateur et l'outil de contribution de mon côté

2023-07-18 12:58 UTC, baptou12 commented
> > Je n'ai pas pu tester vraiment car j'ai l'impression que depuis ce commit [b3933cc](https://github.com/betagouv/aides-jeunes/commit/b3933cc366035892b7da502cee91e05ea05b1eb3) : le mode debug ne fonctionne plus. J'ai créé un ticket pour le fix : https://trello.com/c/spOgz55g/1386-fix-le-mode-debug-sur-la-page-de-resultats et je m'en charge
> 
> De quel mode debug tu parles ? Je n'ai pas de problème pour dev en local sur le simulateur et l'outil de contribution de mon côté

Je parlais de cette page où on voit toutes les aides : `/simulation/resultats?debug` c'est corrigé depuis :-) : https://github.com/betagouv/aides-jeunes/pull/3845

2023-07-18 14:36 UTC, Shamzic commented on src/composables/use-voluntary-organisations.ts
> +    if (!cityInseeCode) {
C'est effectivement pertinent dans le cas où le lien vers l'aide est partagé directement sans simulation. J'ajoute le lien par défaut. :thumbsup:

2023-07-18 15:22 UTC, baptou12 commented on src/composables/use-voluntary-organisations.ts
> +    if (!cityInseeCode) {
Ça marche pas encore ces liens là, mais peut être un jour :-) @guillett t'en pense quoi ?

2023-07-18 15:44 UTC, baptou12 requested changes
J'ai pu testé : on voit bien les mentions de "voluntary_conditions" et le lien vers Jeveuxaider :

2023-07-18 15:44 UTC, baptou12 commented on backend/controllers/outils.ts
> +    const postCode = find(req.params.codePostal)
À d'autre endroit dans le code on met `postalCode`, je propose d'uniformiser (d'autant que en lisant ça ça m'a fait penser à un call http POST ^^). T'en pense quoi ? 

Par ailleurs on pourrait mettre directement la logique de `[0].code` ici.

2023-07-18 15:44 UTC, baptou12 commented on backend/controllers/outils.ts
> +  centerCoordinates: function (req, res) {
On pourrait mettre `centerCoordiatesFromPostalCode` pour être super explicite

2023-07-18 15:44 UTC, baptou12 commented on backend/routes/outils.ts
> +    .route("/outils/communes/:codePostal/centerCoordinates")
Ici j'ai l'impression que les communes sont plus un moyen qu'une finalité non ? tu pense quoi de mettre "/outils/codePostal/:codePostal/centerCoordinates".

2023-07-19 10:27 UTC, Shamzic commented on backend/controllers/outils.ts
> +  centerCoordinates: function (req, res) {
Ok pour moi

2023-07-19 10:43 UTC, Shamzic commented on contribuer/public/admin/config.yml
> +    widget: string
Non mais c'est bien comme ça, ça laisse des possibilités pour l'avenir 👼

2023-07-19 10:54 UTC, Shamzic commented on backend/routes/outils.ts
> +    .route("/outils/communes/:codePostal/centerCoordinates")
Oui on peut alléger la route éventuellement

2023-07-19 11:03 UTC, Shamzic commented on src/composables/use-voluntary-organisations.ts
> +    let cityInseeCode = store.situation.menage.depcom
Il ne sert à rien, c'est un reliquat que je n'ai pas refacto ! On peut se baser uniquement sur le code postal

2023-07-19 12:55 UTC, Shamzic commented on src/composables/use-voluntary-organisations.ts
> +      updating.value = false
D'accord pour le lien.

Pour moi il ne faut pas renvoyer d'erreur si il n'y a pas de code postal car c'est lié au fait qu'il n'y a pas de simulation effectuée et c'est un comportement normal

2023-07-19 14:30 UTC, baptou12 approved these changes
Cool ! LGTM

2023-07-19 14:46 UTC, merged