Ajoute une entrée des données historique dans les stats
betagouv/aides-jeunes pull request #3835
Opened 2023-07-11 14:02 UTC by Cugniere

## Détails

Basé sur la PR #3821 et nécessaire pour la [tâche 1367](https://trello.com/c/GaA3mGON/1367-ajouter-une-vue-avec-le-nombre-de-r%C3%A9ponse-au-sondage-par-mois)

## Notes

Cette PR permet d'exposer des stats historiques pour les données de sondages. Le document `dist/documents/stats.json` contient au niveau de la clef `survey` une nouvelle entrée `historical` : 
```json
"historical": {
  "2023-06": {
    "asked": 1,
    "failed": 1,
    "nothing": 1
  },
  "2023-04": {
    "nothing": 1,
    "asked": 1
  },
  "2023-03": {
    "asked": 3,
    "failed": 2,
    "nothing": 3
  },
  "2022-06": {
    "failed": 1
  }
}
```
À noter qu'il n'y a pas de limites d'ancienneté de la donnée exposée là où la tâche Trello cible les 4 derniers mois. Ce choix arbitraire est dû au fait que la donnée exposée n'a pas vocation à être utilisée uniquement par le site de stats mais pourrait être exploitée dans d'autres cas d'usages / par d'autres personnes.

---

Cette PR contient également une refacto partielle `backend/lib/stats/mongodb.ts` en utilisant notamment des `async/await` dans la fonction `getStats` pour gagner en lisibilité.

2023-07-12 09:02 UTC, baptou12 requested changes

2023-07-12 09:02 UTC, baptou12 commented on backend/lib/stats/mongodb.ts
> +          set.summary.total += row.value
On pourrait sortir total de summary : ça n'arrivera très probablement pas (1) mais si on a un `answer` qui s'appelle "total" un jour, je pense que ça ne va pas être super facile à debug, on évite ça en les mettant à différents niveaux.

(1) Très peu probable, mais frustration max le jour où ça arrive :-)

2023-07-12 13:37 UTC, baptou12 commented on backend/lib/stats/mongodb.ts
> +          set.summary.total += row.value
Ça correspond aussi à la sum dans l'historique, mais après je trouve ça mieux, mais sans être non plus 100% convaincu. 

Autre solution pour éviter la confusion "answer" / total c'est de raise explicitement si une answer a le nom "total". 
Pas de blocage si ça reste comme ça non plus.

2023-07-12 15:02 UTC, Shamzic approved these changes
Je valide `total` à la racine de `surveys`

2023-07-13 08:53 UTC, baptou12 approved these changes

2023-07-17 12:23 UTC, merged