Refactor la condition `taux incapactite` pour une gestion affinée
betagouv/aides-jeunes pull request #3875
Opened 2023-07-26 10:14 UTC by Allan-CodeWorks

# Description

La condition `taux incapactite` fonctionne maintenant comme la condition d'age.
On peut spécifier un opérateur et une valeur de son choix.

2023-07-26 10:15 UTC, Allan-CodeWorks reviewed
Preneur de tout les retours et spécialement sur la manière de tester ;)

2023-07-26 10:37 UTC, Shamzic requested changes

2023-07-26 10:37 UTC, Shamzic commented on tests/unit/compute-javascript-benefits.spec.ts
> +  })
Tout ceci me paraît simplifiable :

```suggestion
  const situation_handicap = {
    demandeur: {
      activite: "situation_handicap",
      taux_incapacite: 30,
    },
  }
  const benefit_situation_handicap = {
    profils: [
      {
        type: "situation_handicap",
        conditions: [
          {
            type: "taux_incapacite",
            value: 50,
            operator: ">=",
          },
        ],
      },
    ],
  }
```

2023-07-26 11:29 UTC, Shamzic commented
Y a un petit problème d'inchoérence avec la valeur du pourcentage du taux d'incapacité du simulateur qui est un nombre compris entre 0 et 1 par rapport à tes tests où ce sont des entiers entre 0 et 100

2023-07-26 12:39 UTC, Allan-CodeWorks commented on tests/unit/compute-javascript-benefits.spec.ts
> +  })
Les valeurs de `situation_handicap` et `benefit_situation_handicap` sont modifiées à chaque tests (à part le premier).
Exemple : 
```python
  it("Checks that someone with incapacite 50 is not eligible with > 50", function () {
    situation_handicap.demandeur.taux_incapacite = 50
    benefit_situation_handicap.profils[0].conditions[0].operator = ">"

    expect(
      testProfileEligibility(benefit_situation_handicap, {
        situation: situation_handicap,
      })
    ).toBe(false)
  })
```
On pourrait en faire des constantes mais ça ferait beaucoup de bruits dans les tests.
Dans l'exemple ci-dessus, on met en valeur les propriétés testées.
Le `afterEach` me semble important pour éviter toute corrélation des tests.

2023-07-26 12:54 UTC, Allan-CodeWorks commented
> Y a un petit problème d'incohérence avec la valeur du pourcentage du taux d'incapacité du simulateur qui est un nombre compris entre 0 et 1 par rapport à tes tests où ce sont des entiers entre 0 et 100.
> 
> Il y a également un petit problème de formatage que tu peux résoudre en lançant `npm run format`
> 
> J'aurais également ajouté un test pour vérifier que la value de taux_incapacité soit non nulle et comprise entre 0 et 100 strictement inclus (ou entre 0 et 1 avec les valeurs réelles), qu'en penses-tu ?
> 
> Mis à part ça et ma suggestion au dessus, tes tests me paraissent cohérents +1

Effectivement, je n'ai pas fait attention à cette différence.
Je n'arrive pas à voir où est la source de ce comportement dans le code.
Je vais modifier et continuer à faire comme avant mais ça me pose tout de même question. Quel est l'intérêt de travail avec des nombres entre 0 et 1 ? Faut-il créer un ticket pour faire ce refacto également ? 

Pour le test, je ne comprends pas bien ce que tu veux tester et comment. Les valeurs de `taux_incapacite` viendront des fichiers `YAML` qui seront ajoutés et modifiés via PR. J'ai l'impression qu'on a des vérifications sur la syntax des fichiers `yaml`avec le fichier `tests/integration/schema-validation-benefits-javascript.spec.ts` mais ça ne vérifie pas les valeurs ?

2023-07-26 15:06 UTC, Shamzic commented on tests/unit/compute-javascript-benefits.spec.ts
> +  })
Ma suggestion supprime du code en double, du coup j'ai du mal à comprendre pourquoi tu penses que ça ferait du bruit ? 🤔

Ce qu'on peut faire si tu veux absolument réinitialiser tes variables à chaque test, c'est de mettre les déclarations uniquement dans le `beforeEach` plutôt que dans le `afterEach` car ça n'a pas trop de sens d'initialiser une variable après un test

2023-07-27 08:11 UTC, Shamzic commented
> Effectivement, je n'ai pas fait attention à cette différence. Je n'arrive pas à voir où est la source de ce comportement dans le code. Je vais modifier et continuer à faire comme avant mais ça me pose tout de même question. Quel est l'intérêt de travail avec des nombres entre 0 et 1 ? Faut-il créer un ticket pour faire ce refacto également ?

C'est les valeurs attendues par Openfisca je suppose. Je pense qu'on peut le faire dans cette PR également car c'est directement lié à tes modifications

> Pour le test, je ne comprends pas bien ce que tu veux tester et comment. Les valeurs de `taux_incapacite` viendront des fichiers `YAML` qui seront ajoutés et modifiés via PR. J'ai l'impression qu'on a des vérifications sur la syntax des fichiers `yaml`avec le fichier `tests/integration/schema-validation-benefits-javascript.spec.ts` mais ça ne vérifie pas les valeurs ?

Effectivement, cette suggestion n'est peut-être pas pertinente, il serait probablement préférable d'ajouter, par exemple, une condition dans l'outil de contribution pour mettre un warning à l'utilisateur qu'un nombre supérieur à 100 n'est pas accepté pour ce taux d'incapacité, mais je ne sais pas si c'est possible

2023-07-27 13:10 UTC, Allan-CodeWorks commented on tests/unit/compute-javascript-benefits.spec.ts
> +  })
Pardon, je me suis un peu embrouillé.

J'ai supprimé le afterEach car il n'est effectivement pas utile.

Pour ce qui de l'affectation multiple des variables `situation_handicap` et `benefit_situation_handicap`, ce que je veux dire c'est qu'elles sont éditées dans les tests.
Si on les déclare comme constante une fois pour tous les tests, on ne pourra plus modifier les valeurs qui nous intéressent lors de chaque test.

Si l'on veut des constantes, il faudra donc redéclarer et initialiser les variables pour chaque test et c'est ça qui créerait du bruit.
Ce serait la méthode la plus sûre pour éviter les effets de bords mais en réaffectant ces deux variables avec les même valeurs, il me semble qu'on limtie l'effet de bord et on simplifie la lecture en évitant de dupliquer du code

2023-07-27 14:33 UTC, Allan-CodeWorks commented on contribuer/public/admin/config.yml
> +    <<: *field_number
Ha oui bonne idée!
Qu'est-ce que tu penses de `hint: Le taux est exprimé par un nombre entre 0 et 1. Exemple 0.8 pour 80%.`
(code déjà appliqué)

2023-07-27 14:39 UTC, Allan-CodeWorks commented
Voici le nouveau champs : 
```yaml
field_taux_incapacite: &field_taux_incapacite
    label: Taux d'incapacité
    name: taux_incapacite
    fields:
      - *field_numeric_operator
      - <<: *field_numeric_value
        label: Taux
        value_type: float
        min: 0
        max: 1
        hint: Le taux est exprimé par un nombre entre 0 et 1. Exemple 0.8 pour 80%.
```

Ça semble faire ce qu'on souhaite.

2023-07-28 13:21 UTC, Shamzic approved these changes
Pour moi c'est ok pour ta PR. Ca me paraît iso avec l'état actuel du simulateur et renvoie toujours les bons nombres décimaux requis pour Openfisca. 👍 

A noter qu'on pourra refacto l'UI dans une autre PR pour afficher un input number à la place des trois choix de paliers (dont les valeurs sont 0.3, 0.65 et 0.9) si c'est nécessaire pour une aide future ayant des conditions de taux d'incapacité plus précises

2023-07-31 08:50 UTC, merged