Ajoute l'aide territoriale aux étudiants de la CT de Martinique
betagouv/aides-jeunes pull request #3876
Opened 2023-07-26 10:41 UTC by yasmine-glitch

2023-07-26 12:14 UTC, Shamzic requested changes

2023-07-26 12:14 UTC, Shamzic commented on data/benefits/javascript/martinique-aide-territoriale-etudiants.yml
> +  - Etre inscrit dans une formation ne bénéficiant pas d'aides de la Collectivité.
Je crois pas que la négation de cette affirmation soit exacte ici d'après les instructions `ne pas être inscrits dans des formations bénéficiant d’aides de la collectivité `,  qu'en penses-tu ?

2023-07-26 12:14 UTC, Shamzic commented on data/benefits/javascript/martinique-aide-territoriale-etudiants.yml
> +  - Etre inscrit dans une formation ne bénéficiant pas d'aides de la Collectivité.
```suggestion
  - Être domicilié fiscalement en Martinique (soi-même ou ses parents).
  - Être inscrit dans une formation ne bénéficiant pas d'aides de la Collectivité.
```

2023-07-26 16:21 UTC, yasmine-glitch commented on data/benefits/javascript/martinique-aide-territoriale-etudiants.yml
> +  - Etre inscrit dans une formation ne bénéficiant pas d'aides de la Collectivité.
Pour moi "Ne pas être inscrits dans des formations bénéficiant d’aides de la collectivité" veut dire la même chose que "Etre inscrit dans une formation ne bénéficiant pas d'aides de la Collectivité."
J'ai choisi la formulation positive de la phrase car il me semble qu'il s'agit d'une règle qu'on suit pour la rédaction des conditions, toujours commencer la phrase par un verbe à l'infinitif.

2023-07-27 08:02 UTC, Shamzic approved these changes

2023-07-27 08:08 UTC, merged