Activer des options de linting de conventions de noms Typescript
betagouv/aides-jeunes pull request #3939
Opened 2023-09-01 13:13 UTC by Cugniere

2023-09-01 14:46 UTC, baptou12 commented on backend/lib/openfisca/mapping/individu/index.ts
> +const individuSchema: IndividuGenerator = {
En réalité c'est plus `Individu` qu'un générator ? Enfin sinon je suis pas sûr de comprendre les utilisation de générator dans la codebase

2023-09-01 14:50 UTC, baptou12 commented on lib/types/individu.d.ts
> +export interface IndividuProperties {
Pourquoi ne pas avoir mis simplement `Individu` ici, enfin sinon on peut mettre le suffix properties à pas mal d'endroit non ?

2023-09-01 14:52 UTC, baptou12 commented on data/benefits/aides-velo-generator.ts
>  import { InstitutionLayout } from "../../data/types/institutions.d.js"
Ici on pourrait changer `InstitutionLayout` aussi (au cas où)

2023-09-01 14:55 UTC, baptou12 commented on lib/dates.ts
> +import { TypicalDates, TypicalDate } from "./types/dates.js"
Pas lié à la PR, mais le "Typical" m'intrigue

2023-09-01 14:56 UTC, Shamzic commented on src/stores/index.ts
> +    situation(): Situation | any {
Du coup si c'est forcément un objet vide on peut éventuellement le préciser comme ça `situation(): Situation | {} {`

2023-09-01 15:13 UTC, Shamzic commented on lib/dates.ts
> +import { TypicalDates, TypicalDate } from "./types/dates.js"
C'est des dates "typiques" du type "il y a 3 mois", "il y a 1 an" de ce que je comprends dans l'interface ^^

2023-09-01 15:14 UTC, baptou12 commented on lib/types/individu.d.ts
> +export interface IndividuProperties {
Selon moi, et comme pour situation, c'est plus à l'autre de changer, en `IndividuMethods` ou qqch comme ça

2023-09-03 20:52 UTC, Shamzic reviewed
Quelques suggestions!

Il ya `ConfigurationLayout` et `MongooseLayout` à refacto dans backend/types (mais peut être prévu dans une seconde refacto ?)

CommuneInterface à refacto dans /lib/types/commune.d.ts

2023-09-03 20:52 UTC, Shamzic commented on src/stores/index.ts
> +    situation() {
Import de /lib/types/situations.d.ts
```suggestion
     situation(): Situation | Record<string, never> {
```

2023-09-04 12:51 UTC, Shamzic approved these changes
Ok pour moi

2023-09-04 13:09 UTC, baptou12 reviewed
(à peu près à 50% des fichiers), mais je poste les deux premiers comments pour que tu puisse regarder)

2023-09-04 13:17 UTC, baptou12 commented on lib/properties/others/complexe-properties.ts
> +import { Step } from "../../types/steps.d.js"
Techniquement on doit pouvoir mettre la version Strict, comme ça remplace celle venant de Property

2023-09-04 13:20 UTC, baptou12 commented on lib/properties/property.ts
> +import { Step } from "../types/steps.js"
Same ça serait pas plutôt `StepStrict` ?

2023-09-04 13:24 UTC, baptou12 requested changes
Seulement la question sur l'utilisation de `Step` / `StepStrict`

2023-09-04 14:44 UTC, baptou12 commented on lib/properties/others/complexe-properties.ts
> +import { Step } from "../../types/steps.d.js"
Selon moi pas la peine pour le moment, à terme ça serait bien d'avoir juste `Step` yes

2023-09-04 15:04 UTC, baptou12 approved these changes

2023-09-04 15:10 UTC, merged