Évite les trops nombreux chiffres après la virgule sur l'avancement lu aux lecteurs d'écran
betagouv/aides-jeunes pull request #3940
Opened 2023-09-04 09:26 UTC by guillett

Pour le moment on à 8.3333333333333% et avec cette PR on a 8.33%.

2023-09-04 09:43 UTC, baptou12 commented on src/composables/progress.ts
> +      return (previousStep.length / activeSteps.length).toFixed(4)
Je pense que dans ce composable c'est bien de garder une valeur numérique plutôt que d'avoir une string en retour. C'est plus un responsabilité d'affichage que de controller le nombre de décimale, t'en pense quoi ? 

(donc probablement [ici](https://github.com/betagouv/aides-jeunes/blob/f9797e74938000c3c9272d9e0568345580614f39/src/components/progress-bar.vue#L34) ? )

2023-09-04 09:44 UTC, baptou12 requested changes
Mettre le `toFixed` à un autre endroit ?

2023-09-04 13:55 UTC, guillett commented on src/composables/progress.ts
> +      return (previousStep.length / activeSteps.length).toFixed(4)
Ouais, c'est vrai que j'ai été un peu vite. J'ai hésité car le bazar provient du choix fait dans ce composable de faire la division indice de l'étape courante / nombre total d'étapes. J'ai pensé que le texte pourrait faire référence aux infos sous-jacentes par exemple étape 3 sur 42. Mais bon c'est un refacto. J'ai fait un dev à minima.

2023-09-04 14:25 UTC, baptou12 approved these changes
Good, manque plus que la CI se rétablisse 😅

2023-09-05 13:00 UTC, baptou12 approved these changes

2023-09-05 13:52 UTC, merged