feat: enlève l'AB test sur les lieux en gardant la nouvelle version
betagouv/aides-jeunes pull request #3941
Opened 2023-09-04 15:27 UTC by baptou12

Ticket : https://trello.com/c/vYTI7wfh/1423-statuer-sur-les-r%C3%A9sultats-de-la-b-testing

2023-09-04 16:05 UTC, Shamzic requested changes
Il est possible de refacto `benefit-cta-light.vue` en `benefit-cta`, sinon RAS !

(Ok aussi pour tes résultats sur la tâche Trello, ce serait peut-être quand même bien de redire au prochain point oral que ce choix post ABtest est fait car je crois pas qu'on l'ait déjà évoqué)

2023-09-04 16:05 UTC, Shamzic commented on src/plugins/ab-testing-service.ts
> +  // /1 Copy / Fill / Uncomment this block
Y aurait-il moyen d'uniformiser la langue des commentaires ? 😄

2023-09-04 16:13 UTC, baptou12 commented on src/plugins/ab-testing-service.ts
> +  // /1 Copy / Fill / Uncomment this block
Ouais t'as raison je suis allé beaucoup trop vite sur ça :-)

2023-09-04 16:14 UTC, baptou12 commented
> (Ok aussi pour tes résultats sur la tâche Trello, ce serait peut-être quand même bien de redire au prochain point oral que ce choix post ABtest est fait car je crois pas qu'on l'ait déjà évoqué)

Yes, je comptais pas merger avant d'en avoir reparler a plusieurs

2023-09-05 09:36 UTC, Shamzic approved these changes

2023-09-05 13:36 UTC, merged