Crée aide au permis de conduire de la ville d'Anzin
betagouv/aides-jeunes pull request #3955
Opened 2023-09-06 14:04 UTC by yasmine-glitch

2023-09-07 14:24 UTC, baptou12 commented on data/benefits/javascript/ville_anzin_aide_au_permis_de_conduire.yml
> +  - type: age
Que ce soit pour l'age ou les profils c'est pas exactement ce que je comprend par rapport au lien en bas : 
- age ils parlent juste moins de 26 ans
- profile ils parlent du RSA ou du service Emploi mais pas explicitement des autres que tu indique

Je loupe qqch ?

2023-09-07 14:24 UTC, baptou12 requested changes
Cf conditions

2023-09-07 17:02 UTC, yasmine-glitch commented on data/benefits/javascript/ville_anzin_aide_au_permis_de_conduire.yml
> +  - type: age
Ce que je comprends moi c'est :
- pour les personnes qui ont moins de 26 ans, elles doivent être accompagnées par la Mission Locale ou le service Emploi de la mairie. Du coup a priori c'est des profils chômeur, inactif, en service civique. En tout cas ni à l'école, ni en études, ni au travail.
- pour les plus de 26 ans, elles doivent être bénéficiaires du rsa et accompagnées par le service Emploi de la mairie. Du coup c'est des profils bénéficiaires du rsa

=> j'enlève les profils "apprenti" et "en professionnalisation" que j'avais mis en me disant qu'il était possible que ce type de profil soit accompagné par une ML mais en fait je pense pas

2023-09-08 08:33 UTC, baptou12 commented on data/benefits/javascript/ville_anzin_aide_au_permis_de_conduire.yml
> +  - type: age
Oui tu as raison, j'avais bien loupé qqch :-)

2023-09-08 08:34 UTC, baptou12 approved these changes

2023-09-11 07:42 UTC, merged