Limite l'envoi de SMS aux numéros français
betagouv/aides-jeunes pull request #3964
Opened 2023-09-07 15:47 UTC by Shamzic

## Problème soulevé 

L'envoi de SMS ailleurs qu'en France ou sur des numéros surtaxés (commençant par 08 par exemple) peuvent engendrer des coûts élevés.

## Modification proposée

Ajout d'une double vérification via une expression régulière:
- Vérification dans l'interface sur le pattern de linput du sms dans la modale d'envoi du récapitulatif 
- Vérification dans le backend. 

Seuls les numéros commençant par 06, 07, 0033, 336, 337, +336 et +337 seront autorisés. 

Reformatage du numéro en 33XXXXXXXXX requis pour le service de SMS actuellement utilisé.

Le format suggestif du numéro de téléphone dans l'interface utilisateur pourrait être modifié en conséquence dans mais j'ai peur que cela surcharge pour pas grand chose => preneur de vos idées

2023-09-08 08:26 UTC, baptou12 commented on backend/controllers/followups.ts
> +        const phoneRegex = /^(((\+?|00)33\s?|0)[67])([\s.-]?\d{2}){4}$/
À ce niveau le numéro est déjà formaté non ? on doit pouvoir simplifier la regexp et remplacer `([\s.-]?\d{2}){4}` par `\d{8}` ça enleve la notion de tiret, point ou espace optionel entre des paires de chiffres.

Je me pose la question de mentionner quelque part que ce sont des numéro français, p.e. dans le nom de la fonction ?

2023-09-08 08:29 UTC, baptou12 commented on src/components/recap-email-and-sms-form.vue
> +          pattern="^(((\+?|00)33\s?|0)[67])([\s\.\-]?\d{2}){4}"
Pareil, je n'avais pas vu mais ici on accepte les numéros avec espaces, point ou tiret entre des paires de chiffres. ça serait pas mieux d'être encore plus strict ? t'en pense quoi ?

2023-09-08 08:52 UTC, baptou12 requested changes
En plus de ça au daily @guillett a parlé de numéros d'outre mer, je pense que ça va complexifier la fonction. A voir si elle devient complexe si on peut pas la mettre dans un fichier à part

2023-09-08 09:08 UTC, Shamzic commented on src/components/recap-email-and-sms-form.vue
> +          pattern="^(((\+?|00)33\s?|0)[67])([\s\.\-]?\d{2}){4}"
J'ai pensé qu'imposer le moins de contraintes possible en terme de tirets, points et espaces était le plus bénéfique pour les utilisateurs. Je ne suis pas opposé à ce que l'on fasse le choix d'être plus strict, à réfléchir!

2023-09-08 09:17 UTC, Shamzic commented on backend/controllers/followups.ts
> +        const phoneRegex = /^(((\+?|00)33\s?|0)[67])([\s.-]?\d{2}){4}$/
> À ce niveau le numéro est déjà formaté non ? on doit pouvoir simplifier la regexp et remplacer `([\s.-]?\d{2}){4}` par `\d{8}` ça enleve la notion de tiret, point ou espace optionel entre des paires de chiffres.


Oui il est formaté par le front et on peut effectivement simplifier si on fait le choix de restreindre le formatage en back.

> Je me pose la question de mentionner quelque part que ce sont des numéro français, p.e. dans le nom de la fonction ?

Yes, je vais faire ça 👍

2023-09-08 09:19 UTC, baptou12 commented on src/components/recap-email-and-sms-form.vue
> +          pattern="^(((\+?|00)33\s?|0)[67])([\s\.\-]?\d{2}){4}"
Je vois deux choses distinctes, d'une part ce qu'on permet à l'usager, d'autre part ce qu'on stock. 
De la même manière que tu enlève les espace en front on peut se dire que c'est le front qui reformate le numéro pour être acceptable par le back et le back lui est très strict sur ce qu'il accepte. 

Ça a le mérite d'avoir une donnée homogène* pour l'envoi ou les traitement futur.

*après on la garde pas ou peu donc no big deal, c'est plus une histoire de best practices

2023-09-08 09:23 UTC, baptou12 commented on src/components/recap-email-and-sms-form.vue
> +          pattern="^(((\+?|00)33\s?|0)[67])([\s\.\-]?\d{2}){4}"
Je me suis trompé de fichier, ici je suis d'ac sorry !

2023-09-08 09:33 UTC, Shamzic commented
Concernant l'outre mer, en espérant ne rien avoir oublié, j'ai établi une liste des 06 avec la version internationale (similaire pour la version en 07) : 

### France métropolitaine  :

Format national : 06 XX XX XX XX
Format international : +33 6 XX XX XX XX

### Guadeloupe :

Format national : 06 XX XX XX XX
Format international : +590 6 XX XX XX XX

#### Martinique :

Format national : 06 XX XX XX XX
Format international : +596 6 XX XX XX XX

### Réunion :

Format national : 06 XX XX XX XX
Format international : +262 6 XX XX XX XX

### Guyane :

Format national : 06 XX XX XX XX
Format international : +594 6 XX XX XX XX

### Mayotte :

Format national : 06 XX XX XX XX
Format international : +262 6 XX XX XX XX

### Saint-Pierre-et-Miquelon :

Format national : 06 XX XX XX XX
Format international : +508 6 XX XX XX XX

2023-09-08 13:53 UTC, baptou12 requested changes

2023-09-08 13:53 UTC, baptou12 commented on backend/controllers/followups.ts
> +          /^(((\+?|00)(33|262|508|590|594|596)\s?|0)[67])\d{8}$/
Selon moi c'est problématique d'avoir l'information des indicatifs redondante à 3 endroits. ça peut être sujet aux erreurs (on oubli un des trois endroit par exemple). 

Après c'est pas si simple dans le sens où parfois c'est dans une regexp... 

Dis moi si tu veux qu'on y réflechisse ensemble

2023-09-08 13:53 UTC, baptou12 commented on backend/controllers/followups.ts
> +        return res.status(403).send("Invalid phone number")
Ça me faisait bizarre `invalid`, j'aurais plutôt mis `unsupported`*, t'en pense quoi ?

2023-09-08 13:53 UTC, baptou12 commented on src/components/recap-email-and-sms-form.vue
>            id="phone"
On indique pas les numéro (indicatifs) qui peuvent être accepter, faudrait p.e. mettre une phrase d'explication ?

2023-09-08 13:53 UTC, baptou12 commented on backend/controllers/followups.ts
> +          /^(((\+?|00)(33|262|508|590|594|596)\s?|0)[67])\d{8}$/
par ailleurs y'a encore un `\s` qui je pense peut être enlevé

2023-09-11 09:45 UTC, Shamzic commented on backend/controllers/followups.ts
> +          /^(((\+?|00)(33|262|508|590|594|596)\s?|0)[67])\d{8}$/
La regex on pourrait éventuellement la mettre dans une variable globale (je ne sais pas où?)

2023-09-11 09:49 UTC, Shamzic commented on backend/controllers/followups.ts
> +        return res.status(403).send("Invalid phone number")
`Phone number format unsupported` pour trancher 👍

2023-09-11 09:58 UTC, Shamzic commented on src/components/recap-email-and-sms-form.vue
>            id="phone"
![image](https://github.com/betagouv/aides-jeunes/assets/18016058/d181ec76-abe6-4529-9e85-9ab1f478d43a)

2023-09-11 09:59 UTC, baptou12 commented on backend/controllers/followups.ts
> +          /^(((\+?|00)(33|262|508|590|594|596)\s?|0)[67])\d{8}$/
Même une regexp global ça aiderai pas pour cette partie là https://github.com/betagouv/aides-jeunes/pull/3964/files#diff-0c1d0609e27f55810982aecb0426a0f36fe9814e7244abd16c8114d9edf350ccR119 non ?

2023-09-11 10:12 UTC, baptou12 reviewed
Juste mon raisonnement sur `invalid`, `unsupported` car j'ai vu que tu avais changé à d'autres endroit, et (perso) je l'aurai pas fait :-) : 
- D'un coté on valid le format d'une string pour vérifier qu'on a bien un email ou un numéro de téléphone, et y'a une définition de ce format(*) : "on est un email ou pas" -> Ici "invalide" s'applique
- D'un autre coté on ajoute une couche "AidesJeunes" qui dit qu'on ne supporte pas certains numéro : On dit pas qu'un numéro Italien (au format E164) est invalide juste qu'on le supporte pas dans notre usage -> Ici plutôt "unsupported"

Du coup en front par exemple je trouve bizarre d'avoir Unsupported Email.

T'en pense quoi ? (pour qu'on aligne le vocabulaire pas que pour cette PR)

(*) en vrai c'est plus subtile pour les emails car certains server/provider mail ajoute des restriction en plus

2023-09-11 11:12 UTC, Shamzic commented
@baptou12 Ok, pour moi c'est `invalid` pour spécifier le format valide en front et `unsupported` en back pour spécifier les numéros supportés français métropolitains/outre-mer

2023-09-12 14:42 UTC, baptou12 commented on backend/controllers/followups.ts
> +          /^(((\+?|00)(33|262|508|590|594|596)\s?|0)[67])\d{8}$/
Je pensais à plusieurs solutions pour centraliser l'info : voici un commit avec un peu l'idée du truc : https://github.com/betagouv/aides-jeunes/commit/5a5a91810a9ecbc2cfa4d6ea57fea74f1d98e9fa

Note: ici on stock seulement les indicatifs, mais on pourrait stocker plusieurs regex (dans le cas où un numero a plus ou moins de 9 chiffre après le 0 sans indicatif par exemple)

2023-09-14 09:21 UTC, Shamzic commented on backend/controllers/followups.ts
> +          /^(((\+?|00)(33|262|508|590|594|596)\s?|0)[67])\d{8}$/
Yes c'est une bonne idée, je vais mettre ça en place

2023-09-14 15:48 UTC, baptou12 commented on backend/models/followup.ts
> +      const prefixes = ["0033", "00262", "00508", "00590", "00594", "00596"]
Du coup on peut utiliser la config ici aussi

2023-09-14 15:49 UTC, baptou12 commented on src/components/recap-email-and-sms-form.vue
> +          pattern="^(((\+?|00)(33|262|508|590|596|594)\s?|0)[67])([\s\.\-]?\d{2}){4}"
Idem (enfin faut passer par en variable vite comme [ici](https://github.com/betagouv/aides-jeunes/blob/6bb6d70b9d8ff7b6a45cd904919fd797acb092f9/vite.config.ts#L64)

2023-09-19 14:50 UTC, baptou12 requested changes

2023-09-19 14:50 UTC, baptou12 commented on backend/controllers/followups.ts
> +      const phoneNumberValidation = (phone) => {
On pourrait sortir sortir la méthode `phoneNumberValidation`

2023-09-19 14:50 UTC, baptou12 commented on backend/controllers/followups.ts
> +          `^(((\\+?|00)(${diallingCodes})|0)[1-9])(\\d{8})$`
je suis pas sûr à 100%, mais j'ai l'impression que tu as des `\` en trop. Par exemple `\\+?` je pense que tu veux dire qu'il y a un `+` optionnel, mais là ça fait un `\` optionnel (doublement avec le `?`

du coup ça serait ça a la place : `\+?` (pareil pour `\d` et dans l'autre regexp en front

2023-09-19 14:50 UTC, baptou12 commented on backend/models/followup.ts
> +    const formattedPhone = isInternational
Pareil je pense qu'on pourrait sortir une méthode "formatPhoneNumber" ou qqch comme ça. Par ailleurs les condition ternaire imbriqué c'est pas facile à lire, dans une autre méthode on aura "plus de place"

2023-09-19 14:50 UTC, baptou12 commented on src/components/recap-email-and-sms-form.vue
> +  return `^(((\\+?|00)(${diallingCodes})\\s?|0)[67])([\\s\\.\\-]?\\d{2}){4}`
cf `\`

2023-09-19 14:50 UTC, baptou12 commented on src/components/recap-email-and-sms-form.vue
> +          :pattern="inputPhonePattern"
On pourrai adapter le message d'erreur ligne 265 https://github.com/betagouv/aides-jeunes/pull/3964/files#diff-30b200d62b7bbc2798db0e23084a320c06abe4e80be4381008a77cc04cd94ad2R265

Par exemple : Numéro de téléphone non pris en charge, vérifiez sa validité.

(propal non bloquante, mais y'a des chance maintenant que ce soit pas la validité du numéro mais juste la non pris en charge pour nous)

2023-09-19 14:50 UTC, baptou12 commented on backend/controllers/followups.ts
> +        return res.status(403).send("Unsupported phone number format")
C'est plus une erreur 400 qu'une 403 je pense : 
403 c'est forbidden (globalement même authentifié le "client" n'a pas le droit d'accéder à la ressource)
400 c'est simplement une Bad Request (le "client" a fait quelque chose de mal dans sa requête : il ne doit pas essayer de recommencer ça ne marchera pas plus)

Pareil en dessous pour validation error.



Source : https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

2023-09-20 10:48 UTC, baptou12 commented on backend/controllers/followups.ts
> +        return res.status(403).send("Unsupported phone number format")
oui encore mieux 422 :-)

2023-09-20 13:14 UTC, Shamzic commented on backend/controllers/followups.ts
> +      const phoneNumberValidation = (phone) => {
Oui, après je trouve ça un peu étrange de placer ici une méthode de validation à la racine de ce controller. Je peux faire un fichier de validation éventuellement

2023-09-20 13:21 UTC, baptou12 commented on backend/controllers/followups.ts
> +      const phoneNumberValidation = (phone) => {
Ok avec ça

2023-09-20 13:45 UTC, baptou12 commented on lib/validation.ts
> +    `^(((\\+?|00)(${diallingCodes})|0)[1-9])(\\d{8})$`
Au cas où comme ça sera marqué en "Outdated", pb de double `\` je pense

2023-09-20 14:38 UTC, Shamzic commented on src/components/recap-email-and-sms-form.vue
> +          :pattern="inputPhonePattern"
J'ai essayé de mettre en place ce que tu suggères mais je suis pas convaincu de l'utilité : 
https://github.com/betagouv/aides-jeunes/pull/3964/commits/6318501e49f0d63ab0780bbf0e7f883a1bc16db5

2023-09-20 14:40 UTC, Shamzic commented on lib/validation.ts
> +    `^(((\\+?|00)(${diallingCodes})|0)[1-9])(\\d{8})$`
J'ai des erreurs typescript si je ne mets pas de double backslash, cela doit être nécessaire quand on utilise ` pour les chaînes de caractères

2023-09-20 14:50 UTC, Shamzic commented on backend/controllers/followups.ts
> +          `^(((\\+?|00)(${diallingCodes})|0)[1-9])(\\d{8})$`
Je confirme que dans les "template litterals" il faut double backslash pour ajouter un backslash, cf htttps://stackoverflow.com/a/31093356

2023-09-20 14:57 UTC, baptou12 commented on src/components/recap-email-and-sms-form.vue
> +          :pattern="inputPhonePattern"
Ah je pensais juste changé le message pas adapter en fonction de l'erreur, comme tu préfère

2023-09-20 14:59 UTC, baptou12 commented on backend/controllers/followups.ts
> +          `^(((\\+?|00)(${diallingCodes})|0)[1-9])(\\d{8})$`
Ah bien vu ! j'avais pas testé, my bad

2023-09-20 15:41 UTC, Shamzic commented on src/components/recap-email-and-sms-form.vue
> +          :pattern="inputPhonePattern"
ah. j'avais mal compris alors, je supprime ce commit

2023-09-20 16:36 UTC, baptou12 approved these changes
LGTM + une reco sur l'utilisation de la config

2023-09-20 16:36 UTC, baptou12 commented on backend/controllers/followups.ts
> +          config.smsService.internationalDiallingCodes
Pas bloquant mais possible d'utiliser `config.smsService.internationalDiallingCodes` directement dans `lib/phone-number.ts`

2023-09-20 16:36 UTC, baptou12 commented on backend/models/followup.ts
> +    const formattedPhone = phoneNumberFormatting(
Same

2023-09-21 09:08 UTC, Shamzic commented on backend/controllers/followups.ts
> +          config.smsService.internationalDiallingCodes
C'est ce que j'ai voulu faire initialement mais comme je l'importe aussi dans le front, importer la config backend dans le front posait problème pour le build donc je l'ai retiré

2023-09-21 09:08 UTC, Shamzic commented on backend/models/followup.ts
> +    const formattedPhone = phoneNumberFormatting(
Reply [here](https://github.com/betagouv/aides-jeunes/pull/3964#discussion_r1332734155)

2023-09-21 09:11 UTC, merged