Conversion aide permis nouvelle aquitaine en openfisca
betagouv/aides-jeunes pull request #3977
Opened 2023-09-13 12:47 UTC by Allan-CodeWorks

# Description

L'[aide permis de conduire de region Nouvelle Aquitaine](https://github.com/openfisca/openfisca-france-local/pull/181) ajouté sur `openfisca-france-local` necessites : 
- la conversion du fichier JS en openfiscs
- l'envoi de la variable `service_civique` à openfisca

2023-09-13 13:52 UTC, Shamzic requested changes

2023-09-13 13:52 UTC, Shamzic commented on openfisca/requirements.txt
> +Openfisca-France==151.3.0
C'est france-local qui passe en 6.3.0. Openfisca-france n'a pas de nouvelle modif pour cette PR, non ?

2023-09-13 13:52 UTC, Shamzic commented on backend/lib/openfisca/mapping/individu/index.ts
> +      return activite === Activite.ServiceCivique ? true : false
```suggestion
      return activite === Activite.ServiceCivique
```

2023-09-15 14:12 UTC, Allan-CodeWorks commented on openfisca/requirements.txt
> +Openfisca-France==151.3.0
Euh.. oui et non :D 
Le simulateur va faire appelle à la variable `nouvelle_aquitaine_aide_permis` (qui sera probablement ajouté dans la version `6.3.0` de `france-local` en effet.

Cependant, et même si je me suis apparemment planter quand j'ai fait ça car ce n'est pas le bon numéro de version, la variable `nouvelle_aquitaine_aide_permis` a nécessité l'ajout de la variable `service_civique`qui est arrivée dans la version `153.1.0` de `openfisca-france`.

Je m'en vais faire cette modification de ce pas

2023-09-18 09:25 UTC, Allan-CodeWorks commented
Toujours en attente que [ Ajoute l'aide permis de conduire de region Nouvelle Aquitaine #181 ](https://github.com/openfisca/openfisca-france-local/pull/181) soit mergée.

2023-09-18 13:41 UTC, Shamzic approved these changes
Ok pour moi
Parcours d'un étudiant boursier à Bordeaux :
![image](https://github.com/betagouv/aides-jeunes/assets/18016058/69e05d7b-b600-492c-9314-ece8d76ea7db)

2023-09-18 13:42 UTC, merged