Corrige les liens d'aide dans les emails (pré-remplissage)
betagouv/aides-jeunes pull request #3982
Opened 2023-09-14 14:43 UTC by Shamzic

Corrige les liens des aides contenant des redirections de pré-remplissange dans les résultats reçus par email

Testé avec l'aide aidde-demonstration-preremplissage, redirection vers le `link`si le `teleservice` de l'aide est un objet de redirection.

2023-09-15 15:56 UTC, baptou12 commented on backend/lib/mes-aides/emails/simulation-results.ts
>      if (droit.teleservice) {
Je pense que se serait mieux de changer seulement la condition `if (droit.teleservice)` en `if (droit.teleservice && droit.teleservice.name !== "redirection")` et que le cas "redirection"continue les `else if/else`. 

Ça évitera d'avoir un lien `droit.link` avec comme label `"Faire une demande en ligne"`. (et d'avoir le label `"Plus d'informations"` si on tombe pas dans un `else if`). Ça te va ?

2023-09-15 15:56 UTC, baptou12 requested changes
cf conditions

2023-09-18 15:29 UTC, Shamzic commented on backend/lib/mes-aides/emails/simulation-results.ts
>      if (droit.teleservice) {
Ah oui effectivement c'est plus propre ainsi

2023-09-18 16:26 UTC, baptou12 approved these changes

2023-09-19 08:02 UTC, merged