Convertit `crous_repas_un_euro_eligibilite` en `montant repas crous`
betagouv/aides-jeunes pull request #3983
Opened 2023-09-15 14:57 UTC by Allan-CodeWorks

# Description :|
[Ticket trello](https://trello.com/c/RB3TnEBM)

Suite la mise à jour 153.2.0(https://github.com/openfisca/openfisca-france/pull/2181) d'`openfisca-france` qui ajoute la variable `crous_repas_montant`, l'aide du simulateur peut être transformée pour mettre en évidence les repas subentionnés pour tous les étudiants.

2023-09-15 15:38 UTC, baptou12 commented on data/benefits/openfisca/crous_repas_montant.yml
> -label: repas du CROUS à 1€
@Allan-CodeWorks je pense qu'il faut que tu change le type (et mettre un unit) pour que le montant s'affiche en haut à droites. Dans le cas 3.3 on affiche ça : 
<img width="830" alt="image" src="https://github.com/betagouv/aides-jeunes/assets/4059803/74314857-63dc-4604-b941-83ee2aae2936">

2023-09-15 15:38 UTC, baptou12 requested changes
type de l'output openfisca

2023-09-15 15:48 UTC, Shamzic commented
J'ai pas trop compris pourquoi openfisca renvoie montant: true ici alors que dans tes tests tu as des valeurs numériques pour un étudiant boursier `crous_repas_montant: [0, 3.30, 1]` ?

2023-09-18 06:59 UTC, Allan-CodeWorks commented on data/benefits/openfisca/crous_repas_montant.yml
> -label: repas du CROUS à 1€
Effectivement, j'ai dû faire ça rapidement, merci beaucoup!

J'ai également ajouté un `floorAt` pour affichier `3.30`au lieu de `3`.
C"est un peu dommage que ça affiche `1.00` pour les boursiers par contre :/

2023-09-18 12:27 UTC, baptou12 approved these changes
LGTM 
<img width="810" alt="image" src="https://github.com/betagouv/aides-jeunes/assets/4059803/8871ffed-8637-45ae-9f8b-c306e6f24a9d">

et 

<img width="801" alt="image" src="https://github.com/betagouv/aides-jeunes/assets/4059803/79fb017a-d375-4d14-8d1d-d80c1d0b37b0">

2023-09-18 13:13 UTC, Shamzic commented
> J'ai fait un parcours pour un étudiant boursier et je n'ai pas de montant affiché. J'ai check le tracer et j'ai des booléens en réponse à crous_repas_montant. Je ne saisi pas pourquoi openfisca renvoie `montant: true` ici alors que dans tes tests tu as des valeurs numériques pour un étudiant boursier `crous_repas_montant: [0, 3.30, 1]` ([ici](https://github.com/openfisca/openfisca-france/blob/7bcaec4b9e26b33e81e35c56f9e8e4a6effa417b/tests/formulas/crous_repas_montant.yaml#L7))?
> 
> EDIT: d'après les remarques de Baptiste plus haut, j'imagine que c'est un soucis de type

Questionnement résolu, ok pour moi également 👍

2023-09-18 14:16 UTC, merged