Ajoute 3 aides au permis : MSA Maine et Loire, département Maine et Loire et ville de Cholet
betagouv/aides-jeunes pull request #4037
Opened 2023-10-18 13:29 UTC by yasmine-glitch

2023-10-18 14:50 UTC, baptou12 commented on data/benefits/javascript/departement_maine_et_loire_conduite_supervisee_afodil.yml
> +   - type: beneficiaire_rsa
Tu as un espace en trop ici, il faudrai aligner les `-` (mais je suis étonné que l'erreur de prettier ne soit pas plus explicite)

2023-10-18 14:50 UTC, baptou12 commented on data/benefits/javascript/msa_maine_et_loire_aide_permis.yml
> +   - type: beneficiaire_rsa
ici aussi

2023-10-19 09:14 UTC, baptou12 requested changes

2023-10-23 09:57 UTC, baptou12 commented on data/benefits/javascript/msa_maine_et_loire_aide_permis.yml
> +  - Être en recherche d’emploi ou sous contrat à durée indéterminée.
C'est peut être moi, mais je comprend pas extactement ce qu'ils demandent sur la page. Cependant je vois rien qui se rapproche de "indépendant ou CDI". Tu l'interprête comment toi @yasmine-glitch ?

2023-10-23 10:04 UTC, yasmine-glitch commented on data/benefits/javascript/msa_maine_et_loire_aide_permis.yml
> +  - Être en recherche d’emploi ou sous contrat à durée indéterminée.
Oui tu as raison, j'ai corrigé pour écrire "contrat à durée déterminée" et remplacer "indépendant" par "salarié". 
On aura du coup pas mal de faux positifs sur cette aide car on n'est pas capables aujourd'hui de cibler les personnes en contrat déterminé VS indéterminé.
Mais avec cette modif, on se rapproche de ce qui est écrit dans le texte officiel de l'aide

2023-10-23 10:23 UTC, baptou12 approved these changes

2023-10-23 14:15 UTC, merged