feat: Extrait la question service civique de la question activite
betagouv/aides-jeunes pull request #4041
Opened 2023-10-20 11:20 UTC by baptou12

2023-10-25 13:03 UTC, baptou12 commented on lib/state/blocks.ts
> +      ...(demandeur
J'ai choisi de mettre cette étape après les steps liées à l'éducation/chômage, ça permet de garder ces questions proche de la question "activité".

2023-10-31 13:23 UTC, Shamzic commented
> (1) Dans le cas où l'activité est service civique initialement, est-ce qu'on préfère garder cette valeur ou bien est-ce qu'on met Autre (sachant que en soit ça pourrait très bien être étudiant par exemple).

Ca me paraît très bien ce que tu as fait en mettant Autre en premier et par la suite la question du Service civique.

2023-10-31 13:25 UTC, Shamzic commented
Je me questionne sur l'enchaînement de la question "Êtes-vous reconnu ou reconnue inapte au travail ?", si la réponse est non, alors la réponse à la question suivante du service civique est forcément négative, non ?

2023-10-31 14:04 UTC, baptou12 commented
> inapte au travail

J'ai pas vraiment trouvé d'info qui allait dans ce sens, ça m'embête de l'enlever si il se peut qu'il y au des usagers concernés. Si on veut l'enlever un peut plus souvent on peut intégrer l'age et le handicap : \
>  entre 16 et 25 ans (et jusqu'à 30 ans si je suis en situation de handicap)

2023-10-31 14:41 UTC, baptou12 commented
> Ca me paraît très bien ce que tu as fait en mettant Autre en premier et par la suite la question du service civique.


J'ai fait ça dans le dernier commit du coup

2023-10-31 16:02 UTC, Shamzic commented
> > inapte au travail
> 
> J'ai pas vraiment trouvé d'info qui allait dans ce sens, ça m'embête de l'enlever si il se peut qu'il y au des usagers concernés. Si on veut l'enlever un peut plus souvent on peut intégrer l'age et la situation de handicap :
> 
> > entre 16 et 25 ans (et jusqu'à 30 ans si je suis en situation de handicap)

Je ne trouve pas d'information non plus pour approuver mes doutes mais moralement parlant, ça me paraît pas cohérent de faire un service civique quand on est inapte au travail. Cela dit, ce n'est pas considéré comme un contrat de travail ( [cette source](https://www.culture.gouv.fr/Nous-connaitre/Emploi-et-formation/Service-civique/Le-service-civique/Le-service-civique-c-est-quoi-Principes-et-objectifs) va dans ton sens donc c'est aussi ok pour moi de laisser ainsi) : 

> "Le service civique ne doit en aucun cas se substituer à un emploi salarié ou d’agent public. L’engagement fait l’objet d’un contrat qui relève du code du service national, et non du code du travail. Le volontaire est placé dans une relation de collaboration et non de subordination vis-à-vis de son organisme d’accueil. 
Le service civique ne doit pas non plus venir concurrencer le bénévolat."

2023-10-31 18:21 UTC, baptou12 commented
Hm, je vais faire la modification, mais c'est plus embêtant je trouve, je poserais la question à Thomas.

2023-11-20 09:23 UTC, guillett commented on backend/lib/migrations/simulations/to-v15.ts
> +  if (
Pourquoi mettre une telle condition ?

Normalement ça ne devrait être exister pour les simulation de version strictement inférieur à 15.

2023-11-20 09:23 UTC, guillett commented on lib/state/blocks.ts
> +      ...(demandeur
> Le Service civique est ouvert à tous les jeunes de 16 à 25 ans, jusqu’à 30 ans en situation de handicap

https://www.jeunes.gouv.fr/le-service-civique-268

Ça pourrait être bien de limité l'affichage de la question.

2023-11-20 09:52 UTC, baptou12 commented on backend/lib/migrations/simulations/to-v15.ts
> +  if (
C'est vrai que la partie version, gère aussi, j'ai voulu écrire une fonction idempotente, même pour les tests en local. Je pense qu'étant une migration, contrairement à du code en prod, ce n'est pas en trop, mais je peux l'enlever si tu pense qu'il faut.

Mais au moins ça me fait penser que j'ai pas modifié ce fichier : https://github.com/betagouv/aides-jeunes/blob/3cedc044e5a128885610c3e637a1e4b50f7c94fa/lib/simulation.ts#L1

2023-11-20 09:55 UTC, baptou12 commented on lib/state/blocks.ts
> +      ...(demandeur
Y'a une différence entre être élligible au service civique et être en service civique non ? Faudrait rajouter une marge d'un an a peu près, t'en pense quoi ?

2023-11-20 10:01 UTC, baptou12 commented
> Pour corriger ce problème, tu peux mettre `inactif` à la place de `autre` pour la valeur de l'activité d'un service civique car sur la [doc d'openfisca](https://legislation.fr.openfisca.org/activite?q=activite), la valeur `inactif` est considérée comme `"Autre, inactif"`

@guillett le point le plus important où j'aurais besoin de ton avis c'est sur le fait d'être ok de mettre inactif dans activité pour quelqu'un qui était en service civique. Dans le front ça fait "Autre" qui me parait bon, mais le fait de mettre inactif dans le back me parait questionable. T'en pense quoi ? 
J'ai modifié le commit pour que le code reflète la proposition de @Shamzic

2023-11-28 10:21 UTC, guillett commented
C'est complètement OK pour moi, tant que c'est une situation réalisable en faisant un parcours sur le simulateur, ce qui semble le cas (étant donné que le service civique est affiché dans presque toutes les situations).

2023-12-01 12:41 UTC, Shamzic requested changes
Ok pour moi, juste une remarque concernant l'[enum ici](https://github.com/betagouv/aides-jeunes/blob/87d45551e4d1d55351b36c3281ded8fb1355fc9e/lib/enums/activite.ts#L12) : service_civique n'est plus une activité non ?

Tests de la migration locale fonctionnel (données fake sur les screens) ✅ 

![image](https://github.com/betagouv/aides-jeunes/assets/18016058/2f1e2df8-c61b-4ebd-97d7-c20533c21d58)

devient 

![image](https://github.com/betagouv/aides-jeunes/assets/18016058/683b4fae-6076-4042-a15d-af78d571a23f)

Test à l'ajout d'une aide avec l'outil de contrib : les critères sont toujours respectés pour l'affichage conditionnel au service-civique ✅ 

Une interrogation subsidiaire : est-ce que ce serait pertinent d'ajouter des tests de migration avec jest ? Je trouverais cela assez utile en dev déjà pour avoir une idée des modifications engendrées, même si je conçois bien qu'une fois la migration effectuée, ces tests n'auraient plus d'utilité (cela dit, on conserve toujours les fichiers de migrations même si ils n'ont plus d'utilité).

2023-12-05 09:03 UTC, baptou12 commented
> Une interrogation subsidiaire : est-ce que ce serait pertinent d'ajouter des tests de migration avec jest ? Je trouverais cela assez utile en dev déjà pour avoir une idée des modifications engendrées, même si je conçois bien qu'une fois la migration effectuée, ces tests n'auraient plus d'utilité (cela dit, on conserve toujours les fichiers de migrations même si ils n'ont plus d'utilité).

Oui c'est possible de faire ça, enfin ça se fait, je peux le faire rapide pour se rassurer

2023-12-05 14:00 UTC, baptou12 commented on lib/state/blocks.ts
> +      ...(demandeur
ok si tu veux

2023-12-06 11:31 UTC, Shamzic commented on tests/unit/backend/migration-to-v15.spec.ts
> +  it("do not modify answers if activite is not service_civique", () => {
Si l'activité est "retraite" il ne faut pas ajouter la réponse "service_civique" d'après la condition récemment ajoutée dans blocks.ts

2023-12-07 10:45 UTC, baptou12 commented
> Pourquoi 31 et pas 30 ans inclus en âge limite ?
> 
> > Si vous êtes en situation de handicap, vous pouvez vous engager en Service Civique dès 16 ans et jusqu’à la veille de vos 31 ans
> > [source](https://www.service-civique.gouv.fr/etre-volontaire/etape03-realiser-mon-service-civique/avantages-volontaires-service-civique)

Selon moi on peut commencer le service civique avant 30 mais on peut être en service civique à 31 ans

2023-12-07 10:56 UTC, Shamzic commented on backend/lib/migrations/simulations/to-v15.ts
> +  )
Je suis étonné que ce code ne soit pas mutualisé quelque part, il y avait un peu plus court pour le faire :
```suggestion
age = dayjs(simulation.dateDeValeur).diff(dateOBirth, "year")
```

2023-12-07 11:00 UTC, Shamzic commented
> Selon moi on peut commencer le service civique avant 30 mais on peut être en service civique à 31 ans, limit je sais pas si à 32 on peut pas y être encore

C'est pas ce que je comprends dans ce qui est écrit du site du gouvernement. Tu pourrais être en SC à 31 ans oui, mais tu dois t'inscrire avant de les avoir du coup je comprends pas comment tu pourrais être en service civique à 32 ans ?

2023-12-07 14:00 UTC, baptou12 commented on backend/lib/migrations/simulations/to-v15.ts
> +  )
j'ai changé pour ta proposition qui est plus concise, mais pas lié à la méthode d'individu :-)

2023-12-07 14:54 UTC, merged