Ajoute le bouton de partage d'une aide - WIP
betagouv/aides-jeunes pull request #4052
Opened 2023-11-01 17:48 UTC by Shamzic

- [ ] : Mettre à jour les balises meta pour open graph
- [ ] : Bouton de partage sur facebook
- [ ] : Bouton pour copier l'url de l'aide dans le presse-papier
- [ ] : Bouton de partage par Email ?
- [ ] : Ajout les boutons des réseaux les plus utilisés par les jeunes (=> quels sont les choix de l'équipe?)

2023-11-03 16:10 UTC, baptou12 requested changes
Pour moi ça fonctionne et ça a l'air de respecter les consigne de cette page du DSFR https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/partage/

Surtout des propositions de renaming, dispo pour en discuter

2023-11-03 16:23 UTC, Shamzic commented on lib/enums/event.ts
> +  CopieLien = "copy-link",
Tu as raison!

2023-11-03 16:25 UTC, Shamzic commented on lib/enums/event.ts
> +  PartageLienEmail = "share-link-email",
`ShareLinkEmailBenefit` pour être encore plus précis ?

2023-11-03 16:33 UTC, Shamzic commented on src/components/droits-details.vue
> +        <p class="fr-share__title">Partager la page</p>
Oui, ce sera plus homogène avec le reste du composant 👍

2023-11-03 16:37 UTC, Shamzic commented on src/components/droits-details.vue
> +    sharingLinkSubject() {
Ajouter `ByEmail` me paraît suffisant

2023-11-03 16:39 UTC, Shamzic commented on src/components/droits-details.vue
> +    async shareLinkEmail() {
Je propose `shareLinkByEmailClick`

2023-11-03 16:58 UTC, baptou12 commented on lib/enums/event.ts
> +  PartageLienEmail = "share-link-email",
Moi ça me va :-)

2023-11-06 13:46 UTC, baptou12 approved these changes
LGTM

2023-11-06 13:46 UTC, baptou12 commented on lib/enums/event.ts
> +  CopyLinkBenefit = "copy-link-benefit",
Pas bloquant car on a déjà français et anglais, mais ça fait bizarre dans le même fichier, la même PR d'avoir un element en français et un en anglais.

2023-11-06 13:55 UTC, Shamzic commented on lib/enums/event.ts
> +  CopyLinkBenefit = "copy-link-benefit",
ah oui t'as raison, je vais uniformiser pour la PR

2023-11-06 14:30 UTC, merged