Simplification Store
betagouv/aides-jeunes pull request #4053
Opened 2023-11-03 08:25 UTC by baptou12

Je vais mettre les explications détaillées, mais il me semble que cette partie du code n'est pas nécéssaire à cause d'une autre fonction qu'on appel après.

2023-11-03 17:44 UTC, Shamzic commented on src/stores/index.ts
>      updateCurrentAnswers(newPath: string | undefined) {
Bon refacto. 

Au passage, une proposition de refacto pour `updateCurrentAnswers` avec son étrange boucle while :

```
  updateCurrentAnswers(newPath: string | undefined) {
      const currentAnswers = this.getAllSteps
        .filter(
          (step) => step.isActive && step.path !== "/" && step.path !== newPath
        )
        .map((step) => {
          return this.simulation.answers.all.find((answer) => {
            return (
              answer.id === step.id &&
              answer.entityName === step.entity &&
              answer.fieldName === step.variable
            )
          })
        })
        .filter(Boolean) // Supprime les valeurs undefined

      this.simulation.answers.current = currentAnswers
    },
```

2023-11-06 10:50 UTC, baptou12 commented on src/stores/index.ts
>      updateCurrentAnswers(newPath: string | undefined) {
@Shamzic J'ai fait une proposition

2023-11-06 10:56 UTC, Shamzic commented on src/stores/index.ts
>      updateCurrentAnswers(newPath: string | undefined) {
Je check ça !

2023-11-06 11:31 UTC, Shamzic requested changes

2023-11-06 11:31 UTC, Shamzic commented on lib/answers.ts
> +export function storeAnswer(answers, newAnswer) {
On pourrait ajouter du typage dans les paramètres ici ? 
(Dis moi si c'est superflu ?)
```suggestion
export function storeAnswer(answers: Answer[], newAnswer: Answer) {
```

2023-11-06 11:31 UTC, Shamzic commented on src/stores/index.ts
> +    updateCurrentAnswers(newPath) {
```suggestion
    updateCurrentAnswers(newPath: string) {
```

2023-11-06 11:31 UTC, Shamzic commented on src/stores/index.ts
> -          current: storeAnswer(currentAnswers, answer, this.simulation.enfants),
Sinon, c'est peut être plus court et tout aussi efficace de faire

```js
this.simulation.enfants = enfants;
this.simulation.answers.all = storeAnswer(this.simulation.answers.all, answer);
```

2023-11-06 11:31 UTC, Shamzic commented on src/stores/index.ts
> -          current: storeAnswer(currentAnswers, answer, this.simulation.enfants),
Sinon, c'est peut être plus court et tout aussi efficace de faire

```js
this.simulation.enfants = enfants;
this.simulation.answers.all = storeAnswer(this.simulation.answers.all, answer);
```
(c'est iso aussi normalement, les tests passent toujours)

2023-11-06 11:51 UTC, baptou12 commented
https://github.com/betagouv/aides-jeunes/pull/4053#discussion_r1383170099
En fait c'est pas exactement exactement iso. Car dans ton morceaux de code on utilise le même object simulation VS dans celui qui est en prod on en recréé un. 

Pas sûr que ça ai un impact (dans react ça peut en avoir beaucoup par exemple) mais c'était pour te montrer la diff. 

Après je pense laisser comme ça si ça te va, histoire de ne pas trop changer de choses autour de la refacto initiale pour cette PR.

2023-11-06 11:54 UTC, baptou12 commented on src/stores/index.ts
> -          current: storeAnswer(currentAnswers, answer, this.simulation.enfants),
En fait c'est pas totalement la même chose, car avant ça créait un nouvel objet simulation, vs là ça l'override. 
Dans certains framework genre react ça a une grande importance. Ici je sais pas trop.

Je préfère laisser comme c'est si ça te vas, pour pas éloigner trop de la refacto initiale ?

2023-11-06 11:54 UTC, baptou12 commented on lib/answers.ts
> +export function storeAnswer(answers, newAnswer) {
Je vais regarder, si les types sont bien fait ça devrait pas poser de soucis, sinon je regarderais pour les corriger.

2023-11-06 13:53 UTC, Shamzic approved these changes

2023-11-07 07:25 UTC, merged