Ajoute l'envoi de SMS manuel (WIP)
betagouv/aides-jeunes pull request #4058
Opened 2023-11-08 17:44 UTC by Shamzic

Feature pour envoyer des SMS manuellement. Objectif : envoyer un sms contenant le lien du sondage post simulation.

2023-11-13 09:18 UTC, guillett commented
Est ce plutôt facile pour toi de couper cette PR en deux avec le refactor d'une part et la nouvelle fonctionnalité d'autre part ?

2023-11-13 14:05 UTC, Shamzic commented
> Est ce plutôt facile pour toi de couper cette PR en deux avec le refactor d'une part et la nouvelle fonctionnalité d'autre part ?

Oui, c'est ce que j'ai expliqué dans la description mais du coup tu trouves qu'il y a déjà trop de refacto ici ?

2023-11-13 14:40 UTC, guillett commented
J'ai l'impression qu'il y a 50% (voire plus) de refacto et 50% pour la nouvelle fonctionnalité. Sur une PR qui fait +400 - 100 je me dis que ça serait bien de découper en deux.

2023-11-14 14:30 UTC, Shamzic commented
> J'ai l'impression qu'il y a 50% (voire plus) de refacto et 50% pour la nouvelle fonctionnalité. Sur une PR qui fait +400 - 100 je me dis que ça serait bien de découper en deux.

J'ai déplacé 100 lignes de refacto ici : https://github.com/betagouv/aides-jeunes/pull/4066/files je pense qu'on est au max ^^

2023-11-14 16:53 UTC, baptou12 requested changes

2023-11-14 16:53 UTC, baptou12 commented on backend/lib/sms-service.ts
> +    const renderUrl = followup.renderSimulationResultsSmsUrl(username, password)
Quitte a sortir dans un service (:+1:), il faudrait ne plus faire appel à des méthodes de followup (à voir si dans cette PR), sinon ça fait :
méthode de followup qui appelle service qui appelle méthode de followup.

2023-11-14 16:53 UTC, baptou12 commented on lib/enums/sms.ts
> +export enum SmsCategory {
On envoi que deux SMS non ? pourquoi on a 4 catégories ? on mélange pas deux concepts ?

2023-11-14 16:53 UTC, baptou12 commented on backend/controllers/followups.ts
> +    req.params.surveyType = SurveyCategory.TrackClickOnBenefitActionSms
Note pour refacto : on pourrait passer directement `SurveyCategory.TrackClickOnBenefitActionSms` et le followup (ici et dans l'email) :-)

2023-11-15 16:18 UTC, Shamzic commented on backend/lib/sms-service.ts
> +    const username = config.smsService.username
J'ai fait une modif dans ce sens

2023-11-15 16:29 UTC, Shamzic commented on backend/lib/sms/sending.ts
> +              SurveyCategory.TrackClickOnBenefitActionSms,
Oui, c'est pas dans les specs et cela reste à définir. J'aurais tendance à découpler les deux envois et faire les deux en même temps si les deux infos sont renseignées.

> * On veut envoyer email ET sms à ceux qui ont mis les deux ? (DHL le fait pour les livraisons)

Oui, j'avais intuitivement cette idée en tête.

> * De manière général si quelqu'un a cliqué sur l'email on veut quand même envoyer le sms ? (on pourrait rajouter `SurveyCategory.TrackClickOnSimulationUsefulnessEmail` et `SurveyCategory.TrackClickOnBenefitActionEmail`

Si le sondage est déjà répondu, cela n'a pas trop de sens de le renvoyer via un autre moyen de communication

@guillett Quel est ton avis sur ces questions ?

2023-11-15 16:53 UTC, Shamzic commented on backend/lib/sms-service.ts
> +    const renderUrl = followup.renderSimulationResultsSmsUrl(username, password)
Suite à ta remarque, j'ai déplacé directement `renderSimulationResultsSmsUrl` dans le service

2023-11-15 16:54 UTC, Shamzic commented on lib/enums/sms.ts
> +export enum SmsCategory {
exact, d'ailleurs cet enum est maintenant dans `messaging.ts`

2023-11-15 17:22 UTC, Shamzic commented on backend/controllers/followups.ts
> +    req.params.surveyType = SurveyCategory.TrackClickOnBenefitActionSms
Pour cette suggestion, j'ai fait des essais sur le PR de refacto mais je suis pas convaincu car on va avoir une méthode avec un argument surveyType dans le controller et ça me semble pas être cohérent avec les autres méthodes de ce controller qui ont seulement res et req en argument (il s'agit probablement d'une bonne pratique ?)

2023-11-16 09:54 UTC, baptou12 commented on backend/controllers/followups.ts
> +    req.params.surveyType = SurveyCategory.TrackClickOnBenefitActionSms
yes, cette logique n'est pas vraiment lié au controller justement

2023-11-16 10:02 UTC, baptou12 commented on backend/lib/messaging/sms/sms-service.ts
> +function renderSimulationResultsSmsUrl(accessToken, phone, username, password) {
Je trouve pas d'autre terme mais en vrai c'est pas vraiment "render" le mot ici. 

P.e. build ?

2023-11-16 10:03 UTC, baptou12 commented on backend/models/followup.ts
> +    const surveyLink = `${baseURL}/api/sms/surveys/${accessToken}`
Pourquoi ce n'est pas dans le service ce nouveau sms ?

2023-11-16 10:04 UTC, baptou12 commented on backend/models/followup.ts
> +FollowupSchema.method("postSurveyBySms", function (messageId) {
Même remarque que pour les emails dans la PR de refacto, est-ce que ça vaudrais pas le coup de l'intégrer à la method d'envoi ? quitte à factorisé entre les differents type d'email/sms

2023-11-16 10:05 UTC, baptou12 commented on backend/models/followup.ts
> +  "sendSurveyByEmail",
à ça on aurait pu le mettre dans l'autre PR, pas bloquant

2023-11-16 10:06 UTC, baptou12 commented on backend/models/followup.ts
> +      await this.sendBenefitActionSms(surveyType)
L'argument `surveyType` n'est pas utilisé

2023-11-16 10:08 UTC, baptou12 commented on backend/lib/messaging/sending.ts
> +async function processSingleSms(smsCategory: SmsCategory, followupId: string) {
Ça je ne sais pas si on s'en sert pour les emails, mais tu pense qu'on s'en servira pour les sms ? Faudrait que @guillett nous éclaire p.e. ?

2023-11-16 10:09 UTC, baptou12 commented on backend/models/followup.ts
> +      await this.sendBenefitActionSms(surveyType)
C'était déjà le cas dans les emails, mais on a beaucoup de méthodes imbriquées non ?

2023-11-16 14:53 UTC, Shamzic commented on backend/lib/messaging/sms/sms-service.ts
> +export async function renderAndSendSimulationResultsSms({
Yes, même logique que pour la PR d'email, on supprime ce `renderAnd`

2023-11-16 15:00 UTC, Shamzic commented on backend/lib/messaging/sms/sms-service.ts
> +function renderSimulationResultsSmsUrl(accessToken, phone, username, password) {
Build c'est mieux oui

2023-11-17 00:13 UTC, Shamzic commented on backend/models/followup.ts
> +    const surveyLink = `${baseURL}/api/sms/surveys/${accessToken}`
Corrigé

2023-11-17 00:14 UTC, Shamzic commented on backend/models/followup.ts
> +FollowupSchema.method("postSurveyBySms", function (messageId) {
Intégré dans la méthode d'envoi du service

2023-11-17 00:16 UTC, Shamzic commented on backend/lib/messaging/sms/sms-service.ts
> +        followup.smsSurveyError = undefined
Preneur d'avis concernant le stockage de ces données. Ces assignation similaires à la partie d'envoi par email  ne me semble pas forcément très utiles, je les ai ajoutées sans être trop certain de leur utilité car je n'ai pas de spécification à ce sujet

2023-11-17 18:05 UTC, Shamzic commented on backend/models/followup.ts
> +      await this.sendBenefitActionSms(surveyType)
> L'argument `surveyType` n'est pas utilisé

Je sais pas si t'as bien ciblé ta citation de code mais là je vois que c'est utilisé dans addSurveyIfMissing et sendBenefitActionSms du coup je comprends pas ta remarque ?

2023-11-20 10:33 UTC, baptou12 commented on backend/models/followup.ts
> +      await this.sendBenefitActionSms(surveyType)
Dans `sendBenefitActionSms` ça n'est pas utilisé : 
<img width="558" alt="image" src="https://github.com/betagouv/aides-jeunes/assets/4059803/ca14960f-4f8c-46ce-a76b-a00eeddf263b">

2023-11-21 16:49 UTC, Shamzic commented
Résolution des multiples rebase [disponible ici dans une nouvelle PR ](https://github.com/betagouv/aides-jeunes/pull/4074)(plus simple à review)

2023-11-21 16:49 UTC, closed without merging