Ajoute l'envoi des sondages par SMS
betagouv/aides-jeunes pull request #4074
Opened 2023-11-21 16:47 UTC by Shamzic

2023-11-29 13:14 UTC, baptou12 requested changes

2023-11-29 13:14 UTC, baptou12 commented on backend/lib/messaging/sending.ts
> +    followups.filter(shouldSendSurveyBySms).map(async (followup: Followup) => {
Tu as fait des tests ? j'ai l'impression que si tu fais ça la fonction filter va mettre en deuxième argument de `shouldSendSurveyBySms` l'index (1) et que du coup on aura toujours `today`(2) qui sera truthy dans la fonction, enfin sauf pour le premier element d'index `0`.


(1) : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
<img width="797" alt="image" src="https://github.com/betagouv/aides-jeunes/assets/4059803/df014dc7-d811-46ea-b39d-885b8657d689">
(2) je te met un comment là haut, mais je pense que `today` n'est pas utilisé, si ?

2023-11-29 13:14 UTC, baptou12 commented on backend/lib/messaging/sending.ts
> +export function shouldSendSurveyBySms(followup: Followup, today?): boolean {
J'ai l'impression que `today` n'est pas utilisé

2023-11-29 13:14 UTC, baptou12 commented on backend/lib/messaging/sms/sms-service.ts
> +    if (status !== 200 || data.responseCode !== 0) {
Normalement ces deux if (ici et dans sms survey) tu dois pouvoir les mettre dans l'axios instance, à tester mais : 

```
async function createAxiosInstance() {
  const instance =  axios.create({
    timeout: 10000,
  })

  instance.interceptors.response.use((response) => response, (error) => {
    if (error) {
      throw error
    }

    const { data, status } = response
    if (status !== 200 || data.responseCode !== 0) {
      throw new Error(`SMS request failed. Body: ${JSON.stringify(data)}`)
    }
  });

  return instance
}

```

Par ailleurs on sait a quoi ressemble l'erreur ? faudrait pas que les numéro apparaissent et reste sur le serveur de manière indéfinie

2023-11-29 13:14 UTC, baptou12 commented on backend/models/followup.ts
> +FollowupSchema.method("findSurvey", function (type: SurveyType) {
Probablement plus utile si on passe par `addSurveyIfMissing`

2023-11-29 13:14 UTC, baptou12 commented on backend/lib/messaging/sms/sms-service.ts
> +  followup.smsSurveySentAt = dayjs().toDate()
Normalement on le stock plutôt dans le survey ça non ?

2023-11-29 13:14 UTC, baptou12 commented on tools/sms-sending-tool.ts
> +  parser.add_argument("--multiple", {
Là tu permet d'envoyer de manière multiple les sis de simulation, dans le tools pour les emails on sépare les categories (types ?) entre single et multiple pour adapter les parsers

2023-11-29 13:34 UTC, Shamzic commented on backend/controllers/followups.ts
> +      const survey = followup.findSurvey(surveyType)
Elle renvoie bien le survey qui a été modifié, cependant ici on va utiliser `findSurvey` pour trouver un le type de survey d'un des trois `case` au dessus et est différent de celui de type `SurveyType.BenefitAction`

2023-11-29 13:45 UTC, Shamzic commented on backend/controllers/followups.ts
>  async function getRedirectUrl(req: Request) {
J'ai fait un ticket pour poursuivre ta démarche

2023-11-29 13:50 UTC, Shamzic commented on backend/lib/messaging/sending.ts
> +      const surveyEmailCreatedAtPlus3Days = surveyEmailCreatedAt.add(3, "day")
Ah oui j'voulais le faire mais j'avais aucune idée de nom pour celle là ahah

2023-11-29 13:58 UTC, baptou12 commented on backend/controllers/followups.ts
> +      const survey = followup.findSurvey(surveyType)
Ok mais du coup dans le cas où il existe pas on voudrait pas le créer ? Là actuellement ça fait une 404. 

Il n'y a pas de raison dans le happy path pour qu'il n'existe pas, mais on est pas toujours dans le happy path (pb de mise en prod, lien envoyé directement à la main, en dev). 

Sinon si on est ok avec le fait d'avoir une 404 si le survey n'existe pas, faudrait utiliser `findSurvey` dans `addSurveyIfMissing`

2023-11-29 14:07 UTC, Shamzic commented on backend/lib/messaging/sending.ts
> +              SurveyType.BenefitAction,
Ce me semble toujours utile même après cette PR ? Ca allègue le nombre de followups à traiter dans `shouldSendSurveyBySms`, ou alors on peut déplacer le filtrage dans cette dernière mais ça me semble moins opti

2023-11-29 14:29 UTC, baptou12 commented on backend/lib/messaging/sending.ts
> +              SurveyType.BenefitAction,
Oui tu as raison, mais du coup je pense qu'il serait plus safe sur le moyen/longterme, de rajouter une clause "on envoi pas à des followup plus vieux de X temps" et d'enlever ça. Sinon c'est un coup à ce qu'un future dev se dise "BenefitAction n'a plus lieu d'être je vire la clause" ⇒ des milliers de mails envoyés

2023-11-29 14:30 UTC, Shamzic commented on backend/lib/messaging/sending.ts
> +    followups.filter(shouldSendSurveyBySms).map(async (followup: Followup) => {
Effectivement je crois que tu as raison, j'ai fait des tests unitaires sur la méthode `shouldSendSurveyBySms` mais pas sur ce filter

2023-11-29 15:18 UTC, Shamzic commented on backend/lib/messaging/sms/sms-service.ts
> +  followup.smsSurveySentAt = dayjs().toDate()
On devrait, mais historiquement `messageId` et `error`  les équivalents concernant l'envoi par email étaient à la racine du followup, j'ai laissé comme ça pour homogénéiser. On peut remettre tout ça à la racine mais ça va faire encore pas mal de refacto

2023-11-29 15:19 UTC, Shamzic commented on backend/lib/messaging/sms/sms-service.ts
> +  followup.smsSurveySentAt = dayjs().toDate()
On devrait, mais historiquement `messageId` et `error`  les équivalents concernant l'envoi par email étaient à la racine du followup, j'ai laissé comme ça pour homogénéiser. Ca risque de faire pas mal de refacto si on met tout dans les surveys

2023-11-29 15:30 UTC, baptou12 commented on backend/lib/messaging/sms/sms-service.ts
> +  followup.smsSurveySentAt = dayjs().toDate()
Bah justement messageId on le met dans le survey [ici](https://github.com/betagouv/aides-jeunes/blob/93ebe944fd6b3706da163a7fdce9ba7385e1abdc/backend/lib/messaging/email/email-service.ts#L55) et au dessus ligne 107 pour les sms. Tu verrais des refacto où ?

2023-11-29 16:06 UTC, Shamzic commented on backend/lib/messaging/sending.ts
> +export function shouldSendSurveyBySms(followup: Followup, today?): boolean {
C'est utilisé dans les tests uniquement (afin qu'ils restent inchangés dans le temps)

2023-11-29 17:48 UTC, Shamzic commented
Dernier ajout de test unitaire WIP

2023-11-30 13:14 UTC, baptou12 commented on tests/unit/lib/state/messaging/messaging-sms.spec.ts
> +  MockDate.reset()
Idéalement il faudrait que tout les MockDate soit dans un before ou un after (ou beforeEach ou afterEach en fonction) car il ne font pas parti du teste à proprement parlé

2023-11-30 13:15 UTC, baptou12 commented on backend/lib/messaging/sending.ts
> +export function shouldSendSurveyBySms(followup: Followup, today?): boolean {
Yes c'était ça. Après coup j'ai vu ça sur le web 😅 comme tu le souhaite on peut garder mockdate https://stackoverflow.com/a/63377110/2528836

2023-11-30 13:21 UTC, Shamzic commented on tools/sms-sending-tool.ts
> +  parser.add_argument("--multiple", {
J'ai corrigé pour ne laisser que le type initial-survey en option `multiple` et les deux type pour l'option 
 `id`, comme pour les emails

2023-11-30 13:27 UTC, Shamzic commented on backend/lib/messaging/sms/sms-service.ts
> +  followup.smsSurveySentAt = dayjs().toDate()
Ok, j'ai peut être répondu un peu vite, tu as vu juste. Je peux supprimer le `smsSurveySentAt` qui ne sert à rien car il y a un `createdAt` dans le survey par défaut et stocker le `smsSurveyError` et directement dans le survey

2023-11-30 14:08 UTC, Shamzic commented on backend/controllers/followups.ts
> +      const survey = followup.findSurvey(surveyType)
C'est vrai que j'ai pas traité ce cas là car il est toujours censé être créé dans le cas idéal. J'ajoute ici un `addSurveyIfMissing` dédié au surveyType à la place du `findSurvey`.

2023-11-30 14:37 UTC, Shamzic commented on backend/lib/messaging/sending.ts
> +              SurveyType.BenefitAction,
C'est compris, est-ce que ça te va le commentaire que j'ai mis pour une future tâche ?

2023-12-04 13:54 UTC, baptou12 commented on package-lock.json
> +        "mockdate": "^3.0.5",
Mockdate encore présent dans le lock

2023-12-04 15:01 UTC, Shamzic commented on tools/sms-sending-tool.ts
> +const multiple_sms_parser = send_types.add_parser(SmsType.InitialSurvey)
Bien vu, la commande n'est pas utile en prod mais peut peut-être servir un jour. C'est corrigé

2023-12-04 15:24 UTC, baptou12 commented on backend/lib/messaging/sending.ts
> +    .sort((a, b) => a.createdAt - b.createdAt)
En fait plus j'y réfléchi plus cette requête me fait peur : je pense même que ça peut faire casser la prod : 

Là on a pas de clause sur le numéro de telephone, donc globalement on va prend tout les followup de la base (quasi) et les trier. ça va faire beaucoup trop je pense.

Déjà a la rigueur on peut limiter by design en prenant des maintenant qu'une **fenêtre temporelle**, **sort** dans la base de donnée ? p.e. même rajouter une **clause sur la présence de numéro de téléphone** ? en soit a quoi bon les recup si on a pas le numéro ? 

Dispo pour en parler si tu veux

2023-12-04 16:22 UTC, Shamzic commented
> LGTM, chaud pour merger demain néanmoins, pour pouvoir faire le premier lancement à la main (avec un limit plus faible ?)

Merci, partisan du merge demain matin avec des envois ayants un limit réduit éventuellement si il y a des craintes de crash

2023-12-05 10:14 UTC, guillett commented on backend/models/survey-schema.ts
> +    openedAt: { type: Date },
Pourquoi ne pas mettre ça dans les answers ?

2023-12-05 10:14 UTC, guillett commented on backend/models/survey-schema.ts
> +    smsSentAt: { type: Date },
Est ce que c'est différent de createdAt ? Et surtout même en cas de différence, est ce que ça apporte suffisant plus pour être conservé ?

2023-12-05 10:15 UTC, guillett commented on lib/types/followup.d.ts
> +  smsSurveyError: any
J'ai l'impression que ce n'est pas utilisé.

2023-12-05 13:13 UTC, merged