Ajoute l'aide fsl energie du var
betagouv/aides-jeunes pull request #4085
Opened 2023-11-27 16:15 UTC by Shamzic

[Tâche associée](https://trello.com/c/Oz5i1vSY/1521-ajouter-le-fsl-%C3%A9nergie-du-var)

2023-11-28 10:32 UTC, baptou12 commented on data/benefits/javascript/departement-var-fonds-de-solidarite-energie.yml
> +  - type: departements
On peut utiliser le "attached_to_institution" pour ne pas dupliquer l'information : "lié au département du var" (cc @Allan-CodeWorks 😄)

cf : https://github.com/betagouv/aides-jeunes/blob/ca4ca8e6a91acc21f603b06298021bf7bfd77e50/lib/benefits/compute-javascript.ts#L143

2023-11-28 10:32 UTC, baptou12 commented on data/benefits/javascript/departement-var-fonds-de-solidarite-energie.yml
> +  - Être majeur ou mineur émancipé ressortissant de l’Union Européenne ou étranger en situation régulière.
On a pas de condition de profile là dessus ?

2023-11-28 10:32 UTC, baptou12 commented on data/benefits/javascript/departement-var-fonds-de-solidarite-energie.yml
> +  - type: departements
Après finalement ça n'a pas l'air d'être tout le var dans la description de l'aide sur le site, non ?

2023-11-28 11:15 UTC, Shamzic commented on data/benefits/javascript/departement-var-fonds-de-solidarite-energie.yml
> +  - Être majeur ou mineur émancipé ressortissant de l’Union Européenne ou étranger en situation régulière.
"mineur émancipé ressortissant de l’Union Européenne ou étranger en situation régulière" je ne crois pas à ma connaissance

2023-11-28 11:17 UTC, Shamzic commented on data/benefits/javascript/departement-var-fonds-de-solidarite-energie.yml
> +  - type: departements
De ce que j'ai compris, c'est tout le var. J'imagine que fais allusion à la liste des ville dans les détails de l'aide et ça c'est pour les endroits où déposer le dossier si l'usager souhaite le faire en physique

2023-11-28 15:40 UTC, baptou12 requested changes
Y'a un truc qui n'est pas clair pour moi. A un moment on parle de FSE mais les liens sont lié aux FSL (*) ? Tu saurais m'expliquer ? 

(*) car les FSL ont l'air d'avoir une gestion particulière cf [ici](https://github.com/betagouv/aides-jeunes/blob/02447119e54e82a1603e69cefbbd309f7456d7c7/data/benefits/dynamic/fsl.ts#L10) et cette ["variable" ](https://github.com/betagouv/aides-jeunes/blob/ca4ca8e6a91acc21f603b06298021bf7bfd77e50/lib/benefits/compute-javascript.ts#L209)

2023-11-28 16:31 UTC, Shamzic commented
> Y'a un truc qui n'est pas clair pour moi. A un moment on parle de FSE mais les liens sont lié aux FSL (*) ? Tu saurais m'expliquer ?
> 
> (*) car les FSL ont l'air d'avoir une gestion particulière cf [ici](https://github.com/betagouv/aides-jeunes/blob/02447119e54e82a1603e69cefbbd309f7456d7c7/data/benefits/dynamic/fsl.ts#L10) et cette ["variable" ](https://github.com/betagouv/aides-jeunes/blob/ca4ca8e6a91acc21f603b06298021bf7bfd77e50/lib/benefits/compute-javascript.ts#L209)

Oui, c'est un choix produit (cc @yasmine-glitch, j'espère que je me trompe pas) pour séparer les aides FSL générées en js qui sont actuellement toutes des aides "maintien". Là il s'agit d'une aide "énergie", elle est assez unique et dispose d'un pré-remplissage d'où le choix de la construire en format yml.

2023-11-29 14:40 UTC, baptou12 reviewed
Pour moi le yml est valide et fonctionnera, il sera montré à toutes personnes habitant dans le var.

C'est très personnel mais je ne trouve pas les descriptions super claires : on parle de problème pour payer ses fournisseur gaz/électricité et en dessous de problèmes pour payer ses charge locative (c'est pas toujours lié). Par ailleurs le lien envoi vers FSL directement et non que FSE, même si j'ai compris que c'était un choix je trouve ça bizarre d'un point de vu experience usager. @yasmine-glitch Tu as un avis ?

2023-11-30 09:03 UTC, yasmine-glitch commented
Hello !
Merci @Shamzic 
Mes commentaires opérationnels
- Cette aide est pour le Var en excluant la métropole de Toulon (exactement comme le FSL qui est dans le fichier js ds fsl)
- Il faut montrer cette aide aux mêmes usagers auxquels on montre le FSL du Var, c'est à dire : ceux qui ont répondu "oui" à la question "rencontrez-vous des difficultés pour payer votre logement et vos factures"
- Je pense que tu peux ajouter une phrase introductive qui dit : "Le Fonds de Solidarité Logement du Var comporte un volet énergie appelé Fonds de Solidarité Energie. Il s'agit d'un dispositif ...

Mes commentaires plus théoriques
Idéalement, d'un point de vue produit, il faudrait une seule aide "FSL du Var" avec trois liens vers les formulaires de demande : accès au logement, maintien dans le logement et énergie.
Mais il me semble qu'on ne peut pas faire ça avec le format actuel d'un aide, d'où ce choix de créer une aide spécifique "FSL énergie du VAR", pour pouvoir avancer.
Sur du plus long terme, il faudra réfléchir à la manière dont on traite les FSL accès au logement et FSL énergie de tous les départements, comme ça a été fait avec les FSL maintien

2023-11-30 16:52 UTC, Shamzic commented
> Cette aide est pour le Var en excluant la métropole de Toulon (exactement comme le FSL qui est dans le fichier js ds fsl)

✅ 

> Il faut montrer cette aide aux mêmes usagers auxquels on montre le FSL du Var, c'est à dire : ceux qui ont répondu "oui" à la question "rencontrez-vous des difficultés pour payer votre logement et vos factures"

✅ 

> Je pense que tu peux ajouter une phrase introductive qui dit : "Le Fonds de Solidarité Logement du Var comporte un volet énergie appelé Fonds de Solidarité Energie. Il s'agit d'un dispositif ...

✅ 

> Idéalement, d'un point de vue produit, il faudrait une seule aide "FSL du Var" avec trois liens vers les formulaires de demande : accès au logement, maintien dans le logement et énergie.
Mais il me semble qu'on ne peut pas faire ça avec le format actuel d'un aide, d'où ce choix de créer une aide spécifique "FSL énergie du VAR", pour pouvoir avancer.

C'est faisable mais effectivement un peu moins évident à modifier en l'état mais c'est faisable aussi. On peut se noter cette proposition de fusion dans une tâche à prioriser ?

> Sur du plus long terme, il faudra réfléchir à la manière dont on traite les FSL accès au logement et FSL énergie de tous les départements, comme ça a été fait avec les FSL maintien

Dans le futur si on se retrouve à ajouter plusieurs autres aides FSL énergie, c'est la solution à adopter 👍

2023-11-30 17:08 UTC, baptou12 commented on data/benefits/javascript/departement-var-fonds-de-solidarite-energie.yml
> +    excludes:
Je n'ai pas l'impression que la [clause exclude](https://github.com/betagouv/aides-jeunes/blob/ca4ca8e6a91acc21f603b06298021bf7bfd77e50/lib/benefits/compute-javascript.ts#L17) soit [codée](https://github.com/betagouv/aides-jeunes/blob/ca4ca8e6a91acc21f603b06298021bf7bfd77e50/lib/benefits/compute-javascript.ts#L89-L104) dans compute-javascript pour les epcis

J'ai test et à toulon ça apparait bien

2023-12-01 14:50 UTC, Shamzic commented on data/benefits/javascript/departement-var-fonds-de-solidarite-energie.yml
> +    excludes:
Ok, j'avais dû mal configurer mon test car je pensais que c'était bon

2023-12-01 15:28 UTC, Shamzic commented on data/benefits/javascript/departement-var-fonds-de-solidarite-energie.yml
> +    excludes:
Exact, j'ai dû foirer mon test, j'ajoute cette condition d'exclusion

2023-12-04 15:54 UTC, baptou12 approved these changes

2023-12-04 16:24 UTC, merged