improvement: corrige les conditions d'affichage de la question du RBG
betagouv/aides-jeunes pull request #4102
Opened 2023-12-07 14:45 UTC by Shamzic

2023-12-07 14:53 UTC, baptou12 requested changes

2023-12-07 14:53 UTC, baptou12 commented on lib/state/blocks.ts
> +                  situation.demandeur.enfant_a_charge = {}
Je pense qu'il faudrait vraiment éviter de commencer à écrire sur la situation dans une fonction `isActive`, le nom suggère qu'on pose seulement une question et pas du tout qu'on fait une action. D'autant que là en plus on override potentiellement une valeur présente non ? 

T'es pas d'accord ? 

Si tu vois pas du tout où le mettre autrement je peux jeter un coup d'oeil

2023-12-07 15:02 UTC, baptou12 commented on lib/state/blocks.ts
> +                  situation.demandeur.enfant_a_charge = {}
ça aide en quoi exactement d'avoir ça ?

2023-12-07 16:07 UTC, baptou12 commented on lib/state/blocks.ts
> +                  situation.demandeur.enfant_a_charge = {}
Ouais mais du coup c'est pas trop dans la philosophie du simulateur qui est de garder toutes les questions même si elles sont plus affiché au cas où on repasse ensuite à 19 ans. (même si ton fix n'override pas les answer mais la situation)


Ça veut dire que ce que tu veux faire c'est ajouter la condition isActive de enfant_a_charge dans la condition de RGB ⇒ autant le faire directement en rajoutant `8 < age && age <= 25` 

(à voir si on factorise pas mais c'est une autre histoire)

2023-12-08 11:18 UTC, Shamzic commented on lib/state/blocks.ts
> +                  situation.demandeur.enfant_a_charge = {}
J'ai proposé un refactor de cette condition + ajout de cette condition à la question du rbg

2023-12-11 16:49 UTC, baptou12 requested changes
J'avoue les dernière modifs lié aux changements que tu voulais faire. Si on veut mettre des méthodes dans individu je pense qu'il vaut mieux les liés aux question : ex: `possiblementACharge` avec la logique dedans. 

p.e. j'ai loupé qqch ?

2023-12-11 16:49 UTC, baptou12 commented on lib/state/blocks.ts
> +                  IndividuMethods.isDependantChild(
Perso je ne trouve pas trop que ça apporte en lisibilité ni en modularité ces deux conditions qu'on répète en allant chercher dans `IndividuMethods`.

2023-12-11 16:49 UTC, baptou12 commented on lib/state/blocks.ts
> +                    situation.dateDeValeur
Pas sûr de comprendre pourquoi on a plus le `datesGenerator` ici ça servait a rien ? On le garde pour `"scolarite"`

2023-12-11 16:49 UTC, baptou12 commented on lib/state/blocks.ts
> +                  IndividuMethods.isOver8YearsOld(
Pas 100% lié mais on est sûr de pourquoi on a la condition `> 8` ? ça pourrait simplifier des trucs.

2023-12-11 16:49 UTC, baptou12 commented on lib/individu.ts
> +    return this.age(individu, dateDeReference) <= 28 + optionCounter
Je comprend pas du tout le "PlusOption" lié au nombre d'enfant ?

2023-12-11 17:32 UTC, Shamzic commented
> J'avoue les dernière modifs lié aux changements que tu voulais faire. Si on veut mettre des méthodes dans individu je pense qu'il vaut mieux les liés aux question : ex: `possiblementACharge` avec la logique dedans.
> 
> p.e. j'ai loupé qqch ?

Je n'ai pas bien compris ta question ?

2023-12-11 17:34 UTC, Shamzic commented on lib/state/blocks.ts
> +                    situation.dateDeValeur
Je ne sais pas pourquoi il était là mais oui il n'est pas nécessaire

2023-12-11 17:35 UTC, Shamzic commented on lib/state/blocks.ts
> +                  IndividuMethods.isOver8YearsOld(
Je n'ai pas d'information sur ça, je l'ai laissé car il est présent historiquement.

(j'imagine que c'est pour éviter de poser la question du RBG trop complexe à des enfants trop jeunes ?)

2023-12-11 17:37 UTC, Shamzic commented on lib/individu.ts
> +    return this.age(individu, dateDeReference) <= 28 + optionCounter
C'est la [condition de la BCS](https://www.service-public.fr/particuliers/vosdroits/F12214) :

![image](https://github.com/betagouv/aides-jeunes/assets/18016058/1ea08551-a3e6-4609-b7b3-2afe26927bc0)

Mais il est probable que ce code soit mal nommé et pas au meilleur endroit, ouvert aux suggestions

2023-12-11 17:51 UTC, baptou12 commented on lib/state/blocks.ts
> +                  IndividuMethods.isOver8YearsOld(
Là on est pas au niveau du RBG mais plus de enfant à charge ou non. Mais ok pour laisser si c'était là, du moins tant qu'on a pas plus d'info

2023-12-11 17:53 UTC, baptou12 commented on lib/individu.ts
> +    return this.age(individu, dateDeReference) <= 28 + optionCounter
ouais là en premiere lecture ça fait vraiment additionner des choux et des carotes je trouvais.

2023-12-12 13:52 UTC, baptou12 requested changes
Ok avec la nouvelle notion de `BCSAgeCondition`, 
En revanche je trouve toujours que les premiers changement sur `enfant_a_charge` et `scolarité` ne me semble pas utile et/ou pas bon : 
- On perd en lisibilité sans gagner sur d'autre plan AMA
- On a des terme qui sont selon moi faux : `isDependantChild` n'est pas le bon terme vu que à partir de 16 ans on peut deja être indépendant. Dans le pire des cas je mettrais : isPossiblyADependantChild ? Mais ans l'ideal je remettrais l'inégalité quon avait

2023-12-12 13:58 UTC, Shamzic commented
> Ok avec la nouvelle notion de `BCSAgeCondition`, En revanche je trouve toujours que les premiers changement sur `enfant_a_charge` et `scolarité` ne me semble pas utile et/ou pas bon :
> 
> * On perd en lisibilité sans gagner sur d'autre plan AMA
> * On a des terme qui sont selon moi faux : `isDependantChild` n'est pas le bon terme vu que à partir de 16 ans on peut deja être indépendant. Dans le pire des cas je mettrais : isPossiblyADependantChild ? Mais ans l'ideal je remettrais l'inégalité quon avait

Oui je pense que je vais supprimer cette refacto car elle n'est finalement pas dans le sujet initial de cette PR (contrairement à ce que je pensais initialement)

2023-12-12 14:39 UTC, merged