Répare le lien dans le header de l'iframe
betagouv/aides-jeunes pull request #4105
Opened 2023-12-11 15:37 UTC by baptou12

Note: on ne peut pas ouvrir directement de lien d'un autre site dans un iframe.
De manière générale autant que ce soit dans un nouvel onglet.

2023-12-11 17:06 UTC, Shamzic commented
Ok pour le code. 

Du point de vue produit, je ne sais pas on veut une ouverture d'un nouvel onglet quand on clique ici donc j'aurais tendance à ajouter une condition d'être dans une iframe pour le `target="_blank"` et conserver l'ouverture sur la même page si on est pas dans l'iframe. Qu'est-ce que tu en penses ?

2023-12-11 17:50 UTC, baptou12 commented
Je suis à l'aise avec le fait d'avoir le target blank tout le temps, c'est un site externe au simulateur, et comme ça l'usager ne perd pas sa page du simulateur juste parce que 1j1s est un labyrinthe. 
Après jsuis pas fermé à faire la modif, @guillett un avis ?

2023-12-12 10:33 UTC, baptou12 commented
> Je suis à l'aise avec le fait d'avoir le target blank tout le temps, c'est un site externe au simulateur, et comme ça l'usager ne perd pas sa page du simulateur juste parce que 1j1s est un labyrinthe. Après jsuis pas fermé à faire la modif, @guillett un avis ?

Je suis parti sur target blank seulement pour l'iframe

2023-12-12 11:11 UTC, Shamzic requested changes

2023-12-12 11:11 UTC, Shamzic commented on src/components/1j1s/header-1j1s.vue
> +                :target="openInNewTab ? '_blank' : '_self'"
openInNewTab n'est pas déclaré dans ce composant, cependant on peut faire plus simple : 

```suggestion
                :target="store.inIframe ? '_blank' : '_self'"
```

2023-12-12 13:19 UTC, baptou12 commented on src/components/1j1s/header-1j1s.vue
> +                :target="openInNewTab ? '_blank' : '_self'"
Ok comme le store est deja utilisé je vais faire ça. en revanche, je pense qu'on pourrait a terme : 
- supprimer la dependance au store dans ce composant pour le rendre juste fonctional
- déclarer le props `collapse` (j'avoue j'ai utilisé l'existant qui n'est pas fou même si ça marche). 

Je simplifie la PR en faisant ce que tu dis

2023-12-12 13:29 UTC, Shamzic approved these changes

2023-12-12 13:45 UTC, merged