Rends argument optionnel pour éviter warning typescript - mutualized-step
betagouv/aides-jeunes pull request #4109
Opened 2023-12-12 15:12 UTC by Shamzic

[Tâche Trello ](https://trello.com/c/qgT7fRcK/1542-erreur-argument-manquant-dans-une-m%C3%A9thode-du-composant-mutualized-step)

Correction d'un warning typescript

2023-12-12 16:47 UTC, baptou12 requested changes

2023-12-12 16:47 UTC, baptou12 commented on src/lib/hint.ts
> +  get(attribute: string, variation?: string): string {
D'un coté ça fonctionne et ça fait un warning en moins, de l'autre ce warning nous montrait un truc un peu tordu dans l'utilisation de ce `Hint`.

Là ça fonctionne seulement parce que on a qu'un seul text qui utilise des variations (handicap [ici](https://github.com/betagouv/aides-jeunes/blob/b177d076e886531e4b22569b631e7249e40974eb/lib/properties/individu-properties.ts#L392-L403)) et que celui ci marche si on passe `undefined` en variation. 

Par ailleurs, en creusant j'ai remarqué qu'on avait même pas besoin de ce `Hint.get` dans `MutualizedStep` : 
On l'utilise pour le transmettre à `MutualizedStepTitle` pour afficher ou non `EnSavoirPlus`. Mais si `Hint.get` renvoi rien, `EnSavoirPlus` ne va s'afficher. 

Donc je me dis autant virer toutes cette logique ? comme je fais [là](https://github.com/betagouv/aides-jeunes/commit/139ee5a1d91a7b619611da3a20c4827e26875635) et garder variation mandatory (ça évitera de l'utiliser ligne 26 alors qu'il est optionnel)

2023-12-12 16:51 UTC, baptou12 commented on src/lib/hint.ts
> +  get(attribute: string, variation?: string): string {
Note: avec mon truc on perd la logique `...executeFunctionOrReturnValue...` je cherche a quoi ça sert là, mais au pire on peu la garder et juste enlevé la conjonction avec le `Hint.get` qui est deja dans le en savoir plus

2023-12-12 16:57 UTC, baptou12 commented on src/lib/hint.ts
> +  get(attribute: string, variation?: string): string {
Donc au final juste ça ? https://github.com/betagouv/aides-jeunes/commit/e26ee39475f6a004f0e5c8427607bac3e02912be

2023-12-13 10:00 UTC, Shamzic commented on src/lib/hint.ts
> +  get(attribute: string, variation?: string): string {
Ah oui je m'attendrais pas à toute cette réflexion! Je vais étudier un refacto de tout ça alors

2023-12-13 13:00 UTC, merged