Refactor listes des aides
betagouv/aides-jeunes pull request #4121
Opened 2023-12-15 15:40 UTC by Shamzic

Refacto en préparation de la fusion des aides Bafa sur la page de résultats

2023-12-16 09:49 UTC, baptou12 commented on src/views/simulation/resultats.vue
> +      <benefits-list :benefits="benefits" />
Le nom du tag c'est plutôt `BenefitsList` non ?

2023-12-16 10:03 UTC, baptou12 requested changes
Cool en tout cas :-)

2023-12-18 09:55 UTC, Shamzic commented on src/views/simulation/resultats.vue
> +      <benefits-list :benefits="benefits" />
Les deux fonctionnent

2023-12-18 10:39 UTC, Shamzic commented on src/components/droits-details.vue
> +import useUtils from "@/composables/use-utils.js"
Oui, c'est sûrement plus adapté et réutilisable dans lib en plus

2023-12-18 11:34 UTC, baptou12 commented on src/views/simulation/resultats.vue
> +      <benefits-list :benefits="benefits" />
yes mais c'est dommage d'utiliser de cette manière qu'a un seul endroit dans le code, d'autant que la déclaration du component en dessous est `BenefitsList`, non ?

2023-12-19 09:51 UTC, baptou12 requested changes
Au cas où car je suis pas sûr que tu ai vu le comment d'hier

2023-12-19 12:53 UTC, Shamzic commented on src/views/simulation/resultats.vue
> +      <benefits-list :benefits="benefits" />
J'ai fait une tâche Trello pour tout uniformiser en PascalCase car c'est ce qui est recommandé dans la doc : https://trello.com/c/F7CkwFEf/1562-refacto-les-tags-vue-en-pascalcase

2023-12-19 14:04 UTC, baptou12 commented on src/views/simulation/resultats.vue
> +      <benefits-list :benefits="benefits" />
Ah `router-link` pour le coup comme c'est un composant vue et non un custom je l'aurais p.e. laisser comme ça, mais comme tu veux !

Là c'était surtout pour garder uniforme deja sur nos composant à nous.

2023-12-19 14:15 UTC, baptou12 approved these changes

2023-12-19 14:23 UTC, merged