Ajoute un thème pour Soliguide
betagouv/aides-jeunes pull request #4211
Opened 2024-02-16 10:24 UTC by guillett

2024-02-21 11:06 UTC, Shamzic commented
Nécessite le merge de la PR https://github.com/betagouv/aides-jeunes/pull/4210

2024-02-21 14:40 UTC, Shamzic requested changes
Il y a un petit soucis d'affichage sur les input avec la classe `--background-contrast-info` qui peut être visible en sélectionnant une suggestion pré-enregistrée par le navigateur. On a le background en bleu foncé sur un texte noir. Peut-être que ce serait bien de surcharger cette classe avec un fond plus clair.

![input-bleu-fonce](https://github.com/betagouv/aides-jeunes/assets/18016058/34f7a064-a9b9-4027-b6da-12f44578e380)

2024-02-21 14:49 UTC, Shamzic commented on src/styles/themes/soliguide.css
> +  --info-main-color-active: grey;
Je n'ai pas de souvenir ni réussi à déterminer où est-ce que cela aurait pu être utilisé non plus... 💭

2024-02-21 15:08 UTC, Shamzic commented
On pourrait ajouter (ici ou dans une autre PR) ceci dans le fichier de css principal pour que la couleur de la bulle Chatwoot corresponde au thème de l'iframe :
```css
.woot-widget-bubble {
  background: var(--main-color) !important;
}
```

2024-03-04 16:45 UTC, guillett commented
Pour l'application du thème à Chatwoot, je me dis qu'on pourrait plutôt éviter l'affichage du support en iframe (pour éviter de faires le support d'autres sites - au moins pour le moment).

2024-03-04 16:46 UTC, guillett commented
@Shamzic est ce que je te laisse review ou je rebase pour gérer les conflits ?

2024-03-04 17:46 UTC, Shamzic commented
> @Shamzic est ce que je te laisse review ou je rebase pour gérer les conflits ?

Tu peux rebase à souhait 👍

2024-03-04 17:47 UTC, Shamzic commented
> Pour l'application du thème à Chatwoot, je me dis qu'on pourrait plutôt éviter l'affichage du support en iframe (pour éviter de faires le support d'autres sites - au moins pour le moment).

Tout à fait!

2024-03-06 09:50 UTC, Shamzic commented
En attendant le rebase, je valide le choix des couleurs pour le composant "en savoir plus" 👍

2024-03-07 17:39 UTC, Shamzic approved these changes

2024-03-08 09:17 UTC, merged