Simplifie le backbutton
betagouv/aides-jeunes pull request #4215
Opened 2024-02-16 16:06 UTC by guillett

2024-02-20 10:19 UTC, Shamzic requested changes
Le label du bouton de retour dans la page des détails d'une aide devrait afficher "Retour aux aides BAFA et BAFD" à la place de "retour aux résultats" lorsqu'on vient de la page de la liste des aides bafa fusionnées.

Suggestion du label dans resultats-detail où la condition du if pourrait être mutualisée dans une autre méthode car elle est aussi utilisée dans le onMounted : 

```js
const backButtonLabel = computed(() => {
  if (
    ABTestingService.getValues().aides_bafa === "aides_bafa_fusionnees" &&
    benefit.value &&
    hasBafaInterestFlag(benefit.value) &&
    hasBenefitsGroup.value === true
  ) {
    return "Retour aux aides BAFA et BAFD"
  } else {
    return "Retour aux résultats"
  }
})
```

2024-02-20 10:36 UTC, Shamzic commented on src/components/buttons/back-button.vue
> +    default: null,
Ici, j'aurais tendance à mettre une route par défaut valide :
```suggestion
    default: '/simulation/resultats',
```

2024-02-20 10:38 UTC, Shamzic commented on src/views/simulation/resultats/lieu-informations.vue
> +  : null
Ici un computed me paraît plus juste, avec une route par défaut valide

2024-03-04 15:19 UTC, guillett commented
J'ai l'impression qu'il y a des liens / dépendances avec ta PR #4170 donc je mets ça en attente pour le moment.

2024-03-07 13:53 UTC, guillett commented
Je préfère garder l'absence de redirection par défaut pour ne pas cacher les soucis sous le tapis.
Tu voudrais que j'inclus un message Sentry en cas de blocage ?

2024-03-08 09:18 UTC, Shamzic requested changes

2024-03-08 09:18 UTC, Shamzic commented on src/components/buttons/back-button.vue
> +      Sentry.captureMessage("No fallback route to go back")
Il manque l'import Sentry dans ce fichier

2024-03-08 09:18 UTC, Shamzic commented on src/components/buttons/back-button.vue
> +    window.history.state?.position === 0
Le 3e argument de trackEvent doit être de type string

2024-03-08 09:52 UTC, Shamzic commented on src/views/simulation/resultats/resultats-detail.vue
> +  return `Retour aux ${benefit.value.groupLabel || "résultats"}`
`benefit.value` peut être undefined ici

2024-03-12 14:59 UTC, guillett commented on src/views/simulation/resultats/resultats-detail.vue
> +  return `Retour aux ${benefit.value.groupLabel || "résultats"}`
:pray:

2024-03-12 15:13 UTC, Shamzic submitted a review, later dismissed
Ok pour moi 👍

2024-03-12 15:33 UTC, guillett commented
On va merger tes PR refacto résultats pour éviter de te mettre des obstacles supplémentaires.

2024-03-27 14:03 UTC, Shamzic commented
C'est toujours ok pour moi,  il reste juste un petit conflit avec tes dernières modifications dans le store des résultats

2024-04-02 14:49 UTC, Shamzic approved these changes
J'ai essayé d'être exhaustif durant mes tests manuels et les comportements du bouton de retour semblent cohérents et isofonctionnels. J'imagine qu'un petit test e2e ou de composant aurait pu aussi être bénéfique sur le long terme. C'est bon pour moi

2024-04-03 07:52 UTC, merged