Draft moncomptepro, problème de CORS
betagouv/aides-jeunes pull request #4251
Opened 2024-03-20 08:48 UTC by Shamzic

Erreur de CORS la requête `https://app-sandbox.moncomptepro.beta.gouv.fr/oauth/authorize?...` depuis le serveur local sur le port 8080

2024-03-22 10:48 UTC, guillett commented
Petit point partage d'intuition, je m'attends à ce que cette PR fasse « diminuer le nombre de lignes ». C'est bien évidemment une règle bancale mais vu qu'une dépendance est utilisée, je m'attends à ce que la taille du code qu'on maintient diminue.

C'est une remarque que je me fais quand je réaliste la revue et je trouve que ça a de la valeur. En particulier pour reposer la question, est ce que j'ai bien tout enlevé/remplacé.

2024-03-22 13:45 UTC, jenovateurs reviewed
Voici une première relecture pour moi.
Il y a beaucoup de questions mais cela me permet de mieux comprendre le fonctionnement du service.

2024-03-22 13:45 UTC, jenovateurs commented on backend/config/index.ts
> +      "https://app-sandbox.moncomptepro.beta.gouv.fr/oauth/authorize",
Je me demande s'il ne faudrait pas mettre une base URI sandbox en env et ensuite des env sur les slug associés (authorize, userinfo, ...)

2024-03-22 13:45 UTC, jenovateurs commented on backend/config/index.ts
> +    authorized_email_users: ["user@yopmail.com"],
Est-ce que cette config va être uniquement utilisée dans un environnement de test ?

2024-03-22 13:45 UTC, jenovateurs commented on backend/controllers/moncomptepro.ts
> +        return res.redirect("/accompagnement?unauthorized")
C'est une redirection sur AidesJeunes ? Sinon peut-être mettre l'url en config.

2024-03-22 13:45 UTC, jenovateurs commented on backend/controllers/moncomptepro.ts
> +        throw new Error("No userInfo email")
L'erreur est catchée quelque part pour un affichage utilisateur ?

2024-03-22 13:45 UTC, jenovateurs commented on backend/controllers/moncomptepro.ts
> +        res.cookie("mcp_token", mcpToken)
Que penses-tu de créer une constante pour ce nom de cookie ?

2024-03-22 13:45 UTC, jenovateurs commented on backend/controllers/moncomptepro.ts
> +    console.error("Error in access:", error)
La console.error est catché par Sentry ?

2024-03-22 13:45 UTC, jenovateurs commented on src/styles/aides-jeunes.css
> +  background-image: url(data:image/svg+xml;charset=utf8,%3Csvg%20width%3D%2235%22%20height%3D%2236%22%20viewBox%3D%220%200%2035%2036%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000
Pourrais-tu plutôt stocker le fichier svg dans un dossier public au lieu de l'intégrer directement dans la feuille de style et de l'importer uniquement lorsque tu en as besoin ? 
Cela pourrait aussi te permettre d'éviter d'utiliser le mot-clé !important.

2024-03-22 13:45 UTC, jenovateurs commented on src/views/accompagnement/accompagnement.vue
> +    <!-- Not used for now -->
Y-a-t-il une recommendation particulière sur le fait de laisser des commentaires de code pour plus tard ?

2024-03-25 15:38 UTC, Shamzic commented on backend/config/index.ts
> +      "https://app-sandbox.moncomptepro.beta.gouv.fr/oauth/token",
Oui, j'ai repris la façon dont c'était fait pour la propriété `github`. C'est juste pour l'ajout dans le `.env` car ces urls, contrairement à celles de github, vont varier selon l'environnement.

2024-03-25 15:41 UTC, Shamzic commented on backend/controllers/github.ts
> -
La connexion à github n'était autorisée que pour les aidants (auparavant les devs et bizdevs de l'équipe) sur la page `/accompagnement`. L'objectif à terme est d'autoriser cette page d'accompagnement à tous les aidants internes ou externes via une auth moncomptepro à la place.

2024-03-25 15:43 UTC, Shamzic commented on backend/config/index.ts
> +    authorized_email_users: ["user@yopmail.com"],
`userinfo_signed_response_alg` ne me paraît pas utile pour cette PR (je pense que je vais le supprimer).
`scope` sera probablement le même quel que soit l'environnement.
`authorized_email_users` sera différent

2024-03-25 15:48 UTC, Shamzic commented on backend/controllers/moncomptepro.ts
> +        throw new Error("No userInfo email")
Non, elle est catch et log en console uniquement

2024-03-25 15:48 UTC, Shamzic commented on backend/controllers/moncomptepro.ts
> +        res.cookie("mcp_token", mcpToken)
Que c'est une bonne pratique 👍

2024-03-25 15:50 UTC, Shamzic commented on backend/controllers/moncomptepro.ts
> +    console.error("Error in access:", error)
Non, il faut explicitement faire un call Sentry pour que ça soit pris en compte. Je peux en faire un ici

2024-03-25 15:53 UTC, Shamzic commented on src/styles/aides-jeunes.css
> +  background-image: url(data:image/svg+xml;charset=utf8,%3Csvg%20width%3D%2235%22%20height%3D%2236%22%20viewBox%3D%220%200%2035%2036%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000
Je pourrais oui, j'avoue que je n'y ai pas trop réfléchi car c'était demandé dans le [readme de moncomptepro](https://github.com/betagouv/moncomptepro).

2024-03-25 16:51 UTC, Shamzic commented on backend/config/index.ts
> +      "https://app-sandbox.moncomptepro.beta.gouv.fr/oauth/token",
J'ai refacto et supprimé certaines uri de cette partie

2024-03-25 17:00 UTC, Shamzic commented on backend/config/index.ts
> +      "https://app-sandbox.moncomptepro.beta.gouv.fr/oauth/authorize",
Ces uri ayant des endpoints normés, ils sont appelés directement par la lib `openid-client` que j'ai utilisées dans le controller, ça m'a permis de refacto et supprimer ces deux variables

2024-03-25 17:00 UTC, Shamzic commented on backend/config/index.ts
> +    authorized_email_users: ["user@yopmail.com"],
j'ai refacto et supprimé `userinfo_signed_response_alg`

2024-03-25 17:20 UTC, Shamzic commented on backend/controllers/moncomptepro.ts
> +        return res.redirect("/accompagnement?unauthorized")
Je l'ai mise en config

2024-04-01 13:39 UTC, jenovateurs requested changes

2024-04-01 13:39 UTC, jenovateurs commented on backend/config/index.ts
> +    authorized_email_users: ["user@yopmail.com"],
Je suppose que ce n'est pas du yopmail qui va être utilisé.

2024-04-01 13:39 UTC, jenovateurs commented on backend/controllers/moncomptepro.ts
> +    console.error("Error in access:", error)
Cela peut-être utile non ?

2024-04-02 09:30 UTC, Shamzic commented on backend/controllers/moncomptepro.ts
> +    console.error("Error in access:", error)
C'est corrigé

2024-04-02 09:33 UTC, Shamzic commented on backend/config/index.ts
> +    authorized_email_users: ["user@yopmail.com"],
Non, pour la partie autorisation, je ne suis pas encore certain sur la façon de configurer tout ça. Pour le moment c'est la config par défaut qui fonctionne en mode test

2024-04-03 09:42 UTC, guillett commented on backend/config/index.ts
> +    authorized_email_users: ["user@yopmail.com"],
Le suivi des accès est un sujet important en sécurité.
Dans un premier temps, les emails peuvent être versionnés (ce seront nos emails à nous).

Dans un second temps, on pourrait imaginer la récupération des emails depuis une source sécurisée avec historisation (un dépôt github privé).

2024-04-04 10:26 UTC, guillett approved these changes
J'ai fait un commit avec des modifications. Pour moi c'est bon en l'état.

2024-04-05 08:14 UTC, Shamzic commented on src/styles/aides-jeunes.css
> +  background-image: url(data:image/svg+xml;charset=utf8,%3Csvg%20width%3D%2235%22%20height%3D%2236%22%20viewBox%3D%220%200%2035%2036%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000
J'ai fait la modif

2024-04-05 08:18 UTC, Shamzic commented
@jenovateurs j'ai pris en compte tes remarques, toujours ouvert si tu as d'autres suggestions

2024-04-09 08:23 UTC, jenovateurs approved these changes

2024-04-09 14:58 UTC, merged