Ajouter des informations complémentaires sur la saisie des revenus
betagouv/aides-jeunes pull request #4254
Opened 2024-03-22 10:48 UTC by jenovateurs

2024-03-22 11:50 UTC, Shamzic commented
Il existe la commande `npm run format` qui va check et corriger automatiquement les erreurs eslint et prettier

2024-03-22 15:03 UTC, jenovateurs commented
Merci @Shamzic pour la recommandation, j'ai lancé la commande et push :-)

2024-03-22 15:10 UTC, guillett commented
@Shamzic est ce que je peux te laisser faire une première passe et j'en ferai une seconde ?

2024-03-22 16:02 UTC, Shamzic requested changes
J'aurais apprécié avoir une petite spécification de la tâche en description. Est-ce que la finalité de la tâche était bien une alert qu'on voulait ou bien une question sans réponse avec un message informatif juste avant de renseigner les montants ?

Dans le contexte de tes modifications, on a plutôt les ressources du demandeur en `1`, puis éventuellement celles de chaque enfant en `2`. Après on peut aussi prévenir qu'il va falloir renseigner le RFR / RBG des parents en `3` mais j'ai peur que ça ne soit pas le meilleur endroit pour cette info car c'est placé dans la partie `revenus/types` et `revenus/montants`.

2024-03-22 16:02 UTC, Shamzic commented on src/components/ressource/types.vue
> +      </ol>
Pour la formulation j'aurais suggéré : 

```
Nous aurons besoin des ressources de : : 
- Vous-même
- Votre conjointe ou conjoint
- Celles de prénom_enfant_1
- Celles de prénom_enfant_2
```

2024-03-22 16:12 UTC, guillett commented
> J'aurais apprécié avoir une petite spécification de la tâche en description. Est-ce que la finalité de la tâche était bien une alert qu'on voulait ou bien une question sans réponse avec un message informatif juste avant de renseigner les montants ?

Sur cette partie comme (maladroitement) dit en rétro par moi-même, on a effectivement simplifié la tâche en modifiant une pagen existante plutôt qu'en créant une nouvelle page en amont de celle modifiée dans cette PR.

Ces travaux et les apprentissages associés seront facilement transférables si, dans une nouvelle PR, on choisit de créer une page en amont.

2024-03-22 16:23 UTC, guillett commented
@jenovateurs je te propose qu'on pair un peu lundi matin sur cette PR si tu veux.

2024-03-25 13:44 UTC, jenovateurs commented
Point réalisé ce matin avec @guillett  afin d'affiner la PR. 
Je vais me baser sur le système d'étape pour mieux identifier les prochains éléments à remplir et retravailler le contenu éditorial.

2024-03-26 16:18 UTC, jenovateurs commented
Point réalisé ce matin avec @guillett concernant l'affichage du message conditionné sur la saisie des revenus des parents.
J'ai ajouté une condition provenant du fichier blocks.

2024-03-27 15:12 UTC, jenovateurs commented
PR liée à un problème d'affichage/collecte de données de revenus - https://github.com/betagouv/aides-jeunes/pull/4101
Nouvelle mise à jour faite pour afficher le message de saisie de revenus des parents par rapport à  bourse_criteres_sociaux_base_ressources_parentale et parents / rfr.

2024-04-09 12:53 UTC, jenovateurs commented on src/components/ressource/types.vue
> +      </ol>
J'ai simplifié l'affichage, est-ce que cela te paraît suffisant ? @Shamzic

2024-04-10 08:11 UTC, Shamzic commented on src/components/ressource/types.vue
> +        Vous devez d'abord saisir vos revenues<span v-if="needCoupleResources"
```suggestion
        Vous devez d'abord saisir vos revenus<span v-if="needCoupleResources"
```

2024-04-10 08:24 UTC, Shamzic reviewed
Il manque toujours l'information de remplissage sur les enfants, cela dit, il y a une question pour savoir si l'enfant a perçu des revenus depuis X temps juste avant le remplissage de ses revenus.. Je suis indécis sur la question

2024-04-10 08:28 UTC, jenovateurs commented
Un avis sur la question https://github.com/betagouv/aides-jeunes/pull/4254#pullrequestreview-1991083287 @guillett ?

2024-04-10 14:06 UTC, jenovateurs commented
> Il manque toujours l'information de remplissage sur les enfants, cela dit, il y a une question pour savoir si l'enfant a perçu des revenus depuis X temps juste avant le remplissage de ses revenus.. Je suis indécis sur la question

Je t'ai fait une nouvelle proposition de message.

2024-04-10 14:52 UTC, Shamzic commented on src/components/ressource/types.vue
> +        Vous devez d'abord saisir vos revenus
Autre suggestion avec **vos** en gras : 

> Pour cette question, seules **vos** ressources personnelles sont à considérer.

> Les ressources perçues par X,Y et Z seront demandées plus tard dans le simulateur.

2024-04-11 14:35 UTC, jenovateurs commented on src/components/ressource/types.vue
> +        Vous devez d'abord saisir vos revenus
Nouvelle proposition :-)
<img width="891" alt="Screenshot 2024-04-11 at 16 35 39" src="https://github.com/betagouv/aides-jeunes/assets/3491729/29487c8e-2de3-4ad6-ae7b-a950f954939a">

2024-04-12 15:32 UTC, Shamzic reviewed
Ça me semble pas mal. Je ne pensais pas qu'on mettrait une carte d'alerte ici mais au moins ça accentue la visibilité. 
(J'aurais juste mis une petite marge entre l'alerte et le titre du dessous pour aérer un peu)

2024-04-18 08:49 UTC, jenovateurs commented
Suggestions intégré @guillett . Merci pour ton aide. Preneur d'une nouvelle relecture.

2024-04-22 22:31 UTC, Shamzic approved these changes
Ok pour moi modulo ma remarque sur l'ordre d'affichage des entités dans l'alert

2024-04-22 22:31 UTC, Shamzic commented on src/components/ressource/types.vue
> +      }
J'aurais inversé l'ordre de ces deux conditions car les ressources des enfants sont demandées avant celles des parents

2024-04-23 08:38 UTC, Shamzic commented on src/components/ressource/types.vue
> +      }
✅

2024-04-23 12:06 UTC, jenovateurs commented on src/components/ressource/types.vue
> +      }
Correction faite ✅

2024-04-23 12:43 UTC, guillett commented on src/components/ressource/types.vue
> +        this.individu._role === "demandeur" && this.aditionnalResources.length
> additional resources

2024-04-23 13:21 UTC, guillett commented
J'ai fait la PR #4304 avec des suggestions de refacto.

2024-04-25 07:25 UTC, merged