Ajoute une reformulation de la question sur l'inscription à France Travail avec de l'AB test
betagouv/aides-jeunes pull request #4256
Opened 2024-03-22 16:05 UTC by guillett

Repose sur #4255.
Réalise https://trello.com/c/4lLcl08N/1631-reformuler-quand-avez-vous-commenc%C3%A9-%C3%A0-%C3%AAtre-au-ch%C3%B4mage-en-depuis-quand-%C3%AAtes-vous-inscrit-%C3%A0-france-travail

La comparaison de cette PR c'est pas chômage versus France Travail mais « avoir le chômage » et « être inscrit ».

2024-03-26 14:34 UTC, Shamzic requested changes

2024-03-26 14:34 UTC, Shamzic commented on src/plugins/ab-testing-service.ts
> +    (Math.random() > 0.5 ? "reformulation" : "actuelle")
Peut-être que ce serait bien d'utiliser des noms un petit peu plus explicites, `actuelle_chomage` / `reformulation_france_travail` par exemple ?

2024-03-26 14:34 UTC, Shamzic commented on lib/properties/individu-properties.ts
> +      const version = abtestingEnvironment.question_debut_chomage
Pour que ce soit fonctionnel, il faut passer par la propriété `value` ici :
 ```suggestion
       const version = abtestingEnvironment.question_debut_chomage.value
```

2024-04-02 12:23 UTC, guillett commented on src/plugins/ab-testing-service.ts
> +    (Math.random() > 0.5 ? "reformulation" : "actuelle")
J'avais modifié la reformulation pour ne pas opposer « avoir le chômage » et « être inscrit à France Travail » mais « avoir le chômage » et « être inscrit au chômage » mais en réalité la formulation « être inscrit au chômage » ne me parait pas très naturel.

2024-04-02 13:04 UTC, Shamzic approved these changes
Ok pour moi
![image](https://github.com/betagouv/aides-jeunes/assets/18016058/354260ea-9e74-428c-b2ff-0e78293b4439)
![image](https://github.com/betagouv/aides-jeunes/assets/18016058/80c0fea2-ac02-424c-9b4c-83469cfd18fe)
(Au passage, je remarque qu'on peut inscrire une date inférieure à sa date de naissance, ce qui est impossible)

2024-04-02 14:36 UTC, merged