Refacto git mv controller/routes github -> moncomptepro + fix imports
betagouv/aides-jeunes pull request #4258
Opened 2024-03-25 17:51 UTC by Shamzic

Permet de réduire le diff de la PR https://github.com/betagouv/aides-jeunes/pull/4251

2024-04-01 08:04 UTC, jenovateurs requested changes

2024-04-01 08:04 UTC, jenovateurs commented on backend/routes/support.ts
> -import githubController from "../controllers/github.js"
Cette PR n'est pas mergeable sur le main uniquement sur l'autre PR ? car pour la partie config/constante ça ne change pas grand chose sur l'aspect fonctionnel contrairement au fichier renommé en moncompteperso on risque de s'y perdre dans les noms.

2024-04-01 08:38 UTC, Shamzic commented on backend/routes/support.ts
> -import githubController from "../controllers/github.js"
Cette PR est mergeable sur main. J'ai déplacée ce renommage uniquement pour réduire le diff sur l'autre PR car il y avait du renommage + modifications, ce qui pouvait porter à confusion pour la review pour Thomas. Si toi ça ne te dérange pas, je peux tout refusionner, ça me va très bien aussi

2024-04-01 09:03 UTC, jenovateurs commented on backend/routes/support.ts
> -import githubController from "../controllers/github.js"
Ca ne me dérange pas d'avoir tout dans une PR.

2024-04-04 12:50 UTC, guillett commented
Pour moi cette PR peut être, du coup, fermée.

2024-04-04 12:59 UTC, closed without merging