Ajoute la feature pour revenir plus tard sur une simulation en cours v2
betagouv/aides-jeunes pull request #4275
Opened 2024-04-05 14:13 UTC by Shamzic

Remplace la [PR](https://github.com/betagouv/aides-jeunes/pull/4198) pour simplifier le rebase

2024-04-05 18:19 UTC, Shamzic commented on backend/controllers/followups.ts
> +    } else {
Ça c'est pas trop SRP compliant placé ici, ce serait peut être bien de le déplacer ailleurs

2024-04-10 15:09 UTC, Shamzic commented
Modification à effectuer: déplacer le bouton "revenir plus tard" à la place de l'ancien bouton "je donne mon avis", conserver le fonctionnement actuel des boutons de navigation

2024-04-12 16:18 UTC, jenovateurs requested changes
Première relecture de code.
Je vais tester en local

2024-04-12 16:18 UTC, jenovateurs commented on backend/controllers/followups.ts
> +  const simulationRecapUrl = `${process.env.MES_AIDES_ROOT_URL}/s/t/${followup.accessToken}`
C'est plus une question, pourquoi ne pas utiliser config.baseURL ? Je vois que MES_AIDES_ROOT_URL est beaucoup utilisé dans le projet.

2024-04-12 16:18 UTC, jenovateurs commented on backend/controllers/followups.ts
> +      console.log("TrackClickTemporarySimulationLink")
Oubli de suppression de log ?

2024-04-12 16:18 UTC, jenovateurs commented on src/styles/aides-jeunes.css
> +@media (max-width: 480px) {
Le point de rupture ne correspond pas au DSFR - https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/grille-et-points-de-rupture
As-tu une contrainte spécifique ?

2024-04-12 16:18 UTC, jenovateurs commented on src/views/simulation/revenir-plus-tard.vue
> +      Vous avez un point de blocage ou vous souhaitez remettre à plus tard la
Je me questionne sur "un point de blocage" : 
- Vous êtes bloqué 
- Il vous manque une information

2024-04-12 16:18 UTC, jenovateurs commented on src/views/simulation/revenir-plus-tard.vue
> +        ><p>Votre simulation a bien été sauvegardée. </p>
```suggestion
        ><p>Votre simulation a bien été sauvegardée.</p>
```

2024-04-12 16:43 UTC, jenovateurs requested changes

2024-04-12 16:43 UTC, jenovateurs commented on src/components/titre-chapitre.vue
> +          >Revenir plus tard?
```suggestion
          >Revenir plus tard ?
```

2024-04-12 16:43 UTC, jenovateurs commented on src/components/titre-chapitre.vue
> +          >Revenir plus tard?
Note en plus : 
Je saisis ma date de naissance, puis je clique sur 'Revenir plus tard' avant de cliquer sur 'Poursuivre la simulation'. Je reviens alors sur la page de saisie de la date de naissance, mais les champs sont vidés. Est-il pertinent de stocker la simulation alors que nous sommes à l'étape de la saisie de la date de naissance et que rien n'a été saisi ?

2024-04-12 16:43 UTC, jenovateurs commented on src/components/titre-chapitre.vue
> +      <div v-if="showRevenirPlusTard" class="fr-col-12 fr-col-sm-6">
Il ne faudrait pas utiliser la classe de bouton tertiaire : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/bouton ?

2024-04-12 16:43 UTC, jenovateurs commented on src/views/simulation/revenir-plus-tard.vue
> +        <p>Identifiant de la simulation: {{ simulationId }}</p>
Petite question : sur l'utilité de cette information.

2024-04-12 16:43 UTC, jenovateurs commented on src/components/titre-chapitre.vue
> +          >Revenir plus tard?
Dans ce cas, lorsque je vais sur le lien enregistré, j'ai cette page : 
![image](https://github.com/betagouv/aides-jeunes/assets/3491729/f963e34e-e7fb-42ef-beab-9d0a22e7e51f)

2024-04-12 16:43 UTC, jenovateurs commented on src/components/titre-chapitre.vue
> +          >Revenir plus tard?
Gestion d'erreur brute, si j'ai une erreur de saisie d'url
<img width="532" alt="Screenshot 2024-04-12 at 18 36 27" src="https://github.com/betagouv/aides-jeunes/assets/3491729/e4bb5b10-9989-4314-a1d1-4a65901a3674">

2024-04-12 16:43 UTC, jenovateurs commented on src/components/titre-chapitre.vue
> +          >Revenir plus tard?
Après avoir été sur le lien de la simulation sauvegardée. Le bouton Retour sur le menu de gauche renvoi sur la même page de récapitulatif.

2024-04-12 16:43 UTC, jenovateurs commented on src/components/titre-chapitre.vue
> +          >Revenir plus tard?
Penser à ajouter des tests Cypress.

2024-04-12 16:43 UTC, jenovateurs commented on src/components/titre-chapitre.vue
Le bouton de sauvegarde de la simulation ne fonctionne pas sur le Deploy Netlify.

2024-04-15 14:49 UTC, Shamzic commented on backend/controllers/followups.ts
> +  const simulationRecapUrl = `${process.env.MES_AIDES_ROOT_URL}/s/t/${followup.accessToken}`
Les deux fonctionnent ici. Je vais mettre config.baseURL, autant l'utiliser vu qu'il est déjà importé dans ce fichier et mieux nommé.

2024-04-15 14:53 UTC, Shamzic commented on src/styles/aides-jeunes.css
> +@media (max-width: 480px) {
> As-tu une contrainte spécifique ?

Oui, c'était lié au responsive. Mais ce code est périmé car j'ai déplacé le bouton et les actions-buttons sont à nouveau inchangés. Je supprime 👍

2024-04-15 15:11 UTC, Shamzic commented on src/components/titre-chapitre.vue
> +          >Revenir plus tard?
> Note en plus : Je saisis ma date de naissance, puis je clique sur 'Revenir plus tard' avant de cliquer sur 'Poursuivre la simulation'. Je reviens alors sur la page de saisie de la date de naissance, mais les champs sont vidés. Est-il pertinent de stocker la simulation alors que nous sommes à l'étape de la saisie de la date de naissance et que rien n'a été saisi ?

Bonne réflexion, ce n'est à mon sens pas utile de laisser cette feature dispo pour la première étape

2024-04-15 15:19 UTC, Shamzic commented on src/components/titre-chapitre.vue
> +          >Revenir plus tard?
> Après avoir été sur le lien de la simulation sauvegardée. Le bouton Retour sur le menu de gauche renvoi sur la même page de récapitulatif.

Je pense que c'est un bug des action-buttons, si on ouvre le récapitulatif dans un nouvel onglet et qu'on fait précédent, on retombe à la première page... 🤔

2024-04-15 15:21 UTC, Shamzic commented on src/components/titre-chapitre.vue
Le backend du deploy Netlify n'est pas à jour

2024-04-15 15:23 UTC, Shamzic commented on src/views/simulation/revenir-plus-tard.vue
> +        <p>Identifiant de la simulation: {{ simulationId }}</p>
Je l'ai ajouté pour debug, mais son utilité est questionnable. Je le retire pour le moment

2024-04-15 15:28 UTC, Shamzic commented on src/components/titre-chapitre.vue
> +      <div v-if="showRevenirPlusTard" class="fr-col-12 fr-col-sm-6">
Cela a remplacé le bouton "je donne mon avis" qui avait ce style par défaut avec les router-link, on peut en discuter! 
Moi je trouve que c'est plus discret ainsi (:

2024-04-23 12:42 UTC, guillett commented on backend/controllers/followups.ts
> +      return createSimulationRecapUrl(followup, res)
En fait, je créérai plutôt le followup dans la fonction `createSimulationRecapUrl` plutôt qu'en amont (quand je relis la PR).

2024-04-23 16:27 UTC, Shamzic commented on backend/controllers/followups.ts
> +      return createSimulationRecapUrl(followup, res)
Je l'ai déplacé

2024-04-26 08:48 UTC, jenovateurs commented on src/views/simulation/revenir-plus-tard.vue
> +      Vous avez un point de blocage ou vous souhaitez remettre à plus tard la
C'est mieux je trouve.

2024-04-26 08:53 UTC, guillett commented on src/components/titre-chapitre.vue
> +      <div v-if="showRevenirPlusTard" class="fr-col-12 fr-col-sm-6">
Je trouve que c'est en discret par contre, pour moi, il y a un soucis d'alignement. En l'état le lien est un peu trop « en l'air » sur desktop. Il faudrait aligner à droite selon moi (il me semble que [c'était le cas du bouton JDMA](https://github.com/betagouv/aides-jeunes/pull/4278/files#diff-3b8c413021a4a830a007aa45b48e9254e1326b54c03f9b91ed34dbfe1e70231bL294)).

2024-04-26 08:54 UTC, jenovateurs commented on src/components/titre-chapitre.vue
> +      <div v-if="showRevenirPlusTard" class="fr-col-12 fr-col-sm-6">
On pourra affiner au besoin.

2024-04-26 09:15 UTC, Shamzic commented on src/components/titre-chapitre.vue
> +      <div v-if="showRevenirPlusTard" class="fr-col-12 fr-col-sm-6">
Bien vu, je remet le style

2024-04-28 13:44 UTC, jenovateurs approved these changes

2024-04-28 13:44 UTC, jenovateurs commented on backend/controllers/followups.ts
> +async function sendFollowupNotifications(followup, res: Response) {
Penses-tu que tu pourrais typer le paramètre followup ? Mais c'est non-bloquant.

2024-04-30 10:06 UTC, merged