Ajoute de l'AB testing sur l'envoi de SMS
betagouv/aides-jeunes pull request #4277
Opened 2024-04-05 15:30 UTC by guillett

2024-04-05 15:34 UTC, jenovateurs commented on src/plugins/ab-testing-service.ts
> +  ABTestingEnvironment.Followup_SMS.index = 2
Pourrais-tu m'expliquer le principe des index ? @guillett

2024-04-05 15:36 UTC, guillett commented on src/plugins/ab-testing-service.ts
> +  ABTestingEnvironment.Followup_SMS.index = 2
Il y a 5 _dimensions personnalisées_ sur Matomo. Chacune a un index. On utilise ça pour nos AB tests. https://stats.data.gouv.fr/index.php?module=CustomDimensions&action=manage&idSite=165&period=day&date=yesterday#/list

2024-04-05 15:50 UTC, jenovateurs requested changes

2024-04-05 15:50 UTC, jenovateurs commented on src/components/titre-chapitre.vue
Question/suggestion : faire comme dans la vue recap-email-and-sms et faire une constante showSms pour réduire le if sur le bouton et la modal title

2024-04-05 15:50 UTC, jenovateurs commented on src/components/titre-chapitre.vue
>          : "Recevoir un récapitulatif par email"
Y a un soucis sur le libellé non ? email/SMS pour la ligne 76
et email pour la ligne 75

2024-04-05 15:50 UTC, jenovateurs commented on src/plugins/ab-testing-service.ts
> +  ABTestingEnvironment.Followup_SMS.index = 2
Donc pour ma prochaine PR de regroupement des aides à la mobilité, il sera nécessaire de supprimer un élément qui a été soumis à un test AB ?

2024-04-08 09:06 UTC, guillett commented on src/plugins/ab-testing-service.ts
> +  ABTestingEnvironment.Followup_SMS.index = 2
Oui, aujourd'hui les 5 sont utilisés mais certains peuvent sûrement être analysés puis remplacés.

2024-04-08 13:17 UTC, Shamzic approved these changes
Ok pour moi. 
Je pense que la variable d'env `VITE_SHOW_SMS_TAB` pourrait être supprimée au passage

2024-04-09 08:19 UTC, jenovateurs approved these changes

2024-04-09 08:44 UTC, merged