Répare le site d'expérimentation
betagouv/aides-jeunes pull request #4282
Opened 2024-04-08 16:08 UTC by guillett

2024-04-12 14:12 UTC, Shamzic reviewed
Le calcul de l'aide au logement me semble fonctionnel en local. J'ai simulé une `boucle (dev)` et lancé les calculs pour chaque catégorie de logement. Ok pour le test e2e.

![image](https://github.com/betagouv/aides-jeunes/assets/18016058/852b6846-e8a8-4f9d-9441-4bf62c39863d)

2024-04-12 14:27 UTC, guillett commented on .github/workflows/check-experimental-website.yml
> +    - cron: "0 7 * * 1-5"
Merci pour cette demande de clarification, j'aurais du expliciter ça dans la PR.

Je n'ai pas voulu mettre ce test dans la CI pour ne pas ralentir chaque itération et surtout car il y a une contrainte d'accès à un payload valide (via les artefact GH).

Je me dis que vérifier tous les jours ouvrés est suffisant pour une fonctionnalité expérimentale.

2024-04-12 14:35 UTC, jenovateurs requested changes
Fonctionne bien en local avec Cypress et manuellement.
Il manque juste de la documentation/commentaire pour moi.

2024-04-12 14:35 UTC, jenovateurs commented on cypress/e2e/experimentations.cy.js
> +      : "http://localhost:3000"
Je pense qu'il faudrait ajouter un commentaire ou documentation pour indiquer la nécessiter de lancer le projet en local. On a l'indice du nom du projet (avec la ligne précédente) mais pas du repo.

2024-04-12 14:35 UTC, jenovateurs commented on cypress/e2e/experimentations.cy.js
> +    const text = ghAction ? "en ligne" : "dev"
Plutôt "local" pour reprendre la même terminologie sur le site d'experimentation.
Version : local

2024-04-12 14:45 UTC, guillett commented on cypress/e2e/experimentations.cy.js
> +      : "http://localhost:3000"
L'URL de la GitHub Pages `https://betagouv.github.io/aides-jeunes-experimentations/ quasiment directement l'URL du dépôt `https://github.com/betagouvaides-jeunes-experimentations/` ce n'est pas suffisant selon toi ?

2024-04-12 15:05 UTC, jenovateurs commented on cypress/e2e/experimentations.cy.js
> +      : "http://localhost:3000"
En effet, tu n'as pas tort. Je pousse ma réflexion sur Cypress : cela rajoute de la complexité pour faire les tests en local. Il faut penser à lancer le service si on veut vérifier la CI complete avant de push du code.
Mais je n'ai pas de réel solution...

2024-04-12 15:11 UTC, guillett commented on cypress/e2e/experimentations.cy.js
> +      : "http://localhost:3000"
J'ai fait le choix d'exclure ce test de la CI implémentée dans la GitHub Action. On peut aussi ajouter de la logique pour exclure ce test de `npm run cypress` lancé en local.
Est ce que tu penses que c'est bien de faire ça ?

2024-04-12 15:21 UTC, jenovateurs commented on cypress/e2e/experimentations.cy.js
> +      : "http://localhost:3000"
De mon point de vue, il serait pertinent de le sortir de la logique propre au Cypress local. Est-il intéressant d’intégrer une autre commande pour tester les interactions d'Aides Jeunes avec d'autres services tiers ?

2024-04-12 16:43 UTC, guillett commented on cypress/e2e/experimentations.cy.js
> +      : "http://localhost:3000"
Je pense que c'est important d'avoir ce test lancé régulièrement. Ces fonctionnalités sont de très grandes opportunités. Il faut, selon moi, pouvoir les présenter rapidement et pour cela rien de tels que des tests automatisés.

2024-04-12 16:44 UTC, guillett commented on cypress/e2e/experimentations.cy.js
> +      : "http://localhost:3000"
Je me dis qu'on peut sortir ce test du dossier `cypress/e2e/` et le `cypress/e2e-extra` par exemple.

2024-04-16 08:22 UTC, jenovateurs commented on cypress/e2e/experimentations.cy.js
> +      : "http://localhost:3000"
Je suis ok avec cette proposition. Comme ça pour faire des tests en local rapide, on peux se concentrer sur le dossier e2e uniquement.

2024-04-16 09:07 UTC, guillett commented on cypress/e2e/experimentations.cy.js
> +      : "http://localhost:3000"
Top, j'ai fait la modification.

2024-04-22 13:09 UTC, jenovateurs approved these changes

2024-04-22 13:13 UTC, merged