Permet la prévisualisation dans Decap avec une iframe
betagouv/aides-jeunes pull request #4290
Opened 2024-04-12 15:27 UTC by guillett

2024-04-16 15:08 UTC, jenovateurs requested changes
J'ai fait une première analyse.

2024-04-16 15:53 UTC, Shamzic commented
Je suis en train d'investiguer mais pour le moment je n'arrive pas à afficher la preview dans l'outil

![image](https://github.com/betagouv/aides-jeunes/assets/18016058/88d0c51f-e1ae-49a5-9b2e-3beac816ec74)

2024-04-16 16:21 UTC, Shamzic commented
J'ai refacto la méthode `send` qui posait problème pour moi :

```js
send() {
    const benefitData = this.props.entry.get("data").toJS()
    const institutionSlug = benefitData.institution;
    const institutionData =
      (institutionSlug && institutionsMap[institutionSlug]) || {}
      const { name: institutionName = '' } = institutionData;
      const institution = {
        label: institutionName,
        ...institutionData,
      };
    this.iframe.current.contentWindow.postMessage(
      {
        source: "decap",
        value: {
          ...benefitData,
          institution,
        },
      },
      baseURL,
    )
  }
  ```

2024-04-17 05:28 UTC, guillett commented
Désolé pour le couac sur la fonction `send`.

2024-04-18 08:26 UTC, guillett commented on src/views/preview.vue
> +    :city="'75056'"
Ce n'est pas un code postal mais un code INSEE celui de Paris.
J'ai repris celui utilisé sur les pages /aides/xxx/

2024-04-18 08:26 UTC, guillett commented
@jenovateurs peux-tu me dire si'l y a autre chose qui bloque que l'url utilisé ? Sinon, hop je modifie et ça peut être mis en prod.

2024-04-18 08:42 UTC, jenovateurs commented
> @jenovateurs peux-tu me dire si'l y a autre chose qui bloque que l'url utilisé ? Sinon, hop je modifie et ça peut être mis en prod.

Non, c'est tout bon pour moi @guillett

2024-04-19 09:20 UTC, Shamzic commented on contribuer/public/admin/main.js
> +const baseURL = "https://mes-aides.1jeune1solution.beta.gouv.fr"
Avec cette dernière modification cela m'affiche la page d'accueil en local, ce ne serait pas mieux de mettre la variable d'environnement classique ?

Si je remet localhost:8080, ça fonctionne mais la preview ne fonctionne plus pour les aides complexes

2024-04-19 09:51 UTC, guillett commented on contribuer/public/admin/main.js
> +const baseURL = "https://mes-aides.1jeune1solution.beta.gouv.fr"
C'est normal que ça ne fonctionne sans merger cette PR. La production n'a pas de route /preview.

2024-04-19 09:51 UTC, guillett commented on contribuer/public/admin/main.js
> +const baseURL = "https://mes-aides.1jeune1solution.beta.gouv.fr"
Par contre, je ne comprends pas que ça ne fonctionne plus en mettant `localhost:8080`. Tu es sûr ?

2024-04-19 14:58 UTC, guillett commented on contribuer/public/admin/main.js
> +const baseURL = "https://mes-aides.1jeune1solution.beta.gouv.fr"
Ok, merci beaucoup @Shamzic ! J'ai testé et j'ai eu des problèmes similaires, je n'ai pas compris d'où ça venait exactement mais c'est corrigé. Je pense qu'il y avait deux problèmes, l'un à cause de la latence et un autre à cause de la référence à la propriété `id` uniquement dans certains cas.

2024-04-19 18:04 UTC, Shamzic commented on contribuer/public/admin/main.js
> +const baseURL = "https://mes-aides.1jeune1solution.beta.gouv.fr"
@guillett C'est good pour l'affichage des aides complexes. 
Cependant, j'ai toujours le soucis d'affichage pour l'ajout d'une aide, je suspecte que cela soit dû à l'initalisation du benefit vide dans `droits-details.vue`

2024-04-22 10:36 UTC, Shamzic reviewed
Il y a des warning en console (`Uncaught (in promise) Error: Missing required param "benefitId"` ) à l'ouverture de la preview à corriger, mais cela fonctionne en l'état en local. 
Petite question sur les props de droits-details, pas bloquant tant que ça roule: j'imagine que tu veux tester directement sur la prod

2024-04-22 11:56 UTC, jenovateurs commented
Petit détail: 
- pour une nouvelle aide, j'ai le logo à undefined et un montant estimé à 1 par défaut.
![image](https://github.com/betagouv/aides-jeunes/assets/3491729/1ce03745-c171-46c6-8a4c-6b169b94d0ea)

2024-04-22 12:13 UTC, jenovateurs requested changes

2024-04-22 12:13 UTC, jenovateurs commented on contribuer/public/admin/main.js
> +    if (event.data.source == "aides-jeunes" && event.data.value == "ready") {
```suggestion
    if (event.data.source === "aides-jeunes" && event.data.value === "ready") {
```

2024-04-22 12:30 UTC, jenovateurs approved these changes

2024-04-22 13:03 UTC, merged