Ajoute la vidéo tutoriel d'ajout d'une aide sur page accueil des liens de l'outil de contribution
betagouv/aides-jeunes pull request #4302
Opened 2024-04-23 11:36 UTC by Shamzic

2024-04-23 12:23 UTC, guillett commented
@Shamzic peux-tu faire un autre dépôt pour y déposer le fichier mp4 de plusieurs Mo pour éviter de charger ce dépôt (et surtout l'historique git) d'un fichier d'une telle taille) ?

2024-04-23 13:12 UTC, Shamzic commented
> @Shamzic par exemple aides-jeunes-static avec un déploiement via Github Pages.

Ah ben j'ai fait aides-jeunes-files 😅

2024-04-28 14:09 UTC, jenovateurs requested changes
Je te propose de faire un h3 / Guides de contribution
contenant ensuite, le ligne vers Google drive en mode documentation Google drive en précisant une nouvelle fenêtre
et en dessous mettre la vidéo de tutoriel car les deux sont des guides pour l'outil de contribution.

2024-05-02 09:31 UTC, jenovateurs approved these changes

2024-05-02 10:03 UTC, merged