Ajouter une page qui décrit les étapes du parcours
betagouv/aides-jeunes pull request #4306
Opened 2024-04-24 13:27 UTC by guillett

2024-07-02 16:29 UTC, jenovateurs requested changes
Petit changement de style

2024-07-02 16:29 UTC, jenovateurs commented on src/styles/aides-jeunes.css
> +.aj-hidden {
Pourquoi ne pas utiliser `fr-hidden ` du DSFR et éviter d'ajouter une nouvelle classe ?

2024-07-02 16:29 UTC, jenovateurs commented on src/styles/aides-jeunes.css
> +.aj-step-button {
J'aurais bien supprimé cette classe et trouvé un autre moyen si tu as une idée.

2024-07-04 13:40 UTC, Shamzic commented on src/styles/aides-jeunes.css
> +.aj-hidden {
Cela ne fonctionne pas avec cette classe, je pense que c'est un soucis du DSFR

2024-07-04 15:11 UTC, Shamzic commented on src/styles/aides-jeunes.css
> +.aj-step-button {
L'intérêt de cette classe permet d'uniformiser les largeur des cases car la largeur des caractères ascii `+` et `-` n'est pas uniforme. 
Je regarde pour une alternative

2024-07-05 15:11 UTC, jenovateurs commented on src/styles/aides-jeunes.css
> +.aj-hidden {
J'ai mis à jour le DSFR en local et ça fonctionne :-). Je propose donc une PR intermédiaire de MAJ du DSFR. Je peux m'en occuper si c'est ok pour toi @Shamzic ?

2024-07-08 07:40 UTC, Shamzic commented on src/styles/aides-jeunes.css
> +.aj-hidden {
C'est ok

2024-07-08 07:50 UTC, jenovateurs commented on src/styles/aides-jeunes.css
> +.aj-hidden {
A merge/faire après la fin de ce ticket : #4456

2024-07-17 14:58 UTC, Shamzic commented on src/styles/aides-jeunes.css
> +.aj-step-button {
Code déprécié

2024-07-19 12:27 UTC, jenovateurs approved these changes
Tout est bon pour moi @Shamzic  merci :-).

2024-07-19 13:35 UTC, merged