Mets à jour des aides dans le simulateur
betagouv/aides-jeunes pull request #4328
Opened 2024-05-07 15:11 UTC by yasmine-glitch

2024-05-16 12:51 UTC, jenovateurs requested changes

2024-05-16 12:51 UTC, jenovateurs commented on data/benefits/javascript/grand-est-passetudes.yml
> +      - "52"
Petite question :
Dans les conditions, j'ai lu les départements de la Côte d'Or (21, 25, ...)
Mais je ne retrouve pas ses codes dans ta liste de values de type departements. Est-ce que ces valeurs correspondent à autre chose ?

EDIT : En regardant le code, j'ai l'impression que c'est le code_insee d'utilisé.
En partant de ce principe, je n'ai pas trouvé d'institution pour la valeur "10". Faut-il la créer ? 
Ne faudrait-il pas ajouter les autres départements (Côte d'or, ...) ?

2024-05-16 12:51 UTC, jenovateurs commented on data/benefits/javascript/hauts-de-france-mon-abo-etudiant-ter.yml
> +label: abonnement Etudiant et Apprenti TER
Question sur le renommage, car d'après le site, le nom de "l'aide" est MON ABO ÉTUDIANT ET APPRENTI TER

2024-05-16 12:51 UTC, jenovateurs commented on data/benefits/javascript/region-auvergne-rhone-alpes-ter-illico-solidaire.yml
> -  - type: age
Ne faudrait-il pas changer les conditions ? "avoir moins de 26 ans"

2024-05-16 12:51 UTC, jenovateurs commented on data/benefits/javascript/region-centre-val-de-loire-carte-rémi-liberté-jeune.yml
>    - type: age
Est-ce que cette condition est encore utile ?

2024-05-16 13:52 UTC, yasmine-glitch commented on data/benefits/javascript/grand-est-passetudes.yml
> +      - "52"
1- je montre l'aide uniquement aux personnes qui résident dans les Ardennes (08), l'Aube (10), la Marne(51) ou la Haute-Marne(52) : ça te semble juste ?
2- En effet le département de l'Aube n'existe pas et celui de la Haute-Marne non plus 🙀 donc il faut les créer : je m'en occupe

2024-05-16 16:23 UTC, yasmine-glitch commented on data/benefits/javascript/region-auvergne-rhone-alpes-ter-illico-solidaire.yml
> -  - type: age
Je ne comprends pas ton commentaire ?

2024-05-17 07:37 UTC, jenovateurs commented on data/benefits/javascript/region-auvergne-rhone-alpes-ter-illico-solidaire.yml
> -  - type: age
Après échange, je n'avais pas vu que l'aide est accessible pour deux situations distincts. L'age n'est donc pas obligatoire pour le deuxième cas. Donc ok pour la suppression de la condition.

2024-05-21 09:47 UTC, jenovateurs approved these changes
Tout est bon pour moi. Merci @yasmine-glitch  :-)

2024-05-21 12:59 UTC, merged