Ajout dynamique des incitations covoiturage
betagouv/aides-jeunes pull request #4333
Opened 2024-05-08 15:03 UTC by jenovateurs

2024-06-12 16:50 UTC, Shamzic reviewed
Première passe

2024-06-12 16:50 UTC, Shamzic commented on data/benefits/dynamic/incitations-covoiturage.ts
> +export function buildIncitationsCovoiturage(
Dans cette méthode on pourrait ajouter un try-catch pour détecter les erreurs potentielles dans la recherche des institutions

2024-06-12 16:50 UTC, Shamzic commented on data/benefits/dynamic/incitations-covoiturage.ts
> +    .map((b) => {
pour améliorer la lisibilité sur la suite :
```js
const institution = b.institution;
```

2024-06-12 16:50 UTC, Shamzic commented on data/benefits/dynamic/incitations-covoiturage.ts
> +    link: "https://www.agglo-sarreguemines.fr/covoiturage/",
Ce lien est présent deux fois dans ce tableau

2024-06-12 16:50 UTC, Shamzic commented on data/types/benefits.d.ts
> +  conditions: any[]
```suggestion
  conditions: string[]
```

2024-06-12 16:50 UTC, Shamzic commented on data/types/benefits.d.ts
> +  institution?: string
institution obligatoire non ?

2024-06-13 15:59 UTC, Shamzic commented on data/benefits/dynamic/incitations-covoiturage.ts
> +    link: "https://www.agglo-sarreguemines.fr/covoiturage/",
Effectivement ça m'a l'air de venir du Grist, mais peut être qu'il y a un subtilité que je ne connais pas

2024-06-18 13:46 UTC, Shamzic commented
Lien avec https://github.com/betagouv/aides-jeunes/pull/4378

2024-07-09 15:54 UTC, Shamzic commented on cypress/e2e/patrimoine.cy.js
> +        results.hasIncitationCovoiturage() //Fini le 31/12/2024
Quel est le contexte de ce commentaire ?

2024-07-09 15:54 UTC, Shamzic commented on data/types/benefits.d.ts
> +export interface CoVoiturageBenefit {
Dans le simulateur, la convention implicite est de nommer les types en anglais, ici on pourrait par exemple nommer ce type `CarpoolingBenefit`, qu'en penses-tu ?

2024-07-09 15:54 UTC, Shamzic commented on data/types/benefits.d.ts
> +export interface CoVoiturageJson {
Même remarque ici concernant le nom en anglais

2024-07-09 15:54 UTC, Shamzic commented on lib/types/link-validity.d.ts
> +interface GristLinkValidityResponse {
Je ne trouve pas d'utilisation de ce type, il me semble que tu les as supprimées

2024-07-10 07:08 UTC, jenovateurs commented on cypress/e2e/patrimoine.cy.js
> +        results.hasIncitationCovoiturage() //Fini le 31/12/2024
Je vais préciser le commentaire, mais l'idée est d'indiquer que le test sera périmé après le 31/12/2024 car il s'agit d'une incitation qui se termine à cette date.

2024-07-10 07:11 UTC, jenovateurs commented on data/types/benefits.d.ts
> +export interface CoVoiturageBenefit {
Je me suis basé sur les aides vélo.
Pour ses aides le nom employé est VeloBenefit et non BikeBenefit.
Mais je peux faire la modification.

2024-07-10 07:42 UTC, Shamzic commented on data/types/benefits.d.ts
> +export interface CoVoiturageBenefit {
Vu ensemble à l'oral, partons sur `CovoiturageBenefit` 👍

2024-07-10 09:29 UTC, jenovateurs commented on lib/types/link-validity.d.ts
> +interface GristLinkValidityResponse {
Effectivement, j'ai oublié de réutiliser ce type au bon endroit. Bien vu :-). Je l'ai rattaché à l'outil de vérification des liens cassés.

2024-07-10 14:19 UTC, Shamzic requested changes
Quelques petites modifs et on est pas loin du merge 👍

2024-07-10 14:19 UTC, Shamzic commented on tests/unit/incitations-covoiturage-benefit-generator.spec.ts
> +  it("maps all benefits to existing institutions and check if is linked to autre type", function () {
Cette description de test ne me semblait pas très claire par rapport au contenu: 
```suggestion
  it("All benefitsCovoiturage should have an existing institution that is not 'autre' type", function () {
```

2024-07-10 14:19 UTC, Shamzic commented on tools/download-incitations-covoiturage-generate-missing-institutions.ts
> +import { Grist } from "../lib/grist"
```suggestion
import { Grist } from "../lib/grist.js"
```

2024-07-10 14:19 UTC, Shamzic commented on tools/download-incitations-covoiturage-generate-missing-institutions.ts
> +import { missingInstitutionsCovoiturageBenefit } from "./generate-missing-institutions"
```suggestion
import { missingInstitutionsCovoiturageBenefit } from "./generate-missing-institutions.js"
```

2024-07-10 14:19 UTC, Shamzic commented on tools/download-incitations-covoiturage-generate-missing-institutions.ts
> +main()
Suggestion pas bloquante : diviser ce code en plusieurs fonctions (le principe de [SoC](https://en.wikipedia.org/wiki/Separation_of_concerns) permet une meilleure lisibilité lors de la review et pour les éventuels futurs lecteurs)

2024-07-10 14:19 UTC, Shamzic commented on tools/generate-missing-institutions.ts
> +import { CovoiturageJson, VeloBenefit } from "../data/types/benefits"
```suggestion
import { CovoiturageJson, VeloBenefit } from "../data/types/benefits.d.js"
```

2024-07-10 14:19 UTC, Shamzic commented on tools/generate-missing-institutions.ts
> +import all from "../data/all"
```suggestion
import all from "../data/all.js"
```

2024-07-10 14:19 UTC, Shamzic commented on tools/generate-missing-institutions-aides-velo.ts
> +import { missingInstitutionsVeloBenefit } from "./generate-missing-institutions"
```suggestion
import { missingInstitutionsVeloBenefit } from "./generate-missing-institutions.js"
```

2024-07-10 14:19 UTC, Shamzic commented on tools/generate-missing-institutions-aides-velo.ts
> +import benefits from "../data/all"
```suggestion
import benefits from "../data/all.js"
```

2024-07-15 13:47 UTC, jenovateurs commented on lib/grist.ts
> +      const response = await axios.get(url, gristConfig)
C'est plutôt : <GristIncitationsCovoiturageResponse | GristLinkValidityResponse>

2024-07-16 07:09 UTC, jenovateurs commented on tools/download-incitations-covoiturage-generate-missing-institutions.ts
> +main()
Effectivement, je viens de refactoriser le script pour plus de clareté.

2024-07-16 14:04 UTC, Shamzic commented on lib/grist.ts
> +        GristIncitationsCovoiturageResponse | GristLinkValidityResponse
En fait, c'est les deux même interfaces, y a pas moyen de les unifier ?

2024-07-16 14:07 UTC, Shamzic commented on lib/grist.ts
> +import { GristLinkValidityResponse } from "./types/link-validity"
```suggestion
import { GristLinkValidityResponse } from "./types/link-validity.d.js"
```

2024-07-16 14:07 UTC, Shamzic commented on lib/grist.ts
> +import { GristIncitationsCovoiturageResponse } from "./types/download-incitations-covoiturage"
```suggestion
import { GristIncitationsCovoiturageResponse } from "./types/download-incitations-covoiturage.d.js"
```

2024-07-16 14:08 UTC, Shamzic commented on tests/unit/incitations-covoiturage-benefit-generator.spec.ts
> +import { Institution } from "@data/types/institutions"
```suggestion
import { Institution } from "@data/types/institutions.d.js"
```

2024-07-16 14:08 UTC, Shamzic commented on tools/download-incitations-covoiturage-generate-missing-institutions.ts
> +import { GristIncitationsCovoiturageResponse } from "../lib/types/download-incitations-covoiturage"
```suggestion
import { GristIncitationsCovoiturageResponse } from "../lib/types/download-incitations-covoiturage.d.js"
```

2024-07-16 14:08 UTC, Shamzic commented on tools/generate-missing-institutions-aides-velo.ts
>  import generator from "../data/benefits/aides-velo-generator"
```suggestion
import generator from "../data/benefits/aides-velo-generator.d.js"
```

2024-07-17 13:33 UTC, jenovateurs commented on lib/grist.ts
> +        GristIncitationsCovoiturageResponse | GristLinkValidityResponse
Ce n'est pas les mêmes interfaces, la première contient les propriétés (GristData) correspondant aux champs du tableau des incitations Covoiturages, qui sont différentes de GristLinkValidity.

2024-07-17 13:34 UTC, jenovateurs commented on lib/grist.ts
> +import { GristLinkValidityResponse } from "./types/link-validity"
.d.ts plutôt ?

2024-07-17 13:37 UTC, jenovateurs commented on lib/grist.ts
> +        GristIncitationsCovoiturageResponse | GristLinkValidityResponse
Si tu as une autre solution, je suis preneur @Shamzic

2024-07-17 13:53 UTC, Shamzic commented on lib/grist.ts
> +        GristIncitationsCovoiturageResponse | GristLinkValidityResponse
Pour moi c'est les même : 

```
export interface GristIncitationsCovoiturageResponse {
  records: GristRecord[]
}
```
et 
```
interface GristLinkValidityResponse {
  records: GristRecord[]
}
```
Je me suis dit qu'on pourrait juste mettre directement une interface GirstResponse
```
interface GristResponse {
  records: GristRecord[]
}
```

2024-07-17 14:06 UTC, merged