Met à jour 4 aides
betagouv/aides-jeunes pull request #4335
Opened 2024-05-10 10:09 UTC by yasmine-glitch

2024-05-13 17:12 UTC, jenovateurs requested changes

2024-05-13 17:12 UTC, jenovateurs commented on data/benefits/javascript/region-pays-de-la-loire-carte-mezzo.yml
Serait-il intéressant de mettre un M à carte mezzo sur le label car je trouve que sur la liste des aides l'affichage n'est pas uniformisé ? 
![image](https://github.com/betagouv/aides-jeunes/assets/3491729/f083b295-bdcc-48e4-a9d4-9f3ede46dd66)

2024-05-13 17:12 UTC, jenovateurs commented on data/benefits/javascript/region-pays-de-la-loire-carte-mezzo.yml
> +instructions: https://www.ter.sncf.com/pays-de-la-loire/tarifs-cartes/cartes-de-reduction/carte-mezzo
C'est ok de mettre deux fois le même lien (instructions & link) ?

2024-05-13 17:12 UTC, jenovateurs commented on data/benefits/openfisca/vendee_bourses_jeunes_benevoles_montant_max.yml
> +link: https://www.vendee.fr/bourse-jeunes-benevoles-vendeens
Sur cette page, j'ai le message suivant :  
> Les candidatures ne sont plus acceptées depuis le 1er octobre 2023. Les inscriptions sont désormais closes.

2024-05-13 17:12 UTC, jenovateurs commented on data/benefits/openfisca/vendee_bourses_jeunes_benevoles_montant_max.yml
> +form: https://www.vendee.fr/fileadmin/user_upload/guide_aides/Dossier_de_candidature_2023.pdf
Il est bien marqué jusqu'au 1 octobre 2023.

2024-05-15 14:28 UTC, yasmine-glitch commented on data/benefits/openfisca/vendee_bourses_jeunes_benevoles_montant_max.yml
> +link: https://www.vendee.fr/bourse-jeunes-benevoles-vendeens
Oui les candidatures vont être réouvertes courant juin, jusqu'à octobre. D'ailleurs je vais reformuler la condition pour plus de clarté.

2024-05-16 13:02 UTC, jenovateurs approved these changes
C'est tout bon pour moi @yasmine-glitch 🎉. Merci pour ton travail de mise à jour !

2024-05-16 13:17 UTC, merged