Met à jour 5 aides
betagouv/aides-jeunes pull request #4343
Opened 2024-05-21 11:12 UTC by yasmine-glitch

2024-05-21 14:38 UTC, jenovateurs requested changes

2024-05-21 14:38 UTC, jenovateurs commented on data/benefits/javascript/grand-est-aide-mobilite-internationale-etudiants.yml
> +instructions: file:///Users/yasmineberrada/Downloads/annexe-1-reglement-mobilites-internationales-vf.pdf
ça ne va pas fonctionner comme lien

2024-05-21 14:38 UTC, jenovateurs commented on data/benefits/javascript/grand-est-aide-mobilite-internationale-etudiants.yml
> +teleservice: https://messervices.grandest.fr/account-management/crge-demandeurs/ux/#/login?redirectTo=https:%2F%2Fmesservices.grandest.fr%2Faides%2F%23%2Fcrge%2Fconnecte%2FF_BMI3%2Fdepot%2Fsimple&jwt
```suggestion
teleservice: https://messervices.grandest.fr/account-management/crge-demandeurs/ux/#/login
```

2024-05-21 14:38 UTC, jenovateurs commented on data/benefits/javascript/grand-est-aide-mobilite-internationale-etudiants.yml
> +teleservice: https://messervices.grandest.fr/account-management/crge-demandeurs/ux/#/login?redirectTo=https:%2F%2Fmesservices.grandest.fr%2Faides%2F%23%2Fcrge%2Fconnecte%2FF_BMI3%2Fdepot%2Fsimple&jwt
J'ai un doute sur ma modification : après connexion, le lien est censé aller dans une sous-partie en particulier ?

2024-05-21 16:02 UTC, yasmine-glitch commented on data/benefits/javascript/grand-est-aide-mobilite-internationale-etudiants.yml
> +instructions: file:///Users/yasmineberrada/Downloads/annexe-1-reglement-mobilites-internationales-vf.pdf
oups 🙀

2024-05-22 09:27 UTC, yasmine-glitch commented on data/benefits/javascript/grand-est-aide-mobilite-internationale-etudiants.yml
> +teleservice: https://messervices.grandest.fr/account-management/crge-demandeurs/ux/#/login?redirectTo=https:%2F%2Fmesservices.grandest.fr%2Faides%2F%23%2Fcrge%2Fconnecte%2FF_BMI3%2Fdepot%2Fsimple&jwt
Oui ce lien sert à rediriger directement sur le formulaire de demande de l'aide dont il est question

2024-05-22 13:15 UTC, merged