Ajoute l'aide à la pratique sportive, culturelle et artistique de la région Ile de France pour les 15-17 ans
betagouv/aides-jeunes pull request #4353
Opened 2024-05-28 15:42 UTC by yasmine-glitch

2024-05-28 18:12 UTC, jenovateurs requested changes
Merci pour ces nouvelles aides @yasmine-glitch

2024-05-28 18:12 UTC, jenovateurs commented on data/benefits/javascript/region-ile-de-france-aide-culture-sport-labaz.yml
> +  - Télécharger l'application mobile LABAZ disponible sur les stores et vous inscrire.
```suggestion
  - Télécharger l'application mobile LABAZ disponible sur les stores et se créer un compte.
```

2024-05-28 18:12 UTC, jenovateurs commented on data/benefits/javascript/region-ile-de-france-aide-culture-sport-labaz.yml
> +  - Choisir dans la liste des partenaires du réseau LABAZ la structure où vous souhaitez
Un lien serait-il utile vers la liste des partenaires ?

2024-05-28 18:12 UTC, jenovateurs commented on data/benefits/javascript/region-ile-de-france-aide-culture-sport-labaz.yml
> +    operator: <=
Y-a-t-il une règle particulière sur l'ajout de " sur l'opérateur ?

2024-05-29 09:26 UTC, yasmine-glitch commented on data/benefits/javascript/region-ile-de-france-aide-culture-sport-labaz.yml
> +  - Choisir dans la liste des partenaires du réseau LABAZ la structure où vous souhaitez
Je ne trouve pas la liste des partenaires en ligne

2024-05-29 09:39 UTC, yasmine-glitch commented on data/benefits/javascript/region-ile-de-france-aide-culture-sport-labaz.yml
> +    operator: <=
Apparemment il faut des "" pour le signe >= mais pas pour le signe <=
J'ignore pourquoi mais j'imagine que le symbole > signifie quelque chose pour le robot

2024-05-29 18:54 UTC, jenovateurs commented on data/benefits/javascript/region-ile-de-france-aide-culture-sport-labaz.yml
> +  - Choisir dans la liste des partenaires du réseau LABAZ la structure où vous souhaitez
En effet, j'ai l'impression que tout se passe dans l'application.

2024-05-29 18:54 UTC, jenovateurs approved these changes
Merci @yasmine-glitch pour l'ajout de cette aide :-).

2024-05-30 08:22 UTC, merged