Ajoute l'aide vacances aux familles de la Caf de Paris
betagouv/aides-jeunes pull request #4372
Opened 2024-06-12 10:23 UTC by yasmine-glitch

2024-06-13 12:55 UTC, jenovateurs requested changes

2024-06-13 12:55 UTC, jenovateurs commented on data/benefits/javascript/caf-paris-aide-vacances-avf.yml
> +label: aide aux vacances en famille (avf)
```suggestion
label: aide aux vacances en famille (avf)
```
```suggestion
label: aide aux vacances en famille (AVF)
```

2024-06-13 12:55 UTC, jenovateurs commented on data/benefits/javascript/caf-paris-aide-vacances-avf.yml
> +  Le montant de l'aide dépend du quotient familial et du nombre d'enfants avec un bonus pour les bénéficiaires de l'aeeh.
Même questionnement sur AEEH, en mode majuscule et en explicitant l'acronyme.

2024-06-13 15:16 UTC, Shamzic approved these changes

2024-07-01 15:05 UTC, jenovateurs commented on data/benefits/javascript/caf-paris-aide-vacances-avf.yml
> +    values:
Je me demande s'il est nécessaire de préciser le département 75 alors que cette information est déjà présente sur l'institution @Shamzic qu'en penses-tu ?

2024-07-02 13:13 UTC, jenovateurs commented on data/benefits/javascript/caf-paris-aide-vacances-avf.yml
> +    values:
Je viens de tester et cela fonctionne, je recommande donc de supprimer dans l'aide 
  - type: departements
    values:
      - "75"

2024-07-02 14:15 UTC, jenovateurs approved these changes
Tout est ok pour moi. Merci @yasmine-glitch .

2024-07-02 15:42 UTC, merged