Maj contenu du bouton "En savoir plus"
betagouv/aides-jeunes pull request #4387
Opened 2024-06-20 17:21 UTC by Shamzic

2024-07-01 15:02 UTC, jenovateurs commented on src/components/en-savoir-plus.vue
> -  <span v-if="text" class="fr-ml-1v" @mouseover="trackInterest()">
Est-il intéressant de logger / tracker les clics sur le bouton pour vérifier que cela fonctionne ou est pertinent ?

2024-07-03 17:37 UTC, Shamzic commented on src/components/en-savoir-plus.vue
> -  <span v-if="text" class="fr-ml-1v" @mouseover="trackInterest()">
Je ne pense pas que cela soit pertinent d'ajouter un tracker car on a directement les stats des entrées sur chaque page via Matomo, cependant on peut ajouter un test e2e

2024-07-09 12:43 UTC, jenovateurs requested changes

2024-07-09 12:43 UTC, jenovateurs commented on src/components/en-savoir-plus.vue
> -        EventAction.EnSavoirPlus,
Il faudrait aussi supprimer la constante dans le fichier lib/enum/event.ts car elle n'est plus utilisable :    EnSavoirPlus = "En savoir plus",
On peux aussi créer un ticket de nettoyage du fichier car j'ai l'impression que de nombreuses constantes sont inutiles @Shamzic . Qu'en penses-tu ?

2024-07-16 07:20 UTC, jenovateurs approved these changes
Tout est bon pour moi @Shamzic , merci pour les modifs :-).

2024-07-16 13:49 UTC, merged