Maj email contact
betagouv/aides-jeunes pull request #4414
Opened 2024-06-25 13:31 UTC by Shamzic

Reprends la branche proposée par la PR #4331 pour effectuer des fixbug et corriger les conflits de rebase

2024-06-25 14:01 UTC, Shamzic commented
@jenovateurs Ok pour moi, je te laisse me dire si c'est toujours bon pour toi

2024-07-09 12:59 UTC, jenovateurs requested changes

2024-07-09 13:00 UTC, jenovateurs commented on backend/lib/mes-aides/emails/templates/simulation-results.txt
> +Vous avez récemment utilisé le simulateur de {{&contextName}}.
Ne serait-il pas plus pertinent de mettre baseURL ? Même chose pour les autres messages ayant comme référence une adresse web .gouv.fr ?

2024-07-10 15:34 UTC, Shamzic commented on backend/lib/mes-aides/emails/templates/simulation-results.txt
> +Vous avez récemment utilisé le simulateur de {{&contextName}}.
C'est un choix possible, oui. Je peux le faire sur tous les emails, mais pour les SMS je préfère laisser le nom sans le dns pour réduire la taille du message au maximum.

2024-07-16 08:11 UTC, jenovateurs approved these changes
All good pour moi, merci :-).

2024-07-16 13:36 UTC, merged