Ajoute l'incitation au covoiturage de l'ATMB pour la Haute-Savoie
betagouv/aides-jeunes pull request #4449
Opened 2024-07-03 12:37 UTC by yasmine-glitch

2024-07-03 13:53 UTC, Shamzic commented on data/benefits/javascript/atmb-aide-covoiturage.yml
> +      - "74093"
J'imagine que toutes les villes du département ne sont pas concernées ? (Si oui, pourquoi ?)

2024-07-03 14:17 UTC, jenovateurs commented
En cours de débug de mon côté pour régler le soucis de pipeline.

2024-07-04 12:18 UTC, Shamzic commented
Il faut effectivement bien déplacer l'incitation dans le bon dossier benefits/javascript pour que les tests passent 👍

2024-07-09 14:25 UTC, jenovateurs requested changes

2024-07-09 14:25 UTC, jenovateurs commented on data/benefits/javascript/atmb-aide-covoiturage.yml
> +  - Réaliser votre trajet en Haute-Savoie (a target="_blank" rel="noopener" title
```suggestion
  - Réaliser votre trajet en Haute-Savoie <a target="_blank" rel="noopener" title
```
Soucis de balise html

2024-07-09 14:25 UTC, jenovateurs commented on data/benefits/javascript/atmb-aide-covoiturage.yml
> +    consulter la carte</a> du territoire couvert par le dispositif).
```suggestion
    (consulter la carte pour découvrir le territoire couvert par le dispositif)</a>.
```
Format plus compréhensible et facile à lire.

2024-07-09 14:25 UTC, jenovateurs commented on data/benefits/javascript/atmb-aide-covoiturage.yml
> +description: "Autoroutes et Tunnel du Mont-Blanc subventionne tous vos trajets en Haute-Savoie, réservés depuis les applications BlaBlaCar Daily et Karos. Vous êtes conductrice ou conducteur ? Receve
```suggestion
description: "ATMB (Autoroutes et Tunnel du Mont-Blanc) subventionne tous vos trajets en Haute-Savoie, réservés depuis les applications BlaBlaCar Daily et Karos. Vous êtes conductrice ou conducteur ? Recevez entre 2 € et 4 € par trajet et par passager selon la distance parcourue, dans la limite de 50 € par mois. Vous êtes passagère ou passager ? Bénéficiez de 2 trajets gratuits par jour."
```

2024-07-09 14:25 UTC, jenovateurs commented on data/benefits/javascript/atmb-aide-covoiturage.yml
> +    consulter la carte</a> du territoire couvert par le dispositif).
En terme de résultat : 
<img width="1191" alt="Screenshot 2024-07-09 at 16 25 08" src="https://github.com/betagouv/aides-jeunes/assets/3491729/6e69c91a-aabd-49d6-a27e-48272556ba5b">

2024-07-16 07:23 UTC, jenovateurs approved these changes
Tout est bon merci @yasmine-glitch :-).

2024-07-16 14:39 UTC, merged