Ajoute une page FAQ
betagouv/aides-jeunes pull request #4483
Opened 2024-07-19 15:20 UTC by Shamzic

2024-07-23 13:02 UTC, jenovateurs requested changes
Revue purement technique, mais nécessiterait un point d'équipe pour discuter de l'intégration de la page.

2024-07-23 13:18 UTC, Shamzic commented on src/views/faq.vue
> +import { ref } from "vue"
C'est par habitude que j'ai déclaré ref. Le déclarer en constante dans un tableau, ça marche aussi

2024-07-23 13:19 UTC, Shamzic commented on src/views/faq.vue
> +        >Retour à la page d'accueil du simulateur</router-link
Oui, tu as raison, je vais faire un retour en arrière plutôt

2024-07-23 13:21 UTC, Shamzic commented on src/views/faq.vue
> +        >Retour à la page d'accueil du simulateur</router-link
C'est vrai, ça fait doublon. Je vais le supprimer pour le moment

2024-07-23 16:25 UTC, jenovateurs requested changes
Un dernier changement.

2024-07-23 16:25 UTC, jenovateurs commented on src/views/faq.vue
> +        >Nous contacter : {{ contactEmail }}</a
Je ne pense pas qu'un look bouton pour du mailto soit une bonne pratique.
Comment faire pour copier l'adresse e-mail si je n'ai pas de logiciel de gestion de boîte mail installé sur mon ordinateur et que j'utilise uniquement mon navigateur web ?
Je pense qu'un lien simple sera plus simple avec l’icône d'indication de lien externe.

2024-07-24 13:27 UTC, jenovateurs requested changes

2024-07-24 13:27 UTC, jenovateurs commented on src/views/faq.vue
> +      À tout moment de la simulation, vous avez la possibilité de cliquer sur le bouton <b>"Revenir plus tard?"</b>
```suggestion
      À tout moment de la simulation, vous avez la possibilité de cliquer sur le bouton <b>"Revenir plus tard ?"</b>
```

2024-07-24 17:08 UTC, Shamzic commented on src/views/faq.vue
> +        >Nous contacter : {{ contactEmail }}</a
> Je ne pense pas qu'un look bouton pour du mailto soit une bonne pratique.

 J'ai repris le fonctionnement existant de la page de la FAQ de 1J1Q. Je remets un lien en attendant les avis de l'équipe à ce sujet. 

> Comment faire pour copier l'adresse e-mail si je n'ai pas de logiciel de gestion de boîte mail installé sur mon ordinateur et que j'utilise uniquement mon navigateur web ?

Normalement ton navigateur détecter que c'est un type="mailto" et tu peux faire clic droit "copier l'adresse email".

2024-07-26 14:42 UTC, jenovateurs approved these changes
Mini request change et après, on merge ? Ou tu veux attendre la finalisation du Pad contenant les MAJ de textes complètes ?

2024-07-26 14:42 UTC, jenovateurs commented on src/views/faq.vue
> +      Si vous n'avez aucun moyen de déterminter le montant de votre RFR ou le RBG de vos parents lorsque vous êtes à leur charge),
```suggestion
      Si vous n'avez aucun moyen de déterminer le montant de votre RFR ou le RBG de vos parents lorsque vous êtes à leur charge), 
```

2024-07-29 13:10 UTC, Shamzic commented
@jenovateurs Merci pour les retours, j'ai rajouté des questions/réponses issues du pad qui me semblaient pertinentes

C'est probablement voué à évoluer prochainement mais en attendant, on peut merger en l'état si ça te va

2024-07-29 13:17 UTC, jenovateurs commented
> @jenovateurs Merci pour les retours, j'ai rajouté des questions/réponses issues du pad qui me semblaient pertinentes
> 
> C'est probablement voué à évoluer prochainement mais en attendant, on peut merger en l'état si ça te va

Tout à fait d'accord avec toi :-). Je vais faire une dernière relecture dès que les pipelines seront terminés.

2024-08-02 15:05 UTC, jenovateurs approved these changes
Parfait, merci @Shamzic !

2024-08-02 15:35 UTC, merged