Ajoute les scolarité "maternelle" et "primaire"
betagouv/aides-jeunes pull request #4487
Opened 2024-07-22 09:46 UTC by Shamzic

2024-07-25 07:02 UTC, jenovateurs commented on backend/lib/teleservices/demarches-simplifiees.ts
> +      Scolarite.scolariteTypes.find((s) => s.value === scolarite)?.label ||
![Screenshot 2024-07-24 at 16-17-39 Modification du brouillon nº 19175164 (Département du Var - FSL Demande de Fonds de Solidarité Energie (FSE)) · demarches-simplifiees fr](https://github.com/user-attachments/assets/82ecd3f1-1d51-44e5-8121-6086059ccbed)
![Screenshot 2024-07-24 at 16-13-47 Évaluez vos droits aux aides avec le simulateur de 1jeune1solution](https://github.com/user-attachments/assets/4468f450-9b10-470c-a1f8-97c7833d82f6)

Je ne sais pas si ça rentre dans le scope de ta tâche mais je ne trouve pas très esthétique et rassurant de voir le nom des variables pour un utilisateur lambda : champ_*

Sinon cela semble fonctionner, bien joué @Shamzic

2024-07-25 07:03 UTC, jenovateurs commented on lib/enums/scolarite.ts
> +  Maternelle = "maternelle",
J'ai vérifié dans open fisca, cela semble être le bon paramètre, il faudrait cependant ajouté un test e2e ou unit pour vérifier que c'est bien récupéré, qu'en penses-tu ?

2024-07-25 07:15 UTC, jenovateurs requested changes
Ajouter un test unitaire dans unit/openfisca/mapping/dispatch-individuals.spec.ts
afin de vérifier que la valeur primaire et/ou maternelle est bien mappé en utilisant la constante mis en place.
Le test n'a pas été fait pour les autres cas mais je pense que ça peut être intéressant à faire pour cet ajout spécifique. Qu'en penses-tu ? 

Et pourquoi pas ajouter un test cypress si on a une aide compatible avec cette situation dans famille.

2024-07-25 10:21 UTC, Shamzic commented on backend/lib/teleservices/demarches-simplifiees.ts
> +      Scolarite.scolariteTypes.find((s) => s.value === scolarite)?.label ||
> Je ne sais pas si ça rentre dans le scope de ta tâche mais je ne trouve pas très esthétique et rassurant de voir le nom des variables pour un utilisateur lambda : champ_*

Effectivement c'est un autre sujet, il faudrait refacto l'affichage des champs contenant des tableaux

2024-07-25 11:58 UTC, Shamzic commented
> Ajouter un test unitaire dans unit/openfisca/mapping/dispatch-individuals.spec.ts afin de vérifier que la valeur primaire et/ou maternelle est bien mappé en utilisant la constante mis en place. Le test n'a pas été fait pour les autres cas mais je pense que ça peut être intéressant à faire pour cet ajout spécifique. Qu'en penses-tu ?

J'ai ajouté un test unitaire, tu me diras si c'est à cela que tu pensais

> Et pourquoi pas ajouter un test cypress si on a une aide compatible avec cette situation dans famille.
Je pourrais en ajouter un dans la PR pour l'aide à la rentrée scolaire

2024-07-29 10:16 UTC, jenovateurs requested changes

2024-07-29 10:16 UTC, jenovateurs commented on tests/unit/openfisca/mapping/dispatch-individuals.spec.ts
> +      expect(result.individus.demandeur.enfant_a_charge.scolarite).toEqual(
Quelle est la différence entre       enfants: [{ id: "e1" }],
 et         situation.demandeur.enfant_a_charge.scolarite
J'ai l'impression que la première option est la plus probable non ?

2024-07-29 13:38 UTC, jenovateurs reviewed
<img width="804" alt="Screenshot 2024-07-29 at 15 37 14" src="https://github.com/user-attachments/assets/fe1592c7-9670-47d5-a141-86eb78db74a6">
Est-ce que cette question a aussi été géré ? @Shamzic

2024-07-30 07:22 UTC, Shamzic commented
> Est-ce que cette question a aussi été géré ? @Shamzic

C'est l'objectif de cette tâche oui

2024-07-30 07:23 UTC, Shamzic commented on tests/unit/openfisca/mapping/dispatch-individuals.spec.ts
> +      expect(result.individus.demandeur.enfant_a_charge.scolarite).toEqual(
Je n'ai pas compris où tu voulais en venir ?

2024-07-30 08:58 UTC, Shamzic commented on tests/unit/openfisca/mapping/dispatch-individuals.spec.ts
> +      expect(result.individus.demandeur.enfant_a_charge.scolarite).toEqual(
C'est corrigé

2024-07-31 08:21 UTC, jenovateurs approved these changes
Approuvé avec la validation de ma suggestion @Shamzic

2024-07-31 08:21 UTC, jenovateurs commented on tests/unit/openfisca/mapping/dispatch-individuals.spec.ts
> +          scolarite: "maternelle",
```suggestion
         scolarite: ScolariteEnfant.Maternelle,
```

2024-07-31 12:26 UTC, merged