Ajoute l'aide allocation rentrée scolaire (modélisée sur openfisca-france)
betagouv/aides-jeunes pull request #4488
Opened 2024-07-22 13:06 UTC by Shamzic

suit la PR #4424

2024-07-25 07:45 UTC, jenovateurs requested changes
Tout est bon pour moi.
Testé uniquement pour un enfant au collège.
Je te propose d'ajouter le test dans e2e / famille aussi.

2024-07-25 07:46 UTC, jenovateurs approved these changes
Le request change est plus approprié dans l'autre PR #4424 donc je te valide celle-ci.

2024-07-25 12:29 UTC, Shamzic commented
Je me permets de te rerequest malgré la validation car j'ai ajouté un test e2e

2024-07-26 10:37 UTC, Shamzic commented
Je repasse en draft temporairement le temps de régler le problème sur le test

2024-07-29 10:20 UTC, jenovateurs approved these changes
Tout est bon, super boulot @Shamzic  :-)

2024-07-29 10:20 UTC, jenovateurs commented on cypress/utils/foyer.js
> -  submit()
Juste pour comprendre, pourquoi avoir enlevé le submit ?

2024-07-29 16:36 UTC, Shamzic commented on cypress/utils/foyer.js
> -  submit()
Parce que l'action suivante continue d'ajouter des enfants sur la même page donc on ne veut pas passer à la page suivante

2024-07-31 13:49 UTC, merged