Ajoute infos "en savoir plus" pour les charges locatives
betagouv/aides-jeunes pull request #4495
Opened 2024-07-29 12:08 UTC by Shamzic

2024-07-31 08:28 UTC, jenovateurs requested changes

2024-07-31 08:28 UTC, jenovateurs commented on src/lib/hint.ts
> +    <h5>Que sont les charges locatives ?</h5>
Je trouve ta structure HTML particulière, deux h5 et pas de paragraphe ou d'autres types de balises de texte.

2024-07-31 10:27 UTC, Shamzic commented on src/lib/hint.ts
> +    <h5>Que sont les charges locatives ?</h5>
C'est inclu dans une balise

et j'ai mis des h5 pour le style proposé par le DSFR.
Qu'est-ce que tu proposes?

2024-07-31 10:31 UTC, Shamzic commented on src/lib/hint.ts
> +    <h5>Que sont les charges locatives ?</h5>
Je peux refacto les autres contenu textuels des hint, en ajoutant des balises `p` car elles n'en avaient pas à l'origine et remplacer la balise `<p v-html>` par une balise `<span v-html>`

2024-08-01 12:32 UTC, jenovateurs commented on src/lib/hint.ts
> +    <h5>Que sont les charges locatives ?</h5>
Et de passer le reste en mode balise <p>

2024-08-01 15:17 UTC, Shamzic commented on src/lib/hint.ts
> +    <h5>Que sont les charges locatives ?</h5>
Ok, le problème que j'avais était esthétique car le style du DSFR par défaut sur les h3 n'était pas adapté  mais en ajoutant la class `fr-text--lg` ça passe mieux.

J'ai modifié selon tes suggestions.

2024-08-02 15:09 UTC, jenovateurs approved these changes
Parfait, merci @Shamzic pour les modifications.

2024-08-02 15:35 UTC, merged