Met à jour 3 aides
betagouv/aides-jeunes pull request #4501
Opened 2024-07-31 16:32 UTC by yasmine-glitch

2024-08-01 12:51 UTC, jenovateurs requested changes

2024-08-01 12:51 UTC, jenovateurs commented on data/benefits/javascript/haut-de-france-aide-transports-salaries.yml
> +link: https://aides.hautsdefrance.fr/sub/tiers/aides/details/?sigle=ATPS23
```suggestion
link: https://aides.hautsdefrance.fr/sub/tiers/aides/details/?sigle=ATPS24
```
Sinon c'était l'aide de 2023.

2024-08-01 12:51 UTC, jenovateurs commented on data/benefits/javascript/haut-de-france-aide-transports-salaries.yml
> -teleservice: https://aides.hautsdefrance.fr/sub/tiers/aides/details/?sigle=ATPS23
Il y a aussi un autre formulaire pour faire un renouvellement : https://aides.hautsdefrance.fr/sub/tiers/aides/details/?sigle=ATPSR24
Comment le mettre en forme ? 

Il y aussi la version FALC / Facile à lire, un lien pertinent à ajouter ? 

Par contre, je ne comprends pas comment faire la demande .

2024-08-01 12:52 UTC, jenovateurs commented on data/benefits/javascript/haut-de-france-aide-transports-salaries.yml
> +link: https://aides.hautsdefrance.fr/sub/tiers/aides/details/?sigle=ATPS23
J'ai aussi l'impression qu'il faut se créer un compte pour pouvoir faire une demande, ce n'est pas bien explicite : https://aides.hautsdefrance.fr/sub/tiers/authentification non ?

2024-08-01 13:06 UTC, jenovateurs requested changes
J'ai quelques questions sur les aides.

2024-08-01 13:06 UTC, jenovateurs commented on data/benefits/javascript/hauts-de-france-transport-etudiants.yml
> +link: https://aides.hautsdefrance.fr/sub/tiers/aides/details/?sigle=ATPEF22%2F23
```suggestion
link: https://aides.hautsdefrance.fr/sub/tiers/aides/details/?sigle=ATPEF23%2F24
```
Même chose que précédemment
!->    Le renouvellement de l’aide n’est possible qu’une seule fois.

2024-08-01 13:06 UTC, jenovateurs commented on data/benefits/javascript/region_auvergne_rhone_alpes-financement-de-formations-dans-le-secteur-de-la-santé.yml
>  interestFlag: _interetAidesSanitaireSocial
J'ai l'impression que l'aide est toujours dispo non ? 
https://www.auvergnerhonealpes.fr/media/8540/download?inline
https://www.auvergnerhonealpes.fr/aides/obtenir-une-bourse-pour-suivre-une-formation-dans-le-secteur-sante-social
https://rhone-alpes.commeunservice.com/bourses/jsp/nouveauContexte.action?codeAction=M42-ACCUEIL#FSS

2024-08-02 17:47 UTC, yasmine-glitch commented on data/benefits/javascript/region_auvergne_rhone_alpes-financement-de-formations-dans-le-secteur-de-la-santé.yml
>  interestFlag: _interetAidesSanitaireSocial
non il s'agit de deux aides distinctes, qui étaient assez similaires. 
region_auvergne_rhone_alpes-bourse-du-secteur-santé-social.yml (existe toujours)
region_auvergne_rhone_alpes-financement-de-formations-dans-le-secteur-de-la-santé.yml (n'existe plus)

2024-08-05 12:20 UTC, jenovateurs approved these changes
Tout est bon pour moi dès que tu auras réglé le souci de Linter. :-).

2024-08-05 15:38 UTC, jenovateurs approved these changes
Tout est bon :-)

2024-08-06 07:35 UTC, merged