Met à jour 7 aides
betagouv/aides-jeunes pull request #4512
Opened 2024-08-02 17:28 UTC by yasmine-glitch

2024-08-05 09:34 UTC, Shamzic commented on data/benefits/javascript/bretagne-jeune-international.yml
> +montant: 300
Me semble que c'est maximum 200€ par mois ici :
```suggestion
montant: 200
```

2024-08-05 12:35 UTC, jenovateurs requested changes

2024-08-05 14:03 UTC, yasmine-glitch commented on data/benefits/javascript/bretagne-jeune-international.yml
>  institution: region_bretagne
L'aide sera relancée en 2025 et le lien est fonctionnel donc je pense que c'est bien si les usagers peuvent connaître son existence et candidater au prochain appel à candidatures.

2024-08-06 15:47 UTC, jenovateurs commented on data/benefits/javascript/bretagne-jeune-international.yml
>  institution: region_bretagne
Il faudrait peut-être l'afficher dans le descriptif ou créer un ticket pour placer un nouvel attribut de warning ou d'info en mode cette aide n'est plus disponible mais elle sera relancé à x ou prochainement. Qu'en penses-tu ?

2024-08-14 09:29 UTC, Shamzic approved these changes

2024-08-15 09:03 UTC, jenovateurs commented on data/benefits/javascript/bretagne-jeune-international.yml
>  institution: region_bretagne
> L'aide sera relancée en 2025 et le lien est fonctionnel donc je pense que c'est bien si les usagers peuvent connaître son existence et candidater au prochain appel à candidatures.

Peut-on l'indiquer en texte dans la description ?

2024-08-22 11:20 UTC, Shamzic commented
>  [yasmine-glitch](https://github.com/yasmine-glitch) requested a review from [Shamzic](https://github.com/Shamzic) [1 hour ago](https://github.com/betagouv/aides-jeunes/pull/4512#event-13974698663)

Toujours ok pour moi

2024-08-23 08:46 UTC, jenovateurs approved these changes
Tout est bon pour moi, merci d'avoir ajouté les compléments d'informations sur les périodes d'ouverture.

2024-08-26 08:51 UTC, merged