Corrige reliquats stats.data.gouv.fr => stats.beta.gouv.fr
betagouv/aides-jeunes pull request #4517
Opened 2024-08-05 11:20 UTC by Shamzic

2024-08-05 12:42 UTC, jenovateurs requested changes
Ne faudrait-il pas mettre une valeur par défaut pour VITE_MATOMO_ID dans le fichier vite.config.ts ?
Il faut aussi penser à MAJ le robot de vérificateur de lien cassé : getPriorityStats dans le fichier tools/check-links-validity.ts . Pour ce dernier point, je te propose de variabiliser l'info pour éviter qu'on l'oublie à l'avenir, il faudra aussi le mettre à jour dans la CI.

2024-08-05 12:42 UTC, jenovateurs commented on backend/config/index.ts
>      id: Number(process.env.MATOMO_ID) || 170,
Il faudrait mettre à jour la valeur par défaut (170) par la nouvelle non ?

2024-08-05 12:42 UTC, jenovateurs commented on contribuer/pages/_document.js
>                        _paq.push(["setSiteId", "240"])
Il faudrait en profiter pour mettre toutes ses constantes dans un .env ? Le SiteId est bon ?

2024-08-05 12:42 UTC, jenovateurs commented on README.md
> +- Matomo ([stats.beta.gouv.fr](https://stats.beta.gouv.fr/index.php?module=CoreHome&action=index&idSite=165&period=range&date=previous30))
Le idSite doit être aussi maj :-)

2024-08-08 08:32 UTC, Shamzic commented on contribuer/pages/_document.js
>                        _paq.push(["setSiteId", "240"])
Je te propose d'en faire un ticket séparé

2024-08-08 08:34 UTC, Shamzic commented on contribuer/pages/_document.js
>                        _paq.push(["setSiteId", "240"])
J'ai créé ce ticket : https://github.com/orgs/betagouv/projects/42/views/1?pane=issue&itemId=73981688

2024-08-08 08:36 UTC, Shamzic commented on contribuer/pages/_document.js
>                        _paq.push(["setSiteId", "240"])
Et effectivement le siteId n'est plus bon! Je corrige

2024-08-08 08:52 UTC, Shamzic commented
> Ne faudrait-il pas mettre une valeur par défaut pour VITE_MATOMO_ID dans le fichier vite.config.ts ? 

La valeur de VITE_MATOMO_ID dans vite.config.ts provient du fichier [index.ts](https://github.com/betagouv/aides-jeunes/blob/360e43cc16b3ce1aa52ca50fc0d8220c1f9cce61/backend/config/index.ts#L80-L81) qui dispose déjà d'une valeur par défaut.

> Il faut aussi penser à MAJ le robot de vérificateur de lien cassé : getPriorityStats dans le fichier tools/check-links-validity.ts . Pour ce dernier point, je te propose de variabiliser l'info pour éviter qu'on l'oublie à l'avenir, il faudra aussi le mettre à jour dans la CI.

Exact, d'ailleurs le siteId n'est pas bon là non plus.

2024-08-08 15:06 UTC, jenovateurs approved these changes
Parfait pour moi, merci pour toutes modifs.

2024-08-08 16:21 UTC, merged