Ajoute l'incitation covoiturage de la région Pays de la Loire.
betagouv/aides-jeunes pull request #4548
Opened 2024-08-19 10:53 UTC by yasmine-glitch

2024-08-23 08:43 UTC, jenovateurs requested changes
Merci pour l'ajout de cette incitation @yasmine-glitch  :-)

2024-08-23 08:43 UTC, jenovateurs commented on data/benefits/javascript/region-pays-de-la-loire-aide-covoiturage.yml
> +  - type: regions
Petite question : le liée à l'institution en mode attached_to_institution ne suffirait-il pas ?

2024-08-23 08:43 UTC, jenovateurs commented on data/benefits/javascript/region-pays-de-la-loire-aide-covoiturage.yml
> +  Vous êtes conductrice ou conducteur ? Recevez entre 0,7\u00a0€ et 2 € par trajet et par passager selon la distance parcourue dans la limite de 84 € de gain par mois.<br />
```suggestion
  Vous êtes conductrice ou conducteur ? Recevez entre 0,75€ et 2 € par trajet et par passager selon la distance parcourue dans la limite de 84 € de gain par mois.<br />
```

2024-08-23 08:43 UTC, jenovateurs commented on data/benefits/javascript/region-pays-de-la-loire-aide-covoiturage.yml
> +  Vous êtes passagère ou passager ? Vous ne payez que 0,50 € par trajet et bénéficiez en plus de 2 trajets gratuits par jour si vous avez un abonnement Pass Navigo ou Imagine R."
Je n'ai pas trouvé la mention du Pass Navigo ou Image R. sur la page. As-tu plus d'informations ?

2024-08-26 08:56 UTC, yasmine-glitch commented on data/benefits/javascript/region-pays-de-la-loire-aide-covoiturage.yml
> +  - type: regions
Je pense que si mais c'est vrai que dans la plupart des aides on remet le code de l'institution.

2024-08-26 08:58 UTC, yasmine-glitch commented on data/benefits/javascript/region-pays-de-la-loire-aide-covoiturage.yml
> +  Vous êtes passagère ou passager ? Vous ne payez que 0,50 € par trajet et bénéficiez en plus de 2 trajets gratuits par jour si vous avez un abonnement Pass Navigo ou Imagine R."
Bien vu ! Ce passage n'a rien à faire là. J'ai fait un vilain copié-collé de l'incitation d'Ile-de-France et oublié de retirer le passage inutile.

2024-08-26 12:02 UTC, jenovateurs commented on data/benefits/javascript/region-pays-de-la-loire-aide-covoiturage.yml
> +  Vous êtes passagère ou passager ? Vous ne payez que 0,50 € par trajet et bénéficiez en plus de 2 trajets gratuits par jour si vous avez un abonnement Pass Navigo ou Imagine R."
C'est des choses qui arrivent à tout le monde :-).

2024-08-26 12:02 UTC, jenovateurs approved these changes
Tout est bon, merci @yasmine-glitch

2024-08-26 15:56 UTC, merged