Supprime les réponses associées à un enfant quand il est supprimé dans le store
betagouv/aides-jeunes pull request #4550
Opened 2024-08-19 17:05 UTC by Shamzic

…

2024-08-21 13:02 UTC, jenovateurs commented
PR ok uniquement sur la partie suppression, il reste le problème de d'historique et je pense qu'il faudrait rajouter un test unitaire ou e2e. Qu'en penses-tu ?

2024-08-26 11:22 UTC, Shamzic commented
Ajout d'une logique custom pour le router proposée dans le 3e point ici : https://github.com/betagouv/aides-jeunes/pull/4554#issuecomment-2306467493

2024-09-02 07:54 UTC, jenovateurs requested changes
Voici des petites modifications.

2024-09-02 07:54 UTC, jenovateurs commented on cypress/utils/foyer.js
> +  deleteChilden,
il manque un r à remplacer de partout :-)
```suggestion
  deleteChildren,
```

2024-09-02 07:54 UTC, jenovateurs commented on src/router.ts
> +  // When a child has been removed from the /enfants step, the previous child questions should be skipped
Des commentaires en anglais ?

2024-09-04 08:22 UTC, Shamzic commented on src/router.ts
> +  // When a child has been removed from the /enfants step, the previous child questions should be skipped
C'est déjà le cas presque partout dans le répo non ?

2024-09-04 08:40 UTC, jenovateurs commented on src/router.ts
> +  // When a child has been removed from the /enfants step, the previous child questions should be skipped
Je ne crois pas avoir vu de décision ferme sur le sujet. Peut-être qu'on devrait l'écrire à un endroit.
J'ai trouvé quelques commentaires en français comme (NOTE: Les variables d'environement suivantes
 * Sont défini directement par pm2 en production
 * et ne sont donc pas dans les .env sur le serveur) ou (Ajoute un accessToken pour chaque followup) ou (L'AB testing repose sur les custom variables de Matomo).
 

 Dans le fichier Contributing.md, ce n'est pas indiqué clairement : 

> Par souci de lisibilité pour les partenaires, notamment administratifs, la langue utilisée pour la description et le suivi de fonctionnalités est le français.
> En revanche, pour éviter le coût du changement de contexte, les discussions techniques peuvent se faire en anglais, la langue la plus utilisée dans le cadre du développement logiciel.

2024-09-04 10:36 UTC, Shamzic commented on src/router.ts
> +  // When a child has been removed from the /enfants step, the previous child questions should be skipped
Oui ce n'est pas clairement défini, il y a des exceptions mais j'ai pour principe de toujours mettre les commentaires en anglais, comme le nom des variables (dans la mesure du possible)

2024-09-05 07:55 UTC, jenovateurs approved these changes
Après plusieurs tests, tout me semble OK.
J'ai juste une remarque sans réelle solution propre.
Lorsque tu ajoutes 3 enfants en laissant le libellé par défaut, tu supprimes le deuxième et tu en crées un nouveau, cela te fait un nouveau li

bellé 3e enfant en doublon visuel. Aurais-tu une solution ? 

<img width="859" alt="Screenshot 2024-09-05 at 09 52 02" src="https://github.com/user-attachments/assets/b7555778-703e-47ca-83fd-f68f387a5321">

En tout cas, ce n'est pas bloquant pour moi. Cela va résoudre déjà pas mal de problème.
Si tu trouves ma remarque pertinente, je te propose la création d'un ticket.

2024-09-16 13:54 UTC, Shamzic commented
> Après plusieurs tests, tout me semble OK. J'ai juste une remarque sans réelle solution propre. Lorsque tu ajoutes 3 enfants en laissant le libellé par défaut, tu supprimes le deuxième et tu en crées un nouveau, cela te fait un nouveau libellé 3e enfant en doublon visuel. Aurais-tu une solution ?

Je vois ce que tu veux dire; ça me paraît pas très grave et on ne peut pas y faire grand chose en l'état tant qu'on met le "nom" en dur de l'enfant. J'ai du mal à imaginer ce qu'on peut puisse d'autre comme libellé par défaut pour éviter cette situation. 

> En tout cas, ce n'est pas bloquant pour moi. Cela va résoudre déjà pas mal de problème. Si tu trouves ma remarque pertinente, je te propose la création d'un ticket.

Ok pour moi si tu arrives à trouver une solution 👍

2024-09-16 13:57 UTC, merged