Ajoute des liens vers la FAQ (page d'accueil & contenu "en savoir plus")
betagouv/aides-jeunes pull request #4587
Opened 2024-08-30 14:16 UTC by Shamzic

2024-09-04 16:16 UTC, jenovateurs requested changes
Le ticket a bien été fait, cependant, en testant, je me rends compte qu'il manque un moyen de retourner facilement au simulateur (et surtout à l'étape où nous étions). Penses-tu que l'ajout d'un tel bouton est facile à faire. Car le bouton en haut à droite te fait revenir à la page d'accueil. Qu'en penses-tu ?

2024-09-16 12:05 UTC, Shamzic commented
> Le ticket a bien été fait, cependant, en testant, je me rends compte qu'il manque un moyen de retourner facilement au simulateur (et surtout à l'étape où nous étions). Penses-tu que l'ajout d'un tel bouton est facile à faire. Car le bouton en haut à droite te fait revenir à la page d'accueil. Qu'en penses-tu ?

C'est pertinent d'ajouter un bouton de retour, effectivement!

Est-ce que ça convient comme ça ?

2024-09-17 20:16 UTC, jenovateurs approved these changes
Juste la suppression d'espace inutile et c'est parfait !

2024-09-17 20:16 UTC, jenovateurs commented on src/views/home.vue
> +        <router-link to="/faq"> Foire aux questions </router-link>
```suggestion
        <router-link to="/faq">Foire aux questions</router-link>
```

2024-09-18 11:17 UTC, merged