Met à jour 2 aides et cache 2 aides
betagouv/aides-jeunes pull request #4591
Opened 2024-09-04 11:15 UTC by yasmine-glitch

2024-09-04 14:09 UTC, jenovateurs requested changes
Je pense qu'il faudrait ajouter le mail : aides-individuelles@caf52.caf.fr
comme action pour faire la demande avec un objet de pré-rempli par exemple ? Qu'en penses-tu ? Car en lisant uniquement l'aide, je n'ai pas trouvé l'information facilement.
De même concernant l'attestation, je n'ai pas retrouvé la mention dans le PDF.

2024-09-04 14:13 UTC, jenovateurs commented on data/benefits/javascript/centre-val-de-loire-aide-depot-garantie.yml
L'information de date de début et de fin est intéressante pour passer les aides en privé automatiquement.

2024-09-12 08:26 UTC, yasmine-glitch commented on data/benefits/javascript/centre-val-de-loire-aide-depot-garantie.yml
Ok c'est noté dans le Grist de suivi des aides à calendrier.

2024-09-12 14:07 UTC, jenovateurs approved these changes
Tout est bon :-)

2024-09-13 10:10 UTC, merged