Mets à jour 2 aides et cache 1 aide.
betagouv/aides-jeunes pull request #4593
Opened 2024-09-05 09:31 UTC by yasmine-glitch

2024-09-05 10:06 UTC, jenovateurs requested changes
Merci pour les MAJ, j'ai juste une question concernant la fin d'une aide.

2024-09-05 10:06 UTC, jenovateurs commented on data/benefits/javascript/region-auvergne-rhone-alpes-bourse-mobilite-internationale-lycee-apprentissage.yml
> +private: true
Ce n'est pas ce lien ? https://www.auvergnerhonealpes.fr/aides/me-former-letranger-avec-la-bourse-region-mobilite-internationale-lyceens-0
Ou c'est une autre aide ?

2024-09-12 10:56 UTC, yasmine-glitch commented on data/benefits/javascript/region-auvergne-rhone-alpes-bourse-mobilite-internationale-lycee-apprentissage.yml
> +private: true
C'est bien la même aide, qui avait disparu pendant l'été et a été relancée en septembre pour la rentrée. J'ai mis l'info dans le Grist.

2024-09-12 14:04 UTC, jenovateurs approved these changes
Tout est bon pour moi.

2024-09-13 10:10 UTC, merged