Réactive 4 aides (private: true => aide disponible à nouveau)
betagouv/aides-jeunes pull request #4594
Opened 2024-09-05 14:42 UTC by yasmine-glitch

Les deux aides de la Loire Atlantique (Permis B et permis AM) doivent être également modifiées dans OF
tests/departements/loire_atlantique/aide_mobilite.yml

2024-09-12 13:58 UTC, jenovateurs requested changes
Quelques petites modifications et pour OpenFisca, je vais regarder :-). Merci de l'avoir vu.

2024-09-12 13:58 UTC, jenovateurs commented on data/benefits/javascript/caf-puy-de-dome-aide-bafa-generale.yml
> +link: https://caf.fr/allocataires/caf-du-puy-de-dome/offre-de-service/vie-personnelle/aide-au-bafa#:~:text=Le%20dispositif%20local,partir%20du%201er%20janvier%202024.
Le principe est que dans l'url, il y a la propriété text, celle-ci va chercher dans la page web cette suite de mot pour positionner l'utilisateur ou l'utilisatrice. En mettant trop de mots, on risque de ne pas pouvoir bien positionner la personne.

2024-09-12 13:58 UTC, jenovateurs commented on data/benefits/javascript/caf-puy-de-dome-aide-bafa-generale.yml
> +instructions: https://caf.fr/allocataires/caf-du-puy-de-dome/offre-de-service/vie-personnelle/aide-au-bafa#:~:text=Le%20dispositif%20local,partir%20du%201er%20janvier%202024.
```suggestion
instructions: https://caf.fr/allocataires/caf-du-puy-de-dome/offre-de-service/vie-personnelle/aide-au-bafa#:~:text=Le%20dispositif%20local
```

2024-09-12 13:58 UTC, jenovateurs commented on data/benefits/javascript/caf_haute_garonne-aide-complémentaire-au-bafa-handicap.yml
> +    href="https://www.calameo.com/read/003857823386e1cb70e9e">l'attestation (PDF)</a>
On est obligé d'utiliser calameo ? Car c'est pas un site institutionnel.

2024-09-13 10:41 UTC, yasmine-glitch commented on data/benefits/javascript/caf_haute_garonne-aide-complémentaire-au-bafa-handicap.yml
> +    href="https://www.calameo.com/read/003857823386e1cb70e9e">l'attestation (PDF)</a>
OK j'ai remis un pdf ciblé sur la page qui va bien

2024-09-13 11:28 UTC, yasmine-glitch commented
@jenovateurs sur OF il est écrit que l'aide est de150 € pour le permis moto et 750 € pour le permis auto.
Sur le site de la Loire Atlantique c'est 100 € pour la moto et 500 € pour l'auto.
Lien de la page OF à laquelle je fais référence : https://github.com/openfisca/openfisca-france-local/blob/c02824bfb8a03082c4a93554db11374b5b3025e4/tests/departements/loire_atlantique/aide_mobilite.yml

2024-09-18 08:27 UTC, jenovateurs commented
> Loire Atlantique

J'ai fait un autre ticket et c'est en cours #4610.

2024-10-09 14:27 UTC, yasmine-glitch commented
@jenovateurs j'ai testé les aides permis auto / moto de la Loire Atlantique et ça fonctionne correctement : on peut merger.

2024-10-10 09:31 UTC, jenovateurs approved these changes
Tout est bon pour moi @yasmine-glitch . Merci pour l'implémentation.

2024-10-10 09:43 UTC, merged