Ajoute le Revenu Minimum Etudiant de la ville de Chenôve
betagouv/aides-jeunes pull request #4595
Opened 2024-09-05 15:24 UTC by yasmine-glitch

2024-09-11 13:32 UTC, jenovateurs requested changes

2024-09-12 11:48 UTC, yasmine-glitch commented on data/benefits/javascript/ville_chenove_revenu_minimum_etudiant.yml
> +          - terminale
Pour que les lycéens en terminale puissent préparer la rentrée universitaire et se projeter.

2024-09-12 11:49 UTC, yasmine-glitch commented
@jenovateurs j'en ai profité pour reformuler les 3 aides RME, en retirant le saut de ligne dans la description.
Et j'ai aussi màj la description du RME de Petit-Couronne, suite à un email reçu de la collectivité.

2024-09-12 12:31 UTC, jenovateurs approved these changes
Tout est ok pour moi @yasmine-glitch , merci pour tes modifications et j'ai résolu les conflits de fichier.

2024-09-13 11:30 UTC, merged