Ajoute la mutuelle communale de Montpellier
betagouv/aides-jeunes pull request #4640
Opened 2024-10-02 16:06 UTC by Shamzic

En attente de la mise en oeuvre de cette mutuelle.
En attente de la PR de modélisation sur Openfisca: https://github.com/openfisca/openfisca-france-local/pull/216

2024-10-04 12:49 UTC, jenovateurs requested changes
Quelques commentaire sur le texte, sinon merci pour l'ajout @Shamzic

2024-10-04 12:49 UTC, jenovateurs commented on data/benefits/openfisca/montpellier_mutuelle_communale.yml
> +description: La ville de Montpellier met à disposition de ses habitants une mutuelle communale avantageuse financièrement.
J'ai un doute sur l'expression "avantageuse financièrement" car on ne peux pas le prouver.
Peut-être mettre que la ville a négocié plusieurs offres pour les citoyens et citoyennes de la ville ?

2024-10-04 12:49 UTC, jenovateurs commented on data/benefits/openfisca/montpellier_mutuelle_communale.yml
> +description: La ville de Montpellier met à disposition de ses habitants une mutuelle communale avantageuse financièrement.
J'ai aussi souvenir que les étudiants n'habitant pas à Montpellier mais étudiants dans un établissement de la ville est également éligible mais il faudrait la source ou document qui le prouve.

2024-10-04 12:49 UTC, jenovateurs commented on data/benefits/openfisca/montpellier_mutuelle_communale.yml
> +  - type: communes
La condition générale n'est pas liée au paramétrage OF ?

2024-10-07 08:46 UTC, Shamzic commented on data/benefits/openfisca/montpellier_mutuelle_communale.yml
> +description: La ville de Montpellier met à disposition de ses habitants une mutuelle communale avantageuse financièrement.
> J'ai un doute sur l'expression "avantageuse financièrement" car on ne peux pas le prouver. Peut-être mettre que la ville a négocié plusieurs offres pour les citoyens et citoyennes de la ville ?

On a tous ce doute je crois. ^^ 
Cela dit , je n'ai pas plus d'informations en l'état

> J'ai aussi souvenir que les étudiants n'habitant pas à Montpellier mais étudiants dans un établissement de la ville est également éligible mais il faudrait la source ou document qui le prouve.

Je n'ai pas trouvé cette infos dans les échanges par mail?

2024-10-07 08:47 UTC, jenovateurs commented on data/benefits/openfisca/montpellier_mutuelle_communale.yml
> +description: La ville de Montpellier met à disposition de ses habitants une mutuelle communale avantageuse financièrement.
C'était lors de la dernière visio. On aura plus d'info bientôt je suppose.

2024-10-07 14:21 UTC, yasmine-glitch commented on data/benefits/openfisca/montpellier_mutuelle_communale.yml
> +description: La ville de Montpellier met à disposition de ses habitants une mutuelle communale avantageuse financièrement.
En effet, les étudiants qui résident dans les villes x et y et étudients à Montpellier sont éligibles aussi.
Je vais envoyer la version test de l'aide aux personnes du CCAS pour validation du texte avec eux.

2024-10-07 17:12 UTC, Shamzic commented on data/benefits/openfisca/montpellier_mutuelle_communale.yml
> +description: La ville de Montpellier met à disposition de ses habitants une mutuelle communale avantageuse financièrement.
Ça marche, cependant on ne peut pas récupérer cette donnée en l'état avec le simulateur

2024-10-14 09:54 UTC, jenovateurs commented on data/benefits/openfisca/montpellier_mutuelle_communale.yml
> +description: La ville de Montpellier met à disposition de ses habitants une mutuelle communale avantageuse financièrement.
L'idée pour moi était juste de l'ajouter en texte dans l'aide pour passer aux amis, ...

2024-10-14 09:56 UTC, jenovateurs requested changes
Ajout dans la description de l'aide la mention de "accessible pour les personnes étudiants sur Montpellier", si par hasard des simulations sont faites en mettant Montpellier comme lieu d'habitation pour voir les dispositifs.

2024-10-14 10:22 UTC, Shamzic commented
@yasmine-glitch @jenovateurs j'ai un peu reformé la description

2024-10-14 10:27 UTC, jenovateurs approved these changes
Parfait, merci à toi.

2024-10-14 11:51 UTC, merged