Aides OF - aide28 > AJ
betagouv/aides-jeunes pull request #4641
Opened 2024-10-03 13:02 UTC by jenovateurs

2024-10-03 13:03 UTC, jenovateurs commented
Pour info, j'ai vérifié avec des simulations que les résultats s'affichaient correctement.
Par contre, je n'arrive pas à trouver d'info concernant ce dispositif : openfisca_france_local/departements/eure_et_loir/transport_social.py

2024-10-09 15:05 UTC, yasmine-glitch commented
@jenovateurs pour trouver les aides de l'Eure et Loire il faut faire une simulation sur le site Mes Aides 28 en simulant une situation d'éligibilité. Pour trouver le dispositif "transport social" j'ai dit que je percevais le RSA.
[Mes Aides 28.pdf](https://github.com/user-attachments/files/17310451/Mes.Aides.28.pdf)

2024-10-11 08:40 UTC, Shamzic requested changes

2024-10-11 08:40 UTC, Shamzic commented on data/benefits/openfisca/eure_et_loir_eligibilite_transport_social.yml
> +prefix: le
```suggestion
prefix: l’
```

2024-10-11 09:05 UTC, Shamzic commented on data/benefits/openfisca/eure_et_loir_eligibilite_adefip.yml
> +  - Faire la demande avec le référent RSA <a href="https://mesdemarches.eurelien.fr/media/uploads/2023/01/05/formulaire-demande-adefip-pdf.pdf" rel="noopener" target="_blank" title="Site Mes démarche
Les usagers ne connaissent pas le mot "téléservice", c'est pour cela que le texte affiché pour le lien du téléservice est "Faire une demande en ligne"

```suggestion
  - Faire la demande avec le référent RSA <a href="https://mesdemarches.eurelien.fr/media/uploads/2023/01/05/formulaire-demande-adefip-pdf.pdf" rel="noopener" target="_blank" title="Site Mes démarches euréliens - Nouvelle fenêtre">par écrit</a> ou <a href="https://formulaires.mesdemarches.eurelien.fr/vous-etes-un-partenaire-referent-d-un-beneficiaire-rsa-1/" rel="noopener" target="_blank" title="Teleservice demande - Nouvelle fenêtre">en ligne</a>.
```

2024-10-11 14:00 UTC, jenovateurs commented
J'approuve tes modifications @yasmine-glitch  mais étant à l'orgine de la PR, je ne peux pas le faire moi-même.

2024-10-14 10:21 UTC, Shamzic approved these changes

2024-10-14 10:26 UTC, merged