Ajoute le revenu minimum étudiant de la ville de Cerizay.
betagouv/aides-jeunes pull request #4642
Opened 2024-10-03 14:55 UTC by yasmine-glitch

2024-10-04 12:54 UTC, jenovateurs requested changes
Quelques petits points à corriger.
Merci @yasmine-glitch :-).

2024-10-04 12:54 UTC, jenovateurs commented on data/benefits/javascript/ville_cerizay_revenu_minimum_etudiant.yml
> +  - Compléter <a target="_blank" title="Formulaire de demande Revenu Minimum Etudiant de Cerizay - Nouvelle fenêtre" rel="noopener" href="file:///Users/yasmineberrada/Downloads/Dossier%20inscription%
```suggestion
  - Compléter <a target="_blank" title="Formulaire de demande Revenu Minimum Etudiant de Cerizay - Nouvelle fenêtre" rel="noopener" href="https://cerizay.fr/index.php/acces-rapide/telechargements/category/11-education-et-jeunesse?download=1052:dossier-rme-2024-2025f">le dossier de demande<a/> et le déposer en mairie de Cerizay.
```

2024-10-04 12:54 UTC, jenovateurs commented on data/benefits/javascript/ville_cerizay_revenu_minimum_etudiant.yml
> +form: file:///Users/yasmineberrada/Downloads/Dossier%20inscription%20RME%202024-2025.pdf
```suggestion
form: https://cerizay.fr/index.php/acces-rapide/telechargements/category/11-education-et-jeunesse?download=1052:dossier-rme-2024-2025
```

2024-10-04 12:54 UTC, jenovateurs commented on data/benefits/javascript/ville_cerizay_revenu_minimum_etudiant.yml
> +montant: 1000
Je n'ai pas trouvé la mention max 1000, quelle est ta source ?

2024-10-07 18:10 UTC, yasmine-glitch commented on data/benefits/javascript/ville_cerizay_revenu_minimum_etudiant.yml
> +montant: 1000
C'est à la page 4 du dossier d'inscription : https://cerizay.fr/index.php/acces-rapide/telechargements/category/11-education-et-jeunesse?download=1052:dossier-rme-2024-2025

"Le montant maximum du RME s’élèvera à 1000€ par année scolaire et par étudiant soit maximum 100€ par mois par étudiant."

2024-10-10 09:27 UTC, jenovateurs approved these changes
Tout est bon pour moi.

2024-10-10 09:46 UTC, merged