Fixbug adresse destination invalide (envoi de SMS)
betagouv/aides-jeunes pull request #4648
Opened 2024-10-08 16:02 UTC by Shamzic

Certains numéros de SMS sont validés par le front mais par valides pour autant en backend.   : 
<details>
      <summary>Exemple de numéro invalide</summary>
      ```
      +594 696 00 01 02
      ```
    </details>

Cette correction remonte l'erreur "adresse de destination invalide" soulevée par le backend et l'interprête sur le front avec un message spécifique.

2024-10-08 16:15 UTC, jenovateurs commented
C'est un doublon avec cette PR @Shamzic : https://github.com/betagouv/aides-jeunes/pull/4643 ?

2024-10-09 10:07 UTC, Shamzic commented
> C'est un doublon avec cette PR @Shamzic : #4643 ?

Ça ne corrige pas la même chose, non

2024-10-11 15:39 UTC, jenovateurs requested changes
Plus des questions et remarques.

2024-10-11 15:39 UTC, jenovateurs commented on backend/controllers/followups.ts
> +    return res.status(500).send(error.message)
Ajout d'un Sentry pour envoyer l'erreur ?

2024-10-11 15:39 UTC, jenovateurs commented on backend/lib/messaging/sms/sms-service.ts
> +    followup.smsError = JSON.stringify(error, null, 2)
Tu as pu tester ? Cela ne va pas faire de doublon json entre ici et la génération de la réponse.

2024-10-11 15:39 UTC, jenovateurs commented on src/components/modals/errors-email-and-sms-modal.vue
> +          numéro valide ou utiliser l'envoi par email.
```suggestion
          numéro valide ou utiliser l'envoi par email seulement.
```

2024-10-11 15:39 UTC, jenovateurs commented on src/components/recap-email-and-sms-form.vue
> +    if (!error?.response?.data?.includes("Invalid destination address")) {
À voir, s'il ne faudrait pas avoir une constante pour gérer les « codes d'erreur », comme ça on pourrait voir le lien entre l'erreur envoyée en back et reçue en front.

2024-10-17 16:42 UTC, Shamzic commented
Rebase avec l'intégration le refacto de la #4652

2024-10-17 16:43 UTC, Shamzic commented on backend/controllers/followups.ts
> +    return res.status(500).send(error.message)
Ajouté avec la #4652

2024-10-17 17:26 UTC, Shamzic commented on backend/lib/messaging/sms/sms-service.ts
> +    followup.smsError = JSON.stringify(error, null, 2)
Je ne sais pas si j'ai bien compris mais normalement oui la condition sur le `Sentry.captureException(error)` est effective et j'ai aussi trouvé un problème ici => j'ai corrigé la sauvegarde du message d'erreur ici https://github.com/betagouv/aides-jeunes/pull/4648/commits/2b91c53b9367938e30d1d18751ce76ca9c15435d

2024-10-17 17:34 UTC, Shamzic commented on src/components/recap-email-and-sms-form.vue
> +    if (!error?.response?.data?.includes("Invalid destination address")) {
À mes yeux, le lien est plutôt explicite ici en regardant le contenu de `error.response.data`, je suis preneur d'un exemple si tu as une meilleure implémentation

2024-10-28 09:13 UTC, jenovateurs approved these changes
Tout est bon pour moi

2024-10-28 14:24 UTC, merged