Refactoring: améliore la gestion des erreurs des followups
betagouv/aides-jeunes pull request #4652
Opened 2024-10-15 12:25 UTC by Shamzic

PR intermédiaire à #4648 

- Ajoute d'un type enum pour les statuts et les messages d'erreur
- Centralise la remontée des erreurs dans la persistance du followup
- Modifications ouvertes à toute suggestion d'amélioration

2024-10-16 06:56 UTC, jenovateurs requested changes
Quelques petites modifications, je pense que je vais devoir adapter l'autre PR sur le sujet ou l'annuler.

2024-10-16 06:56 UTC, jenovateurs commented on backend/controllers/followups.ts
> +      if (email) await sendSimulationResultsEmail(followup)
J'aurais inversé, d'abord l'e-mail et ensuite le téléphone car plus de chance que le premier fonctionne.
On pourra aussi adapter le message en mode erreur avec le numéro de téléphone, l'email a bien été envoyer ressayer plus tard ou un truc du genre.

2024-10-16 06:56 UTC, jenovateurs commented on backend/controllers/followups.ts
>      Sentry.captureException(error)
À postériori, je me demande si le captureException et le console error est pertinent, sachant qu'on ne retrouve plus le survey.

2024-10-16 12:52 UTC, Shamzic commented on backend/controllers/followups.ts
> +      if (email) await sendSimulationResultsEmail(followup)
Peut-être dans un second temps, faire les deux envois séparément avec des messages dédié à chaque service ?

2024-10-16 12:54 UTC, Shamzic commented on backend/controllers/followups.ts
>      Sentry.captureException(error)
Le console.error c'est sûr qu'il n'est pas utile. Le captureException, comme tu avais pris l'initiative de l'ajouter, je te laisse décider si tu souhaites le retirer. Je l'aurais aussi enlevé de mon côté

2024-10-28 09:14 UTC, jenovateurs commented on backend/controllers/followups.ts
>      Sentry.captureException(error)
Je te propose de le retirer alors.

2024-10-28 09:15 UTC, jenovateurs requested changes
Supprimer le SentryError plutôt mieux traiter maintenant.

2024-10-28 09:15 UTC, jenovateurs commented on backend/controllers/followups.ts
>      Sentry.captureException(error)
```suggestion

```

2024-10-28 16:04 UTC, closed without merging