Mise à jour - covoiturage
betagouv/aides-jeunes pull request #4654
Opened 2024-10-16 07:27 UTC by jenovateurs

2024-10-17 12:41 UTC, yasmine-glitch commented
Pour les codes SIRET introuvables :
- 218501633 c'est la commune de l'île de Noirmoutier => un seul code postal 85330
- j'ai remplacé 393623939 (siren de la société Keolis dans la CC Tarbes LOurdes Pyrénées) par 200069300 (Siren de la CC Tarbes Lourdes Pyrénées) => signalé à Victor au cas où ce soit une erreur

2024-10-24 11:00 UTC, Shamzic requested changes
J'ai resize les images  (commit direct) et une suggestion pour une condition qui me semble avoir évoluée, mais je veux bien votre validation

2024-10-24 11:00 UTC, Shamzic commented on data/benefits/dynamic/incitations-covoiturage.json
> -    "link": "https://cc-alsacerhinbrisach.fr/vos-services/deplacements/covoiturage/",
Celui là me semble toujours d'actualité (?)

2024-10-24 11:00 UTC, Shamzic commented on data/benefits/dynamic/incitations-covoiturage.json
> -    "link": "https://www.aunisatlantique.fr/vies-pratique-et-associative/transports-et-mobilite/covoiturage/",
Lui aussi (?)

2024-10-24 11:00 UTC, Shamzic commented on data/benefits/dynamic/incitations-covoiturage.json
> -    "link": "https://www.paysflechois.fr/actualites/le-covoiturage-facilite/",
Lui aussi (?)

2024-10-24 11:00 UTC, Shamzic commented on data/benefits/dynamic/incitations-covoiturage.json
> -    "link": "https://www.grandpoitiers.fr/au-quotidien/deplacements/partage-des-voitures/covoiturage",
Citation sur le lien :

> "jusqu’au 31 décembre 2024 ou jusqu’à épuisement de l’enveloppe dédiée. " 

C'est déjà épuisé là ?

2024-10-24 11:00 UTC, Shamzic commented on data/benefits/dynamic/incitations-covoiturage.json
> -    "link": "https://www.picardieverte.com/la-ccpv-paie-vos-covoiturages/urbanisme-habitat/mobilite/",
Toujours d'actu (?)

2024-10-24 11:00 UTC, Shamzic commented on data/benefits/dynamic/incitations-covoiturage.json
> +    "conducteur_montant_min_par_passager": 1.5,
```suggestion
    "conducteur_montant_min_par_passager": 1.25,
```

2024-10-24 11:00 UTC, Shamzic commented on data/benefits/dynamic/incitations-covoiturage.json
> +    "conducteur_montant_min_par_passager": 2.25,
```suggestion
    "conducteur_montant_min_par_passager": 2,
```

2024-10-24 13:50 UTC, Shamzic approved these changes

2024-10-28 09:16 UTC, merged