Formulation d'informations sur la question de l'inaptitude au travail
betagouv/aides-jeunes pull request #4660
Opened 2024-10-18 14:49 UTC by Shamzic

Ouvert aux suggestions

2024-10-18 15:18 UTC, jenovateurs commented
> ## Description
> 
> Ouvert aux suggestions!
> 
> D'après vous, est-ce que ceci est correct ? ⬇️
> 
> > Qu’elle soit totale ou temporaire, il est suggéré de répondre par Oui à la question sur l’inaptitude au travail lors de votre simulation.
> 
> Concernant le point "Ordre des questions entre handicap et inaptitude" => Je n'ai plus en tête la raison de ce choix: est-ce acté qu'on inverse l'ordre de ces deux questions ?
> ## Sources
> 
>     * https://travail-emploi.gouv.fr/la-reconnaissance-de-linaptitude-medicale-au-travail-et-ses-consequences
> 
>     * https://fmh-association.org/etre-declare-inapte-au-travail/#:~:text=Le%20salari%C3%A9%20b%C3%A9n%C3%A9ficiera%20d'une,ses%20capacit%C3%A9s%20physiques%20ou%20mentales.

L'idée était d'évaluer les impacts d'inverser la question du handicap vs incapacité.

2024-10-18 15:23 UTC, jenovateurs requested changes
Sur le principe je suis ok.
Mais j'aurais ajouté une petite phrase sous la question pour préciser du style
" inapte (AH, ... ) ou inaptitude temporaire ".
Ou un autre ticket concernant le bouton en savoir plus (pas suffisamment visible ?) car la personne qui a fait le test n'avait pas trouvé de solution.

2024-10-21 12:45 UTC, Shamzic commented
> L'idée était d'évaluer les impacts d'inverser la question du handicap vs incapacité.

Ok pour le faire dans une autre PR, quels seraient les critères de mesure ?

2024-10-21 13:22 UTC, jenovateurs commented
> > L'idée était d'évaluer les impacts d'inverser la question du handicap vs incapacité.
> 
> Ok pour le faire dans une autre PR, quels seraient les critères de mesure ?

Vérifier si c'est plus logique en terme de compréhension en mode, tu es dans une situation de handicap, mais est-ce que tu es en incapacité de travaillé.
Cela permettrait aussi d'éviter d'associer handicap et incapacité.
La mesure serait aussi de vérifier si les aides obtenus sont les même ou non et si l'enchainement des questions reste le bon si on fait varier les réponses. Quand penses-tu @Shamzic ?

2024-10-21 13:22 UTC, jenovateurs approved these changes
C'est ok pour moi, il suffit "juste" de crée le nouveau ticket associé.

2024-10-21 14:52 UTC, Shamzic commented
> Vérifier si c'est plus logique en terme de compréhension en mode, tu es dans une situation de handicap, mais est-ce que tu es en incapacité de travaillé. Cela permettrait aussi d'éviter d'associer handicap et incapacité. La mesure serait aussi de vérifier si les aides obtenus sont les même ou non et si l'enchainement des questions reste le bon si on fait varier les réponses. Quand penses-tu @Shamzic ?

J'ai du mal à me projeter dans ces deux situations pour cerner le problème de fond car pour moi être en situation de handicap et être en incapacité de travail sont deux choses bien distinctes mais tu sembles avoir plus de billes pour ce sujet ensemble, j'ai fait un ticket

2024-10-21 14:56 UTC, merged