Amélioration de la barre de recherche
betagouv/aides-jeunes pull request #4661
Opened 2024-10-18 15:16 UTC by jenovateurs

1ère itération simple de recherche.
Une deuxième permettrait de faire une recherche dans le contenu ou associer des mots-clés.

2024-10-21 13:36 UTC, Shamzic requested changes
En l'état, la recherche ne fonctionne que sur les 5 premiers caractères car le watcher qui génère les aides affichées est basé sur le code postal, il faudrait adapter cela aux mots-clés qui peuvent être de taille différente

2024-10-21 13:36 UTC, Shamzic commented on src/views/liste-aides.vue
> +import { Benefit } from "@data/types/benefits"
L'import de Benefit n'est pas nécessaire si on type correctement la nouvelle variable 
```suggestion
```

2024-10-21 13:36 UTC, Shamzic commented on src/views/liste-aides.vue
> +const selectedBenefits = ref<Benefit | null>()
Suggestion de nom pour cette variable qui semble concerner les mots-clés 

```suggestion
const searchTerms = ref<string | null>()
```

2024-10-21 13:36 UTC, Shamzic commented on src/views/liste-aides.vue
> +              >Filtrer par code postal ou mot-clés :</label
```suggestion
              >Filtrer par code postal ou mots-clés :</label
```

2024-10-21 13:36 UTC, Shamzic commented on src/views/liste-aides.vue
> +  }
Suggestion d'alternative plus concise (pas obligatoire)

```suggestion
  if (searchTerms.value) {
    return Object.fromEntries(
      Object.keys(types).map((type) => [type, filterByBenefit(type)])
    )
  }
```

2024-10-21 15:13 UTC, Shamzic commented on src/views/liste-aides.vue
> +  if ([0, 3].includes(newZipCode.length)) {
Ce n'est pas vraiment ce qui est attendu dans une recherche par mot clef, ici la recherche sera déclenché si la barre contient soit 0 soit 3 caractères. J'aurais tendance à proposer ceci :

```suggestion
  if (newZipCode.length > 0) {
```

2024-10-22 16:06 UTC, jenovateurs commented on src/views/liste-aides.vue
> +  if ([0, 3].includes(newZipCode.length)) {
> Ce n'est pas vraiment ce qui est attendu dans une recherche par mots-clés, ici la recherche sera déclenchée si l'input contient soit 0, soit 3 caractères. J'aurais tendance à proposer ceci :

Bien vu, j'ai améliorer ta recherche en mode > 2, c'est une recommendation du RGESN (normalement > 3) mais bon pour FSL c'est trois caractères.

2024-10-23 10:40 UTC, Shamzic commented on src/views/liste-aides.vue
> +  if ([0, 3].includes(newZipCode.length)) {
Ok nickel la reco !

2024-10-23 10:45 UTC, Shamzic approved these changes

2024-10-23 10:45 UTC, merged