feat: rework page d'accueil
betagouv/aides-jeunes pull request #4679
Opened 2024-10-25 15:47 UTC by Shamzic

2024-12-18 17:16 UTC, jenovateurs requested changes
- Iframe : de mon point de vue, il faudrait en faire une dédiée à ce contexte.
- Proposition de changement du label du bouton secondaire : Accéder à la liste complète des aides  ==> Accéder à la liste des aides 
- Sur le bandeau des + de la plateforme, j'aurais maj le contenu de la boite gratuit. Car le contre de cela : "Si c'est gratuit, c'est toi le produit" et je propose d'ajouter un laïus sur la protection des données personnelles.
- Sur la section : Comment ça marche ? => je propose la suppression des sous-descriptions car il y a de la répétition (typiquement : "5 minutes suffisent pour compléter une simulation")
– Sur les logos partenaires, je pense que les logos ministériels devraient être plus visibles et donc découpés (typiquement celui sur les jeunes).
- Du point de vue de l’Impact, on passe de la note de B à D (forcément à cause du coût des images). Je me demande si on peut ajouter du lazy loading pour les logos partenaires.

2025-01-07 13:47 UTC, jenovateurs commented on src/components/home/features-section.vue
> +      "<b>Public et gratuit</b> : vos données personnelles sont protégées et ne sont jamais utilisées à des fins commerciales, conformément au RGPD.",
conformément à notre politique de confidentialité avec lien à mettre :-).

2025-01-07 13:54 UTC, Shamzic commented
> Je n'ai plus la liste des partenaires ou listing des aides, c'est normal ?

Oui, j'ai commenté les pages car cela fait baisser la note d'ecoindex, mais tu peux les décommenter pour voir ce que ça donne.

2025-01-07 14:12 UTC, jenovateurs commented
Petit commentaire supplémentaire pour l'ajout du petit logo, lien (externe) sur le lien équipe et politique de confidentialité dans les petit encadré au début.

2025-01-07 14:22 UTC, Shamzic commented
> Petit commentaire supplémentaire pour l'ajout du petit logo, lien (externe) sur le lien équipe et politique de confidentialité dans les petit encadré au début.

Ok pour le lien vers la page d'équipe. Pour la politique de confidentialité, c'est pas mieux de conserver l'ouverture dans la même fenêtre sans ouvrir un nouvel onglet ? (vu que c'est une page interne)

2025-01-07 14:29 UTC, yasmine-glitch commented
Merci beaucoup Simon !
Je propose de cette petite modification. Qu'en penses-tu ?
<img width="1348" alt="Capture d’écran 2025-01-07 à 15 29 03" src="https://github.com/user-attachments/assets/5d63958d-41f2-4fe0-9a4e-4ce33eae6b94" />

2025-01-08 10:51 UTC, Shamzic commented
> Ici, "je suis accompagné" est trop vague à mon sens. 

J'avais mis des petites descriptions en dessous précédemment: https://github.com/betagouv/aides-jeunes/pull/4679/commits/fa11f61de96b927d5479dc581f62470677e67382 et Jérémy a suggéré de les retirer car il y avait de la redondance. Comment vois-tu la chose ici ?

>Est-ce qu'on pourrait mettre un lien vers une page "trouver de l'aide près de chez moi" sur laquelle la personne renseigne son code postal et voit la liste des lieux d'accompagnement ? Je sais que ça demande du travail en plus donc dans un premier temps on peut enlever le point 4.

Je peux retirer ce point et faire la page d'accompagnement plus tard dans une autre PR

2025-01-13 16:33 UTC, yasmine-glitch approved these changes
Ok pour moi.
Dernières suggestions 
- écrire formation au singulier (dans l'énumération du premier bloc)
- réorganiser les logos des partenaires pour avoir mettre bordeaux sur la même ligne que les autres collectivités, covoiturage.beta sur la même ligne que les autres services numériques avec lesquels on collabore, et enfin jeunes.gouv et étudiants.gouv sur la même ligne

2025-01-13 17:40 UTC, Shamzic commented
> réorganiser les logos des partenaires pour avoir mettre bordeaux sur la même ligne que les autres collectivités, covoiturage.beta sur la même ligne que les autres services numériques avec lesquels on collabore, et enfin jeunes.gouv et étudiants.gouv sur la même ligne

L'affichage dynamique en fonction de la largeur de l'écran peut poser un soucis d'ordre pour ces logos. Est-ce que cela conviendrait comme ça ? Aussi, j'ai créé / repris des logos de ce que j'ai trouvé sur internet, mais si vous avez mieux, je suis prenneur!

2025-01-27 11:24 UTC, jenovateurs approved these changes
Testé et validé

2025-01-29 13:47 UTC, merged