Mise à jour du paquet mesaidesvelo avec le paquet betagouv
betagouv/aides-jeunes pull request #4705
Opened 2024-11-05 17:24 UTC by Shamzic

Reprise de la PR de EmileRolley #4695

2024-11-08 14:30 UTC, Shamzic commented
Je me suis permis quelques refacto @EmileRolley @jenovateurs preneur de vos retours (:

2024-11-11 16:49 UTC, jenovateurs requested changes
Premier retour sur certains aspects. Merci pour cette intégration !

2024-11-12 15:06 UTC, Shamzic commented on tests/integration/benefits-description.spec.ts
> +            expect(innerText.length).toBeLessThanOrEqual(600)
598 pour la plus longue actuellement, cela dit il y en a vraiment peu qui dépassent l'ancienne limite de 420

2024-11-12 15:10 UTC, EmileRolley commented on tests/integration/benefits-description.spec.ts
> +            expect(innerText.length).toBeLessThanOrEqual(600)
Vous pouvez proposer des modifications sur les descriptions pour les raccourcir directement dans les règles si vous voulez. Je n'ai pas un avis très fort sur l'édito des descriptions. Si vous avez des idées d'ailleurs n'hésitez pas.

2024-11-12 15:30 UTC, Shamzic commented on tests/integration/benefits-description.spec.ts
> +            expect(innerText.length).toBeLessThanOrEqual(600)
@EmileRolley Merci pour le retour, j'ai fait une issue pour en parler directement sur ton répo https://github.com/betagouv/publicodes-aides-velo/issues/10

2024-11-20 13:14 UTC, Shamzic commented on tests/integration/benefits-description.spec.ts
> +            expect(innerText.length).toBeLessThanOrEqual(600)
Modification proposée ici : https://github.com/betagouv/publicodes-aides-velo/pull/18

2024-11-22 10:13 UTC, jenovateurs reviewed
En attente du merge de la PR https://github.com/betagouv/publicodes-aides-velo/pull/18
pour valider cette PR.
@EmileRolley aurais-tu un peu de temps pour y jeter un œil ?
Merci d'avance.

2024-11-29 10:39 UTC, jenovateurs requested changes
Présence de doublon dans les noms d'aide, on dirait un bug. Des idées pour son amélioration ?
<img width="407" alt="Screenshot 2024-11-29 at 11 31 13" src="https://github.com/user-attachments/assets/3ef06856-a628-44aa-a394-392ea22c6cb8">
<img width="407" alt="Screenshot 2024-11-29 at 11 31 54" src="https://github.com/user-attachments/assets/a9b432ce-c50a-4a0c-af8f-95ec6f6ee2db">

<img width="407" alt="Screenshot 2024-11-29 at 11 34 45" src="https://github.com/user-attachments/assets/ccb29f27-7a86-42b1-b169-9921bd2f64c9">

Si je suis les règles établit dans betagouv/aides-velo, les dispositifs PMR : 
Vélo adapté pour PMR
Nécessite en tout cas pour l'Hérault (j'ai pas vérifié les autres) d'être en situation de handicap. Ma suggestion est d'ajouter la checkbox dans ce cas là. Qu'en penses-tu ? @Shamzic

2024-11-29 14:35 UTC, Shamzic commented
> Présence de doublon dans les noms d'aide, on dirait un bug. Des idées pour son amélioration ?

Ce ne sont pas des doublons mais des "variations" d'une aide avec le même nom qu'il faudrait mettre à jour, ou bien fusionner ces aides sur @betagouv/publicode-aides-velo

> Nécessite en tout cas pour l'Hérault (j'ai pas vérifié les autres) d'être en situation de handicap. Ma suggestion est d'ajouter la checkbox dans ce cas là. Qu'en penses-tu ? @Shamzic

Je n'ai pas compris où est-ce que tu veux ajouter une checkbox ?

2024-12-02 08:27 UTC, jenovateurs requested changes

2024-12-02 08:27 UTC, jenovateurs commented on tests/integration/benefits-description.spec.ts
> +            expect(innerText.length).toBeLessThanOrEqual(450)
Il faudrait mettre à jour cette information sur l'outil de contribution.

2024-12-02 09:03 UTC, Shamzic commented on tests/integration/benefits-description.spec.ts
> +            expect(innerText.length).toBeLessThanOrEqual(450)
J'ai oublié de préciser; pourra laisser à 420 (comme avant) après le merge de cette modif https://github.com/betagouv/publicodes-aides-velo/pull/20/files

2024-12-02 09:31 UTC, jenovateurs commented on tests/integration/benefits-description.spec.ts
> +            expect(innerText.length).toBeLessThanOrEqual(450)
Ok trop bien alors si on peux remettre 420.

2024-12-02 09:34 UTC, jenovateurs commented
> Je n'ai pas compris où est-ce que tu veux ajouter une checkbox ?

<img width="358" alt="Screenshot 2024-12-02 at 10 32 34" src="https://github.com/user-attachments/assets/3642ade5-684e-49a9-9d2b-8e7f2ed2fd1a">

Pour moi, si on n'est pas en situation de handicap, on supprime la checkbox.

2024-12-02 09:35 UTC, jenovateurs commented
À tester si le problème inverse n'est pas présent. Je suis en situation de handicap et je coche juste « adapté pour PMR » ; est-ce que les aides d'achat génériques sont affichées quand même, car j'ai l'impression que l'aide PMR est un bonus supplémentaire à l'aide de base.

2024-12-03 11:46 UTC, Shamzic commented on tests/integration/benefits-description.spec.ts
> +            expect(innerText.length).toBeLessThanOrEqual(450)
Yes, d'ailleurs nous avons maintenant accès aux review/merge sur le répo publicodes-aides, si ça te dit (:

2024-12-03 14:36 UTC, Shamzic commented
> Pour moi, si on n'est pas en situation de handicap, on supprime la checkbox.

Ok. J'ai restreint à la condition dans [mon dernier commit](https://github.com/betagouv/aides-jeunes/pull/4705/commits/08d535e84ee53c1050280b5a1be903c7360201b7) pour que le demandeur soit en situation de handicap mais cela pose éventuellement soucis pour le cas où le demandeur n'est pas en situation de handicap mais qu'il a un enfant à sa charge qui est en situation de handicap. Ici, la case ne sera pas affichée mais est-ce qu'il serait quand même bénéficiaire d'une aide vélo pour PMR dû au handicap de son enfant ?

2024-12-03 15:25 UTC, Shamzic commented
> À tester si le problème inverse n'est pas présent. Je suis en situation de handicap et je coche juste « adapté pour PMR » ; est-ce que les aides d'achat génériques sont affichées quand même, car j'ai l'impression que l'aide PMR est un bonus supplémentaire à l'aide de base.

Il y a deux aides "génériques" (si je comprends bien ce dont tu parles), c'est le bonus vélo et celle de la région Île-de-France. Elles sont bien affichées lorsque l'utilisateur coche uniquement "vélo adapté", la description est dynamique sur le type de vélo choisi. 

Le problème est le suivant : sur mes mesaidesvelo.fr l'affichage est conditionné par un unique type de vélo (ex: la [page des les aides d'un vélo mécanique](https://mesaidesvelo.fr/ville/montpellier?velo=m%C3%A9canique%20simple) et la [page spécifique pour les aides au vélo électrique](https://mesaidesvelo.fr/ville/montpellier?velo=%C3%A9lectrique)). Sur Aides Jeunes, on a le soucis d'avoir le aides de tous les types de vélo affichées ensembles et cela peut porter à confusion vu que l'aide bonus vélo n'est affichée qu'une fois avec un seul type de vélo, malgré le fait que l'utilisateur en ait coché plusieurs (le type générique affiché dans la description est le premier de la liste transmise à mesaidesvelo).

2024-12-03 17:11 UTC, Shamzic commented
@jenovateurs [Cette suggestion](https://github.com/betagouv/aides-jeunes/pull/4705/commits/ef4a0288adce0f6d3ec1de2c788ff0fdac2b3caf) permet de préciser les types de vélo proposés par l'aide pour éviter les doublons (cf ton screen plus haut). C'est plus précis mais le petit inconvénient à cela c'est que le titre de l'aide est un peu long pour certains cas. Qu'en pense-tu ?

2024-12-06 16:29 UTC, jenovateurs commented
Merci pour la prise en compte de ma suggestion.
Pour gérer le problème de longueur, peux-t-on supprimer le nom de la ville, car on a l'info avec le sous-titre ou l'élément parent.
<img width="400" alt="Screenshot 2024-12-06 at 17 28 04" src="https://github.com/user-attachments/assets/ae8b2f4a-681c-4842-9e48-b05919f5d691">
Qu'en penses-tu ?

2024-12-09 15:57 UTC, Shamzic commented
> Merci pour la prise en compte de ma suggestion. Pour gérer le problème de longueur, peux-t-on supprimer le nom de la ville, car on a l'info avec le sous-titre ou l'élément parent. Qu'en penses-tu ?

On peut, mais c'est très spécifique.

2024-12-09 16:08 UTC, Shamzic commented
> > Merci pour la prise en compte de ma suggestion. Pour gérer le problème de longueur, peux-t-on supprimer le nom de la ville, car on a l'info avec le sous-titre ou l'élément parent. Qu'en penses-tu ?
> 
> On peut, mais c'est très spécifique.

2024-12-09 16:18 UTC, Shamzic commented
> Merci pour la prise en compte de ma suggestion. Pour gérer le problème de longueur, peux-t-on supprimer le nom de la ville, car on a l'info avec le sous-titre ou l'élément parent. Qu'en penses-tu ?


Je suis ok, c'est modifié.

2024-12-11 16:14 UTC, Shamzic commented
> Il y a encore des descriptions trop longues sinon c'est top @Shamzic . Concernant le raccourcissement des descriptions, c'est en cours sur le repo dédié ?

Zut, il y a encore la description de aidesvelo_aides_béthune_bruay qui est trop longue..

2024-12-12 16:43 UTC, Shamzic commented
La PR https://github.com/betagouv/publicodes-aides-velo/pull/27 désactive l'aide aidesvelo_aides_béthune_bruay car elle n'est plus valide

2024-12-12 17:42 UTC, EmileRolley commented
> En attente du merge de [betagouv/publicodes-aides-velo#27](https://github.com/betagouv/publicodes-aides-velo/pull/27) qui désactive l'aide aidesvelo_aides_béthune_bruay car elle n'est plus valide

Je peux merge demain si vous voulez !

2024-12-18 17:19 UTC, jenovateurs commented
De nouveau un autre élément trop long. Je te propose d'itérer en local avec le package chargé et checker la CI jusqu'au bout correction par correction. Qu'en penses-tu @Shamzic ?

2024-12-27 09:23 UTC, jenovateurs commented
Pour info : j'ai ajouté notre test de taille de caractère du champ description : https://github.com/betagouv/publicodes-aides-velo/pull/31
Donc en attente de relecture/merge pour retester notre CI.

2025-01-06 07:49 UTC, jenovateurs approved these changes
Après plusieurs tests, tout me semble correcte. Merci pour cette super PR.

2025-01-06 09:03 UTC, merged