Ajoute la Carte Jeunes 01 de l'Ain pour les collégiens.
betagouv/aides-jeunes pull request #4714
Opened 2024-11-06 16:42 UTC by yasmine-glitch

[#4588](https://github.com/betagouv/aides-jeunes/issues/4588)

2024-11-07 13:49 UTC, jenovateurs requested changes
Merci pour l'ajout @yasmine-glitch , quelques petites retouches/interrogations.

2024-11-07 13:49 UTC, jenovateurs commented on data/benefits/javascript/departement_ain_carte_jeunes.yml
> +  - type: age
Ne serait-il pas plus pertinent de se baser sur le type de scolarité (au collège) pour être plus précis, car à 16 ans, si on n’a pas redoubler, on peut être au lycée, non ?

2024-11-07 13:49 UTC, jenovateurs commented on data/benefits/javascript/departement_ain_carte_jeunes.yml
> +  - type: age
Testé en local, c'est toujours dommage qu'on ne puisse pas spécifier les enfants de tel age. Car faire la simulation en tant qu'enfant qui a 10 ans me semble compliqué.

2024-11-07 13:49 UTC, jenovateurs commented on data/benefits/javascript/departement_ain_carte_jeunes.yml
> +    rel="noopener" title="Téléservice demande Carte Jeunes 01 - Nouvelle fenêtre" href="
Ajouter un espace insécable &nbsq;  pour éviter le retour à la ligne 
<img width="916" alt="Screenshot 2024-11-07 at 14 47 10" src="https://github.com/user-attachments/assets/8844bda4-4166-428a-b410-016b92642100">

2024-11-08 07:58 UTC, jenovateurs commented on data/benefits/javascript/departement_ain_carte_jeunes.yml
> +  - type: age
Je vais l'ajouter facilement dans ta PR, si tu es ok.

2024-11-11 16:03 UTC, jenovateurs commented on data/benefits/javascript/departement_ain_carte_jeunes.yml
> +  - type: age
En attente de validation de la #4721

2024-11-21 10:25 UTC, jenovateurs commented on data/benefits/javascript/departement_ain_carte_jeunes.yml
> +  - type: age
PR merge dans main donc merge fait avec cette PR.

2024-11-21 10:26 UTC, jenovateurs commented on data/benefits/javascript/departement_ain_carte_jeunes.yml
> +  - type: age
PR merge donc modification fait ici aussi.

2024-11-21 10:27 UTC, jenovateurs commented on data/benefits/javascript/departement_ain_carte_jeunes.yml
> +    rel="noopener" title="Téléservice demande Carte Jeunes 01 - Nouvelle fenêtre" href="
On ne peux pas le faire, c'est du CSS...

2024-11-21 15:42 UTC, Shamzic commented on data/benefits/javascript/departement_ain_carte_jeunes.yml
> +    rel="noopener" title="Téléservice demande Carte Jeunes 01 - Nouvelle fenêtre" href="
Tu peux le faire en ajoutant ceci par exemple :
```css
[target=_blank] { /* ou .classedulien*/
  white-space: nowrap;
}
```

2024-11-21 15:42 UTC, Shamzic approved these changes

2024-11-21 15:43 UTC, Shamzic commented
C'est bon pour moi , je t'ai mis un commentaire pour le style du lien @jenovateurs

2024-11-21 16:43 UTC, jenovateurs approved these changes
Tout est bon pour moi.

2024-11-21 18:14 UTC, Shamzic commented
Comme Yasmine n'est pas de retour avant un petit moment, je me permets de merger

2024-11-21 18:14 UTC, merged