[Wait Upgrade OF] - Intégration des aides OF de la ville d'Antony dans AJ
betagouv/aides-jeunes pull request #4719
Opened 2024-11-08 12:59 UTC by jenovateurs

En attente de MAJ d'OF pour merge la PR.

2024-11-08 16:37 UTC, Shamzic requested changes

2024-11-08 16:37 UTC, Shamzic commented on data/benefits/openfisca/antony_aide_depart_sejour_adapte.yml
> +entity: individus
```
antony_aide_depart_sejour_adapte: "You tried to compute the variable 'antony_aide_depart_sejour_adapte' for the entity 'individus'; however the variable 'antony_aide_depart_sejour_adapte' is defined for 'familles'. Learn more about entities in our documentation: <https://openfisca.org/doc/coding-the-legislation/50_entities.html>."
```

```suggestion
entity: familles
```

2024-11-08 16:37 UTC, Shamzic commented on data/benefits/openfisca/antony_bourse_communale.yml
> +entity: individus
```suggestion
entity: familles
```

2024-11-08 16:37 UTC, Shamzic commented on data/benefits/openfisca/antony_bourse_conservatoire.yml
> +entity: individus
```suggestion
entity: familles
```

2024-11-08 16:37 UTC, Shamzic commented on data/benefits/openfisca/antony_noel_pour_tous.yml
> +entity: individus
```suggestion
entity: familles
```

2024-11-11 15:56 UTC, jenovateurs commented
MEP après les fix sur la ville d'antony sur OF

2024-11-20 13:53 UTC, Shamzic commented
J'ai cherry-pick les commits de fix depuis la PR #4733

2024-11-20 14:05 UTC, Shamzic commented
Petites modifs sur les yaml des aides et c'est bon pour moi

2024-11-20 15:10 UTC, merged

2024-11-21 09:45 UTC, Shamzic commented
J'aurais attendu le merge du bump car là maintenant ça pollue la PR du bump mais on peut faire comme ça aussi