4723 ajouter un bouton pour commencer une simulation depuis la page toutes les aides
betagouv/aides-jeunes pull request #4743
Opened 2024-11-22 16:19 UTC by Shamzic

Lisible commit par commit

2024-11-25 10:56 UTC, jenovateurs reviewed
Avis purement design, j'aime bien la version mobile.
Pour la version desktop, je la trouve moins uniforme avec le reste. Je te propose de "coller" au bouton retour à l'accueil. Je pense aussi qu'un petit message Mattermost serait utile pour avoir d'autres avis.

2024-12-09 14:21 UTC, jenovateurs commented
Contre proposition pour le desktop  :


<img width="1226" alt="Screenshot 2024-12-09 at 15 20 45" src="https://github.com/user-attachments/assets/b2a6bee6-73d4-4f7a-98dc-59d700055f59">

2024-12-09 14:25 UTC, jenovateurs commented
legère modification
<img width="1226" alt="Screenshot 2024-12-09 at 15 25 26" src="https://github.com/user-attachments/assets/ce9f6881-378d-40ad-bb02-b8c56137e8c5">

2024-12-09 14:28 UTC, jenovateurs commented
Dernière hypothèse
![Uploading Screenshot 2024-12-09 at 15.28.41.png…]()

2024-12-10 09:27 UTC, jenovateurs commented
Résultat final : 
V3 win !

2024-12-16 10:55 UTC, yasmine-glitch approved these changes
ok pour la solution 3 ! Merci beaucoup :)

2024-12-31 08:58 UTC, jenovateurs requested changes
Pour respecter au mieux la V3, il y a une légère différence sur le premier bouton Retour à l'accueil c'est un "fr-btn--tertiary"

2024-12-31 09:00 UTC, jenovateurs reviewed
<img width="293" alt="Screenshot 2024-12-31 at 10 00 06" src="https://github.com/user-attachments/assets/c3196016-0fc0-447b-9e46-c2f205291066" />
Côté mobile, je me demande s'il n'y a pas une règle de bouton de même taille pour celui de retour à l'accueil.

2025-01-06 07:52 UTC, jenovateurs approved these changes
Tout est bon merci @Shamzic

2025-01-06 14:43 UTC, merged