Stats annuelles et mensuelles du nombre de simulations en fonction des institutions
betagouv/aides-jeunes pull request #4764
Opened 2024-12-11 15:16 UTC by Shamzic

- Changement: nombre de simulations apr institutions sur 6 mois -> sur 1 an 
- Nouveau: nombre de simulations par mois par institution

2024-12-13 16:32 UTC, jenovateurs requested changes
Je suis ok sur la fonctionnalité, mais pas sur l'impact côté BDD.
Je ne connais pas le nombre de consultations de cette page de stats, car on n’a pas mis de tracking. Mais le coup de la requête est lourd. Je propose donc une mise en cache du calcul sur n-1 à n-11 et un rafraîchissement de la data sur n si on veut être précis. Afin de limiter le calcul récurrent sur 1 an. Qu'en penses-tu @Shamzic ?

2024-12-18 16:21 UTC, jenovateurs commented
> > Je suis ok sur la fonctionnalité, mais pas sur l'impact côté BDD. Je ne connais pas le nombre de consultations de cette page de stats, car on n’a pas mis de tracking. Mais le coup de la requête est lourd. Je propose donc une mise en cache du calcul sur n-1 à n-11 et un rafraîchissement de la data sur n si on veut être précis. Afin de limiter le calcul récurrent sur 1 an. Qu'en penses-tu @Shamzic ?
> 
> Ok pour ta proposition, je suis d'accord qu'il y a de la redondance qu'on pourrait supprimer. Je me demandes juste sur quel calcul tu t'es basé pour estimer la lourdeur de la requête et de quelle manière veux-tu mettre cela en cache ?

Il suffit de faire un explain sur MongoDb, voici les variantes pour les requêtes :
1 -  $gt: new Date(new Date().setFullYear(new Date().getFullYear() - 1))
2 - $gt: new Date(new Date().setMonth(new Date().getMonth() - 6))

## 1 an
<img width="967" alt="Screenshot 2024-12-18 at 17 13 43" src="https://github.com/user-attachments/assets/a2a80376-67ca-4583-a703-07655180fbe2" />

## 6 mois

<img width="967" alt="Screenshot 2024-12-18 at 17 14 36" src="https://github.com/user-attachments/assets/8c5aca5c-b4d0-423d-ae37-dd51e32461c1" />

## Résultat

Doublement en terme de performance et de besoin en ressource même si je pense qu'on a un bon serveur.
On passe donc de 5 secondes à 11 secondes.

## Solution
Création d'une nouvelle table avec mise en cache des données sur les 11 derniers mois. Ajout du nouveau mois en cache lorsqu'on passe au mois suivant. Et pour finir pour l'utilisateur : 
- jointure dans une vue sur Mongo entre la table en cache et le mois courant
- une seule requête alléger
=> résultat final

2025-01-03 17:04 UTC, Shamzic commented
Intéressant cet outil, je ne connaissais pas! C'est curieux, je n'ai pas du tout les mêmes temps d'exécution sur la table des simulation en production:

### Récupération des simulation des 12 derniers moi
```js
{"createdAt": {$gt: new Date(new Date().setFullYear(new Date().getFullYear() - 1))}}
```
![image](https://github.com/user-attachments/assets/1bec019c-6a11-4d60-959d-71369e88995f)
### Récupération des  simulations des 6 derniers mois
```js
{"createdAt": {$gt: new Date(new Date().setMonth(new Date().getMonth() - 6))}}
```
![image](https://github.com/user-attachments/assets/16175f1b-b920-4a21-8525-355cbac991c5)

2025-01-06 07:54 UTC, jenovateurs commented
Autre solution, il existe probablement un système de cache paramétrable dans MongoDb.

2025-02-05 10:35 UTC, Shamzic commented
Je ferme car ce n'est pas prioritaire

2025-02-05 10:35 UTC, closed without merging