Met à jour 4 aides de la région Pays de la Loire.
betagouv/aides-jeunes pull request #4781
Opened 2024-12-26 12:14 UTC by yasmine-glitch

Améliorations de descriptions / apport de précisions.
Correction de valeurs erronées.

2024-12-27 09:27 UTC, jenovateurs requested changes
Merci pour l'ajout Yasmine :-)

2024-12-27 09:27 UTC, jenovateurs commented on data/benefits/javascript/region_pays_de_la_loire-bourses-pour-les-élèves-et-étudiant-e-s-en-formation-sanitaire-et-sociale.yml
> +          - terminale
Je ne comprends pas cette limite car c'est pour les élèves et étudiants.

2024-12-27 09:27 UTC, jenovateurs commented on data/benefits/openfisca/pays_de_la_loire_epass_jeunes_culture_sport.yml
> +  le BAFA ou un diplôme de secourisme."
```suggestion
  le BAFA ou un diplôme de secourisme. Vous pouvez aussi depuis un ordinateur, éditer et imprimer un bon d’échange à usage unique."
```

2025-01-03 16:46 UTC, Shamzic commented on data/benefits/javascript/region_pays_de_la_loire-bourses-pour-les-élèves-et-étudiant-e-s-en-formation-sanitaire-et-sociale.yml
> +    value: 30
J'ai pas trouvé cette info dans les liens de l'aide, c'est confirmé en interne ?

2025-01-06 08:56 UTC, yasmine-glitch commented on data/benefits/javascript/region_pays_de_la_loire-bourses-pour-les-élèves-et-étudiant-e-s-en-formation-sanitaire-et-sociale.yml
> +    value: 30
Hello Simon, non c'était simplement pour cadrer et ne pas montrer l'aide à absolument tout le monde. Mais en fait tu as raison : je vais garder uniquement la limite des 15 ans et enlever celle des 30 ans. Toute personne de plus de 15 ans intéressée par les formations sanitaires et sociales verra cette aide.

2025-01-06 15:12 UTC, Shamzic approved these changes

2025-01-09 16:50 UTC, jenovateurs approved these changes

2025-01-13 15:55 UTC, merged